insights/client/__init__.py, insights/client/client.py, insights/client/client_config.py, insights/tests/test_client.py, setup.py
also adding an entry point to call the client
=> making logging_file overridable

insights/client/client.py, insights/client/connection.py, insights/client/utilities.py, insights/tests/client/test_utilities.py
Also fix a couple functions to make them easier to test.
=> add additional utilities tests

insights/client/__init__.py, insights/client/client.py
The goal here is to clean up the code and hopefully make it more approachable, yet keep the exact same logging behavior as before.
=> Logging refactor

insights/parsers/smbstatus.py, insights/parsers/tests/test_smbstatus.py
- raise ParseException when output is empty or does not contain header line
- refine the docstring as per 3.0
=> Fix ValueError of smbstatus for special content

insights/parsers/httpd_conf.py, insights/parsers/tests/test_httpd_conf.py
- Remove the useless filter in test
- Refine the doctest
=> Fix split error for sections without name

docs/shared_parsers_catalog/gnocchi.rst, insights/parsers/gnocchi.py, insights/parsers/tests/test_gnocchi.py, insights/specs/__init__.py, insights/specs/default.py
- GnocchiConf
- GnocchiMetricdLog
=> Add gnocchi module

insights/specs/sos_archive.py
Added foreman_production_log spec to sos_archive.py
=> Add foreman_production_log spec to sos_archive.py

docs/shared_parsers_catalog/neutron_l3_agent_log.rst, insights/parsers/neutron_l3_agent_log.py, insights/parsers/tests/test_neutron_l3_agent_log.py, insights/specs/__init__.py, insights/specs/default.py
Signed-off-by: lichen <lichen@redhat.com>
=> Add neutron_l3_agent_log parser

insights/specs/sos_archive.py
Add missing sos spec See #1082.
=> Add pcs_status spec. #1082.

insights/parsers/bond.py, insights/parsers/tests/test_bond.py
Enhanced bond parser for getting active slave interfaces
=> Enhance parser bond

insights/parsers/fstab.py, insights/parsers/tests/test_fstab.py
=> Enhance parser fstab with method match_device_of_path()

Jenkinsfile
Add Jenkinsfile to repo for build testing
=> Add Jenkinsfile for pipeline builds

insights/parsers/meminfo.py, insights/parsers/tests/test_meminfo.py
=> Fix a bug caused by typo in parser meminfo

Jenkinsfile
Ensure python3 is properly tested in Jenkins
=> Fix Jenkins Python3 testing

insights/core/spec_factory.py, insights/tests/test_specs.py
Added check to glob_file() function in spec_factory.py to throw 
exception if more than 1000 files collected
Added a test for ContentException thrown when files > 1000
=> Added check to glob_file() function in limit number of files

insights/combiners/httpd_conf.py, insights/combiners/tests/test_httpd_conf.py, insights/parsers/httpd_conf.py, insights/parsers/tests/test_httpd_conf.py
=> Fix httpd_conf cannot handle directives in nest and parallel sections correct

insights/specs/__init__.py, insights/specs/default.py
=> Spec for spec_store_bypass vuln file

README.rst, docs/notebook_index.rst, docs/notebooks/Diagnostic Walkthrough.ipynb
Looking to make the project more accessible to users of insights-core.
Added an addition "walk through" notebook example.
=> Rework of README.rst

insights/specs/sos_archive.py
Added specs for systemctl list-units and systemctl list-unit-files in sos_archives
=> Copied simple file specs changes from insights_archive to sos_archive

insights/client/client.py
=> missing config in call

insights/specs/default.py
Reverts RedHatInsights/insights-core#1184
=> Revert "Fix and remove unnecessary secondary specs from DefaultSpecs"

docs/api.rst, docs/customtut_parsers.rst, docs/intro.rst, docs/quickstart_insights_core.rst
Signed-off-by: Noah Watkins <nwatkins@redhat.com>
=> Fixing some doc typos

insights/util/fs.py
* Fixes issue #1238 by clearing umask before setting mode and then
resetting umask to the original value after setting mode.
=> Fixed problem with setting tmp file permissions

insights/parsers/mysqladmin.py, insights/parsers/tests/test_mysqladmin.py
Record bad lines and keep on parsing instead of raise exception.
=> Enhance parser mysqladmin with bad_lines property

insights/tests/test_fs.py
* Added test to change touch times
* Added parametrized test of modes
=> Added some more fs tests

insights/parsers/mount.py, insights/parsers/tests/test_mount.py
=> Fix the dead loop in Mount.get_dir() in some cases

insights/__init__.py
* Removes -q switch and makes that the default
* Adds -D switch for full debug output
* Makes -v switch logging.INFO output
=> Make quiet default output option for cmd line

docs/notebooks/Config Tree Tutorial.ipynb, insights/combiners/httpd_conf.py, insights/configtree/__init__.py, insights/configtree/tests/test_dsl.py
Created case insensitive variants of all the predicates when working on strings. Also updated case handling for httpd config section tags.
=> Add case insensitivity options to configtree.

docs/notebooks/Config Tree Tutorial.ipynb, docs/notebooks/Datasource Registry.ipynb, docs/notebooks/Development Examples.ipynb, docs/notebooks/Diagnostic Walkthrough.ipynb, docs/notebooks/Insights Core Tutorial.ipynb, docs/notebooks/Rule Migration Guide.ipynb, insights/__init__.py, insights/core/hydration.py
Also updated the notebooks so they can all be run out of the root directory of the repo.
=> -p arg is comma separated. Refactor insights.run functions, and dedup context parameters

insights/specs/__init__.py, insights/specs/default.py, venv
Additional control indicator for CPU is needed.
=> Added specs for additional CPU control indicators

insights/combiners/tests/test_httpd_conf_tree.py, insights/configtree/__init__.py
Properly handle httpd config continuation lines.
=> Httpd continuations

insights/core/__init__.py, insights/tests/test_file_listing.py
Fix the bug described in #1306
=> Fix the bug of `FileListing.total_of()` (#1306)

insights/parsers/saphostctrl_instances.py, insights/specs/insights_archive.py
Correct the simple_file for `saphostctl` command as per the result of `mangle`
=> Fix the simple_file in insights-archive for saphostctl

insights/specs/sos_archive.py
Add Specs for `lsscsi` in sos archive
Signed-off-by: Akshay Gaikwad <akgaikwa@redhat.com>
=> Specs lsscsi in sos archive

docs/notebook_index.rst, docs/notebooks/Filters Tutorial.ipynb, docs/notebooks/death_star.ini
* Add jupyter notebook for filtering
* Add references in existing docs
* Add test file for notebook to notebook directory
=> Add tutorial files for filters

insights/specs/__init__.py
This spec should have been multi-output as well.
=> Make cpu_vulns multi-output

insights/client/__init__.py, insights/client/client.py, insights/client/phase/v1.py
See here:
https://mojo.redhat.com/message/1001213
=> Be more careful about deleting parent directory of archive after upload

docs/shared_parsers_catalog/yum.rst, insights/parsers/tests/test_yum_repolist.py, insights/parsers/yum.py
- handle the out of date repos
- add docstring and test
- raise SkipException for incorrect content
=> Enhance YumRepoList

Jenkinsfile, setup.py
* Fixes issue #1261
* Adds bundles for docs, testing, and flake8
* Modifies Jenkinsfile to use new bundles
=> Split setuptools extras bundle

insights/parsers/getsebool.py, insights/parsers/tests/test_getsebool.py
* Fixes issue #1394
* Added check for SELinux being disable before processing data
* SkipException is raised if SELinux is disabled
* Added test for exception logic
=> Add check for selinux disabled in getsebool

docs/shared_parsers_catalog/systool.rst, insights/parsers/systool.py, insights/parsers/tests/test_systool.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for command 'systool -b scsi -v'

insights/parsers/pcs_status.py, insights/specs/__init__.py
Reverts RedHatInsights/insights-core#1412
=> Revert "Updated pcs_status parser to support filter"

insights/specs/insights_archive.py
Modified simple_file specs from insights_archive to pick file from insights_archive.py
=> Added code for changing specs spelling

docs/shared_parsers_catalog/ceph_log.rst, insights/parsers/ceph_log.py, insights/parsers/tests/test_ceph_log.py, insights/specs/__init__.py, insights/specs/default.py
New parser for parsing file /var/log/ceph/ceph.log.
=> Added parser for file /var/log/ceph/ceph.log

insights/util/subproc.py
Resolve https://github.com/RedHatInsights/insights-core/issues/1432
=> Fix the UnicodeDecodeError in call() of util/subproc.py

insights/client/client.py, insights/client/config.py, insights/client/constants.py, insights/client/insights_spec.py, insights/tests/client/test_client.py
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1597308
=> Restore exit handler

insights/parsers/gnocchi.py
- to avoid any disorder of section attribution problem
=> Add the default filter for gnocchi (ini like config)

insights/specs/default.py
Added the following to default.py
Added xfs_mounts datasource using the Mount parser to retrieve 'xfs' mount points
@datasource(Mount)
def xfs_mounts(broker):
mnt = broker[Mount]
mps = mnt.search(mount_type='xfs')
return [m.mount_point for m in mps if mps]
Added xfs_info spec. Iterates through mount points from xfs_mounts datasource to get xfs info for each.
xfs_info = foreach_execute(xfs_mounts, "/usr/sbin/xfs_info %s")
=> Added xfs_mounts datasource and xfs_info spec

insights/client/config.py
See https://github.com/RedHatInsights/insights-client/pull/72
=> unsuppress options for parity with the updated manpage

insights/core/archives.py
Adds tar file handling back for #1457.
=> Fix bug that broke plain tar file extraction.

insights/core/spec_factory.py
=> Ensure resolved symlinks point inside the resolved root of the directory being analyzed

insights/combiners/tests/test_nginx_conf_parser.py, insights/parsers/nginx_conf.py
- add test for _NginxConf parser
=> Deprecate NginxConf parser

insights/parsers/systemd/__init__.py, insights/parsers/systemd/config.py, insights/parsers/tests/test_systemd_config.py, insights/specs/__init__.py, insights/specs/default.py
- Deprecated the non-used MultiOrderedDict
- Change the parse_systemd_ini function to a base Class
- Add test for doc examples
=> New Parser SystemdLogindConf

docs/shared_parsers_catalog/neutron_l3_agent_conf.rst, insights/parsers/neutron_l3_agent_conf.py, insights/parsers/tests/test_neutron_l3_agent_conf.py, insights/specs/__init__.py, insights/specs/default.py
New parser for parsing file l3_agent.ini.
=> Added parser for file l3_agent.ini

docs/shared_parsers_catalog/scsi_fwver.rst, insights/parsers/scsi_fwver.py, insights/parsers/tests/test_scsi_fwver.py, insights/specs/__init__.py, insights/specs/default.py
Added parser for finding what mode is used by scsi host.
=> added parser for "/sys/class/scsi_host/host[0-9]*/fwrev"

docs/shared_parsers_catalog/scsi_eh_deadline.rst, insights/parsers/scsi_eh_deadline.py, insights/parsers/tests/test_scsi_eh_deadline.py, insights/specs/__init__.py, insights/specs/default.py
Added parser for finding eh_deadline timeout value for scsi_hosts
=> Added parser code for /sys/class/scsi_host/host0/eh_deadline

insights/formats/text.py
Changed a header and added labels for those not using color.
=> Updated text, cli output.

docs/shared_parsers_catalog/ls_var_lib_nova_instances.rst, insights/parsers/ls_var_lib_nova_instances.py, insights/parsers/tests/test_ls_var_lib_nova_instances.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
New parser for parsing output of command 'ls -laRZ /var/lib/nova/instances'
=> Added parser for command 'ls -laRZ /var/lib/nova/instances'

insights/specs/default.py, insights/specs/insights_archive.py
- The start of DST remains November 4th.
=> Uncheck DST timezone files

insights/specs/default.py, insights/specs/insights_archive.py
Reverts RedHatInsights/insights-core#1505
=> Revert "Uncheck DST timezone files"

insights/tests/__init__.py, insights/tests/test_test.py, insights/tests/test_util.py
=> Change unordered_compare to deep_compare

insights/combiners/httpd_conf.py, insights/parsers/httpd_conf.py
=> Deprecate HttpdConf and HttpdConfAll

docs/embedded_content.rst
- added runtime output to examples
- added note about make_metadata usage
=> Embedded content docs update

insights/parsers/ps.py, insights/parsers/tests/test_ps.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
* Add new ps parser for the ps command: ps -eo pid,ppid,comm
* Add tests
* Add specs
=> Add new parser for ps -eo pid,ppid,comm

insights/__init__.py
=> Check that "" is in sys.path in insight:main

insights/client/constants.py
to avoid hitting the watchdog timeout (600s) on multiple upload retries
=> reduce time between retries from 300s to 180s

setup.py
Removed the version from requests in runtime.
=> Changed requests==2.13.0 in setup.py runtime to requests

docs/shared_parsers_catalog/ceph_conf.rst
=> Added missing rst entry for parser CephConf

insights/parsers/installed_rpms.py, insights/parsers/tests/test_installed_rpms.py
=> Update "from_package" to support epoch

docs/conf.py
=> Update conf.py for python 2.6 support

insights/formats/text.py
Added support for make_fingerprint in text.py format
=> Lh handle fingerprints

insights/parsers/bond.py, insights/parsers/tests/test_bond.py
Removed exception handling, it's not required, raising unnecessary exceptions
=> Removed exception handler from Bond class

docs/shared_parsers_catalog/rabbitmq.rst, insights/parsers/rabbitmq.py, insights/parsers/tests/test_rabbitmq_env.py, insights/specs/__init__.py, insights/specs/default.py
=> Parser for file /etc/rabbitmq/rabbitmq-env.conf

insights/client/connection.py
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1645491
=> python 3 compatability fix for proxy response check

insights/parsers/kdump.py, insights/parsers/tests/test_kdump.py, insights/specs/default.py
- the spec 'kdump' is duplicated with 'sysconfig_kdump' which is added to uploader.json
=> Remove useless docstring and spec of kdump

Jenkinsfile, insights/parsers/installed_rpms.py, setup.py
* Updated jenkins for doc build only
* Updated setup to use latest versions of sphinx and tools modules
* Fixed errors with embedded colons in installed_rpms module
=> Build docs in python3

insights/specs/__init__.py, insights/specs/default.py
https://bugzilla.redhat.com/show_bug.cgi?id=1656763
=> Get max UID to detect CVE-2018-19788 polkit

docs/shared_parsers_catalog/nova_user_ids.rst, insights/parsers/nova_user_ids.py, insights/parsers/tests/test_nova_user_ids.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Parser to parse output of 'id -u nova' & 'id -u nova_migration'

insights/specs/sos_archive.py
This adds  `ls_dev` specs in `sos_archive.py`
=> Add specs ls_dev in sos_archive

insights/parsers/ceilometer_log.py, insights/parsers/tests/test_ceilometer_log.py, insights/specs/__init__.py, insights/specs/default.py
Modified parser `ceilometer_log` to parse log file ceilometer `compute.log`
=> Enhanced parser ceilometer_log to parse file /var/log/ceilometer/compute.log

docs/quickstart_insights_core.rst
=> Fixing re-declaration error in hostname_rel.py

insights/specs/insights_archive.py
This change allows the max_uid spec to work with archives.
=> Add path to max_uid command output

insights/tools/query.py
=> Make "insights-info" more accurate

insights/parsers/ceph_version.py
=> Add Ceph releases 2.5, 3.0, 3.1 & 3.2

insights/core/spec_factory.py
Sending a value to a depleted generator in python 3.7 raises `StopIteration`.
It turned out that explicitly sending a value back into the generator wasn't
needed anyway.
Fixes #1652
=> Fix a generator exception with python3.7

insights/tests/client/test_utilities.py, insights/tests/test_fs.py
=> Some tests were leaving files in /tmp

docs/quickstart_insights_core.rst, examples/rules/bash_version.py, examples/rules/hostname_rel.py
Update quickstart docs and add examples shown in docs to examples/rules dir.
=> Update quickstart and add examples

insights/formats/_markdown.py
* Outputs markdown to STDOUT
* Use with -f _markdown switch
=> Add new formatter for markdown output

insights/combiners/tests/test_virt_who_conf.py, insights/combiners/virt_who_conf.py
Minor changes to docstrings, examples and test inputs.
=> Update docstring and examples

insights/core/spec_factory.py, insights/parsers/tests/test_gluster_vol.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py, insights/tests/test_specs.py, insights/tools/cat.py
Contains a new class for surfacing to parsers and the insights cat tool data that's not the result of a file collection or command execution.
=> Rhev data center ds

insights/parsers/sctp.py, insights/parsers/tests/test_sctp.py, insights/specs/__init__.py, insights/specs/default.py
Added parser for `/proc/net/sctp/assocs` specs, specs are important to check the state of associations formed by SCTP sockets.
=> Added parser for `/proc/net/sctp/assocs` specs

insights/specs/insights_archive.py
* Fix insights archive spec for ceph_insights to match actual command in JSON
=> Fix insights archive spec for ceph_insights

insights/core/__init__.py, insights/tests/test_logfileoutput.py
=> Enhance 'token_scan' to support list

insights/core/__init__.py
- For #1697 
Skip this bad line from CommandParser
=> New bad_line for 'python -m insights.tools'

insights/parsers/ssh_client_config.py, insights/parsers/tests/test_ssh_client_config.py, insights/specs/__init__.py, insights/specs/default.py
=> New parser ForemanProxySshConfig

docs/shared_parsers_catalog/ironic_inspector_log.rst, insights/parsers/ironic_inspector_log.py, insights/parsers/tests/test_ironic_inspector_log.py, insights/specs/__init__.py, insights/specs/default.py
=> Add parser for ironic-inspector.log

insights/collect.py, insights/core/spec_factory.py
=> Add LC_ALL and LANG to default environment when running commands

insights/specs/__init__.py
=> Add filterable option to IronicInspectorLog

insights/tools/query.py
- https://github.com/RedHatInsights/insights-core/issues/1645
https://github.com/RedHatInsights/insights-core/issues/1645#issuecomment-468166815
https://github.com/RedHatInsights/insights-core/issues/1645#issuecomment-469552049
- Limit to only outputs Parsers/Combiners by default
Added "-S" option to output related `Specs` in addition
- Check the parent dir when the file name is "*" os "*.xx" in `glob_file`
=> Enhance command: "insights info"

insights/core/__init__.py
=> Update the `Examples` of LogFileOutput and Syslog

insights/client/connection.py, insights/tests/client/test_platform.py
https://projects.engineering.redhat.com/browse/RHIPLAT1-713
=> Canonical fact fix

insights/__init__.py, insights/collect.py, insights/command_parser.py, insights/tools/cat.py, insights/tools/query.py, setup.py
* Add new insights command with run, cat, info, and collect as
subcommands
* Maintains the existing insights-command capability
=> Add capability to run insights subcommand as cli

insights/parsers/qemu_xml.py, insights/parsers/tests/test_qemu_xml.py, insights/specs/__init__.py, insights/specs/sos_archive.py
This includes:
* New parser ``VarQemuXML`` to parse XML files
under "/var/run/libvirt/qemu/" directory.
* New parser is based on exising ``QemuXML`` parser.
=> Add new spec in qemu_xml parser

insights/parsers/__init__.py, insights/parsers/tests/test_parsers_module.py
=> Fixes parse_fixed_table header name prefix bug.

insights/combiners/sap.py, insights/combiners/tests/test_sap.py
=> Identify business instances and function instances

insights/parsers/sapcontrol.py, insights/parsers/tests/test_sapcontrol.py, insights/specs/default.py
Reason to change this spec:
- due to issue #1697, the spec cannot be collected yet
- foreach_collect of client-v3 works well for this spec
API is not changed.
=> Change sapcontrol to use foreach_execute

insights/parsers/modinfo.py, insights/parsers/tests/test_modinfo.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
Added a parser for the spec `/sbin/modinfo vmxnet3`
=> Added parser for modinfo vmxnet3

insights/specs/default.py
=> [ceilometer/collector.log] Return the first existing file

insights/specs/sos_archive.py
Made changes for specs for netstat in `spec/sos_archive.py`.
=> Changes spec for netstat parser in sos_archive.py

insights/parsers/sap_hdb_version.py, insights/parsers/tests/test_sap_hdb_version.py
- and skipped empty parse result
=> Added sid to HDBVersion

insights/parsers/mysql_log.py, insights/specs/default.py
=> Enhance spec 'mysql_log' with '/var/log/mysql/mysqld.log'

docs/shared_combiners_catalog/cloud_provider.rst, insights/combiners/cloud_provider.py, insights/combiners/tests/test_cloud_provider.py
Uses the following parsers to to get facts to determine cloud provider
- InstallledRpms
- YumRepoList 
- DMIDecode
=> Adding Cloud Provider combiner and tests

insights/parsers/subscription_manager_list.py, insights/parsers/tests/test_subscription_manager_list.py, insights/parsers/virt_uuid_facts.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
- and deprecated `VirtUuidFacts` parser.
=> Use command 'subscription-manager facts --list' to list all facts

insights/specs/insights_archive.py
=> Fix the aws_instance_type spec to "python -m cat"

docs/shared_combiners_catalog/package_provides_httpd.rst, docs/shared_parsers_catalog/package_provides_httpd.rst, insights/combiners/package_provides_httpd.py, insights/combiners/tests/test_package_provides_httpd.py, insights/parsers/package_provides_httpd.py, insights/parsers/tests/test_package_provides_httpd.py, insights/specs/__init__.py, insights/specs/default.py
* Show the running httpds and its corresponding package
=> Add a new parser package_provides_httpd

insights/tools/insights_inspect.py
Added color to ipython shell.
Added command line arg to turn off datasource filtering.
=> Added color to ipython shell for insights-inspect.

insights/client/client.py, insights/client/connection.py
Accept 200 or 202 from the API. Inexplicably, it's sending 200 right now.
=> accept 200 as well as 202

insights/client/connection.py, insights/client/data_collector.py, insights/tests/client/test_displayname.py
also put it in the archive
also fix a couple logging messages
=> post display name to both urls for the transition period

insights/client/connection.py, insights/client/constants.py, insights/client/phase/v1.py, insights/tests/client/connection/test_url_guess.py, insights/tests/client/phase/test_post_update.py
also skip reg check on --payload
=> upload to legacy mirror because cloud certs are being disabled. 

insights/client/collection_rules.py
=> hack the uploader.json url for legacy_upload=False

insights/parsers/dmesg.py, insights/parsers/tests/test_dmesg.py
- Also fix a bug when parsing dmesg output of RHEL7
=> Dmesg now can return logs with specified prefix

insights/core/cluster.py, insights/core/hydration.py
=> Recognize directories of exploded archives as clusters.

docs/shared_parsers_catalog/mistral_log.rst, insights/parsers/mistral_log.py, insights/parsers/tests/test_mistral_log.py, insights/specs/__init__.py, insights/specs/default.py
* Add parser for `/var/log/mistral/executor.log` file.
=> [New parser] Mistral Executor Log file Parser

docs/shared_parsers_catalog/swift_log.rst, insights/parsers/swift_log.py, insights/parsers/tests/test_swift_log.py, insights/specs/__init__.py, insights/specs/default.py
Parser to access `/var/log/containers/swift/swift.log` and
`/var/log/swift/swift.log` file.
=> [New parser] Swift Log file parser

insights/combiners/redhat_release.py, insights/combiners/tests/test_redhat_release.py
- When nothing available, skip the combiner
=> Raise SkipException instead of ParseException in redhat_release

insights/parsers/subscription_manager_list.py, insights/parsers/tests/test_subscription_manager_list.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
- No plugins use this spec for now
- Will remove it from the uploader.json as well
=> Remove subscription_manager_repos_list_enabled from insights_archive.py

insights/combiners/ceph_version.py, insights/combiners/tests/test_ceph_version.py, insights/parsers/ceph_cmd_json_parsing.py, insights/parsers/tests/test_ceph_cmd_json_parsing.py, insights/specs/__init__.py, insights/specs/sos_archive.py
=> Add parser ceph_report and update ceph_version combiner

insights/core/dr.py, insights/tests/integration.py
https://bugzilla.redhat.com/show_bug.cgi?id=1666035
=> Fix deprecation warnings thrown when running tests for prodsec.rules

insights/parsers/passenger_status.py, insights/parsers/tests/test_passenger_status.py
=> Fix a bug of PassengerStatus

insights/core/__init__.py, insights/tests/test_logfileoutput.py
=> Enhance the keep_scan and token_scan of LogFileOutput

insights/__init__.py, insights/command_parser.py, setup.py
Added command_parser.py to parse sub-arguments to run the following 
insights commands:
- cat
- collect
- inspect
- info
- run
Added entry point (insights) in setup.py for 
'insights.command_parser:main'
=> Core command line

insights/parsers/systemd/config.py, insights/parsers/tests/test_systemd_config.py, insights/specs/default.py, insights/specs/insights_archive.py
Fix issue: https://github.com/RedHatInsights/insights-core/issues/1985
=> Use "systemctl cat" to collect unit file content

insights/parsers/systemd/config.py, insights/parsers/tests/test_systemd_config.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
* Add new data source implemented by simple_command()
* Add new parser which produces the parsed content of rpcbind.socket unit file
=> Add new parser SystemdRpcbindSocketConf

insights/combiners/cloud_provider.py
=> Change optional to at_least_one for CloudProvider

insights/specs/sos_archive.py
Add `ip_s_link` in sos_archive.py
=> Add sos archive path for specs ip_s_link

insights/parsers/software_collections_list.py
=> Limit the SCL parser only for rhel-6/7

insights/specs/default.py
=> Change installed_rpms in default for RHEL6

insights/parsers/installed_rpms.py, insights/parsers/tests/test_installed_rpms.py
=> Add redhat_signed for InstalledRpm

docs/shared_components_catalog/openstack.rst, insights/components/openstack.py, insights/components/tests/test_openstack.py, insights/parsers/qemu_xml.py, insights/parsers/tests/test_qemu_xml.py
=> Enhance QemuXML to include Openstack metadata

insights/specs/insights_archive.py
Add PR to resolve the issue https://github.com/RedHatInsights/insights-core/issues/2026
=> Added Missing specs

insights/command_parser.py
If found in first byte of arg replace em dash with '--' 
If found in first byte of arg replace en dash with '-'
=> If found replace em dash with '--' or replace en dash with '-'

docs/component_config.rst, docs/index.rst, insights/__init__.py, insights/collect.py
=> default_component_enabled consistently applied to loaded components

docs/shared_parsers_catalog/setup_named_chroot.rst, insights/parsers/setup_named_chroot.py, insights/parsers/tests/test_setup_named_chroot.py, insights/specs/__init__.py, insights/specs/default.py
New parser to parse file `setup-named-chroot.sh`.
Signed-off-by: Preeti Pandey <ppandey@redhat.com>
=> Parser for file setup-named-chroot.sh

insights/parsers/nmcli.py, insights/parsers/tests/test_nmcli.py
The issue: https://github.com/RedHatInsights/insights-core/issues/2051
=> NmcliConnShow parser fails when there is warning in cmd output 

insights/tools/apply_spec_filters.py
- fix: https://github.com/RedHatInsights/insights-core-assets/issues/226
=> Add the missed `globs` to apply_spec_filters

insights/client/config.py, insights/client/phase/v1.py, insights/client/utilities.py, insights/tests/client/phase/test_pre_update_support.py, insights/tests/client/test_utilities.py
This reverts commit 7a0ecae4a33ab9354cb22529877abf346f626619.
=> Revert "don't run the client without cgroups unless specified (#2063)"

conftest.py, insights/tests/test_rules_fixture.py
* Make run_rule fixture more compatible with archive_provider
* Update tests
=> Enhance run_rule fixture

insights/components/rhel_version.py
=> Update insights.components.rhel_version pydoc.

docs/api.rst, docs/notebooks/Insights Core Tutorial.ipynb, insights/__init__.py, insights/core/plugins.py, insights/formats/text.py, insights/plugins/info.py
Fixes https://github.com/RedHatInsights/insights-core/issues/2073
=> Create a make_info response type for rules.

insights/specs/insights_archive.py
=> Add modinfo spec to insights_archive

insights/specs/default.py
=> Add the same httpd conf to other httpd packages too

insights/parsers/systemctl_show.py, insights/parsers/tests/test_systemctl_show.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> New spec to get output of "systemctl show nginx"

insights/specs/sos_archive.py
=> Add sos_commands/services/chkconfig_--list to sos archive specs.

examples/rules/bash_version.py
=> Fix the examples/rules/bash_version rule with json format

docs/shared_parsers_catalog/sys_bus.rst, insights/parsers/sys_bus.py, insights/parsers/tests/test_sys_bus.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
Added parser for `/sys/bus/usb/drivers/cdc_wdm/module/refcnt` device usage.
=> Parser cdc wdm

insights/specs/insights_archive.py
Fix issue: https://github.com/RedHatInsights/insights-core/issues/2038
Signed-off-by: Chen Lizhong <lichen@redhat.com>
=> Use first_file to backward compatibility

insights/client/config.py, insights/client/support.py, insights/tests/client/support/test_collect_support_info.py, insights/tests/client/test_config.py
=> forbid certain options, and skip network functions with --support with offline mode

insights/specs/sos_archive.py
- teamdctl_config_dump = glob_file("sos_commands/teamd/teamdctl_*_config_dump")
- teamdctl_state_dump = glob_file("sos_commands/teamd/teamdctl_*_state_dump")
=> Added new spc in sos_archive.py for teamd

docs/shared_parsers_catalog/ovs_ofctl_dump_flows.rst, insights/parsers/ovs_ofctl_dump_flows.py, insights/parsers/tests/test_ovs_ofctl_dump_flows.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
Parser is added to process the ovs flows
=> Parser ovs flow dumps

.gitignore
=> add .python* to .gitignore

insights/core/spec_factory.py
=> "find" wasn't correctly creating its result dictionary.

insights/core/context.py, insights/core/spec_factory.py
=> Fix missing context attributes accessed during rule integration tests.

insights/parsers/yum.py
=> add one more string to trailing_ignore of parse_fixed_table

docs/manpages/insights-run.rst, insights/__init__.py, insights/tests/spec_tests.py, insights/tests/test_dr_run.py
Add new switch `-b`/`--bare` to specify a specific input file for a spec to the ``run`` command
=> Add new switch to run to allow bare file specs

insights/client/auto_config.py, insights/tests/client/auto_config/test_try_satellite5_configuration.py
=> add missing parameter

insights/specs/sos_archive.py
=> Add lscpu spec to sosreport archives

insights/tools/insights_inspect.py
While going though the code, I've noticed some minor inconsistencies, so sending fixes along.
=> Minor code comment fix: s/make_pass/Hostname

insights/parsers/hosts.py, insights/parsers/tests/test_hosts.py
=> update hosts to mix with dict

insights/parsers/hosts.py, insights/parsers/tests/test_hosts.py
- considering the issue #2177, we should re-implement the Hosts parser
This reverts commit 65a1768ece421d06e0663875660f5060fc37ab93.
=> Revert "update hosts to mix with dict (#2172)"

insights/parsers/hosts.py, insights/parsers/tests/test_hosts.py
=> add 'lines' to return lines with the original order for Hosts

CONTRIBUTING.md
Signed-off-by: Joel Savitz <jsavitz@redhat.com>
=> Fix git remote command in CONTRIBUTING.md

insights/combiners/modinfo.py, insights/combiners/tests/test_modinfo.py, insights/parsers/modinfo.py, insights/parsers/tests/test_modinfo.py
- Fix it before the Combiner ModInfo being running in production
- see: #2122 
- No rules are broken
=> Remove the redundant self.data from ModInfo

insights/parsers/partitions.py, insights/parsers/tests/test_partitions.py
- fix: #2124 
- No rules are broken
=> Remove the self.partitions from Partitions

insights/combiners/sap.py
=> Remove the redundant self.data from Sap

insights/combiners/nmcli_dev_show.py, insights/parsers/nmcli.py
=> Remove the redundant self.data from NmcliDevShow

insights/parsers/fcoeadm_i.py
=> Remove the redundant self.fcoe from FcoeadmI

insights/parsers/passenger_status.py
=> Remove the redundant self.data from PassengerStatus

insights/combiners/httpd_conf.py, insights/combiners/tests/test_httpd_conf_tree.py
Some characters like ';' and others were prohibited unnecessarily in attributes. This PR allows them while also allowing '<', '>', '<=', >=', and '!=' as stand alone attributes.
Fixes #2151
=> Allow some operator chars as attributes and within attributes

docs/shared_parsers_catalog/aws_instance_id.rst, insights/parsers/aws_instance_id.py, insights/parsers/tests/test_aws_instance_id.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
* Add new parser for AWS instance ID document
* Add new parser for AWS instance ID pkcs7 signature
* Add tests and documentation
=> Add new parsers for AWS Instance ID information

insights/parsers/hammer_task_list.py, insights/parsers/tests/test_hammer_task_list.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Update parser for parsing hammer tasks

README.rst
Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>
=> Fix a small typo.

docs/shared_parsers_catalog/kernel_config.rst, insights/parsers/kernel_config.py, insights/parsers/tests/test_kernel_config.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
Parser is required to collect kernel configuration parameters.
=> Parser kernel config file

insights/parsers/tests/test_vdo_status.py, insights/parsers/vdo_status.py
Enhance parser of vdo_status 
* Fix the "VDO statistics: not available" can not be parsed issue https://github.com/RedHatInsights/insights-core/issues/2209
* fix: #2209
=> Enhance parser of vdo_status 

insights/formats/html.py
=> Update jquery to version 3.4.1 in html format.

insights/specs/sos_archive.py
=> Add "ovs_vsctl_show" in sos archive

insights/combiners/modinfo.py, insights/combiners/tests/test_modinfo.py, insights/parsers/modinfo.py, insights/parsers/tests/test_modinfo.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/sos_archive.py
=> ModInfo supports `modinfo_ALL_MODULES`

docs/notebooks/Parsr Query Tutorial.ipynb, insights/parsr/query/__init__.py
=> Fix lift2 example in Custom Predicates of Parsr Tutorial Notebook

insights/parsers/cpu_vulns.py
Add descriptions and example for parser to fix documentation issue
https://github.com/RedHatInsights/insights-core/issues/2247
=> Improve documentation for parser of cpu_vulns

insights/parsers/mount.py
=> Fix typos in mount.py

docs/shared_parsers_catalog/cloud_init_log.rst, insights/parsers/cloud_init_log.py, insights/parsers/tests/test_cloud_init_log.py, insights/specs/__init__.py, insights/specs/default.py
=> Add parser for /var/log/cloud-init.log

insights/parsers/podman_inspect.py, insights/parsers/podman_list.py, insights/parsers/tests/test_podman_inspect.py
=> tiny update for podman_inspect and podman_list

insights/core/__init__.py
=> Update docstings of LogFileOutput

docs/shared_parsers_catalog/rhosp_release.rst, insights/parsers/rhosp_release.py, insights/parsers/tests/test_rhosp_release.py, insights/specs/__init__.py, insights/specs/default.py
=> Parser for /etc/rhosp-release

insights/parsers/docker_inspect.py, insights/parsers/docker_list.py, insights/parsers/tests/test_docker_inspect.py, insights/parsers/tests/test_docker_list.py
- use parse_fixed_table in docker_list
- mix DockerInspect with dict
- fix: #2252 
=> Update docker_list and docker_inspect

insights/combiners/cpu_vulns_all.py
Enhance document for combiner of cpu_vulns_all
- Add descriptions as docstring
- Add sample output for files
=> Enhance document for combiner of cpu_vulns_all

insights/core/spec_factory.py
=> fix typo in grep patterns args for files

insights/combiners/tests/test_httpd_conf_tree.py, insights/core/__init__.py
=> Allow duplicate includes if they don't cause infinite recursion

insights/specs/sos_archive.py
=> add sssd_logs to sos_archive.py

insights/parsers/sctp.py, insights/parsers/tests/test_sctp.py, insights/specs/__init__.py, insights/specs/default.py
=> Add Parser SCTPSnmp

docs/shared_parsers_catalog/satellite_enabled_features.rst, insights/parsers/satellite_enabled_features.py, insights/parsers/tests/test_satellite_enabled_features.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add new parser satellite_enabled_features

insights/specs/sos_archive.py
* This adds datasource path from sos archive for httpd_M specs.
=> Add sos archive path for httpd_M

insights/parsers/__init__.py, insights/parsers/tests/test_yum_repolist.py, insights/parsers/yum.py
=> fix repolist parse error

insights/parsers/systemd/unitfiles.py, insights/parsers/tests/test_unitfiles.py
=> Add is_failed method to systemd.unitfiles.UnitFiles Parser

insights/parsers/sctp.py, insights/parsers/tests/test_sctp.py
fix: https://github.com/RedHatInsights/insights-core/issues/2303
=> Enhanced to resolve content exception issue

insights/combiners/satellite_version.py, insights/combiners/tests/test_satellite_version.py, insights/parsers/satellite_version.py
=> Make satellite_version support Capsule

insights/parsers/gluster_vol.py, insights/parsers/tests/test_gluster_vol.py
=> [GlusterVolStatus] Fix process name for longer host or brick name

insights/specs/default.py, insights/specs/insights_archive.py
Fixes: https://github.com/RedHatInsights/insights-core/issues/2318
=> Remove spec fist since it can't be collected by client

docs/shared_parsers_catalog/vma_ra_enabled_s390x.rst, insights/parsers/tests/test_vma_ra_enabled_s390x.py, insights/parsers/vma_ra_enabled_s390x.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
New Parser for file '/sys/kernel/mm/swap/vma_ra_enabled'
=> New Parser for file /sys/kernel/mm/swap/vma_ra_enabled

setup.py
=> Workaround the doc error by locking Pygments to 2.4.2

insights/parsers/systemctl_show.py, insights/parsers/tests/test_systemctl_show.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for "systemctl show postgresql"

insights/parsers/ksmstate.py, insights/parsers/tests/test_ksmstate.py
=> Change ksmstate to class

insights/parsers/systemctl_show.py, insights/parsers/tests/test_systemctl_show.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
- refer to #2078 #2345 
This reverts commit fd1b894dbd97c3ef8c091d6e397426a92f97a129.
=> Revert "Add parser for "systemctl show postgresql" (#2338)"

insights/parsers/systemctl_show.py, insights/parsers/tests/test_systemctl_show.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py, insights/specs/sos_archive.py
- fix: #2078
- And deprecate all the existing SystemctlShow*
=> Enhance SystemctlShow* to use "systemctl show *.service"

insights/core/dr.py
=> add get_links to core.dr

insights/parsers/ip.py, insights/specs/insights_archive.py
https://github.com/RedHatInsights/insights-core/issues/2356
=> Modified to maintain backward compatibility

insights/combiners/satellite_version.py, insights/combiners/tests/test_satellite_version.py
=> Fixes #2350 Add Check in CapsuleVersion combiner

insights/parsers/hammer_ping.py, insights/parsers/tests/test_hammer_ping.py
* Fixes https://github.com/RedHatInsights/insights-core/issues/2358
* Sometimes there are only two lines instead of three lines for some service
=> Enhance hammer ping

insights/parsers/hammer_ping.py, insights/parsers/tests/test_hammer_ping.py
=> Keep original content in case we want to output the whole content

insights/parsers/kpatch_patches.py, insights/specs/insights_archive.py
=> Add kpatch_patch_files to insigths_archive and update doc

insights/parsers/netstat.py, insights/parsers/tests/test_netstat.py, insights/specs/__init__.py, insights/specs/default.py
Added a parser to get TCP and IP layer packet stats which are added in kernel released in `RHEL-7.6` or higher.
=> Added parser code for proc/net/netstat

insights/combiners/cloud_provider.py, insights/combiners/tests/test_cloud_provider.py
* Add new check for alibaba in dmidecode manufacturer
* Add tests
* Documentation cleanup
* Minor refactoring of code for readability
=> Add Alibaba to cloud provider combiner

insights/parsers/tests/test_openshift_get.py
=> fix the datatime comparison error caused by new PyYAML-5.3

docs/shared_parsers_catalog/udev_rules.rst, insights/parsers/tests/test_udev_rules.py, insights/parsers/udev_rules.py, insights/specs/__init__.py, insights/specs/default.py
=> New parser for "/usr/lib/udev/rules.d/59-fc-wwpn-id.rules"

docs/shared_parsers_catalog/findmnt.rst, insights/parsers/findmnt.py, insights/parsers/tests/test_findmnt.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for "findmnt -lo+PROPAGATION"

insights/formats/text.py
=> Automatically add links dictionary to text output format.

insights/parsers/tests/test_systemctl_show.py
=> Revert the tests of SystemctlShow* which were marked as deprecated

docs/shared_parsers_catalog/smt.rst, insights/parsers/smt.py, insights/parsers/tests/test_smt.py
These parsers are already in use in our private repository.
=> Parsers for Simultaneous multithreading

insights/contrib/soscleaner.py
=> python 3 unicode tweak in soscleaner

insights/client/apps/compliance/__init__.py, insights/tests/client/apps/test_compliance.py
:warning: - The compliance backend must have https://github.com/RedHatInsights/compliance-backend/pull/296 to work
=> Perform multiple OpenSCAP scans and upload results in one archive

insights/client/__init__.py, insights/client/apps/compliance/__init__.py, insights/client/archive.py, insights/client/client.py, insights/client/data_collector.py, insights/client/phase/v1.py, insights/tests/client/phase/test_collect_and_upload.py, insights/tests/client/test_client.py, insights/tests/client/test_skip_commands_files.py
=> consolidate temp file deletion into single func called at exit

insights/parsers/azure_instance_type.py, insights/parsers/tests/test_azure_instance_type.py, insights/specs/default.py
- and update the command of curl to full path in the spec
- #2441
=> Fix issue with curl in azure data

insights/client/archive.py, insights/client/data_collector.py, insights/client/phase/v1.py
=> restore --no-upload messaging to pass QE integration tests

insights/client/apps/aws/__init__.py, insights/client/connection.py, insights/tests/client/apps/test_aws.py
Move the cert_verify=True out of connection.py so it's only set on the AWS and Hydra connections.
=> Aws feature tweaks

insights/client/apps/compliance/__init__.py, insights/tests/client/apps/test_compliance.py
=> Fix profiles API endpoint to get profiles only for this host

insights/contrib/soscleaner.py
=> whitelist json mimetype for soscleaner

docs/shared_parsers_catalog/satellite_installer_configurations.rst, insights/parsers/satellite_installer_configurations.py, insights/parsers/tests/test_satellite_installer_configurations.py, insights/specs/__init__.py, insights/specs/default.py
=> Add parser for "/etc/foreman-installer/custom-hiera.yaml"

insights/specs/insights_archive.py
=> Add missed command for insights archive

insights/core/__init__.py, insights/tests/test_yaml_parser.py
=> Raise SkipException instead of ParseException when the file is empty

insights/parsers/tests/test_yum_repolist.py, insights/parsers/yum.py, insights/specs/default.py, insights/specs/insights_archive.py
* Add switch to prevent plugins from being loaded running command
* Modify docs in parser and add test for parser
* Modify default spec and add new command to archive spec
* Fix #2473
=> Add noplugins switch to spec yum repolist

insights/parsers/mount.py
=> update the docstring of mount.py

insights/client/archive.py, insights/tests/client/test_skip_commands_files.py
=> When missing dependencies don't collect it

docs/quickstart_insights_core.rst
fixed a typo in the documentation
=> fixed typo

insights/parsers/systemctl_show.py, insights/parsers/tests/test_systemctl_show.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for 'systemctl show *.target'

insights/core/evaluators.py
=> Change InsightsEvaluator to pass stream along to its superclass during construction

insights/defaults.yaml
Add ssl part into content section in defaults.yaml to support https connection
=> Add ssl part into content section in defaults.yaml to support https

insights/client/collection_rules.py, insights/client/phase/v1.py, insights/tests/client/phase/test_pre_update_support.py
=> Warn if remove.conf has bad permissions

insights/client/__init__.py, insights/client/apps/aws/__init__.py, insights/client/client.py, insights/client/collection_rules.py, insights/client/connection.py, insights/client/constants.py
Create a custom log level for network calls and remove the 'network' logger
- moved all requests and responses to the new NETWORK log level
BZ #1708685
RHCLOUD-2198
=> Custom net log level

insights/parsers/rhsm_releasever.py, insights/parsers/tests/test_rhsm_releasever.py
https://github.com/RedHatInsights/insights-core/issues/2509
=> Enhanced to handle the None value of release version

docs/shared_parsers_catalog/sys_kernel.rst, insights/parsers/sys_kernel.py, insights/parsers/tests/test_sys_kernel.py, insights/specs/__init__.py, insights/specs/default.py
=> Add new parser for "/proc/sys/kernel/sched_rt_runtime_us"

docs/shared_parsers_catalog/named_checkconf.rst, insights/parsers/named_checkconf.py, insights/parsers/tests/test_named_checkconf.py
=> Parser for Named-checkconf

insights/combiners/krb5.py, insights/combiners/tests/test_krb5.py
=> New 'files' attribute in AllKrb5Conf combiner

docs/shared_parsers_catalog/yum_list.rst, insights/parsers/tests/test_yum_list_installed.py, insights/parsers/yum_list.py
=> Add base class YumListRpm for 'yum list' commands

insights/parsers/tests/test_foreman_log.py
=> Update test data for foreman logs

docs/shared_parsers_catalog/rpm_v_packages.rst, insights/parsers/rpm_v_packages.py, insights/parsers/tests/test_rpm_v_packages.py
=> Parser for 'rpm -V coreutils procps procps-ng shadow-utils passwd sudo'

insights/client/data_collector.py
Remove extra references to remove.conf
=> messaging fixes for blacklist

insights/client/client.py
=> direct to insights console after registration

docs/shared_parsers_catalog/ndctl_list.rst, insights/parsers/ndctl_list.py, insights/parsers/tests/test_ndctl_list.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for spec "ndctl list -Ni"

docs/shared_parsers_catalog/cron_daily_rhsmd.rst, insights/parsers/cron_daily_rhsmd.py, insights/parsers/tests/test_cron_daily_rhsmd.py, insights/specs/__init__.py, insights/specs/default.py
=> Add parser for "/etc/cron.daily/rhsmd"

insights/tests/__init__.py
=> Print 'result' when assert failed in test

insights/specs/__init__.py
=> Remove semid from RegistryPoint

insights/parsers/uname.py
=> Add RHEL-8.2 kernel entry

docs/shared_parsers_catalog/config_file_perms.rst, insights/parsers/config_file_perms.py, insights/parsers/tests/test_config_file_perms.py
=> Parsers for Configuration File Permissions

docs/shared_parsers_catalog/ls_var_www_perms.rst, insights/parsers/ls_var_www_perms.py, insights/parsers/tests/test_ls_var_www_perms.py
=> Parser for 'ls /var/www' permissions

docs/docs_guidelines.rst, insights/core/remote_resource.py, insights/parsers/ethtool.py, insights/parsers/nmcli.py, insights/parsers/vdo_status.py, insights/parsers/yum.py, setup.py
* Update version of doc build tools
* Fix errors in doc build
=> Update docs to work with the latest version of Sphinx

docs/shared_parsers_catalog/whoopsie.rst, insights/parsers/tests/test_whoopsie.py, insights/parsers/whoopsie.py
=> Parser for a path to whoopsie report

insights/client/utilities.py
=> strip whitespace before UUID check for machine-id, log exception

docs/shared_parsers_catalog/imagemagick_policy.rst, insights/parsers/imagemagick_policy.py, insights/parsers/tests/test_imagemagick_policy.py
=> Parser for ImageMagick policy.xml file

insights/specs/default.py
On RHEL6 grubby cmd path is different.
https://github.com/RedHatInsights/insights-core/issues/2578
=> updated specs

.gitignore, docs/api.rst, docs/api_index.rst, docs/conf.py, docs/index.rst, insights/util/autology/__init__.py, insights/util/autology/datasources.py, insights/util/specs_catalog.py
* Add new module autology for spec introspection
* Add new reporting function for spec documentation that runs during
sphinx build
* Modify docs to support new specs documentation page
* Ignore new dynamically generated specs documentation page in git
=> Initial version of autology and specs documentation

insights/parsers/tests/test_yum_list_available.py, insights/parsers/yum_list.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
Add a parser to provide the output of `yum list available`
Signed-off-by: Joel Savitz <jsavitz@redhat.com>
=> parser: add parser for yum list available

insights/parsers/blkid.py
- Fix: https://github.com/RedHatInsights/insights-core/issues/674
=> Fix KeyError in parser blkid

docs/shared_parsers_catalog/corosync_cmapctl.rst, insights/parsers/corosync_cmapctl.py, insights/parsers/tests/test_corosync_cmapctl.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser "corosync_cmapctl"

docs/shared_parsers_catalog/systemd_analyze.rst, insights/parsers/systemd_analyze.py, insights/parsers/tests/test_systemd_analyze.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for the command 'systemd-analyze blame'

insights/parsers/cpuinfo.py, insights/parsers/tests/test_cpuinfo.py
=> Update return values of cpuinfo

docs/conf.py
=> Update copyright in docs to include 2019 and 2020.

insights-completion.bash
=> Add simple bash completion script for the insights command.

insights/parsers/ceph_version.py, insights/parsers/tests/test_ceph_version.py
=> Update the deprecated/useless items in ceph_version

insights/combiners/ceph_version.py, insights/combiners/tests/test_ceph_version.py, insights/parsers/ceph_version.py, insights/parsers/tests/test_ceph_version.py
=> Add is_els to CephVersion

insights/parsers/rpm_v_packages.py, insights/parsers/tests/test_rpm_v_packages.py, insights/specs/default.py, insights/specs/insights_archive.py
=> [RpmVPackages] Add 'chrony' package verification

insights/shell.py
=> Include the 'q' query helper in make_rule.

insights/util/autology/datasources.py, insights/util/specs_catalog.py
* Add existing datasource head to autology catalog
* Add description to catalog doc template for doc build
=> Add datasource head to autology

insights/parsers/tests/test_cib.py, insights/specs/default.py, insights/specs/sos_archive.py
* The localtion of cib.xml in sosreport is at "sos_commands/pacemaker/crm_report/<hostname>/cib.xml"
* since hostname is unknown, so use glob here and then get the first one
=> Support cib.xml in sosreport

insights/client/config.py
=> restore help messages for certain options

docs/shared_parsers_catalog/ls_tmp.rst, insights/parsers/ls_tmp.py, insights/parsers/tests/test_ls_tmp.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> New parser for ls_tmp

insights/parsers/installed_rpms.py, insights/parsers/tests/test_installed_rpms.py
- For some rules, it's necessary to check the "vendor" of the installed packages.
=> Add vendor attribute to InstalledRpm

insights/specs/sos_archive.py
=> Add spec for sosreport

insights/collect.py, insights/core/spec_factory.py
also disable parallel run strategy because RHEL 8 threading is broken
=> load client denylist in core collector

docs/shared_parsers_catalog/engine_db_query.rst, insights/parsers/engine_db_query.py, insights/parsers/tests/test_engine_db_query.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for command: engine-db-query --statement "QUERY" --json

insights/parsers/haproxy_cfg.py, insights/parsers/tests/test_haproxy_cfg.py
=> New 'lines' attribute in HaproxyCfg parser

insights/client/collection_rules.py, insights/client/map_components.py, insights/tests/client/collection_rules/test_map_components.py, insights/uploader_json_map.json
=> map files and commands to core components

insights/client/core_collector.py, insights/collect.py
=> load client config timeout in core

insights/util/file_permissions.py
=> Fix small docstring errors in util/file_permissions.py

insights/client/collection_rules.py, insights/tests/client/collection_rules/test_get_conf_file.py, insights/tests/client/test_collect.py
=> change to RuntimeError so it is caught by top level except

insights/specs/sos_archive.py
=> [Spec-Update] pcs_status spac updated to first_file.

insights/parsers/foreman_log.py, insights/parsers/tests/test_foreman_log.py, insights/specs/default.py
> Add candlepin_log to default specs
> Add time_format to CandlepinLog parser to support Milliseconds
> Fix Examples for other parsers in foreman_log module
=> Add Candlepin Log

insights/specs/default.py
The specs are present for sos_archive only. The specs are mandetory for insights-archive as well.
=> Added specs for insights archive

insights/parsers/neutron_conf.py
* Add additional filters that may not be added by rules to capture some
additional data
=> Add filters to neutron conf parser

docs/shared_parsers_catalog/neutron_sriov_agent.rst, insights/parsers/neutron_sriov_agent.py, insights/parsers/tests/test_neutron_sriov_agent.py, insights/specs/__init__.py, insights/specs/default.py
Add parser to provide the content of neutron
sriov agent configuration file.
=> Add parser for neutron sriov agent file

docs/shared_parsers_catalog/named_conf.rst, insights/parsers/named_conf.py, insights/parsers/tests/test_named_conf.py, insights/specs/__init__.py, insights/specs/default.py
Added
```
insights/parsers/named_conf.py
insights/parsers/tests/test_named_conf.py
docs/shared_parsers_catalog/named_conf.rst
```
Updated
```
```
=> Add parser NamedConf

insights/parsers/lvm.py
According to the spec: lvs_noheadings, The docstring for class Lvs needs to be updated
=> Update the docstring of Lvs

insights/specs/default.py, insights/specs/insights_archive.py
=> Restore ethtool -c specs for core collection

docs/shared_parsers_catalog/lsvmbus.rst, insights/parsers/lsvmbus.py, insights/parsers/tests/test_lsvmbus.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser to parse output of 'lsvmbus -vv'

insights/tests/client/test_client.py, insights/tests/client/test_utilities.py
=> remove invalid tests, mock some filesystem writes

docs/shared_parsers_catalog/designate_conf.rst, insights/parsers/designate_conf.py, insights/parsers/tests/test_designate_conf.py, insights/specs/__init__.py, insights/specs/default.py
=> Add designate parser

insights/specs/default.py
=> Add spec /proc/mounts into default.py

insights/uploader_json_map.json
Update the uploader.json map in the repo. We include the new version of this during releases for the production egg but don't currently have a way to keep it in sync in the repo, thus this manual update.
TODO: figure out a solution for that
=> update uploader.json map

insights/parsers/tests/test_yum_repos_d.py, insights/parsers/yum_repos_d.py
=> Update yum.repos.d parser to be less tolerant.

insights/parsers/tests/test_ls_etc.py, insights/specs/default.py, insights/specs/insights_archive.py
Added specs for "ls -lan /etc/rc.d/init.d". Used existing parser LsEtc.
=> Added specs and test cases for "ls -ln /etc/rc.d/init.d/"

insights/client/auto_config.py, insights/tests/client/auto_config/test_try_satellite5_configuration.py
=> make sure to add new arg for sat 5

insights/client/connection.py
=> check value of system fetch response

docs/shared_parsers_catalog/spamassassin_channels.rst, insights/parsers/spamassassin_channels.py, insights/parsers/tests/test_spamassassin_channels.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
Specs and parser for spamassassin channels.
=> Spamassassin channels parser

docs/shared_parsers_catalog/awx_manage.rst, insights/parsers/awx_manage.py, insights/parsers/tests/test_awx_manage.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py, insights/specs/sos_archive.py
=> New parser AnsibleTowerLicenseType

docs/shared_parsers_catalog/ipsec_conf.rst, insights/parsers/ipsec_conf.py, insights/parsers/tests/test_ipsec_conf.py, insights/specs/__init__.py, insights/specs/default.py
Added
```
insights/parsers/ipsec_conf.py
insights/parsers/tests/test_ipsec_conf.py
docs/shared_parsers_catalog/ipsec_conf.rst
```
Updated
```
```
=> Add spec ipsec_conf

docs/shared_parsers_catalog/libssh_config.rst, insights/parsers/libssh_config.py, insights/parsers/tests/test_libssh_config.py, insights/specs/__init__.py, insights/specs/default.py
Added
```
insights/parsers/libssh_config.py
insights/parsers/tests/test_libssh_config.py
docs/shared_parsers_catalog/libssh_config.rst
```
Updated
```
```
=> Add spec libssh_config

setup.py
=> Remove defunct entry_point references.

insights/client/data_collector.py, insights/contrib/soscleaner.py, insights/tests/client/data_collector/test_done.py, insights/tests/client/data_collector/test_redact.py
Rollback soscleaner to the version prior to commit of https://github.com/RedHatInsights/insights-core/pull/2527.
However, keep the metadata ignore that was added after the fact.
=> Rollback soscleaner

docs/shared_parsers_catalog/open_vm_tools.rst, insights/parsers/open_vm_tools.py, insights/parsers/tests/test_open_vm_tools.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
- New parser for command `vmware-toolbox-cmd stat raw text session`
=> New parser OpenVmToolsStatRawTextSession

insights/specs/default.py, insights/specs/insights_archive.py
=> Add more options to the "lvs" spec

docs/shared_parsers_catalog/mokutil_sbstate.rst, insights/parsers/mokutil_sbstate.py, insights/parsers/tests/test_mokutil_sbstate.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Spec and parser for mokutil command

insights/specs/sos_archive.py
=> Add 'firewall_cmd_list_all_zones' spec for sos archive

insights/combiners/cloud_provider.py, insights/combiners/tests/test_cloud_provider.py
* Added new cloud provider for IBM cloud
* Refactored combiner without changing public interface
* Updated tests and docs
=> Add new IBM cloud provider, refactor combiner

docs/shared_parsers_catalog/abrt_ccpp.rst, insights/parsers/abrt_ccpp.py, insights/parsers/tests/test_abrt_ccpp.py, insights/specs/__init__.py, insights/specs/default.py
Added  AbrtCCppConf  parser class for  /etc/abrt/plugins/CCpp.conf
=> Added parser for abrt CCpp.conf

insights/client/__init__.py
https://github.com/RedHatInsights/insights-core/issues/2721
=> Cleanup temp dir created for egg download (#2721)

insights/parsers/subscription_manager_list.py, insights/parsers/tests/test_subscription_manager_list.py
* Some gss rules have to check the raised exception to check specific
issue when subscription-manager can't work
=> Save the raised exception

docs/shared_parsers_catalog/dotnet.rst, insights/parsers/dotnet.py, insights/parsers/tests/test_dotnet.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> New parser for DotNetVersion

docs/shared_parsers_catalog/networkmanager_config.rst, insights/parsers/networkmanager_config.py, insights/parsers/tests/test_networkmanager_config.py, insights/specs/__init__.py, insights/specs/default.py
=> new parser networkmanager_config

MANIFEST.in
=> add uploader json map to manifest for build

insights/parsers/sap_hdb_version.py
=> Support insights-cat sap_hdb_version temporary

insights/combiners/rsyslog_confs.py, insights/combiners/tests/test_rsyslog_confs.py, insights/parsers/rsyslog_conf.py, insights/parsers/tests/test_rsyslog_conf.py, insights/specs/__init__.py, insights/specs/default.py
Reverts RedHatInsights/insights-core#2818
- The related rules are updated per this change. It can be merged now.
=> Revert "Revert "Add combiner for rsyslog_conf""

insights/__init__.py, insights/specs/must_gather_archive.py
* Adding new module for must gather archives
* Loading new module when running
=> Add specs for must gather archive context

insights/parsr/query/__init__.py
* There were already a couple of convenience functions in Result so this
just adds another
* This fixes #2798
=> Add line convenience method to parsr Result class

insights/client/apps/playbook_verify/__main__.py
=> fix(playbook verify): remove placeholder module

insights/combiners/tests/test_ps.py, insights/parsers/ps.py
=> Skip the 'grep -F' in ps in the first pass of parsing

insights/parsers/__init__.py, insights/parsers/tests/test_parsers_module.py
=> Skip None value when doing keyword_search

insights/parsers/alternatives.py, insights/parsers/tests/test_alternatives.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py, insights/specs/sos_archive.py
=> Add spec and parser for alternatives_display_python

insights/specs/default.py
=> Add spec "httpd limits" back

insights/specs/default.py, insights/specs/insights_archive.py
=> Add spec "corosync_cmapctl" back

docs/shared_parsers_catalog/satellite_content_hosts_count.rst, insights/parsers/satellite_content_hosts_count.py, insights/parsers/tests/test_satellite_content_hosts_count.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for the satellite clients count spec

insights/specs/default.py, insights/specs/insights_archive.py, insights/tests/client/collection_rules/test_map_components.py
=> Revert the saphostexec_status and saphostexec_version specs

insights/parsers/ceph_version.py
Update according https://access.redhat.com/solutions/2045583
=> Update ceph version mapping

docs/shared_parsers_catalog/ls_ipa_idoverride_memberof.rst, insights/parsers/ls_ipa_idoverride_memberof.py, insights/parsers/tests/test_ls_ipa_idoverride_memberof.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> New parser ls_ipa_idoverride_memberof

docs/shared_parsers_catalog/puppet_ca_cert_expire_date.rst, insights/parsers/puppet_ca_cert_expire_date.py, insights/parsers/tests/test_puppet_ca_cert_expire_date.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser to parse the puppet ca cert expire date

insights/specs/insights_archive.py
=> Bind first_file to HostArchiveContext in insights_archive.py

insights/specs/default.py
=> Add docstring for datasource "corosync_cmapctl_cmd_list"

insights/collect.py, insights/specs/default.py, insights/specs/insights_archive.py
* This command should only run on satellite server
=> Enhance "satellite_content_hosts_count" with @datasource

insights/specs/sos_archive.py
Newly added "lsblk -O -P" command outupt in
sosreport. (https://github.com/sosreport/sos/commit/a8dbdd2143f693758b4df76a615d06c85d8638fd)
=> Add sos archive spec - lsblk_pairs

insights/parsr/__init__.py, insights/parsr/tests/test_function_error.py
=> Show original exceptions for mapped or lifted functions.

docs/shared_parsers_catalog/yum_updateinfo.rst, insights/parsers/tests/test_yum_updateinfo.py, insights/parsers/yum_updateinfo.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
Refers to : https://gitlab.cee.redhat.com/insights-release-eng/insights-core-assets/-/issues/6
=> Add new parser - yum updateinfo

insights/specs/default.py
* Since these should only run when performing host collection, they need
to include the proper context
* HostContext should be used as an arg and not a kwarg
* Fixes #2908
=> Add HostContext to all custom datasources

insights/parsers/ip.py, insights/parsers/tests/test_ip.py
Parser updated to get the value of `promiscuity` item.
=> Enhanced parser insights/parsers/ip.py

insights/collect.py, insights/parsers/satellite_mongodb.py, insights/parsers/tests/test_satellite_mongodb.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for spec to get the count of non-yum type repos

docs/shared_parsers_catalog/ld_library_path.rst, insights/parsers/ld_library_path.py, insights/parsers/tests/test_ld_library_path.py, insights/specs/__init__.py, insights/specs/default.py
=> New parser for LD_LIBRARY_PATH of all PIDs

insights/specs/sos_archive.py
This adds sosreport path of virsh_list_all spec.
=> Add virsh_list_all spec path in sosreport

docs/shared_parsers_catalog/gfs2_file_system_block_size.rst, insights/collect.py, insights/parsers/gfs2_file_system_block_size.py, insights/parsers/tests/test_gfs2_file_system_block_size.py, insights/specs/__init__.py, insights/specs/default.py
=> Add spec to get the block size of gfs2 file system

insights/specs/insights_archive.py
=> Remove the sap_hdb_version from insights_archive.py

insights/specs/default.py
=> Check file existence state before opening it  in cloud_cfg datasource

docs/shared_parsers_catalog/ls_var_cache_pulp.rst, insights/parsers/ls_var_cache_pulp.py, insights/parsers/tests/test_ls_var_cache_pulp.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py
=> Add parser for spec "ls -lan /var/cache/pulp"

insights/core/filters.py, insights/tests/test_filters.py
=> Raise exceptions on empty filter strings

insights/contrib/soscleaner.py
=> fix: prevent soscleaner from erasing insights_archive.txt

insights/specs/default.py
* Check for presence of command on system before returning results to be
executed
* Make list of commands consistent for all executables
* Fix #2954
=> Fix problem with corosync_cmapctl_cmd_list datasource

insights/parsers/sealert.py, insights/parsers/tests/test_sealert.py
https://github.com/RedHatInsights/insights-core/issues/2951
=> Fix handling of edge cases for Sealert parser

insights/core/serde.py
* When deserializing a spec from an archive use ContentException instead
of Exception when file is missing from the archive
* Fix #2962
=> Use specific exception for missing archive spec

docs/shared_parsers_catalog/insights_client_conf.rst, insights/parsers/insights_client_conf.py, insights/parsers/tests/test_insights_client_conf.py, insights/specs/__init__.py, insights/specs/default.py
=> New spec and parser for insights-client.conf

insights/parsers/dmsetup.py, insights/parsers/tests/test_dmsetup.py, insights/specs/__init__.py, insights/specs/default.py, insights/specs/insights_archive.py, insights/specs/sos_archive.py
=> Add spec and parser for dmsetup_status

insights/parsers/cpuinfo.py, insights/parsers/tests/test_cpuinfo.py
=> Update microcode keyword check in the cpuinfo parser

insights/parsers/ld_library_path.py, insights/parsers/tests/test_ld_library_path.py, insights/specs/default.py
=> Update ld_library_path to check SAP users only

insights/combiners/sap.py, insights/combiners/tests/test_sap.py
=> Enhance Sap.local_instances to check either of Hostname or FQDN

docs/shared_combiners_catalog/lspci.rst, insights/combiners/lspci.py, insights/combiners/tests/test_lspci.py, insights/parsers/lspci.py
=> New Combiner LsPci for lspci commands

insights/combiners/logrotate_conf.py, insights/combiners/tests/test_logrotate_conf_tree.py
=> Fix bug where missing endscript caused an infinite loop.

insights/parsers/tests/test_tuned.py, insights/parsers/tuned.py
- Fixed: #2986 
- Refactored the examples in docstring, removed the deprecated `shared`
- Added test for doc
- Skip when empty
=> Enhance tuned list parser Tuned

insights/specs/sos_archive.py
=> [New-Spec] tuned_adm

insights/parsers/satellite_postgresql_query.py, insights/parsers/tests/test_satellite_postgresql_query.py, insights/specs/__init__.py, insights/specs/default.py
=> Add spec to get satellite compute resources

insights/core/context.py, insights/core/spec_factory.py, insights/specs/default.py, insights/util/subproc.py
* Need to apply #2630 for core collection
* Fixes bugzilla 1935846
=> Use SIGTERM for rpm and yum commands

insights/specs/insights_archive.py
* This spec is no longer collect by new clients but may still be
collected by older clients so adding back to support those
=> Add lssap spec to insights archives

insights/parsers/redhat_release.py, insights/parsers/tests/test_redhat_release.py
* Update parser to handle additional release strings
* Update documentation and tests
* Fix #2999
=> Update redhat-release parser to fix issues

insights/parsers/puppet_ca_cert_expire_date.py, insights/parsers/tests/test_puppet_ca_cert_expire_date.py
=> Extend CertificateInfo instead of duplicate code

insights/parsers/certificates_enddate.py, insights/parsers/tests/test_certificates_enddate.py, insights/specs/default.py
* Since it is to check expired date of certificates for several directories
by command find, even the directories don't exist, the command shouldn't fail
=> Update spec "certificates_enddate" to make it always success

insights/specs/default.py
* these two commands should still return even some file doen't exist
=> Update spec to make it always success
