- insights/specs/default.py
- insights/specs/sos_archive.py
* Remove unsupported poggresql conf and log path
* remove the path which is only supported in sosreport to sos_archive
> Update spec "postgresql_conf" and "postgresql_log"

- insights/parsers/mongod_conf.py
- insights/specs/default.py
/etc/opt/rh/rh-mongodb34/mongod.conf has same YAML format as of rh-mongodb26
> Add conf file path for rh-mongodb34 to mongod_conf

- insights/specs/insights_archive.py
> [spec] Add azure_instance_plan to archive specs

- insights/specs/default.py
- change to use "su" as per the suggestion from the customer
https://bugzilla.redhat.com/show_bug.cgi?id=1949056
> Use 'su' for sap_hdb_version instead of 'sudo'

- insights/parsers/azure_instance_plan.py
> [fix] Fix attribute in docs for azure_instance_plan

- docs/shared_parsers_catalog/sap_hana_python_script.rst
- insights/parsers/sap_hana_python_script.py
- insights/parsers/tests/test_sap_hana_python_script.py
- insights/specs/__init__.py
- insights/specs/default.py
- And refine the dependent Datasources and make them reusable
> New parser for sap_hana_landscape

- docs/shared_parsers_catalog/greenboot_status.rst
- insights/parsers/greenboot_status.py
- insights/parsers/tests/test_greenboot_status.py
- insights/specs/__init__.py
- insights/specs/default.py
> Collect /usr/libexec/greenboot/greenboot-status

- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/collection_rules/test_map_components.py
The spec is time-consuming, so I disable it.
Updated
```
insights/specs/insights_archive.py
```
> Disable the spec Lsinitrd

- insights/parsers/mongod_conf.py
- insights/parsers/tests/test_mongod_conf.py
> Update parser MongodbConf to support another dbPath format

- insights/ocp.py
- insights/ocpshell.py
> ocp and ocpshell supports yaml files with multiple docs

- docs/shared_parsers_catalog/pmrep.rst
- insights/parsers/__init__.py
- insights/parsers/pmrep.py
- insights/parsers/tests/test_pmrep.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> New parser pmrep command

- insights/parsers/tests/test_virsh_list_all.py
- insights/parsers/virsh_list_all.py
* The parser didn't account for error messages in the content, so I
updated it to exclude the error messages.
* Add test entry for error messages.
* Fix #3044
> Fix ValueError exception in virsh_list_all parser

- docs/shared_parsers_catalog/rpm_ostree_status.rst
- insights/parsers/rpm_ostree_status.py
- insights/parsers/tests/test_rpm_ostree_status.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> Collect `rpm-ostree status --json`

- insights/specs/__init__.py
- insights/specs/default.py
* Remove uesless spec
* Change glob_file to first_file
> Update mongod_conf spec

- insights/specs/default.py
- insights/specs/insights_archive.py
This is used to fix issue https://github.com/RedHatInsights/insights-core/issues/3065
> Update pmrep_metrics spec in insights_archive.py

- insights/parsers/uname.py
> Support RHEL 8.4 released on 18th May

- insights/specs/default.py
- insights/tests/client/collection_rules/test_map_components.py
> added vmware_tools_conf spec

- insights/parsers/greenboot_status.py
- insights/parsers/tests/test_greenboot_status.py
> Add fallback boot detected to GreenbootStatus

- insights/specs/default.py
* package_provides_java is duplicate with package_provides_command
> Remove "package_provides_java"

- .github/pull_request_template.md
* This template will help ensure that developers are providing the
necessary information to help maintainers review their PRs.
> Add a pull request template to the project

- CONTRIBUTING.md
* Update documentation to reference the new PR template that is
required to submit a new PR.
Provide complete details of the issue and how this PR fixes the issue. You can link to one or more existing open, publicly-accessible issue(s) that provide details.
This PR updates the CONTRIBUTING doc to include information about the new PR template added in #3089
> Update CONTRIBUTING to reference the PR template

- insights/specs/default.py
Provide complete details of the issue and how this PR fixes the issue. You can link to one or more existing open, publicly-accessible issue(s) that provide details.
Fixes #3095 
Provide complete details of the enhancement.
> Fix the command of gcp_license_codes

- CONTRIBUTING.md
This removes restructuredtext format `::` that was used in CONTRIBUTING.md which is a markdown format file.
> Correcting rst syntax in contributing md file

- insights/parsers/scheduler.py
- insights/parsers/tests/test_scheduler.py
When there is no active scheduler, the parser throws an exception.
This change fixes the problem.
> Fix exception thrown from Scheduler parser

- insights/core/context.py
- insights/parsers/httpd_M.py
- insights/parsers/httpd_V.py
- insights/parsers/tests/test_httpd_M.py
- insights/parsers/tests/test_httpd_V.py
- insights/tests/__init__.py
* Also add args interface for rule testing in InputData and Context
> Update parser "httpd_M" and "httpd_V" to return right binary path

- insights/parsers/foreman_log.py
- insights/parsers/tests/test_foreman_log.py
Provide complete details of the issue and how this PR fixes the issue. You can link to one or more existing open, publicly-accessible issue(s) that provide details.
Provide complete details of the enhancement.
Log format refferred from documentation https://httpd.apache.org/docs/2.4/logs.html
> Host and datetime parsing for ForemanSSLAccessLog

- insights/specs/default.py
> New spec to collect running httpd and corresponding pkg

- insights/client/config.py
- insights/tests/client/test_config.py
Fixes issue where using --unregister and --offline options together causes a traceback.
https://bugzilla.redhat.com/show_bug.cgi?id=1920946
> fix: disallow unregister in offline mode

- docs/api_index.rst
- docs/custom_datasources_index.rst
- docs/index.rst
- insights/collect.py
- insights/specs/datasources/cloud_init.py
- insights/specs/default.py
- insights/tests/datasources/test_cloud_init.py
- insights/util/specs_catalog.py
Establish a new pattern for the implementation of custom datasources using the cloud_cfg datasource
* Move this datasource out of default.py into its own module
* Create tests for this datasource
* Update documentation for all custom datasources
> Move cloud_cfg datasource into separate module

- insights/specs/__init__.py
* This spec is a glob spec and can collect multiple items so it needs to
be defined with `multi_output=True`
* Spec merged in PR #3112
* Fixes #3115
> Fix spec that will collect multiple data items

- docs/shared_parsers_catalog/ansible_tower_settings.rst
- insights/parsers/ansible_tower_settings.py
- insights/parsers/tests/test_ansible_tower_settings.py
- insights/specs/__init__.py
- insights/specs/default.py
As the spec gets approved, add back the parser
Reverts RedHatInsights/insights-core#3117
> Add parser ansible_tower_custom (#3102)

- insights/specs/datasources/ps.py
- insights/tests/datasources/test_ps.py
* Add tests for the new ps datasource
* Fix problem with possible leading lines before the headings in ps
datasource
> Add testing for ps datasource

- docs/custom_datasources_index.rst
- docs/shared_parsers_catalog/candlepin_broker.rst
- insights/parsers/candlepin_broker.py
- insights/parsers/tests/test_candlepin_broker.py
- insights/specs/__init__.py
- insights/specs/datasources/candlepin_broker.py
- insights/specs/default.py
- insights/tests/datasources/test_candlepin_broker.py
> Add parser for spec "/etc/candlepin/broker.xml"

- docs/shared_components_catalog/cloud_provider.rst
- insights/components/cloud_provider.py
Fixes: #3110 and update a bit description.
> Add doc entry for component cloud_provider

- docs/shared_components_catalog/ceph.rst
- insights/collect.py
- insights/components/ceph.py
- insights/components/tests/test_ceph.py
- insights/specs/default.py
Move the `is_ceph_monitor` to the component module.
> Change is_ceph_monitor as Component IsCephMonitor

- docs/custom_datasources_index.rst
- insights/specs/__init__.py
- insights/specs/datasources/__init__.py
- insights/specs/datasources/package_provides.py
- insights/specs/default.py
- insights/tests/datasources/test_get_running_commands.py
- insights/tests/datasources/test_package_provides.py
- insights/tests/test_specs.py
* Move datasource to separate module
* Update to fix issues in collecting data
* Add testing for datasource and functions
* Update docs
> Update datasource package_provides_command

- insights/specs/default.py
* Since the combiner "SatelliteVersion" and "CapsuleVersion" is already raises
SkipComponent if it is not satellite server or capsule, so use it directly
I want to separate datasource ""is_satellite_server" and "is_satellite_capsule", but I found the combiner "SatelliteVersion" and "CapsuleVersion" already raise SkipComponent if it is not satellite server or capsule, so use it directly.
> Remove "is_satellite_server" and "is_satellite_capsule"

- docs/custom_datasources_index.rst
- insights/specs/datasources/sap.py
- insights/specs/default.py
- insights/tests/datasources/test_sap.py
Move  the existing sap datasources to the new `insights.specs.datasource` module
> Move sap related datasource into new insights.specs.datasource module

- docs/manpages/insights-run.rst
- insights/__init__.py
- insights/core/plugins.py
- insights/formats/html.py
- insights/formats/text.py
- insights/tests/test_rules_fixture.py
* Changes how rules that return none are handled. Instead of raising a
SkipComponent and ignoring the rule, they will now be counted in the
results.
* Add a make_none response type
* Update formatters to handle the new type
* Update tests
* Fix #3026
> Add make_none response for rules

- insights/formats/__init__.py
- insights/formats/_json.py
- insights/formats/_markdown.py
- insights/formats/_yaml.py
- insights/formats/text.py
This PR is trying to let the `insights-run` to support filtering the rule result. See the details in the Jira card `INSGHTCORE-103`
> Add new option '--show-rules' to insights-run

- insights/combiners/lspci.py
- insights/combiners/tests/test_lspci.py
> Combiner LsPci should not modify Parser LsPci*

- insights/formats/__init__.py
- insights/formats/_json.py
- insights/formats/_markdown.py
- insights/formats/_yaml.py
- insights/formats/text.py
Reverts RedHatInsights/insights-core#3154 due to #3161
> Revert "Add new option '--show-rules' to insights-run"

- insights/specs/default.py
Signed-off-by: Rahul <rasrivas@redhat.com>
This MR is related to adding the spec for the dnsmasq_config parser and DnsmasqConfTree combiner.
> New spec dnsmasq_config for the dnsmasq_config parser and DnsmasqConfTree combiner

- insights/specs/sos_archive.py
-c option was added years back https://github.com/sosreport/sos/commit/30445cdbeac07bd23e37f7dab81a72be1382fe6d
Recent change to remove -b https://github.com/sosreport/sos/commit/5d87a4db0a24f879e92611e09475ae652fa4dff9
> Add spec paths for Lsof in sosreport

- insights/client/apps/ansible/playbook_verifier/__init__.py
- insights/client/apps/ansible/playbook_verifier/__main__.py
Turn on playbook validation now that all templates have been successfully signed.  
NOTE:  Wait to Push this until it is ready, I'll swap from draft PR to real PR when that time is right.
> RHCLOUDTurn playbook validation on

- insights/formats/__init__.py
- insights/formats/_json.py
- insights/formats/_markdown.py
- insights/formats/_yaml.py
- insights/formats/text.py
This PR makes the `insights-run` to support filtering the rule result. See the details in the Jira card `INSGHTCORE-103`
And fixed the issue #3161
> Add new option '--show-rules' to insights-run 

- insights/parsers/foreman_log.py
- insights/parsers/tests/test_foreman_log.py
- insights/specs/__init__.py
- insights/specs/default.py
> New spec "/var/log/httpd/foreman-ssl_error_ssl.log"

- insights/tests/datasources/test_candlepin_broker.py
* This fixes testing issues with python 3.8 and the latest pytest where
the order of attributes changes in the XML tags.
* The new test doesn't compare everything, but compares most things
including removal of sensitive tags.
> Update candlepin_broker tests to work with newer python pytest

- setup.py
Update setup.py to support tests for multiple versions of python
* For testing only specify python module version requirements based on the python version
> Update setup.py for multiple versions of python

- insights/parsers/satellite_postgresql_query.py
- insights/parsers/tests/test_satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> New spec to get if SCA is enabled on satellite

- insights/parsers/lsof.py
- insights/parsers/tests/test_lsof.py
* Refactor code using iter/next to avoid functions deprecated by PEP 479
* Add tests
* Replaces the fixes attempted in #3185 
> Fix iter/next code in lsof

- insights/specs/default.py
Add the spec for "mssql_api_assessment" as the output file is decided.
> Add default spec mssql_api_assessment

- insights/parsers/cups_ppd.py
- insights/parsers/tests/test_cups_ppd.py
Current recognize the line containing "*" as valid content, however, line starting with "*%" is comment. Update code to handle following content:
~~~
*% Copyright 2007-2014 by Apple Inc.
~~~
> Enhance parser cups_ppd

- insights/specs/datasources/lpstat.py
- insights/tests/datasources/test_lpstat.py
Update datasource lpstat to handle more kinds of output
> Enhance datasource lpstat

- insights/collect.py
- insights/combiners/hostname.py
- insights/combiners/tests/test_hostname.py
- insights/combiners/tests/test_sap.py
- insights/combiners/tests/test_uptime.py
- insights/combiners/uptime.py
- insights/specs/default.py
- insights/tests/datasources/test_sap.py
* We will no longer collect facter due to issues documented in Bugzilla 1989655
* Update combiners to remove dependency
* Remove spec from HostContext collection
* Update tests
> Stop collection of facter and remove dependencies

- insights-core.spec
* Update the requires entries in the rpm spec file to allow building it
on el7. Since a lot of the packages start with python36 on el7.
* Added the missing CacheControl and pyyaml requirements.
I added a check for el7 in the rpm spec, so that the requirement package names are correct since for el7 a lot of python3 packages start with python36. Also added in the missing CacheControl and pyyaml requirements. This change is for the master branch only please don't cherry pick this PR I will open a separate PR for the 3.0 branch.
> [master] Update requires in core rpm spec for el7

- insights/combiners/httpd_conf.py
- insights/combiners/tests/test_httpd_conf_tree.py
- insights/parsr/__init__.py
Fixes https://github.com/RedHatInsights/insights-core/issues/3211
> Fix bug about some httpd directives may have empty string as attribute

- docs/shared_parsers_catalog/ros_config.rst
- insights/parsers/ros_config.py
- insights/parsers/tests/test_ros_config.py
- insights/specs/__init__.py
- insights/specs/default.py
> Add config.ros parser

- docs/shared_combiners_catalog/ansible_info.rst
- insights/combiners/ansible_info.py
- insights/combiners/tests/test_ansible_info.py
* Add new combiner to collect ansible info for fingerprinting an ansible system
* Add documentation and tests
> Add combiner for ansible information

- docs/custom_datasources_index.rst
- insights/specs/datasources/yum_updates.py
Signed-off-by: mhornick <mhornick@redhat.com>
Fixes #3223
> Add yum_updates to documentation

- docs/api.rst
Fixing broken sosreport link (Doc change)
> Fixing broken sosreport link

- insights/parsers/awx_manage.py
- insights/parsers/tests/test_awx_manage.py
- insights/specs/default.py
- insights/specs/insights_archive.py
Signed-off-by: Rahul <rasrivas@redhat.com>
This PR is for the `awx_manage` parser enhancement to return values of the `LOG_AGGREGATOR_ENABLED` and`LOG_AGGREGATOR_LEVEL` parameter as well.
> Enhance awx_manage spec

- insights/parsers/nfnetlink_queue.py
- insights/parsers/tests/test_nfnetlink_queue.py
Replace the assert check with if statement and raise a parse exception if met. Updated the parse to inherit from a list, and added the data property for backwards compatibility. Moved the docstring from the top to within the class. Updated the test to look for parse and skip exceptions instead of assertion errors.
> Update the nfnetlink parser

- insights/parsers/mdstat.py
- insights/parsers/tests/test_mdstat.py
Went through and replaced all asserts with if statements that raise parse exceptions if not met. This required several logic updates due to how the asserts were used. Updated the doc strings of each function so they were uniform. Updated the test to check for parse exceptions instead of assertion errors, also added a couple additional test.
> Update mdstat parser to remove asserts

- insights/tests/client/collection_rules/test_map_components.py
* PR #3258 changed the certificates_enddate spec that caused this client test to fail
* This updates the command wrapping so that the test will work
> Fix: Fix issue in client test due to spec change

- insights/parsers/system_time.py
- insights/parsers/tests/test_system_time.py
> Fix: check 'tab' in lines of ntp.conf

- docs/custom_datasources_index.rst
- insights/collect.py
- insights/parsers/ssl_certificate.py
- insights/parsers/tests/test_ssl_certificate.py
- insights/specs/__init__.py
- insights/specs/datasources/ssl_certificate.py
- insights/specs/default.py
- insights/tests/datasources/test_ssl_certificate.py
This parser is used by a insights rule to check mssql tls expiration date.
> Add parser mssql_tls_file

- CHANGELOG.md
The CHANGLOG.md is missed in the last tag/release with tito.
> fix: adding the missed CHANGELOG

- insights/collect.py
- insights/combiners/redhat_release.py
- insights/combiners/tests/test_redhat_release.py
- insights/components/rhel_version.py
- insights/components/tests/test_rhel_version.py
- insights/parsers/grub_conf.py
- insights/specs/default.py
Updated the rhel_version component to have a base class that the other classes inherit to cut down on the duplicate code. Added the IsRhel9 component check. Added rhel9 checks to the redhat_release combiner. Added the IsRhel9 check for the BootLoaderEntries parser. Added the IsRhel9 check for the corosync_cmapctl_cmd_list datasource, and added IsRhel9 to the collect manifest for the corosync_cmapctl_cmd_list datasource.
> Add in IsRhel9 component

- insights/specs/default.py
These spec paths are different on RHEL8
> Fix: Enhance some spec path

- docs/quickstart_insights_core.rst
Create a new section for project development setup.
Moved the insights core setup to that new section and added a new subsection to deploy the insights client development.
> Added new section for client development

- insights/parsers/lpstat.py
- insights/parsers/tests/test_lpstat.py
There is this format existing: "device for savtermhpc: implicitclass:savtermhpc", this PR is used to handle this format.
> Enhance parser LpstatProtocol

- insights/parsers/satellite_postgresql_query.py
- insights/parsers/tests/test_satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
> feat: New spec to get the count of satellite tasks with reserved resource

- insights/parsers/satellite_postgresql_query.py
- insights/parsers/tests/test_satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
> feat: New spec to get satelltie empty url repositories

- insights/specs/datasources/ssl_certificate.py
- insights/tests/datasources/test_ssl_certificate.py
> Fix: Only get "SSLCertificateFile" when "SSLEngine on" is configured

- insights/specs/default.py
* It is deleted before by bob since it isn't used in any rule.
But now I'll use it in one rule, so add it back now.
> chore: Add spec "foreman_production_log" back.

- insights/parsers/__init__.py
- insights/parsers/tests/test_parsers_module.py
This PR targets to enhance the `calc_offset` and let it support checking all the target items being in the line.
> feat: enhance calc_offset to support check all target in line

- insights/parsers/satellite_postgresql_query.py
- insights/parsers/tests/test_satellite_postgresql_query.py
> Fix: Enhance parser "SatellitePostgreSQLQuery"

- insights/parsers/systemctl_show.py
- insights/parsers/tests/test_systemctl_show.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> feat: New spec to get all services which enabled CPUAccounting

- docs/shared_parsers_catalog/losetup.rst
- insights/parsers/losetup.py
- insights/parsers/tests/test_losetup.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
Signed-off-by: Takayuki Nagata <tnagata@redhat.com>
This parser is used by a insights rule to check configured loop back devices, its back end files and 'DIO' flags.
> feat: New spec and parser for losetup -l

- insights/parsers/hammer_ping.py
- insights/parsers/tests/test_hammer_ping.py
> fix: Enhance hammer_ping parser

- insights/client/config.py
This PR modifies the message of the group parameter given by the help command in insights-client. The previous message wasn't correct as you can add a group in any time, not only during registration.
This PR fixes the Jira ticket ESSNTL-439, and has been manually checked.
> 🐛 new message for --group in client

- docs/shared_parsers_catalog/db2.rst
- insights/parsers/db2.py
- insights/parsers/tests/test_db2.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
This PR added a new spec and parser for the command "db2ls -a -c".
> New parser for Db2ls

- insights/parsers/ps.py
- insights/parsers/tests/test_ps.py
In sosreports the ps auxwwwm is used as the primary ps output now, the -m adds in all of the threads spawned per process. I added the thread count to the pid_info dictionary, and handled the stat column that's only in the thread lines.
> feat: Add thread counts to ps's pid_info dict

- insights/combiners/satellite_version.py
- insights/combiners/tests/test_satellite_version.py
> fix: Enhance combiner "SatelliteVersion" and "CapsuleVersion"

- insights/combiners/satellite_version.py
- insights/combiners/tests/test_satellite_version.py
* Sometimes satellite will register to itself, in this case,
we also need to identify it's a satellite server.
> fix: Enhance combiner "SatelliteVersion"

- insights/combiners/satellite_version.py
- insights/combiners/tests/test_satellite_version.py
> Revert satellite version enhancement and Enhance "CapsuleVersion" only

- insights/specs/datasources/yum_updates.py
- insights/tests/datasources/test_yum_updates.py
fixing bugzilla bug #2055163
Signed-off-by: Michael Mraka <michael.mraka@redhat.com>
fixing bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=2055163
> skip code on RHEL8.4 because of caching bug

- insights/contrib/soscleaner.py
- insights/tests/test_soscleaner.py
> fix: Fix the regression bug of soscleaner IP obsfuscating

- insights/specs/datasources/yum_updates.py
The code had an issue where it was looping over the dictionary updates that was being updated in another loop. So it was checking the beginning pkgs over and over each loop for updates which was un-necessary and caused the slowness. So I simplified the code down to the least amount of looping and variables.
> fix: Fix slowness on RHEL 8 by simplifying looping over pkgs

- docs/shared_parsers_catalog/ktimer_lockless.rst
- insights/parsers/ktimer_lockless.py
- insights/parsers/tests/test_ktimer_lockless.py
- insights/specs/__init__.py
- insights/specs/default.py
Signed-off-by: Rahul Srivastava <rasrivas@redhat.com>
Parser to parse the output of file `/sys/kernel/ktimer_lockless_check`
> New parser ktimer_lockless

- insights/parsers/satellite_postgresql_query.py
- insights/parsers/tests/test_satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> feat: New spec to get satellite repos with multiple reference

- insights/parsers/pcs_status.py
- insights/parsers/tests/test_pcs_status.py
> fix: Enhance "PCSStatus" to make it compatible with new output format

- insights/parsers/sys_module.py
- insights/parsers/tests/test_sys_module.py
- insights/specs/__init__.py
- insights/specs/default.py
> feat: New parser Ql2xmqSupport for /sys/module/qla2xxx/parameters/ql2xmqsupport

- insights/specs/default.py
> Only collect "*.conf" for nginx

- docs/shared_parsers_catalog/bdi_read_ahead_kb.rst
- insights/parsers/bdi_read_ahead_kb.py
- insights/parsers/tests/test_bdi_read_ahead_kb.py
- insights/specs/__init__.py
- insights/specs/default.py
> Add parser bdi_read_ahead_kb for '/sys/class/bdi/*/read_ahead_kb' files

- docs/shared_parsers_catalog/nginx_log.rst
- insights/parsers/nginx_log.py
- insights/parsers/tests/test_nginx_log.py
- insights/specs/__init__.py
- insights/specs/default.py
Signed-off-by: Rahul Sharma <rahushar@redhat.com>
Add new spec and parser to parse contents of nginx log file `/var/log/nginx/error.log`
> Feat: Add spec and parser for 'nginx_log'

- insights/parsers/satellite_postgresql_query.py
- insights/parsers/tests/test_satellite_postgresql_query.py
> fixes: the last login time is considered as DB query result

- insights/parsers/uname.py
Kernel version: kernel-4.18.0-372.9.1.el8.x86_64.rpm
> feat: RHEL 8.6 is GA

- insights/parsers/uname.py
- insights/tests/parsers/test_uname.py
> fix: Handle the value in kernel-alt pkg

- insights/parsers/sysconfig.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/sos_archive.py
- insights/tests/parsers/test_sysconfig_doc_examples.py
- insights/tests/parsers/test_sysconfig_nfs.py
Add spec and parser for file '/etc/sysconfig/nfs' .
> Add spec and parser for file '/etc/sysconfig/nfs'

- insights/combiners/ceph_version.py
- insights/parsers/ceph_version.py
- insights/tests/parsers/test_ceph_version.py
- Add the new versions of ceph
- Replace the use of "regex" instead of the general splitting operations
- Remove the loading of parser module from the combiner
> feat: New ceph version and enhance

- insights/parsers/redhat_release.py
- insights/tests/parsers/test_redhat_release.py
* Add new check and attributed for Alpha releases
* Add test and documentation for new attribute
> Add Alpha to redhat release detection

- docs/custom_datasources_index.rst
- insights/specs/datasources/corosync.py
- insights/specs/datasources/httpd.py
- insights/specs/datasources/md5chk.py
- insights/specs/default.py
- insights/tests/datasources/test_corosync.py
- insights/tests/datasources/test_httpd.py
> refactor: move the rest of datasource to the datasources dir

- docs/shared_parsers_catalog/nfs_conf.rst
- insights/parsers/nfs_conf.py
- insights/parsers/sysconfig.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_nfs_conf.py
Add new spec and parser for file /etc/nfs.conf .
> Add new parser for /etc/nfs.conf

- insights/specs/default.py
* Fixes the CI release conflict with uploader.json
* We'll replace all the old specs with new filtered spec together with uploader.json later.
> fixes: Recover "modinfo_xxx" specs

- insights/combiners/modinfo.py
- insights/parsers/modinfo.py
- insights/tests/combiners/test_modinfo.py
> feat: Add combiner "ModulesInfo"

- insights/parsers/nmcli.py
- insights/tests/parsers/test_nmcli.py
> fix: Enhance nmcli

- docs/shared_parsers_catalog/wc_proc_1_mountinfo.rst
- insights/parsers/wc_proc_1_mountinfo.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_wc_proc_1_mountinfo.py
Add new spec and parser for file `/proc/1/mountinfo`.
> Add spec and parser for 'wc_-l_.proc.1.mountinfo'

- insights/collect.py
Add pre-check for teamdctl_state_dump
> Fix: Add pre-check for teamdctl_state_dump

- docs/custom_datasources_index.rst
* Some custom datasources were missing from the docs build those have been added
> doc: Add missing datasource docs to build

- docs/api.rst
The guidelines, examples and the release timeline will help developers to plan the function
deprecation w.r.t the insights-core release cycle.
* [] Is this PR to correct an issue?
> Add release timeline

- docs/custom_datasources_index.rst
- insights/collect.py
- insights/specs/datasources/httpd.py
- insights/specs/default.py
- insights/tests/datasources/test_httpd.py
- insights/tests/datasources/test_package_provides.py
- fix  #3503 
There are existing rules depends on this spec
> fix: Revert the httpd_on_nfs datasource spec

- insights/specs/default.py
> Fix: grubenv cannot be collected when error shown in output

- insights/parsers/ls_systemd_units.py
- insights/specs/default.py
Updating paths for `ls_systemd_units` parser. These paths are probably unused, but we want to keep them just in case. Relevant MR in insights-core-assets is !464.
> Update ls_systemd_units parser

- insights/parsers/satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_satellite_postgresql_query.py
New spec to get satellite logs table size and its parser
> feat: New spec to get satellite logs table size and its parser

- docs/shared_parsers_catalog/cron_jobs.rst
- insights/parsers/cron_jobs.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_cron_jobs.py
New spec "/etc/cron.d/foreman" and its parser
> feat: New spec "/etc/cron.d/foreman" and parser

- insights/specs/datasources/corosync.py
- fix: [bz-2130242](https://bugzilla.redhat.com/show_bug.cgi?id=2130242), remove the unused print statement
> fix: bz-2130242, remove the print statement

- docs/custom_datasources_index.rst
- insights/__init__.py
- insights/collect.py
- insights/combiners/nginx_conf.py
- insights/core/__init__.py
- insights/core/context.py
- insights/core/spec_factory.py
- insights/parsers/docker_list.py
- insights/parsers/nginx_conf.py
- insights/parsers/podman_list.py
- insights/parsers/redhat_release.py
- insights/specs/__init__.py
- insights/specs/datasources/container/__init__.py
- insights/specs/datasources/container/nginx_conf.py
- insights/specs/default.py
- insights/tests/combiners/test_nginx_conf.py
- insights/tests/combiners/test_redhat_release.py
- insights/tests/parsers/test_nginx_conf.py
- insights/tests/parsers/test_redhat_release.py
- Support collecting specs from containers
- Added basic classes `ContainerParser` and `ContainerConfigCombiner`
- Added `redhat_release` spec and `ContainerRedhatRelease` parser for container
- Added `nginx_conf` spec and `ContainerNginxConfTree` combiner for container
> feat: [PoC] Support Container Specs

- docs/shared_parsers_catalog/mpirun.rst
- insights/parsers/mpirun.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_mpirun.py
*Adding a Specs for Advisory rule mpirun_version*
> [New-parser] parser_mpirun_version

- insights/tests/datasources/container/test_nginx_conf.py
- insights/tests/datasources/container/test_running_rhel_containers.py
Add tests for the existing container specs
> test: add test for existing container specs

- docs/shared_parsers_catalog/subscription_manager.rst
- insights/parsers/subscription_manager.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_subscription_manager.py
New spec and parser for `subscription-manager facts`.
- Will implement a combiner `CloudInstance` once other specs related to cloud instance are finished.
> feat: new spec and parser for 'subscription-manage facts' 

- insights/core/serde.py
- insights/tests/test_add_exception.py
- insights/tests/test_serde.py
> fix: values of broker.tracebacks should be string

- docs/shared_parsers_catalog/fapolicyd_rules.rst
- insights/parsers/fapolicyd_rules.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_fapolicyd_rules.py
feat: New spec "/etc/fapolicyd/rules.d/*.rules" and parser
> feat: New spec "/etc/fapolicyd/rules.d/*.rules" and parser

- docs/shared_combiners_catalog/cloud_instance.rst
- insights/combiners/cloud_instance.py
- insights/tests/combiners/test_cloud_instance.py
A new combiner `CloudInstance` combines the basic information for a cloud instance.
> feat: New Combiner CloudInstance

- insights/core/dr.py
- insights/core/plugins.py
- insights/core/serde.py
- insights/specs/datasources/container/__init__.py
- insights/tests/datasources/test_datasource_timeout.py
- insights/tests/test_add_exception.py
* Added timeout using signals in the datasource invoke function, when the timeout is hit it raises a TimeoutException.
> feat: Add timeout to datasources

- insights/parsers/date.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_date.py
feat: New spec "timedatectl" and the parser
> feat: New spec "timedatectl" and the parser

- insights/parsers/uname.py
see https://access.redhat.com/articles/3078
RHEL 9.1 is GA.
> feat: RHEL 9.1 is GA

- .github/workflows/main.yml
- https://github.com/actions/setup-python/issues/401
Signed-off-by: Chen lizhong <lichen@redhat.com>
> test: use ubuntu 20.04 instead of latest as the issue in latest

- setup.py
Pin the module versions to fix the docs build.
> fix: Update the pinned doc modules

- insights/specs/default.py
Add nginx error log which is installed from RHSCL
> Add nginx error log which is installed from RHSCL

- docs/shared_parsers_catalog/ls_var_lib_rsyslog.rst
- insights/parsers/ls_var_lib_rsyslog.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_ls_var_lib_rsyslog.py
feat: New spec "ls -lZ /var/lib/rsyslog" and the parser 
> feat: New spec "ls -lZ /var/lib/rsyslog" and the parser

- docs/shared_parsers_catalog/cpu_online.rst
- insights/parsers/cpu_online.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_cpu_online.py
This spec is used to add container check on one insights-plugins advisor rule
> feat: Add container spec sys_cpu_online

- insights/parsers/grubby.py
- insights/tests/parsers/test_grubby.py
> Fix: fix parser GrubbyDefaultKernel cannot handle invalid content

- insights/core/dr.py
This lets systems that process many archives load and order components once instead of on every analysis.
Fixes #3648
> Allow callers to order components for execution.

- insights/combiners/rhel_for_edge.py
- insights/tests/combiners/test_rhel_for_edge.py
Reverts RedHatInsights/insights-core#3634
> Revert "Fix: Add condition to check the output of "rpm-ostree status" firstly"

- insights/parsers/installed_rpms.py
Signed-off-by: Chenlizhong <lichen@redhat.com>
To fix the issue https://github.com/RedHatInsights/insights-core/issues/3650
Check the content first to determine from_json or from_list, this will improve the performance.
> fix: check the content first in class InstalledRpms

- insights/parsers/jboss_version.py
- insights/tests/parsers/test_jboss_version.py
Signed-off-by: Chen lizhong <lichen@redhat.com>
Add parser for datasource jboss_runtime_versions
https://github.com/RedHatInsights/insights-core/pull/3600
> feat: add JbossRuntimeVersions parser

- insights/specs/default.py
- insights/specs/insights_archive.py
> fix: add '-d 2' to yum_repolist spec

- insights/tests/test_canonical_facts.py
- insights/util/canonical_facts.py
- Add the CloudInstance and OSRelease for puptoo (Advisor UI)
- for details see ESSNTL-3114 (for CloundInstance)
> feat: add CloudInstance to canonical_facts

- docs/shared_parsers_catalog/sos_conf.rst
- insights/parsers/sos_conf.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_sos_conf.py
New spec "/etc/sos.conf" and its parser
> feat: New spec "/etc/sos.conf" and its parser

- insights/parsers/rpm_pkgs.py
- insights/specs/datasources/rpm_pkgs.py
- insights/tests/datasources/test_rpm_pkgs.py
- insights/tests/parsers/test_rpm_pkgs.py
This PR udpates datasource logic to provide additional information about packages. The original `RpmPkgs` parser was replaced by `RpmPkgsWritable` parser.
> Update rpm_pkgs datasource and create its new parser

- insights/parsers/mssql_api_assessment.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_mssql_api_assessment.py
Add this spec/parser to container support into mssql api rules.
> feat: Add container spec mssql_api_assessment

- insights/parsers/sys_block.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_sys_block.py
New spec and parser for glob file: `/sys/block/*/queue/stable_writes`
> feat: New spec and parser for sys_block_queue_stable_writes

- insights/parsers/installed_rpms.py
- https://access.redhat.com/security/team/key/
- Update the Package signing keys  according to https://access.redhat.com/security/team/key/
- And turn them to all lower cases
> chore: update the latest package signing keys

- insights/core/dr.py
- not only for ParseExceptions
- use log.debug instead of log.warning
to avoid printing the info to the console
- record the detailed traceback info to broker.exceptions
which will also be put into the meta_data later
and record the TB accurately to the actual spec register entry
- fix INSGHTCORE-185 and INSGHTCORE-188
> fix: print short info only for all Exceptions

- docs/custom_datasources_index.rst
- docs/shared_parsers_catalog/machine_id.rst
- insights/parsers/machine_id.py
- insights/specs/__init__.py
- insights/specs/datasources/machine_ids.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/datasources/test_machine_ids.py
- insights/tests/parsers/test_machine_id.py
> feat: New spec to get the duplicate machine id 

- insights/specs/default.py
- insights/specs/insights_archive.py
> New spec "ls -lan /etc/selinux/targeted/policy"

- insights/core/spec_factory.py
- some tiny updates to remove unused code from sepc_factory.py and a bit of simplify
> chore: tiny simplify and remove unused code in spec_factory.py

- insights/client/apps/compliance/__init__.py
Follow-up on https://github.com/RedHatInsights/insights-core/pull/3721 with a KB article link to explain the issue.
> feat: RHICOMPL-3706 add link to KB article about OOM issues

- insights/core/evaluators.py
To fix below kind of list index error. 
self.release = broker[Specs.redhat_release].content[0].strip()\n", "IndexError: list index out of range
> fix: check content before use it

- insights/parsers/blacklisted.py
- update the spec in docstring per #3723
> doc: update the file name of BlacklistedSpecs in doc

- docs/shared_parsers_catalog/repquota.rst
- insights/parsers/repquota.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_repquota.py
New parser for 'repquota -agnpuv' command
> Feat: New parser for repquota command

- insights/client/connection.py
- insights/tests/client/support/test_collect_support_info.py
_legacy_apy_registration_check checks if the system is registered or not. The server can response:
1. A 200 status, telling the system is registered. Unless if the "unregistered_at" parameter is not null. In that case the system is unregistered. 
2. A 404 status with a json telling the system is not registered. 
3. Other status error, telling the HTTPS connection faced some problems.
This commit adds a condition to only check the json response if the status code is 200 or 404 which means the server has information about the registration status of the system.
1. If it is unregistered the .unregistered file is created and machine-id and .registered files don't exists in the system
2. If it is registered both .registered and machine-id file are in the system and the …
> Fix check registration status to be robust against network failures

- insights/parsers/ip.py
- insights/tests/parsers/test_ip.py
> feat: add "vf_enabled" parse for spec ip_s_link

- insights/specs/default.py
- insights/specs/insights_archive.py
A new advisor rule requests to check the files from findutils package.
> fix: Add new package findutils into spec rpm_V_packages

- insights/parsers/rpm_pkgs.py
- insights/specs/datasources/rpm_pkgs.py
- insights/tests/datasources/test_rpm_pkgs.py
- insights/tests/parsers/test_rpm_pkgs.py
> fix: datasource rpm_pkgs returns list of string but not tuple

- insights/contrib/soscleaner.py
> fix: soscleaner get relative_path safely

- insights/parsers/auditd_conf.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/sos_archive.py
- insights/tests/parsers/test_auditd_conf.py
Add new spec and parser for file `/etc/audisp/audispd.conf`
> feat: add spec and parser for /etc/audisp/audispd.conf

- insights/tests/__init__.py
Use log.warning() instead of print()
> fix: use log instead of print in test.run_input_data

- insights/client/client.py
- insights/client/constants.py
- insights/tests/client/test_client.py
Reverts RedHatInsights/insights-core#3702
> Revert "feat: logrotate client implementation"

- insights/parsers/installed_rpms.py
- insights/tests/parsers/test_installed_rpms.py
> fix: handle the first line is warning in InstalledRpms

- insights/parsers/cpuinfo.py
- insights/parsers/installed_rpms.py
- insights/parsers/rpm_pkgs.py
- RpmPkgs was deprecated, but the deprecated function was forgotten.
> chore: add the missed deprecate warnings

- insights/parsers/gluster_peer_status.py
- insights/tests/parsers/test_gluster_peer_status.py
> fix: Unhandled 'Connection failed' in 'gluster_peer_status' parser

- insights/specs/default.py
After the data collection and data analysis, the plugin that uses this spec is abandoned because there is no hit. Then the spec is useless too.
> Remove spec lsinitrd_lvm_conf

- insights/parsers/parted.py
- insights/tests/parsers/test_parted.py
Resolve https://github.com/RedHatInsights/insights-core/issues/3783
> fix: fix IndexError in PartedL

- insights/parsers/machine_id.py
- insights/parsers/repquota.py
- insights/tests/parsers/__init__.py
- insights/tests/parsers/test_machine_id.py
- insights/tests/parsers/test_repquota.py
- `SkipException` is deprecated and will be removed soon
- Replace it with the `SkipComponent`
> fix: Replace SkipException with SkipComponent

- insights/parsers/uname.py
> feat: uname supports RHEL 9.2

- docs/shared_parsers_catalog/cups_confs.rst
- insights/parsers/cups_confs.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_cups_confs.py
> Feat: Add new parser CupsdConf

- insights/parsers/cups_confs.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_cups_confs.py
Add new parser CupsFilesConf for insights rule
> Feat: Add new parser CupsFilesConf

- insights/specs/default.py
- insights/specs/insights_archive.py
> Remove useless postgresql queries

- insights/parsers/satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_satellite_postgresql_query.py
> feat: New spec to get RHV hosts count on satellite and its parser

- insights/parsers/systemctl_status_all.py
- insights/specs/default.py
- insights/tests/parsers/test_systemctl_status_all.py
- see INSPEC-401
This spec was ever collected, this PR will add it back
And add attributes to the existing Parser
> feat: update SystemctlStatusAll and add its spec back

- insights/tests/__init__.py
- insights/tests/test_util.py
- check the missing components by passing them to the "expected"
- do not break the existing tests
- see RHINRULE-283
> feat: enhance test to check the missing components

- insights/collect.py
- insights/specs/default.py
remove spec ls_rsyslog_errorfile
> Feat: remove spec ls_rsyslog_errorfile

- docs/shared_parsers_catalog/etc_machine_id.rst
- insights/parsers/etc_machine_id.py
- insights/tests/parsers/test_etc_machine_id.py
> FEAT: Add new parser EtcMachineId

- insights/specs/default.py
- insights/specs/insights_archive.py
> Feat: new spec "ls -lan /etc/watchdog.d/"

- insights/parsers/satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_satellite_postgresql_query.py
* Also fix wrong database name in sql
> feat: New spec to get repos which ingores source rpms on Satellite

- insights/parsers/sysconfig.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_sysconfig_doc_examples.py
- insights/tests/parsers/test_sysconfig_stonith.py
> Feat: new spec "/etc/sysconfig/stonith" and its parser

- docs/shared_parsers_catalog/watchdog_logs.rst
- insights/core/__init__.py
- insights/parsers/watchdog_logs.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_watchdog_logs.py
> Feat: new spec "/var/log/watchdog/*" and the parser

- .github/workflows/main.yml
> fix: Build python26 instead of install

- insights/parsers/yumlog.py
- insights/specs/__init__.py
- insights/tests/parsers/test_yumlog.py
- see: ESSNTL-4697
- and update the Parsers implementation
- The updates of this PR keep backward compatiblity
> feat: change Specs.yumlog to filterable=True

- .github/workflows/main.yml
- insights/tests/client/apps/test_malware_detection.py
- https://github.com/actions/setup-python/issues/672
> fix: CI test for python27

- insights/specs/sos_archive.py
Newer sos versions put container output under /host in the root of the sosreport archive.
> fix: Add /host prefix to a few specs

- insights/parsers/subscription_manager.py
- insights/tests/combiners/test_cloud_instance.py
- insights/tests/parsers/test_subscription_manager.py
- insights/util/canonical_facts.py
- and move it to the insights.parsers
- See the issue of RHINENG-987
> fix: refactor the SubscriptionManageID parser

- insights/client/apps/compliance/__init__.py
- insights/tests/client/apps/test_compliance.py
Reverts RedHatInsights/insights-core#3829
> Revert "RHICOMPL-3862 Adjust insights-client to upload reports in the ARF format"

- insights/parsers/ls.py
- insights/tests/parsers/test_ls.py
- insights/tests/parsers/test_ls_file_listing.py
Add a safety check to these `fetching` methods to avoid `KeyError` that breaks the rules
> feat: add safety check to methods of 'LS' Parsers

- .github/workflows/main.yml
- noxfile.py
- setup.py
Add CI/CD test with python3.11
> Update CI/CD to include python3.11

- insights/parsers/subscription_manager.py
* Add new filter to collect image builder fact from subscription manager facts to understand which images are built by image builder
> feat: Add new fact to sub mgr facts filters

- docs/custom_datasources_index.rst
- insights/client/apps/manifests.py
- insights/client/core_collector.py
- insights/collect.py
- insights/specs/__init__.py
- insights/specs/datasources/malware_detection.py
- insights/specs/default.py
- and move the entry of Malware detection to Specs, see [INSGHTCORE-203]
- passing the client_config to core collection is also helpful to the #3679
> [POC] Pass the client_config to the core collection

- docs/shared_parsers_catalog/xfs_quota.rst
- insights/parsers/xfs_quota.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_xfs_quota.py
Add new parser XFSQuotaStatue for adviser rule
> FEAT: Add new parser XFSQuotaState

- insights/client/apps/compliance/__init__.py
**Closes** https://issues.redhat.com/browse/RHICOMPL-1529
Fix for the possible Compliance issue when response can't be decoded into json
> Fix Compliance possible json decoding issue

- docs/custom_datasources_index.rst
- insights/specs/datasources/mount.py
- insights/specs/default.py
- insights/tests/datasources/test_mount.py
> feat: revert the xfs_info spec

- insights/combiners/logrotate_conf.py
- insights/tests/combiners/test_logrotate_conf.py
> Fix: Enhance LogrotateConfAll Combiner

- docs/shared_parsers_catalog/proc_random_entropy_avail.rst
- insights/parsers/proc_random_entropy_avail.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_proc_random_entropy_avail.py
> feat: New spec "/proc/sys/kernel/random/entropy_avail"

- insights/combiners/modprobe.py
- insights/formats/_markdown.py
- insights/parsers/installed_rpms.py
- insights/tests/combiners/test_sap.py
- insights/tests/parsers/test_aws_instance_id.py
- insights/tests/parsers/test_dumpe2fs_h.py
- insights/tests/parsers/test_grub_conf_kdump.py
- insights/tests/parsers/test_sssd_conf.py
- insights/tests/test_scannable.py
- insights/tools/apply_spec_filters.py
- fix the newly reported flake8 errors in python3 CI/CD.
> fix: flake8 rule E721

- .github/workflows/main.yml
> fix: use python26 image instead of building it

- insights/core/spec_factory.py
- fix #3866
- and fix the infinite loop between load() and content() of DatasourceProvider
> fix: datasource specs cannot be loaded during collection

- insights/client/data_collector.py
- insights/specs/__init__.py
- insights/specs/default.py
- see INSPEC-414
- relate to #3858 
> [INSPEC-414] collect .exp.sed for analysis

- insights/specs/datasources/yum_updates.py
> ESSNTL-5101: disable libdnf info logging

- docs/shared_parsers_catalog/buddyinfo.rst
- insights/parsers/buddyinfo.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/sos_archive.py
- insights/tests/parsers/test_buddyinfo.py
Add spec and parser for /proc/buddyinfo
> Add spec and parser for /proc/buddyinfo

- insights/client/data_collector.py
Fix issue https://github.com/RedHatInsights/insights-core/issues/3885
> fix: Do not redact mssql_api_assessment

- insights/client/data_collector.py
- insights/specs/default.py
> chore: collect '/etc/.exp.sed'

- insights/formats/__init__.py
- insights/formats/_json.py
Added the rendered content as a variable in the json since it's missing. Also changed the outputted json to indent and sorted the keys.
> feat: Add rendered content to json output

- insights/client/archive.py
Last PR added a new change without test, revert that change.
> fix: revert change in path directory

- insights/client/archive.py
insights-client compress the archive into a tar file. This change modify the input of the tar command to be the archive directory and not the temporary directory.
> Fix tar dir

- insights/client/archive.py
Change the tar command to create the archive tarfile with the correct structure.
```
- insights-localhost-XxXxX.tar
|_ - insights-localhost-XxXxX
|_ - /data
|_ - /metada
```
> fix: change tar command

- insights/tests/test_uploader_json.py
- insights/util/symbolic_name.py
> feat: new test for symbolic_name in uploader.json

- .github/workflows/main.yml
> fix: another attempt to fix the py26 CI/CD

- insights/parsers/aws_instance_id.py
- insights/tests/parsers/test_aws_instance_id.py
> fix: skip invalid content for AWS parsers

- insights/parsers/udev_rules.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_udev_rules.py
> feat: add spec and parser for udev 66-md-auto-re-add.rules

- insights/tests/parsers/test_lvm.py
- Just fix a flake8 error for py26 in test
> fix: flake8 error in test of lvm for py26

- docs/shared_parsers_catalog/postfix_conf.rst
- insights/parsers/postfix_conf.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_postfix_conf.py
Add new parser postfix_conf for adviser rule
> Feat: Add new parser PostfixMaster

- insights/specs/default.py
- insights/specs/insights_archive.py
Update spec rpm_V_packages with adding glibc package check
> Update spec rpm_V_packages

- insights/parsers/lpstat.py
- insights/specs/__init__.py
- insights/specs/datasources/lpstat.py
- insights/specs/default.py
- insights/tests/datasources/test_lpstat.py
- insights/tests/parsers/test_lpstat.py
Add ner parser LpstatQueuedJobs and datasource lpstat_queued_jobs_number
> FEAT: Add new parser LpstatQueuedJobs

- insights/specs/datasources/yum_updates.py
> RHINENG-1764: start processing every errata for available package

- docs/shared_parsers_catalog/sendmail.rst
- insights/parsers/sendmail.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_sendmail.py
> feat: New spec "/etc/mail/sendmail.mc"

- insights/parsers/leapp.py
- insights/specs/__init__.py
- insights/specs/datasources/leapp.py
- insights/specs/default.py
- insights/tests/datasources/test_leapp.py
- insights/tests/parsers/test_leapp.py
> feat: New spec and parser for migration-results

- insights/core/filters.py
- insights/tests/test_filters.py
- or no filterable dependency component
- fix #3918 
> fix: raise Exception when adding filters to non-filterable datasource

- insights/tests/test_util.py
- insights/util/__init__.py
- it's helpful for rule execution performance
- See TYCHE-1016
> fix: show internal DeprecationWarnings only when pytest

- docs/custom_datasources_index.rst
- docs/shared_parsers_catalog/xfs_db.rst
- insights/parsers/xfs_db.py
- insights/specs/__init__.py
- insights/specs/datasources/mount.py
- insights/specs/default.py
- insights/tests/datasources/test_mount.py
- insights/tests/parsers/test_xfs_db.py
Add the spec and parser for new insights plugins, the detailed information is in RHINRULE-440
> feat: New spec and parser for xfs_db -r -c frag command

- insights/contrib/nginxparser.py
- insights/parsers/multipath_conf.py
- insights/parsers/rabbitmq.py
- insights/tests/parsers/test_multipath_conf.py
Related to https://github.com/RedHatInsights/insights-core/issues/1     
See context in INSGHTCORE-73
> Deprecate pyparsing usage in parsers

- insights/parsers/xfs_db.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_xfs_db.py
Add the spec and parser for new insights plugins, the detailed information is in RHINRULE-440
> feat: New spec and parser for xfs_db -r -c freesp command

- insights/combiners/sap.py
- insights/tests/combiners/test_sap.py
Update attributes:
Function_instances ==> daa_instances
business_instances ==> instances
remove local_instances
> Enhance SAP combiner with update attributes name

- insights/combiners/sap.py
- insights/parsers/saphostctrl.py
- insights/tests/combiners/test_sap.py
- update the Sap Parser a bit
- turn attributes into properties
- remove useless tests
- fix the issue that cannot identify SAP instances type when `InstanceType` is missing
> fix: identify SAP instances per short type when InstanceType is missing

- insights/core/dr.py
- insights/tests/__init__.py
- insights/tests/core/test_dr.py
- insights/tests/datasources/test_datasource_timeout.py
- insights/tests/test_broker_exceptions.py
- insights/tests/test_integration_support.py
- insights/tests/test_serde.py
- insights/tests/test_specs.py
- and handle "DefaultSpecs" specially in the method
- see INSGHTCORE-243 for details
> fix: use get_dependencies in get_registry_points

- insights/specs/default.py
Fix issue: https://github.com/RedHatInsights/insights-core/issues/3934
> Enhance chkconfig spec deps_isrhel6

- insights/parsers/yum.py
- insights/tests/parsers/test_yum_repolist.py
Fix https://github.com/RedHatInsights/insights-core/issues/3854 
`Exception Details - Top 10` Before fix:
Type | Message | Count 
-- | -- | -- 
ParseException | Failed to parser yum repolist: Line containing 'repo id' was not found in table | 246 
ParseException | Failed to parser yum repolist: Line containing 'repo id' was not found in table | 239 
ParseException | Failed to parser yum repolist: Line containing 'repo id' was not found in table | 225 
ParseException | Failed to parser yum repolist: Line containing 'repo id' was not found in table | 212 
ParseException | Failed to parser yum repolist: Line containing 'repo id' was not found in table | 184 
ParseException | Failed to parser yum repolist: Line containing 'repo id' was not found in table | 168 …
> fix: yum unexpected ParseException

- insights/core/spec_factory.py
- insights/specs/core3_archive.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> fix: compatible support built-in files for old archives

- insights/combiners/cloud_provider.py
- insights/parsers/rhsm_conf.py
- insights/specs/__init__.py
- insights/tests/__init__.py
- and add default and required filters
- fix: #3916 
> fix: make Specs.rhsm_conf as filterable=True

- docs/shared_parsers_catalog/squid.rst
- insights/parsers/squid.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_squid.py
> feat: New spec "/var/log/squid/cache.log" and parser

- insights/parsers/ps.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_ps.py
> feat: Add one more arg to the command "ps -eo"

- insights/parsers/uname.py
- See https://access.redhat.com/articles/3078
> feat: uname supports RHEL 9.3

- insights/core/ls_parser.py
- insights/tests/parsers/test_ls.py
Resolve https://github.com/RedHatInsights/insights-core/issues/3955
> fix: ls_laZ handling "?" as rhel8 selinux context

- insights/parsers/ethtool.py
- insights/tests/parsers/test_ethtool.py
Resolve https://github.com/RedHatInsights/insights-core/issues/3953
> fix: ethtool.Ring parsing be blocked by TypeError

- insights/tests/client/test_client.py
- A temporarily generated directory "mock_dirname" will be generated in test_client
This PR is to remove it after test.
> test: remove the temporarily generated dir in test_client

- insights/specs/default.py
> feat: Add spec "httpd_limits" back

- insights/parsers/yum_conf.py
- insights/specs/__init__.py
> fix: change Specs.yum_conf to filterable=True

- insights/core/spec_factory.py
- insights/tests/test_specs.py
- fix #3958
- add and refine tests
> fix: do not collect filterable specs when no filters

- insights/specs/__init__.py
- insights/specs/default.py
- Collect a new file for analysis purpose
> chore: INSPEC-432 collect convert2rhel.facts

- docs/shared_parsers_catalog/bootc.rst
- insights/parsers/bootc.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_bootc.py
- Add spec and parser for command "bootc status --json" see INSPEC-443
> INSPEC-443: new spec and parser for bootc status

- .readthedocs.yaml
- readthedocs.yml
* RTD requires all projects to move to version 2
* See: https://blog.readthedocs.com/migrate-configuration-v2/
> fix: Update readthedocs to version 2

- insights/specs/default.py
> Add spec "/var/log/candlepin/candlepin.log" back

- insights/parsers/satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_satellite_postgresql_query.py
> feat: New spec to get the count of revoked certificates on satellite

- insights/specs/default.py
- insights/specs/insights_archive.py
> feat: Add "systemd" to the spec "rpm -V"

- insights/parsers/crypto_policies.py
- insights/tests/parsers/test_crypto_policies_opensshserver.py
Fix issue https://github.com/RedHatInsights/insights-core/issues/3993
> Enhance crypto_policies_opensshserver for rhel9

- insights/core/__init__.py
- insights/core/spec_factory.py
- insights/tests/test_specs_save_as.py
- see [RHINENG-7584](https://issues.redhat.com/browse/RHINENG-7584)
- TODO:
The following document sections should be updated as well.
https://github.com/RedHatInsights/insights-core/blob/3cf45d33fe11fc883dc74ceed33f11ad409e8ebc/docs/api.rst?plain=1#L98
https://github.com/RedHatInsights/insights-core/blob/3cf45d33fe11fc883dc74ceed33f11ad409e8ebc/docs/api.rst?plain=1#L152
As they also relate to the `Legacy Data Collection` that will soon be removed by #3951, I'd like to update the doc after that PR.
> feat: new 'Save As' feature to core collection

- insights/core/__init__.py
- insights/core/spec_factory.py
- insights/tests/test_specs_save_as.py
- The former resolution cannot resolve cases when  mult_output=True. 
As these cases are rare, we can resolve them after the new
Obfuscation is moved into the core.
> fix: 'Save As' as a limited workaround

- insights/core/serde.py
There are many "xx is not a loaded component" lines in log. These are not real errors. So change the log level to debug level.
> fix: change log level to debug for ValueError in serde.py

- insights/tests/client/apps/test_playbook_verifier.py
- This is a supplement to #4005, before removing the temp_dir check its existence.
> fix: rmtree error in playbook verification tests of py27

- insights/parsers/subscription_manager_release.py
Resolve the parser deprecation part of https://github.com/RedHatInsights/insights-core/pull/3998#issuecomment-1918514607
> feat: deprecate parser SubscriptionManagerReleaseShow

- docs/shared_parsers_catalog/rhui_release.rst
- insights/combiners/rhsm_release.py
- insights/parsers/rhui_release.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/combiners/test_rhsm_release.py
- insights/tests/parsers/test_rhui_release.py
> feat: New spec "rhui-set-release" and parser

- insights/tests/client/apps/test_malware_detection.py
Podman exposes `/run/.containerenv` file inside of containers. This patch is required to run the test suite inside of a Podman container environment.
> fix(test): Make the malware detection detect Podman containers

- insights/core/spec_cleaner.py
- insights/tests/core/test_spec_cleaner_reports.py
- see RHINENG-8044 for details
> fix: RHINENG-8044 create facts with right permission respecting umask

- docs/custom_datasources_index.rst
- insights/client/config.py
- insights/parsers/insights_client_conf.py
- insights/specs/__init__.py
- insights/specs/datasources/pcp.py
- insights/specs/default.py
- insights/tests/datasources/test_pcp.py
See [INSGHTCORE-276](https://issues.redhat.com/browse/INSGHTCORE-276)
> feat: collect PCP RAW data per 'ros_collect' set in insights-client.conf

- insights/parsers/bond.py
- insights/tests/parsers/test_bond.py
Added parsing of the permanent hardware addr to the bond parser.
> feat: Add permanent hardware addr to bond parser

- insights/core/spec_factory.py
- fix the following error reported in meta_data:
```
if not (self.ds.no_redact and
AttributeError: 'simple_command' object has no attribute 'no_redact'\n"]
```
> fix: no such attribute error

- insights/client/connection.py
- insights/client/utilities.py
- insights/tests/client/connection/test_LEGACY_reg_check.py
- insights/tests/client/connection/test_reg_check.py
- insights/tests/client/support/test_collect_support_info.py
- insights/tests/client/test_utilities.py
Reverts RedHatInsights/insights-core#3965
> Revert "fix: check status created a machine-id file"

- insights/client/__init__.py
> fix(client): Update typo in a log statement

- docs/shared_parsers_catalog/cron_log.rst
- insights/parsers/cron_log.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_cron_log.py
> feat: New spec /var/log/cron and parser

- insights/combiners/rhsm_release.py
- insights/tests/combiners/test_rhsm_release.py
* Only set minor release when the parser has minor release set
> fixes: Update combiner "RhsmRelease"

- insights/parsers/rhui_release.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> Deprecate the spec "rhui_set_release" and parser

- insights/core/spec_factory.py
- this is a typo introduced when adding "save_as"
- This typo was introduced when adding the "save_as", thanks @huali027 for catching this issue.
> fix: datasource should not be deserialized by RawProvider

- insights/core/spec_factory.py
- insights/tests/test_specs_save_as.py
> fix: save_as in meta_data should reflex the actual config

- insights/combiners/rhsm_release.py
- insights/parsers/rhui_release.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/combiners/test_rhsm_release.py
- insights/tests/parsers/test_rhui_release.py
> feat: New spec "rhui_releasever" and parser

- insights/specs/insights_archive.py
Add the specs into insights_archive.py so that the archive collected by old version insights-client can work well.
> Add httpd_conf to insights_archive.py to support legacy collection

- insights/parsers/rhui_release.py
- insights/tests/parsers/test_rhui_release.py
> fixes: Enhance "RHUIReleaseVer" to support "7Server" format

- insights/combiners/krb5.py
- insights/tests/combiners/test_krb5.py
> Fix: AllKrb5Conf cannot handle 'includedir' configured

- insights/core/spec_factory.py
> fix: missed passing 'cleaner' to super in ContainerProvider"

- insights/client/apps/manifests.py
- insights/parsers/client_metadata.py
- insights/parsers/dmidecode.py
- insights/parsers/etc_machine_id.py
- insights/parsers/ip.py
- insights/parsers/mac.py
- insights/parsers/subscription_manager.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/apps/test_malware_detection.py
- insights/tests/parsers/test_ip.py
- insights/tests/parsers/test_mac.py
- insights/tests/test_canonical_facts.py
- insights/util/canonical_facts.py
> refactor: generate 'canonical_facts' from Parsers instead of Specs

- docs/shared_parsers_catalog/systemctl_get_default.rst
- insights/parsers/systemctl_get_default.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_systemctl_get_default.py
<!--
Provide complete details of the issue or enhancement. You may link to existing open publicly-accessible issues or enhancement requests that provide these details.
Please do not include links to any websites that are not publicly accessible. You may include non-link reference numbers to help you and your team identify non-public references. 
This information is necessary before your PR can be reviewed.
You may remove this comment.
add new parser SystemctlGetDefault for spec systemctl_get_default
> FEAT: Add new parser SystemctlGetDefault

- insights/core/spec_cleaner.py
- insights/tests/core/spec_cleaner/test_clean_file_redact.py
- before this change, the file will keep untouched in this case
- it resolves RHINENG-8846
> fix: when all content are redacted, empty the file

- insights/collect.py
> fixes: Add the right parser to collect the datasource "nginx_ssl_certificate_files"

- insights/collect.py
> fix: incorrect deps in default_manifest for HttpdConfTree combiner

- insights/core/spec_cleaner.py
Fix issue https://github.com/RedHatInsights/insights-core/issues/4075
> fix: workaround redaction for special case

- insights/core/spec_cleaner.py
- insights/tests/core/spec_cleaner/test_clean_filter.py
- insights/tests/core/spec_cleaner/test_get_obfuscate_functions.py
- in addition to obfuscation/redaction, filtering is also supported
- introduce get_obfuscate_functions to return the required obfuscate functions
> feat: enhance Cleaner.clean_content to process lines in memeory

- docs/custom_datasources_index.rst
- insights/parsers/pmlog_summary.py
- insights/specs/__init__.py
- insights/specs/datasources/pcp.py
- insights/specs/default.py
- insights/tests/datasources/test_pcp.py
- insights/tests/parsers/test_pmlog_summary.py
- RHINENG-8434
and mark the pmlogsummary specs as IP/hostname no_obfuscate
See RHINENG-8434
> add spec to collect pmlogsummary of PCP Raw data

- insights/parsers/subscription_manager.py
Add filter "conversions.activity" for Puptoo usage -
system_profile['conversions'] field, see RHINENG-9420
> feat: add filter to Specs.subscription_manager_facts

- insights/client/connection.py
- insights/tests/client/test_upload_archive_cfacts.py
- RHINENG-8790
- fix the issue of RHINENG-8772 and RHINENG-7793
> fix: obfuscate/redact the facts for legacy_upload=False

- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
Add new  spec to collect gpu info
> fix: add "nvidia-smi -L" command to collect gpu data

- insights/combiners/sudoers.py
- insights/tests/combiners/test_sudoers.py
> Feat: enhance combiners sudoers

- insights/parsers/uname.py
- https://access.redhat.com/articles/3078
> chore: uname supports RHEL 9.4

- insights/specs/default.py
Add this spec for cups data analysis
> feat: Add spec cups_ppd

- insights/parsers/nginx_conf.py
- insights/tests/parsers/test_nginx_conf.py
- RHINENG-9862
- fix the issue reported in RHINENG-9862
> fix: special chars in nginx directive name

- docs/shared_parsers_catalog/nmap.rst
- insights/parsers/nmap.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_nmap.py
Create this parser to enhance an existing Advisor rule
> feat: Add parser nmap

- insights/parsers/ssh.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_ssh.py
Add this spec for Advisor rule enhancement
> feat: Add parser sshd_config_d back

- insights/collect.py
- customized manifest for collection triggered from
'insights-collect' entrypoint should be supported
- it fixes the following error reported when running `insights-collect` from the venv
```
$ insights-collect
...
sys.exit(load_entry_point('insights-core', 'console_scripts', 'insights-collect')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/liuxc/work/insights/insights-core/insights/collect.py", line 567, in main
archive, errors = collect(manifest, out_path,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/liuxc/work/insights/insights-core/insights/collect.py", line 452, in collect
black_list.update(rm_conf or {})
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
> fix: add manifest option back to insights.collect()

- insights/core/spec_factory.py
- do not need to set the root for SerializedArchiveContext
- fix: #4108 
- fix: #4108
> fix: correct the `root` of SerializedArchiveContext

- insights/parsers/falconctl.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_falconctl.py
Add the new spec for the new Advisor rule
> Add spec falconctl version

- insights/parsers/installed_product_ids.py
- insights/tests/parsers/test_installed_product_ids.py
* Add file delimiter and file path to the filters to keep the mapping between data and file
> feat: Enhance InstalledProductIDs to support more lines/filters

- docs/custom_datasources_index.rst
- insights/collect.py
- insights/parsers/ssl_certificate.py
- insights/specs/__init__.py
- insights/specs/datasources/ssl_certificate.py
- insights/specs/default.py
- insights/tests/datasources/test_ssl_certificate.py
- insights/tests/parsers/test_ssl_certificate.py
> feat: New spec and parser to get the expire date of ssl certificate in rsyslog

- insights/parsers/subscription_manager.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_subscription_manager.py
Add new parser SubscriptionManagerStatus
> FEAT: Add new parser SubscriptionManagerStatus

- insights/client/collection_rules.py
- insights/collect.py
- insights/specs/datasources/client_metadata.py
- insights/tests/datasources/test_client_metadata.py
- this is a continuation of RHINENG-6956
- and a prepariation for RHINENG-7581
> chore: use datasoruce to collect blacklist_report

- insights/core/spec_factory.py
- When spec cannot be collected, record the reason in the following order:
1. File/Command does not exist
2. No 'filters' but the spec is 'filterable=True'
3. Customer does not allow collecting the spec (blacklist)
- This change only works when original file/command path is used in
the file-redaction.yaml.  When symbolic name (aka spec name) or
component is used, "blacklist" will be recorded first as usual.
- see RHINENG-6983 for details
> fix: change the validate order when collecting specs

- docs/shared_parsers_catalog/blacklisted.rst
- docs/shared_parsers_catalog/version_info.rst
- the parsers were removed in #4134
> doc: remove the doc-entries of removed parsers

- insights/core/spec_factory.py
> chore: refine the exception msg for empty content

- docs/shared_parsers_catalog/cifs.rst
- insights/parsers/cifs.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_cifs.py
> feat: New spec "/proc/fs/cifs/DebugData" and parser

- .github/workflows/main.yml
> test: fix py26 test in CI/CD 

- insights/parsers/kubelet_conf.py
- insights/specs/__init__.py
- insights/specs/sos_archive.py
- insights/tests/parsers/test_kubelet_conf.py
> feat: New spec and parser for /etc/kubernetes/kubelet.conf

- docs/custom_datasources_index.rst
- insights/parsers/ssl_certificate.py
- insights/specs/__init__.py
- insights/specs/datasources/ssl_certificate.py
- insights/specs/default.py
- insights/tests/datasources/test_ssl_certificate.py
- insights/tests/parsers/test_ssl_certificate.py
> feat: New spec and parser to get rsyslog CA cert expiration date

- insights/specs/datasources/compliance/compliance_ds.py
- The following error message is always printed even no `--compliance` is specified.
`Missing required packages for compliance scanning. ...`
- Do not print such error messages when no compliance is specified.
> fix: print compliance errors only when compliance is specified

- .github/workflows/main.yml
- insights/tests/parsers/test_spamassassin_channels.py
- setup.py
This patch ensures we test on a Python present in CentOS Stream 10/ RHEL 10.
> chore(ci): Test on Python 3.12

- docs/shared_components_catalog/selinux.rst
- insights/collect.py
- insights/combiners/selinux.py
- insights/components/selinux.py
- insights/parsers/selinux_config.py
- insights/specs/default.py
- insights/tests/components/test_selinux.py
- insights/tests/parsers/test_selinux_config.py
- add dependencies for sealert to manifest
- refine the SelinuxConfig parser: remove LegacyItemAccess and update its docstring
- see RHINENG-6854
> fix: collect sealert only when SELinux is not disabled

- docs/shared_parsers_catalog/pidstat.rst
- insights/parsers/pidstat.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/parsers/test_pidstat.py
> feat: New spec "/usr/bin/pidstat" and parser

- insights/parsers/nmap.py
- insights/tests/parsers/test_nmap.py
resolve https://github.com/RedHatInsights/insights-core/issues/4157
> fix: handle another input format in parser NmapSsh

- insights/specs/__init__.py
- insights/specs/default.py
* To collect the file collect the file /run/cloud-init/cloud.cfg
* see RHINENG-11298
> feat: collect the file /run/cloud-init/cloud.cfg for analytics

- README.rst
> doc(README): Python 2.6 unsupported announcement

- insights/parsers/os_release.py
- insights/tests/parsers/test_os_release.py
- mix it with  directly instead of LegacyItemAccess
- refine docstring and examples
- see RHINENG-11387
> chore: re-write the OsRelease parser

- insights/specs/default.py
- relevant analysis is finished, do not collect it anymore
> chore: remove collection of cups_pdd

- docs/shared_parsers_catalog/login_pam_conf.py
- insights/parsers/login_pam_conf.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_login_pam_conf.py
> feat: New spec "/etc/pam.d/login" and parser

- docs/shared_parsers_catalog/securetty.py
- insights/parsers/securetty.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_securetty.py
> feat: New spec "/etc/securetty" and parser

- docs/shared_parsers_catalog/sys_class.py
- insights/parsers/sys_class.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_sys_class.py
> feat: New spec "/sys/class/tty/console/active" and parser

- insights/parsers/nvidia.py
- insights/tests/combiners/test_os_release.py
- insights/tests/parsers/test_nvidia.py
[RHINENG-11470](https://issues.redhat.com/browse/RHINENG-11470)
> feat: add parser for spec nvidia_smi_l

- insights/core/__init__.py
- insights/parsers/cifs.py
- insights/parsers/cluster_conf.py
- insights/parsers/fapolicyd_rules.py
- insights/parsers/greenboot_status.py
- insights/parsers/lspci.py
- insights/parsers/sap_dev_trace_files.py
- insights/parsers/sendmail.py
- insights/parsers/sysctl.py
- insights/parsers/udev_rules.py
- insights/tests/parsers/test_cifs.py
- insights/tests/parsers/test_fapolicyd_rules.py
- insights/tests/parsers/test_lspci.py
- insights/tests/parsers/test_sap_dev_trace_files.py
- insights/tests/parsers/test_sendmail.py
- insights/tests/parsers/test_sysctl.py
- insights/tests/parsers/test_udev_rules.py
- insights/tests/test_textfileoutput.py
- for TextFileOutput, new 'raw_line' key replaces the 'raw_message'
in the _parse_line result.  'raw_message' will be kept
for at least 2 minor version (1 year) for compatibility
- let LogFileOutput base on the new base parser, and no
any usage changes will be made to this parser
- for more details see RHINENG-6942
> feat: introduce a new TextFileOutput base parser

- insights/client/apps/ansible/playbook_verifier/__init__.py
- insights/client/apps/ansible/playbook_verifier/__main__.py
- insights/tests/client/apps/test_playbook_verifier.py
- Updates logging of the playbook verifier
- Corrects type hints of one method
- Ensures that all plays of a playbook have been iterated
> feat: Iterate over all plays in a playbook

- insights/parsers/os_release.py
- insights/tests/parsers/test_os_release.py
fix for given input example from [RHINENG-11387](https://issues.redhat.com/browse/RHINENG-11387)
> fix: single quoted string parse of os_release

- insights/combiners/sssd_conf.py
- insights/tests/combiners/test_sssd_conf.py
SSSD can not start without a configuration, but it is possible to start
only with a config snippet.
https://issues.redhat.com/browse/RHINENG-11838?focusedId=25331191&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25331191
> fix: handle non-existing configuration in SSSDConfAll

- insights/parsers/satellite_postgresql_query.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_satellite_postgresql_query.py
> feat: New spec and parser for host facts count of Satellite

- .github/pull_request_template.md
> chore: add sensitive data checkpoint to PR template

- insights/specs/__init__.py
- insights/specs/default.py
> spec: stop collecting cloud_init_cfg_run

- insights/tools/coverage.py
- A very tiny change to the coverage report messages
> test: refine the messages of coverage check in CI/CD

- insights/combiners/lspci.py
- insights/tests/combiners/test_lspci.py
* Closes #4218 where data is not being combined correctly
* Added new test with data specific to failure
> fix: Fix issue 4218 in lspci combiner

- .github/workflows/main.yml
> test(ci/cd): use Codecov instead of self scripts

- .github/workflows/main.yml
- The gitleaks get the config file from `.github/` dir by default,
Change it to the exsiting one.
> test(ci/cd) update the config-path for gitleaks-action

- .github/workflows/main.yml
- Jira: RHINENG-12797
- Paste the URLs directly in the CI/CD YAML instead of making a new script
> test(ci/cd:py26): download pkgs instead of using personal repo

- docs/shared_parsers_catalog/image_builder_facts.rst
- insights/parsers/image_builder_facts.py
- insights/tests/parsers/test_image_builder_facts.py
> parsers: add parser for image builder facts (RHINENG-13943)

- .flake8
- docs/shared_parsers_catalog/cloud_init.rst
- insights/parsers/cloud_init.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_cloud_init.py
- and commit fixes made by `black` to the `specs/__init__.py` and `default.py` 
- see RHINENG-14387
> new spec and spec for cloud-init query

- .pre-commit-config.yaml
- setup.py
initial repos:
- black
- flake8
- gitleaks
- pre-commit-hooks
- remove unused hooks and reopen #4252
> chore: add initial .pre-commit hooks

- .github/workflows/main.yml
> ci: fix action errors of py26 test

- .pre-commit-config.yaml
- and sort the ignores of flake8
> chore: remove 'check-docstring-first' from pre-commit-hooks

- insights/specs/default.py
Signed-off-by: xintli <xintli@redhat.com>
rh-pre-commit.version: 2.3.2
Add spec sysconfig_irqbalance for collecting /etc/sysconfig/irqbalance configuration file
> Add spec sysconfig_irqbalance

- insights/parsers/date.py
- insights/tests/parsers/test_date.py
RHINENG-14572 - handling ansi color code in content of parser `TimeDateCtlStatus`
> fix: ansi color code in parser TimeDateCtlStatus

- insights/specs/datasources/aws.py
- insights/tests/datasources/test_aws.py
> fix: invalid content of datasource aws_imdsv2_token

- insights/collect.py
- insights/specs/default.py
RHINENG-14570
resolve part of https://github.com/RedHatInsights/insights-core/pull/4312
> feat: remove the collection of unused spec fw_devices

- insights/core/__init__.py
- insights/tests/parsers/test_fwupdagent.py
- insights/tests/test_json_parser.py
to fix json ParseException in FwupdagentSecurity 
RHINENG-14570
resolve part of https://github.com/RedHatInsights/insights-core/pull/4312
> fix: handler extra header lines in JSONParser

- insights/specs/default.py
> chore: do not collect chkconfig on RHEL 7+

- insights/parsers/ceph_version.py
- insights/tests/parsers/test_ceph_version.py
Signed-off-by: Ping Qin <piqin@redhat.com>
Enhanced CephVersion parser per https://access.redhat.com/solutions/2045583 to support more versions.
> feat: Enhanced CephVersion parser to support more versions

- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
> spec: collect output of 'flatpak list'

- docs/shared_parsers_catalog/nvidia.rst
- insights/parsers/nvidia.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_nvidia.py
Signed-off-by: Ping Qin <piqin@redhat.com>
It's a requirement from RHINENG-15570.
> feat: Add new parser NvidiaSmiActiveClocksEventReasons

- insights/client/connection.py
- insights/client/phase/v1.py
- insights/tests/client/phase/test_pre_update_checkin.py
- insights/tests/client/phase/test_pre_update_support.py
* Card ID: CCT-265
This patch updates the logging messages shown to the user when the host is registered/not-registered with subscription-manager or when the host is registered/not-registered with insights-client.
> fix(client): Update logging messages

- insights/client/connection.py
- insights/client/phase/v1.py
- insights/tests/client/phase/test_pre_update_checkin.py
- insights/tests/client/phase/test_pre_update_support.py
Reverts RedHatInsights/insights-core#4348
> Revert "fix(client): Update logging messages"

- insights/combiners/cloud_provider.py
- insights/tests/combiners/test_cloud_provider.py
- Oracle Cloud is supported by checking the InstalledRpms. See RHINENG-14729
- bunch of updates made by black check are also included
> add oracle cloud to CloudProvider combiner

- insights/core/ls_parser.py
- insights/tests/parsers/test_ls.py
- insights/tests/parsers/test_lsinitrd.py
Reverts RedHatInsights/insights-core#4346 as some rules are broken by this.
> Revert "Several speed improvements for parsing ls directory output"

- insights/parsers/azure_instance.py
- insights/tests/combiners/test_cloud_instance.py
- insights/tests/parsers/test_azure_instance.py
- Azure instance id can only be a UUID, 
all other unexpected lines should be skipped
RHINENG-16370
> fix: skip unexpected Azure instance id

- insights/collect.py
- insights/specs/default.py
- use the same command as done in manually test
remove the filter of insights_client
remove the --input-logs option
> chore: update the ausearch command

- insights/cleaner/__init__.py
- insights/cleaner/ip.py
- insights/tests/cleaner/test_reports.py
> fix: use IPv4 in facts and csv report

- setup.py
- https://www.cve.org/CVERecord?id=CVE-2025-27516
Signed-off-by: Lizhong Chen <lichen@redhat.com>
> fix: set Jinjia version as CVE-2025-27516

- insights/tests/client/collection_rules/test_get_rm_conf.py
- insights/tests/client/connection/test_init_session.py
- insights/tests/client/init/test_fetch.py
- insights/tests/client/test_upload_archive_cfacts.py
- test_get_rm_conf/test_rm_old_load_ok: Breaks when additional keys are present.
- test_upload_archive_cfacts: Tests failed when additional log messages were created during the test run.
- test_init_session/test_get_rhsm_and_env: Additional logging confused the assert.
- test_fetch/test_request*: Not enough attributes were mocked, which was raising errors due to logging and additional logic.
- test_fetch/test_egg_release: Too many things were mocked, crashing on Python's internal code.
> fix(test): Ensure tests pass in all testing environments

- insights/parsers/lvm.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_lvm.py
> feat: new spec "vgs --foreign --shared" and its parser

- insights/parsers/ls.py
- insights/tests/parsers/test_ls_file_listing.py
- this method is used by rules, exceptions will break the rules' execution
> fix: no exception for ls.permissions_of

- insights/tests/datasources/malware_detection/test_malware_detection.py
- this file was removed by mistake in PR #4400
- apply the changes made by black btw.
> fix(test): revert test_malware_detection which was removed by mistake

- insights/tests/datasources/compliance/test_compliance.py
- Fix the issue detected in CI due to new version of flake8
> fix(flake8): aviod a false positive F824 in test

- insights/specs/__init__.py
- insights/specs/default.py
Add this spec for a new Advisor rule
> Add spec tomcat_web_xml

- insights/parsers/ls.py
- insights/parsers/ls_boot.py
- insights/parsers/ls_dev.py
- insights/parsers/ls_sys_firmware.py
> chore: FileListing should be a CommandParser

- insights/collect.py
- and use the one defined in spec_factory
> chore: reomve the duplicated SAFE_ENV in collect

- insights/client/phase/v1.py
- insights/tests/client/phase/test_post_update.py
* Card ID: CCT-869
This update checks registration status using the `.registered` file instead of querying Inventory, which improves performance by reducing API calls. If the file exists, an upload proceeds.
> feat(client): Disable API registration check

- .github/workflows/main.yml
- insights/tests/core/test_hydration.py
- add a single action for Python 3.6 test
and skip unsuited tests
- change docs test to use Python 3.12
- JIRA: RHINENG-17568
> fix(ci/cd): update to use Ubuntu 22.04 for code-test

- docs/notebooks/Datasource Registry.ipynb
- docs/notebooks/Diagnostic Walkthrough.ipynb
- docs/notebooks/Filters Tutorial.ipynb
- docs/notebooks/Insights Core Tutorial.ipynb
- fix the docs test issue in #4420 4420
> chore: update notebooks based on python3

- insights/parsers/subscription_manager.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/tests/parsers/test_subscription_manager.py
> feat: add spec subscription_manager_syspurpose

- insights/version.py
- pyproject.toml
- But keep the setup.py/cfg for python2.7/3.6 and rpm build
- Jira: RHINENG-13536
> chore: change to build with pyproject.toml

- pyproject.toml
- rename 'license' to 'license-files'
- change 'readme' to dynamic
- remove not often used python versions
> fix(pyproject.toml): fix errors reported from '-m build'

- insights/parsers/smartctl.py
- insights/specs/__init__.py
- insights/specs/datasources/dev.py
- insights/specs/default.py
- insights/specs/manifests.py
- insights/tests/datasources/test_dev.py
- insights/tests/parsers/test_smartctl.py
This spec is used for a new Advisor rule
> feat: Add spec smartctl_health

- insights/parsers/named_checkconf.py
- insights/tests/parsers/test_named_checkconf.py
> fix: Enhance parser "NamedCheckconf" to support new filtered option

- insights/specs/manifests.py
fix for spec `subscription_manager_syspurpose` collection
> fix: add spec deps component IsGtOrRhel84 to manifests

- insights/core/ls_parser.py
- insights/tests/test_ls_parser.py
This is for issue https://github.com/RedHatInsights/insights-core/issues/4447
> fix: Update files_permissions function for T permission

- insights/specs/datasources/ls.py
- insights/tests/datasources/test_ls.py
Update the datasource to replace spec ls_dev
> feat: Add files into datasource list_files_with_lH

- insights/specs/__init__.py
> fix: hostname should be obfuscated for lvs and grubby

- insights/client/__init__.py
- insights/client/auto_config.py
- insights/client/config.py
- insights/client/connection.py
- insights/client/constants.py
- insights/tests/client/auto_config/test_autoconfig_urls.py
- insights/tests/client/auto_config/test_branch_info_call.py
- insights/tests/client/connection/test_init.py
> Revert "chore(client): Simplify automatic configuration logic (#4376)"

- insights/combiners/redhat_release.py
- insights/components/rhel_version.py
- insights/tests/combiners/test_redhat_release.py
- insights/tests/components/test_rhel_version.py
- insights/tests/parsers/test_redhat_release.py
* Update components for RHEL10
* Update redhat_release combiner for RHEL10
* Update all tests for RHEL10
> Feat: Add support for RHEL 10

- insights/tests/parsers/test_dnf_module.py
Based on the recent `dnf_module` "active" streams output differences discussion on RHEL8 and RHEL9 systems, though, no fix is needed for the code handling logic, adding some more unit test cases for RHEL9 spec input with notes for a better clarification.
> test: add unit tests for dnf_module RHEL9 spec input

- insights/specs/datasources/corosync.py
- insights/tests/datasources/test_corosync.py
> feat: Collect "corosync-cmapctl" on RHEL10

- insights/parsers/aws_instance_id.py
- insights/tests/parsers/test_aws_instance_id.py
> fix: handle invalid cmd output of aws curl

- insights/parsers/ceph_version.py
> feat: Add ceph new versions 2025_0701

- insights/parsers/ls.py
- insights/specs/manifests.py
- insights/tests/parsers/test_ls_file_listing.py
- insights/tests/parsers/test_ls_files.py
Add this var for Advisor rules update
> feat: Add error_lines to LSlHFiles parser

- .github/workflows/main.yml
> chore(ci/cd): update the codecov actions to v5

- docs/shared_parsers_catalog/crictl_ps.rst
- insights/parsers/crictl_ps.py
- insights/specs/__init__.py
- insights/specs/sos_archive.py
- insights/tests/parsers/test_crictl_ps.py
> New parser for sos_commands/crio/crictl_ps

- build_core_rpm.sh
> chore(script): update the file name typo in last operation
