RedHatInsights/insights-core

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

* https://issues.redhat.com/browse/YARA-258
The scan_only option applied to both the filesystem and processes but it was a little confusing to parse the items and decide whether to scan the filesystem and/or processes.  Also, there was  a scan_exclude option but it only applied to the filesystem.  To clear this up and make the filesystem and processes options separate, this PR creates the following options: filesystem_scan_only, filesystem_scan_exclude, processes_scan_only and processes_scan_exclude.  This makes them more explicit and less confusing.  I hope so anyway.

Separate scan_only and scan_exclude options for filesystem and processes

---

CHANGELOG.md

I missed to update the CHANGELOG.md while tagging version 3.0.258.

Update the ChangeLog to include insights-core-3.0.258

---

insights/specs/datasources/yum_updates.py
insights/tests/datasources/test_yum_updates.py

Current `yum updates` datasource is limited to work on RHEL7.
This PR extends functionality to RHEL 8.5+ systems.
When run on RHEL 8 prior RHEL 8.5 it skips data collection (a bug in dnf ignores cacheonly flag and may cause downloading data over network ).

Improved yum/dnf updates datasource to work on RHEL 8.5+

---

insights/client/apps/malware_detection/__init__.py
insights/specs/datasources/malware_detection.py
insights/tests/client/apps/test_malware_detection.py

* [ x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ x] Is this PR an enhancement?
This PR allows the malware-detection app to download rules via a Satellite proxy.  The malware-detection rules are on C.R.C but if the system is using a Satellite, then malware-detection needs to use the Satellite URL (and hence its certificates) to initiate the request, which the Satellite will then forward onto C.R.C.
The malware-detection app runs insights-client auto_config to determine if a Satellite is being used by checking the base_url.

Support downloading malware-detection rules via Satellite

---

setup.py

* Fix #3343 issue with older version of Markupsafe and Jinga2
* Pin correct versions for python 2.7 and use newer versions for python 3

Fix issue with Markupsafe and Jinja2 versions

---

insights/client/config.py

[ESSNTL-943](https://issues.redhat.com/browse/ESSNTL-943) reports the lack of exception when both parameters `--offline` and `--check-results` are passing to insights-client.
This PR adds the parameters that need a connection as `--check-results` and `--diagnosis` to be checked if `--offline` parameter is active in the validation of parameters. This will prevent trying to continue with the execution and not being able to finish the request because of the lack of connection.

Parameters checked when offline is active

---

insights/client/__init__.py
insights/tests/client/init/test_fetch.py

https://bugzilla.redhat.com/show_bug.cgi?id=2045995
From the BZ: "If there is a new Egg available to download the whole binary content of the new Egg (zip) file is dumped to the terminal. This binary content has also terminal control characters and PuTTy and responds also to them".  This only happens when verbose mode is enabled, and only under certain conditions (eg after deleting the etag file).

Don't log the insights-core egg in verbose mode

---

insights/core/serde.py
insights/tests/test_serde.py

* When some spec is collecting several files, we should keep the results
once one of them is good, and only set results to empty when all of them
fails with errors
* fix: #3356 

fix: Keep the results once one of them is good

---

insights/client/phase/v1.py
insights/tests/client/phase/test_post_update.py

`insights-client --status` was exiting good if it was registered, and otherwise. But the correct exit should be bad if a problem happened and good whether it is registered and unregistered.
Follow discussion in [ESSNTL-2001](https://issues.redhat.com/browse/ESSNTL-2001)
Clarification Edit (I copied here @subpop 's comment ):
To clarify, this PR is changing the behavior of insights-client so that regardless of the output of the --status command, the process will exit with a 0 if the process executed successfully. Prior to this change, the process would exit with a 1 if the output was "unregistered" and a 0 if the output was "registered". This change brings the client in more compliance with normal command line utility …

Fix: [insights-client] insights-client --status returns 1 when it is unregistered ESSNTL-2001

---

insights/combiners/grub_conf.py
insights/combiners/tests/test_grub_conf.py
insights/combiners/tests/test_selinux.py
insights/parsers/grub_conf.py

Spec `grub2_cfg` can also exist on RHEL8, so update to make it can be used for RHEL8 systems.

fix: Enhance parser Grub2Config

---

insights/specs/datasources/candlepin_broker.py

Using the xml element tree getiterator function has been deprecated for a while it seems. To get rid of the warning I updated to using iter wrapped in a list which is all the getiterator function did.

fix: Fix deprecation warning for using ET.getiterator

---

insights/combiners/grub_conf.py
insights/combiners/tests/test_grub_conf.py
insights/combiners/tests/test_selinux.py
insights/parsers/grub_conf.py

Reverts RedHatInsights/insights-core#3360, this commit broke my internal Insights-Facts app, and I imagine would cause issues with rule hits. This commit removed the BootLoaderEntries combiner from the GrubConf combiner, which means any rules only utilizing the GrubConf combiner looking for cmdline entries will no longer return anything for RHEL 8+ systems that are using the default blscfg setting. It looks like there is only 1 rule utilizing both combiners, and around 20+ rules that utilizes only the GrubConf combiner and not both. Instead of removing the BootLoaderEntries combiner, there needs to be a check if grub2.boot_entries exist, if so set self.grub = _grub2 otherwise self.grub = grub_bles.

Revert "fix: Enhance parser Grub2Config"

---

insights/combiners/ps.py
insights/combiners/tests/test_ps.py
insights/specs/sos_archive.py

SOS Report no longer collects ps auxwww and ps auxwwwm, it removed the  auxwww since auxwwwm basically shows the same thing with threads added. Adding this spec caused a ValueError in the ps combiner due to the thread entries containing a - in the pid column. So I updated the combiner to check to make sure the pid column entry is a digit before  continuing.

feat: Add new sos ps spec and fix ValueError caused by it

---

insights/contrib/soscleaner.py
insights/tests/test_soscleaner.py

Account for cases where IP addresses can appear at the end of a line in
the space-preserving netstat obfuscation function _sub_ip_netstat.
Resolves: RHBZ#2029997
Signed-off-by: Link Dupont <link@sub-pop.net>

fix: correctly obfuscate IP addresses at EOL

---

insights/specs/datasources/ipcs.py
insights/tests/datasources/test_ipcs.py

Due to application workload or misbehavior the semaphores count might increase
significantly. Additionally, the current rules expects semids from selected
owners namely 'root', 'apache', and 'oracle'.
Closes-Bug: RHBZ#2071058

Fix BZ#2071058

---

insights/client/__init__.py
insights/client/auto_config.py
insights/client/client.py
insights/client/connection.py
insights/tests/client/auto_config/test_autoconfig_urls.py
insights/tests/client/connection/test_url_guess.py

This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=2006386 by replacing all string occurrences of "cloud.redhat.com" with "console.redhat.com".

Replace “cloud.redhat.com” with “console.redhat.com”

---

insights/client/constants.py
insights/contrib/soscleaner.py
insights/tests/test_soscleaner.py

This Pull Request is a fix for [ESSNTL-444](https://issues.redhat.com/browse/ESSNTL-444) / [Bug 2026141](https://bugzilla.redhat.com/show_bug.cgi?id=2026141), introducing a list of Specs excluded from the IP obfuscation by the SOSCleaner. The files generated by some Specs contain package versions consisting of four numeric parts. Those strings are indistinguishable from IPv4 addresses and the SOSCleaner incorrectly obfuscates them. The now invalid package versions case false rule hits further down in the cloud console.
As a hotfix, a hardcoded list of Specs excluded from the IP address obfuscation is introduced. A more proper way would be to have a flag in the Spec that would allow it to exclude itself from the obfuscation, or to provide a custom obfuscation pattern. …

Exclude some Specs from IP address obfuscation

---

insights/client/utilities.py
insights/tests/client/test_utilities.py

In old version of the client, the machine-id could be a non-hyphen
UUID. Upload still works but `insights-client-results.service` fails with
a `Error: failed to download advisor report.` error message.
This patch fixes this issue by actually returning a `UUID4` object with
hyphens. Moreover, it also adds a unit test to check non-hyphen `UUID`
from old client.
Resolves: rhbz#1998560
Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>

fix(client): Return valid machine-id UUID4 object

---

insights/parsers/yum_updates.py

* Parser was using the wrong spec and should be using yum_updates
*  This was causing JSON parsing exceptions in the parser when running

fix: Fix spec for YumUpdates parser

---

insights/parsers/ibm_proc.py
insights/parsers/tests/test_ibm_proc.py

According to the collected `ibm_fw_vernum_encoded` file, there is a `\x00` invisible symbol at the EOL. This PR removed this invisible symbol.

fix: strip the '\x00' from the ibm_fw_vernum_encoded before parsing

---

insights/combiners/logrotate_conf.py
insights/combiners/tests/test_logrotate_conf_tree.py
insights/parsers/logrotate_conf.py
insights/parsers/tests/test_logrotate_conf.py

Due to an issue found with the httpdconf parser that was in the combiner I'm moving the newer logrotate parser out of it's combiner as well. Added docstring to the moved parser, and added doctest.

fix: Move _LogRotateConf parser out of combiner

---

insights/parsers/sys_module.py
insights/parsers/tests/test_sys_module.py
insights/specs/__init__.py
insights/specs/default.py

feat: Add new crash_kexec_post_notifiers parser

---

insights/combiners/tests/test_httpd_conf_tree.py
insights/parsers/httpd_conf.py

The parsr logic didn't handle line continuations properly, and didn't handle multi-line quoted directives either. I fixed the logic and added in tests.

fix: Multiline quote parsing of httpd conf files

---

insights/tests/client/apps/test_malware_detection.py

This is to correct problems encountered when running the malware-detection tests on RHEL6 systems outside the automated PR check environment. Malware detection won't be supported on RHEL6 so no need to check it works in that environment anyway.

Skip malware-detection tests on RHEL6/python2.6 (not supported)

---

docs/shared_parsers_catalog/containers_policy.rst
insights/parsers/containers_policy.py
insights/parsers/tests/test_containers_policy.py
insights/specs/__init__.py
insights/specs/sos_archive.py

CRI-O crashes with "_gpgme_ath_mutex_lock" on worker nodes when signature verification is enabled. The signature verification policy, `/etc/containers/policy.json`, specifies the policy. For the Detail info, please see: INSIGHTOCP-695 card.

Feat: Add spec and parser for 'containers_policy'

---

insights/tests/client/apps/test_malware_detection.py

- Patch findmnt command to return consistent output
- Fix missing directories on Fedora 35
Fixes https://github.com/RedHatInsights/insights-core/issues/3397 and other problems identified due to running the actual findmnt command on test machines.

Fix failing malware-detection tests

---

MANIFEST.in.client
insights/client/apps/compliance/__init__.py
insights/client/archive.py
insights/compliance_obfuscations.yaml
insights/tests/client/apps/test_compliance.py
insights/tests/client/test_archive.py

As compliance relies on the external OpenSCAP tool, it was ignoring the `--obfuscate` and `--obfuscate-hostname` parameters. This proposed solution goes through the OpenSCAP result XML file and removes the sensitive information based on the predefined xpaths stored in a YAML file.

feat: RHICOMPL-2450 implemented OpenSCAP result obfuscation

---

insights/combiners/nfs_exports.py
insights/contrib/pyparsing.py

The collections module was moved to collections.abc in py3.3 it looks like, and collections was deprecated completely in py3.10. This causes specs to not load in py3.10 environments. Switched to using six.moves compatibility layer for this issue. Also reordered the imports in the pyparsing module.
Fixes #3405

fix: Deprecation warnings and removal of collections

---

docs/shared_combiners_catalog/mounts.rst
insights/combiners/mounts.py
insights/combiners/tests/test_mounts.py
insights/parsers/fstab.py
insights/parsers/mount.py
insights/parsers/tests/test_mount.py
insights/specs/__init__.py
insights/specs/default.py
insights/specs/sos_archive.py

This `/proc/self/mountinfo` can provide additional info that `/bin/mount` and `/proc/mounts` don't collect.

Add parser for /proc/self/mountinfo and new combiner mounts

---

.github/workflows/main.yml
.gitignore
noxfile.py
setup.py

* RHEL9 will include Python 3.9 so include it in the testing
* Update default version of Python to 3.8 for linting and docs
* Add noxfile.py to enable testing with nox for development

Update CI/CD to include Python 3.9

---

insights/client/apps/compliance/__init__.py

`insights-client --compliance` currently does not upload reports for RHEL 9 systems. For more information on the exact error message, please see the Jira ticket: RHICOMPL-2975

Add os major version 9 for Compliance

---

insights/client/apps/compliance/__init__.py
insights/tests/client/apps/test_compliance.py

`grep` behaves differently when searching for a string in a single file. The issue is that it doesn't include the filename in the output so for example `grep xccdf_org.ssgproject.content_profile_anssi_bp28_high /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml` would return `<xccdf-1.2:Profile id="xccdf_org.ssgproject.content_profile_anssi_bp28_high">` but `/usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml:  <xccdf-1.2:Profile id="xccdf_org.ssgproject.content_profile_anssi_bp28_high">` is needed for `insights-client --compliance` to work correctly. This can be fixed by passing the `-H` switch.

fix(Compliance): Find policy correctly when there is one datasteam file

---

insights/specs/default.py

the `specs.default.get_owner` is not used, this PR removed it from the code.

chore: remove the unused get_owner from specs.default

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

* Download versioned signatures file corresponding to installed version of yara
* Also fixes permission denied bug from fuse mounted filesystems
https://issues.redhat.com/browse/YARA-320
Make the malware detection client aware of the version of yara installed on the machine and to select the appropriate signature file for scanning.
Also piggybacks a bug fix whereby os.path.samefile() may raise a permission denied exception when trying to access Fuse filesystem mountpoints, yes even as root!

malware-detection feature: handle different yara versions

---

docs/custom_datasources_index.rst
docs/shared_parsers_catalog/user_group.rst
insights/parsers/user_group.py
insights/specs/__init__.py
insights/specs/datasources/user_group.py
insights/specs/default.py
insights/tests/datasources/test_user_group.py
insights/tests/parsers/test_user_group.py

New datasource spec and parser for group info

feat: New spec and parser for group_info

---

docs/shared_combiners_catalog/sudoers.rst
docs/shared_parsers_catalog/sudoers.rst
insights/combiners/sudoers.py
insights/parsers/sudoers.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/combiners/test_sudoers.py
insights/tests/parsers/test_sudoers.py

feat: new spec and parser for /etc/sudoers

---

insights/specs/sos_archive.py

adding systemd_analyze_blame = simple_file("insights_commands/systemd-analyze_blame")  in insights_archive.py
<!--
Provide complete details of the issue or enhancement. You may link to existing open publicly-accessible issues or enhancement requests that provide these details.
Please do not include links to any websites that are not publicly accessible. You may include non-link reference numbers to help you and your team identify non-public references. 
This information is necessary before your PR can be reviewed.

Updating sos_archive to parse file for GSS rule

---

insights/core/evaluators.py

The insights-engine (old) runs rules via the InsightsEvaluators, this PR updates the Evaluators to support running rules in parallel.
- See also #3418 
- BTW, I didn't make the new `parallel` as an attribute of the `Evaluators` class, since I think it is better to pass it via arguments. (The same to the `incremental`, but to avoid breaking the interface, I didn't touch it in this change)

feat: Support parallelly running for insights-engine

---

insights/__init__.py

Add --no-load-default arg, if this arg is passed the default plugins aren't loaded. This allows the execution of other projects without loading all the specs from core which can cause exceptions. Re-ordered the arguments so that they're in alphabetical order. Added some empty lines between some of the code below the args so that it's easier to read.

feat: Add --no-load-default arg to the insights-run command

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

* Add yara version as a query parameter when requesting signatures.yar
Sends the yara version to the malware detection backend which is responsible to determining which signatures file to send back to the client.  Previously the client requested a specific file to send.  But now the client always asks for the same signatures.yar file but appends a ?yara_version=x.y.z query parameter to the request, which the backend parses and chooses the appropriate signatures file based on that version.

malware-detection: implement yara version handling differently

---

insights/tests/client/apps/test_compliance.py
insights/tests/client/test_archive.py
insights/tests/client/test_client.py

Test were passing but it ended throwing these errors:
```
ERROR:insights.client.archive:ERROR: Could not create /var/cache/insights-client
Error in atexit._run_exitfuncs:
File "/home/bfahr/work/insights/insights-core/insights/client/archive.py", line 261, in storing_archive
os.makedirs(self.keep_archive_dir)
File "/usr/lib64/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/cache/insights-client'
```
This PR mocked `atexit` call that was causing this error.

Fix tests that removing temp archives

---

insights/util/canonical_facts.py

* For client apps that don't use insights components, this will allow them to use get_canonical_facts for uploads and not have to load components in the app.

FIX: Update canonical_facts to load needed components

---

insights/tests/test_soscleaner.py

The RPM_OUTPUT_SHADOW_UTILS (introduced in #3331) does not appear anywhere in the SOSCleaner tests or anywhere else. Removing it to declutter the test case.

Remove RPM_OUTPUT_SHADOW_UTILS

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

Downloading rules in stage wasn't working properly.  This PR uses the base_url insights-client config value as the basis for where the rules are located in stage.

Handle downloading malware-detection rules from stage environment

---

insights/parsr/iniparser.py
insights/parsr/tests/test_iniparser.py

Iniparser is only setup to parse string.printable characters. This doesn't include non ascii characters from various languages, which causes an exception when they're in a config file. So replace the characters with question marks.
Fixes #3450

fix: Replace non ascii characters with question marks

---

insights/tests/datasources/test_ethernet.py

- Fixed an incorrect test case newly added to the `ethernet` datasource.

Fix: test error of nmcli command in the datasource ethernet

---

insights/parsers/podman_list.py
insights/specs/default.py
insights/specs/insights_archive.py
insights/tests/parsers/test_podman_list.py

- Revert the `podman list` specs
- Change the `PodmanList` parsers to base on the `DockerList` parsers, since the output of the `podman` commands is the same as the `docker` commands
- This is the preparation for the support of `Container Specs`

feat: revert and refine the padman list specs and parsers

---

insights/specs/default.py

The rule `podman_cni_bridge.py` needs the spec `cni_podman_bridge_conf`

Fix: Restore the spec cni_podman_bridge_conf

---

insights/specs/default.py

* the spec is used in rules, so add it back
The parser "LvmConf" is replaced by parser "LvmConfig" in rules, so add the spec back.

fix: Add spec "lvmconfig" back

---

setup.py

The release of v5.1.0 breaks docs build for a lot of projects apparently according to the issue on their project. So restrict the version to v5.0.2 and below.

fix: Restrict Sphinx's version since it breaks docs build

---

insights/tests/test_fs.py
insights/util/fs.py

* Addresses BZs 2088120 and 2104839 where the archive yum updates.xml
and the locally created archive were being left in world writable
state.
* Change default umask and mode to more reasonable values as defaults
* Updated tests

Fix: Fix error with umask not being restored when dir exists

---

insights/specs/default.py

Add teamdctl_config_dump spec to default.py.

Feat: Add teamdctl_config_dump spec to insights_archive 

---

insights/parsers/lvm.py
insights/tests/parsers/lvm_test_data.py
insights/tests/parsers/test_lvm.py

It fails to parse the content when there is "umask=077" in the configuration.
fixes: https://github.com/RedHatInsights/insights-core/issues/3475

fix: the parser "LvmConfig" raises exception

---

docs/custom_datasources_index.rst
docs/shared_parsers_catalog/system_user_dirs.rst
insights/parsers/system_user_dirs.py
insights/specs/__init__.py
insights/specs/datasources/system_user_dirs.py
insights/specs/default.py
insights/tests/datasources/test_system_user_dirs.py
insights/tests/parsers/test_system_user_dirs.py

We are working on new rules (CVE-2021-35937, CVE-2021-35938, CVE-2021-35939), which need a new parser and data source for checking non-root owned packaged directories.
CI is failing because the datasource uses the rpm module, which is the system package and the current virtual environment does not have it.

Add new system_user_dirs datasource and parser

---

insights/core/context.py

The current marker 'namespaces' matches RHCOS SOSReport archives. RHCOS SOS-Report archives are always identified as MustGatherContext instead of SosArchiveContext, thus no rule hits result when running rules against RHCOS SOS-Report. The commit changes the marker of MustGatherContext to 'cluster-scoped-resources' to avoid matching RHCOS SOSReport.

Update the marker for MustGatherContext

---

insights/client/utilities.py
insights/parsers/__init__.py
insights/parsers/passenger_status.py
insights/parsers/sealert.py
insights/parsers/uname.py
insights/tests/parsers/test_satellite_postgresql_query.py

* Version 5.0.2 of flake8 detected some errors that needed
to be fixed to allow CI/CD tests to pass

New version of flake8 found some errors

---

docs/custom_datasources_index.rst
insights/specs/datasources/aws.py
insights/specs/default.py
insights/tests/datasources/test_aws.py

* AWS IMDSv2 uses sessions for metadata access which requires the extra step of collecting a token prior to accessing metadata
* Add a new datasource to get the IMDSv2 token
* Modifiy existing specs to use the token to access metadata
* Add datasource to docs
* This change resolves #3485

fix: Update aws specs to use IMDSv2

---

insights/client/apps/malware_detection/__init__.py
insights/client/config.py
insights/tests/client/apps/test_malware_detection.py

This PR sets the number of download/upload retries for malware-detection to 5.  This is especially important for uploads because we don't want to fail after one unsuccessful attempt to upload the results archive.  Doing a malware scan could take a long time, and if we are unable to upload the archive, then insights-client fails and deletes the archive, which would waste all that effort in doing the scan, and be an unhappy user experience.  A better user experience would be to at least retry uploading the archive a number of times before failing.  (An even better user experience would be to keep the archive instead of deleting it  but that's another PR for another day.)

Automatically retry malware-detection downloads & uploads

---

docs/shared_parsers_catalog/auditctl.rst
insights/parsers/auditctl.py
insights/parsers/auditctl_status.py
insights/specs/__init__.py
insights/specs/default.py
insights/specs/insights_archive.py
insights/specs/sos_archive.py
insights/tests/parsers/test_auditctl.py

This update is targeting to add a new spec and parser for "auditctl -l". Since there is an existing module `auditctl_status`, and the existing parser didn't follow the latest design. This PR also:
- Mark the old "AuditctlStatus" parser as deprecated
- Move the `auditctl` related parsers to `auditctl` module.

feat: New spec  and parser for"auditctl -l"

---

insights/client/archive.py
insights/client/constants.py
insights/tests/client/test_archive.py

This PR adds a new temporary directory for use during the collection of the archive. Insights-client was using `var/tmp/` with this modification the new temporary path is `/var/tmp/insights-client`. This change is motivated by:
1) SELinux denials
2) Alignment with the use of others directories

New location for temp directory

---

insights/collect.py

* When collect is called from the cli, the malware datasource calls client configuration which parses the collect args and fails.
* This PR removes the args after parsing to avoid the failure.
* Fix #3505

Fix issue calling collect from cli

---

insights/client/auto_config.py
insights/client/config.py
insights/client/connection.py
insights/tests/client/apps/test_compliance.py
insights/tests/client/auto_config/test_autoconfig_urls.py
insights/tests/client/connection/test_init_session.py

Insights-client wasn't honoring the no_proxy configuration of `/etc/rhsm/rhsm.conf` file.
This PR adds the no_proxy value to the auto-configuration module, to retrieve the value of the rhsm configuration file. It provides some tests related to this.
This fix is related to: [rhbz#2065233]((https://bugzilla.redhat.com/show_bug.cgi?id=2065233)

Added no_proxy autoconfiguration from rhsm conf and tests

---

insights/client/insights_spec.py

* util/subproc was already using which to get the full path for timeout, but the command spec was not.  This change uses the which util to ensure the full path is obtained for the timeout command
* Fix #1130

Ensure full path when using timeout command

---

insights/specs/default.py
insights/specs/sos_archive.py

secure parser is only used for sos_archive currently, but insights rule also use this parser. Add this spec in default.py.

Feat: add secure spec to default.py

---

insights/combiners/sap.py
insights/parsers/saphostctrl.py
insights/tests/combiners/test_sap.py
insights/tests/datasources/test_sap.py
insights/tests/parsers/test_saphostctrl.py

From BZ-1969572, the "InstanceType" should be used as the identifier for SAP `function_instance`
- Added the InstanceType to the fixed filter of saphostctrl
- Remove the unused "CreationClassName" from the fixed filter
- Add a full_type function to get the full InstanceType
- check "Solution Manager Diagnostic Agent" for function_instance
- Convert the Parser SAPHostCtrlInstances to a list

fix: support InstanceType in saphostctrl

---

insights/client/client.py
insights/client/phase/v1.py

Create a private method to clean the local files that set the register status for `insights-client`. This process was done for both unregistration (legacy_upload = True and False). The method was already created, this PR just use this method as well when `legacy_upload` is False.

Refractor cleanup local files for unregistration processes

---

docs/custom_datasources_index.rst
docs/shared_components_catalog/cryptsetup.rst
docs/shared_parsers_catalog/cryptsetup_luksDump.rst
insights/collect.py
insights/components/cryptsetup.py
insights/parsers/cryptsetup_luksDump.py
insights/specs/__init__.py
insights/specs/datasources/luks_devices.py
insights/specs/default.py
insights/specs/insights_archive.py
insights/tests/components/test_cryptsetup.py
insights/tests/datasources/test_luks_devices.py
insights/tests/parsers/test_cryptsetup_luksDump.py

Signed-off-by: daniel.zatovic <daniel.zatovic@gmail.com>
- Added `cryptsetup_luksDump` spec which collects the output of `cryptsetup luksDump` spec with salt and digest fields filtered out (although luksDump public is designed to contain only public information, salt and digest can potentially be sensitive)
- Added `LUKS_Dump` parser, which parses the output using `parsr` library (it works for both - LUKS1 and LUKS2 output formats)

Feat: Add spec and parser for cryptsetup luksDump

---

insights/parsers/smt.py
insights/specs/default.py
insights/tests/parsers/test_smt.py

`insights-core-assets` already has the `cpu_smt_control` entries, so no further changes are necessary.

New parser for CpuSMTControl and tests update

---

insights/specs/datasources/system_user_dirs.py
insights/specs/default.py

Fix bz-2126966, the "rpm/yum/dnf" related command should use "SIGTERM" instead of the default "SIGKILL".
- also modified the "rpm_ostree_status"

fix: bz-2126966: use SIGTERM for rpm instead of SIGKILL

---

insights/combiners/rhel_for_edge.py

This is a follow-up of https://github.com/RedHatInsights/insights-core/pull/3526 to make the docstring more readable.

feat: [rhel_for_edge] Update docstring to make it more readable

---

insights/parsers/saphostctrl.py
insights/tests/parsers/test_saphostctrl.py

- fix: #3530
- Generate the InstanceType as per the InstanceName, since it is not collected by the old archives.
- Since the old archives didn't collect the InstanceType lines, when applying the new logic of #3512 against the old archives an exception will be thrown and the `Sap` combiner gets fail.
- This PR fixes this and makes the parse compatible with the old archives.

fix: make SAPHostCtrlInstances compatible with old archives

---

insights/specs/default.py
insights/specs/insights_archive.py

Restore the spec which was removed in https://github.com/RedHatInsights/insights-core/commit/eb70e566a327b12445dbba4b6ca05b90772effa0

fix: Restore the spec ovs_appctl_fdb_show_bridge

---

insights/core/__init__.py
insights/parsers/engine_log.py

The following will be deprecated after insights-core-3.2.25:
* insights.core.scannable: Better use the `core.Parser` with filter.
* insights.parsers.engine_log: Use insights.parsers.ovirt_engine_log instead.

Deprecate insights.core.scannable & engine_log parser

---

docs/shared_parsers_catalog/ls_krb5_sssd.rst
insights/parsers/ls_krb5_sssd.py
insights/specs/__init__.py
insights/specs/default.py
insights/specs/insights_archive.py
insights/tests/parsers/test_ls_krb5_sssd.py

Signed-off-by: Rahul Srivastava <rasrivas@redhat.com>
This is a new parser request to list all the files present in the `/var/lib/sss/pubconf/krb5.include.d` directory.

Feat: New parser for the "ls -lan /var/lib/sss/pubconf/krb5.include.d" command

---

insights/specs/default.py
insights/specs/insights_archive.py

The analytics task based on this spec was Done, Remove it from the insights collection (both core collection and uploader.json)

chore: Remove authselect_current from core collection

---

insights/core/dr.py
insights/tests/test_get_dependency_specs.py

This Patch removed the duplicated items from the list returned by get_dependency_specs

refactor: remove duplicated specs from get_dependency_specs

---

insights/client/core_collector.py
insights/collect.py
insights/core/serde.py
insights/tests/client/data_collector/test_redact.py
insights/tests/test_collect.py
insights/tests/test_serde.py

* Modified how exceptions are handleled in the `insights.core.serde.marshal` function, so error tracebacks are captured and serialized to a meta-data file in the archive (as before) and also exceptions are added to the broker for later retrieval.
* Added `_parse_broker_exceptions` and modified `collect` function in the `insights.collect` module, so all broker exceptions are analyzed after core collection and exception types that are defined in `EXCEPTIONS_TO_REPORT` set will be included as a dict and returned from the `collect()` function, as a second value in the tuple. This is needed so insights-client can analyze those errors and direct the collection logic flow differently if necessary.

fix: Add ability to return exceptions during insights collect

---

insights/tests/client/collection_rules/test_map_components.py

virt-who command were removed in egg v3.0.298, this was causing to not be asserted in the tests.

Removed assert of virt-who

---

insights/core/spec_factory.py
insights/util/autology/datasources.py

- fix the following issue:
The `rpm_format` of `installed_rpms` includes `%` characters, which caused the `collect_execute` cannot collect it from the container correctly.
https://github.com/RedHatInsights/insights-core/blob/1880a9c21b6c54c018fd0237b20ae6aeffd60d29/insights/core/spec_factory.py#L1011
This patch fixes this issue with:
```the_cmd = "/usr/bin/%s exec %s %s" % (engine, cid, cmd)```
- and update the insights/util/autology/datasources.py correspondingly

fix: let container_execute to support rpm_format of installed_rpms

---

insights/client/apps/malware_detection/__init__.py
insights/client/client.py
insights/client/config.py
insights/client/connection.py
insights/tests/client/apps/test_malware_detection.py
insights/tests/client/test_client.py

This is to fix https://bugzilla.redhat.com/show_bug.cgi?id=2117686
The insights-core connection.py._http_request() code doesn't handle network exceptions. Callers of this function just get status_codes containing errors rather than any network exception handling. This PR catches network exceptions in the _http_request() method and raises them up the call stack until they are caught in the client.py.upload() and _legacy_upload() functions.  This allows the --retries option to work correctly because before, --retries didn't work if there was a network exception.

Handle upload exceptions allowing --retries to work properly

---

insights/tests/client/apps/test_malware_detection.py

Malware test was trying to create a `machine-id` file if there isn't one in the system.
I have mocked the method that tries to create the machine-id as a solution.

Avoid test to write in disk if machine-id is not found

---

insights/specs/datasources/container/__init__.py
insights/tests/datasources/container/test_running_rhel_containers.py

From RHEL 8, the "docker" command is from the package "podman-docker". In
general when using command "docker" to access a container, the following
message will be reported on the top::
`Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.`
But sometimes, this line won't be outputted as expected, in this case, it's
necessary to remove the duplicated containers from the output of "docker".
This PR enhances the `runing_rhel_containers` and remove such duplicates.

fix: remove duplicated containers from running_rhel_containers

---

insights/specs/default.py

The refactoring made in commit 4438d91b3979557bc2019838c716c3b1378ec36a missed a call to a function. Instead of passing results of the function generated by _make_rpm_formatter, it passed the generated function directly to the string substitution.
Signed-off-by: daniel.zatovic <daniel.zatovic@gmail.com>
This resulted in calling the rpm command with wrong parameters and rpm not finding any packages:
```
$ insights-inspect insights.parsers.cryptsetup_luksDump.LuksDump -D
...
DEBUG:insights.util.subproc:Executing: [['timeout', '-s', '15', '30', '/bin/rpm', '-qa', '--qf', '<function _make_rpm_formatter.<locals>.inner at 0x7f71f3af29e0>']]
...
```

fix: missing call to a RPM format generation function

---

insights/parsers/cryptsetup_luksDump.py
insights/tests/parsers/test_cryptsetup_luksDump.py

Signed-off-by: daniel.zatovic <daniel.zatovic@gmail.com>
Every second-level section in the `cryptsetup luksDump` output is immediately followed (without a newline) by another second-level section. E.g. the "Digests" section
```
Digests:
0: pbkdf2
Hash:       sha256
Iterations: 119373
1: pbkdf2
Hash:       sha256
Iterations: 1000
```
However, when there are multiple data segments, there _is_ a newline:
```
Data segments:
0: crypt
offset: 16777216 [bytes]
length: (whole device)
cipher: aes-xts-plain64
sector: 4096 [bytes]
1: crypt
offset: 16777216 [bytes]
length: (whole device)
cipher: aes-xts-plain64
sector: 4096 [bytes]
flags : backup-previous
```
Most of the time, there is a single data segment. However, during re-encryption, there might appear multiple segments. …

fix: LuksDump not parsing multiple data segments

---

insights/parsers/pcs_config.py
insights/tests/parsers/test_pcs_config.py

Signed-off-by: Takayuki Nagata <tnagata@redhat.com>
`pcs config` shows empty `Corosync Nodes` on pacemaker remote nodes, and `data[in_line]` has an empty list. This fix checks the range before accessing `data[in_line][0]`. Without this fix, an exception is raised.

fix: check list range to avoid exception

---

insights/specs/__init__.py
insights/specs/datasources/ethernet.py
insights/specs/default.py
insights/tests/datasources/test_ethernet.py

This spec is not used by any existing specs/datasources, parsers, or rules. Let's just remove it.

chore: remove the unused 'ethernet_interfaces' spec

---

insights/specs/default.py

Remove the inner function as commented [here](https://github.com/RedHatInsights/insights-core/pull/3572/files#r1008107573) by Ryan.

fix: remove the inner functions of the _make_rpm_formatter

---

docs/shared_parsers_catalog/azure_instance.rst
insights/parsers/azure_instance.py
insights/parsers/azure_instance_plan.py
insights/parsers/azure_instance_type.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_azure_instance.py

- And move the AzureInstancePlan and AzureInstancePlan to azure_instance.py
- More the original parsers as deprecated
- change to use the latest supported API version '2021-12-13' provided by Azure

feat: new spec and parser for 'azure_instance_id'

---

insights/client/config.py
insights/client/core_collector.py

Add a top-level --manifest argument. This argument expects a path to an
insights collection manifest file. If the argument is not None, the
manifest is used instead of the default manifest to collect data.
Fixes: https://issues.redhat.com/browse/ESSNTL-3540

feat(client): add --manifest argument

---

insights/parsers/greenboot_status.py
insights/tests/parsers/test_greenboot_status.py

We discovered that the [greenboot-status parser](https://github.com/RedHatInsights/insights-core/blob/6cea5730e2dcb45d71702867b9bac35f94e99a2/insights/parsers/greenboot_status.py) does not check for the case where `greenboot-status` outputs "WARNING: No greenboot logs were found!". In this case, the archive contained no greenboot-status command output. The absence of this output [caused puptoo](https://github.com/RedHatInsights/insights-puptoo/blob/c221d6454b55c30f7ebe17cc517fe9d7f28c78f4/src/puptoo/process/profile.py#L213) to not set the profile["host_type"] field to "edge". When host_type was not set to "edge", the hosts were not showing up in Edge inventory.

fix(parsers): add support for missing logs

---

.github/workflows/main.yml

* Github is deprecating Node.js 12 actions, this PR updates to the latest version of actions
* For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Update github actions to use latest version

---

insights/parsers/dotnet.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_dotnet.py

New parser for dotnet --version in container

Feat: New Parser for 'dotnet --version' Command for Containers

---

insights/client/__init__.py

This PR is for more gracefully handling network exceptions if there is a problem accessing/downloading the egg URL.  Its to better handle the error shown in https://bugzilla.redhat.com/show_bug.cgi?id=2107323.  It doesn't actually have anything to do with retrying downloads because --retry only applies to uploads.
Logs before PR (unhandled exceptions and tracebacks):
Logs after PR (helpful error messages and graceful failure):

Handle network exceptions when accessing egg URL

---

insights/parsers/system_user_dirs.py
insights/specs/datasources/system_user_dirs.py
insights/tests/datasources/test_system_user_dirs.py
insights/tests/parsers/test_system_user_dirs.py

This PR should fix the complexity issue and also update the code logic, which was not entirely accurate.

Update system_user_dirs datasource

---

insights/parsers/installed_rpms.py
insights/specs/default.py
insights/tests/parsers/test_installed_rpms.py

Update container_installed_rpms spec to full path and add doctest for ContainerInstalledRpms

Fix: Update container_installed_rpms spec

---

docs/shared_parsers_catalog/ls_var_lib_pcp.rst
insights/parsers/ls_var_lib_pcp.py
insights/specs/__init__.py
insights/specs/default.py
insights/specs/insights_archive.py
insights/tests/parsers/test_ls_var_lib_pcp.py

Signed-off-by: Mohit Kumar <mohikuma@REDHAT.COM>

[New Specs] ls_var_lib_pcp

---

docs/shared_parsers_catalog/pcp_openmetrics_log.rst
insights/parsers/pcp_openmetrics_log.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_pcp_openmetrics_log.py

Signed-off-by: Mohit Kumar <mohikuma@REDHAT.COM>

New specs var_log_pcp_openmetrics_log

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

This is a rather weak attempt at hiding the downloaded malware rules file, but its slightly less obvious than what's currently being used.  This is a temporary fix until I can get something better happening, eg having the rules file in memory and written to disk as needed.

Rename downloaded temp malware rules file

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

Removes /usr/local/bin from the list of paths used to search for the yara binary.  When installing from the yara rpm the binary should only be found in /usr/bin or /bin

Don't look for yara installed in /usr/local/bin

---

insights/client/apps/malware_detection/__init__.py

Notify the user if the malware scan_timeout is encountered so they know that the filesystem or process may not have been fully scanned.

Display message when malware scan_timeout aborts scan

---

insights/core/dr.py
insights/core/plugins.py
insights/core/serde.py
insights/specs/datasources/container/__init__.py
insights/tests/core/test_dr.py
insights/tests/datasources/test_datasource_timeout.py
insights/tests/test_add_exception.py
insights/tests/test_serde.py

Added timeout using signals in the datasource invoke function, when the timeout is hit it raises a TimeoutException. Added code in the dehydrate to properly dehydrate caught exceptions.

feat: Add timeout to datasources

---

insights/combiners/mounts.py

Signed-off-by: Chen lizhong <lichen@redhat.com>
Before remove the combiner.mounts, give deprecate warning by this MR.
https://github.com/RedHatInsights/insights-core/pull/3606

fix: add deprecated warning message in insights.combiners.mounts

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

- just in case the previously-named rules file isn't deleted for some reason
Just some small changes to some recent malware-detection commits I made.  Main one was making sure the old downloaded rules file is still deleted.  I've renamed the file, but its possible (although rare) that the old file could be maintained on the customer's system and isn't deleted as we've changed the file name now that we are deleting.  This commit makes sure the old file name is still deleted as well.

Keep the code to delete previously-named malware rules file

---

insights/parsers/ethtool.py
insights/tests/parsers/test_ethtool.py

Signed-off-by: Chen lizhong <lichen@redhat.com>
Fix errors:
insights.parsers.ethtool.CoalescingInfo ValueError("invalid literal for int() with base 10: 'n/a'")
insights.parsers.ethtool.TimeStamp ParseException('bad line: \tsoftware-receive')
insights.parsers.ethtool.TimeStamp ParseException('bad line: \thardware-transmit')
insights.parsers.ethtool.Ring ValueError("invalid literal for int() with base 10: 'n/a'"

fix: fix errors in ethtool

---

insights/client/client.py
insights/client/phase/v1.py
insights/tests/client/phase/test_LEGACY_post_update.py
insights/tests/client/phase/test_post_update.py
insights/tests/client/test_client.py

If insights-client is not register and there is a machine-id file in the system the registration process should fail. 
It prints a new message asking to unregister the system again.
This resolves: rhbz#2071093

Feat register no machine-id

---

insights/client/__init__.py
insights/client/client.py
insights/client/config.py
insights/client/phase/v1.py
insights/tests/client/phase/test_post_update.py
insights/tests/client/test_client.py
insights/tests/client/test_config.py

Working on deprecate --force-reregistration client option. This option will be deprecate in favor of the explicit running of `insights-client --unregister` and `insights-client --register`. This work is part of the improvement of the re-registration safeguard [RHIN-500]
Resolves: #rhbz2071082

Remove usage of reregistration and deprecate cli-option

---

.github/workflows/main.yml

fix: fix CI issue when preparing py26 env

---

insights/client/apps/malware_detection/__init__.py

Some customers have /var/tmp instead of /tmp and unfortunately the logic for deleting old malware rules files fails in that case. This PR adds /var/tmp as a location to try deleting old rules files from.  Why do we want to delete old malware rules files ... because they cause false positives in matching systems.

Delete old malware rules files from /var/tmp as well

---

insights/core/spec_factory.py
insights/tests/test_specs.py

- fix: #3584 
- print the brief Exception message instead of the whole Traceback when command not found for command specs
- and test it in broker

fix: Log brief msg instead of Traceback when cmd not found

---

setup.py

Signed-off-by: Jakub Svoboda <jsvoboda@redhat.com>
The pinned version of [ipython is not compatible with Python 3.6](https://libraries.io/pypi/ipython/8.6.0). The pinning makes running pip install -e ".[develop]" impossible. As a result, setting up a fresh development environment with old Python is impossible without removing the pin. The pin was introduced in https://github.com/RedHatInsights/insights-core/pull/3615.

Improve old Python compatibility by not requiring ipython 8.6.0.

---

.github/workflows/main.yml

fix: py26 CI not found 'Python.h'

---

insights/specs/datasources/aws.py

When I test the playbooks, I found the spec "aws_instance_id_doc" can not be collected on RHEL 7.5:
```
2022-12-23 08:42:34,794     INFO insights.core.dr Trying insights.specs.default.DefaultSpecs.aws_instance_id_doc
2022-12-23 08:42:34,794    DEBUG insights.core.plugins The provider can only be a single string or a tuple of strings, but got 'AQAAAPTeS4-aK9v5iEb27uBubd5HjzogWpB_-0K1_sgGoVverKIrkg=='.
```
After debugging it, I found the return type of `aws_imdsv2_token` is unicode.

fix: Convert aws_token to string since sometimes it's unicode

---

insights/core/spec_factory.py
insights/specs/default.py

Added the ability to override env variables in CommandOutputProvider for specs, along with updating each function that inherited from CommandOutputProvider. Added an override for the yum command to unset the LC_ALL env variable. Fixed an issue where self.create_env() was being called multiple times instead of once. Fixed some pep issues.

feat: Add env override to CommandOutputProvider

---

insights/core/plugins.py
insights/tests/datasources/test_datasource_timeout.py

* Since timeout signals are only needed when HostContext is used we only need to set the signal in that case, logic was change to skip when using any other context than Hostcontext.
* Changes were made to the pytest module to add HostContext object to the broker in present tests
* Additional pytests were added to test when not HostContext

Create timeout signal for hostcontext only

---

insights/combiners/rhel_for_edge.py
insights/tests/combiners/test_rhel_for_edge.py

This enhancement is to add optional condition to check if the vm is from edge image

Fix: Add condition to check the output of "rpm-ostree status" firstly

---

docs/custom_datasources_index.rst
docs/shared_parsers_catalog/sys_fs_cgroup_memory.rst
insights/parsers/sys_fs_cgroup_memory.py
insights/specs/__init__.py
insights/specs/datasources/sys_fs_cgroup_memory.py
insights/specs/default.py
insights/tests/datasources/test_sys_fs_cgroup_memory.py
insights/tests/parsers/test_sys_fs_cgroup_memory.py

This PR is used to check the memory.swappiness setting under `/sys/fs/cgroup/memory` dir, check the CEECBA-6282 to see the detailed information.

feat: New datasource "sys_fs_cgroup_uniq_memory_swappiness" and its parser

---

insights/specs/datasources/sys_fs_cgroup_memory.py
insights/tests/datasources/test_sys_fs_cgroup_memory.py

…datasource into archive
Signed-off-by: Qin Ping <piqin@redhat.com>
With this enhancement, all the data can be written to the archive when the `sys_fs_cgroup_uniq_memory_swappiness` datasource gets multiple records.

Fix: write all data to sys_fs_cgroup_uniq_memory_swappiness

---

insights/combiners/rhel_for_edge.py
insights/tests/combiners/test_rhel_for_edge.py

This enhancement is to add optional condition to check if the vm is from edge image. Per this update, the combiner can determine if the vm is from edge image with checking only one parser, this can save the resource and improve the correctness.

 Fix: Add condition to check the output of "rpm-ostree status" firstly into combiner rhel_for_edge

---

insights/client/apps/malware_detection/__init__.py

Customers who have /tmp linked to /var/tmp will get false positives from the downloaded rules file in /var/tmp because we only check for the rules file in /tmp.  /facepalm ... D'oh ... crikey ... sheesh ... good lord ....  Anyway, this PR makes sure we check /tmp, /var/tmp, /usr/tmp and tempfile.gettempdir() for the downloaded rules file so we can ignore it in all those locations.

Exclude malware-detection rules files in /var/tmp (and other locations)

---

insights/client/apps/malware_detection/__init__.py
insights/specs/datasources/malware_detection.py

* And make log messages more informative when things go wrong
The malware-detection app can fail silently when things go wrong unexpectedly.  This also causes it to not upload results archives leaving customers confused as to why it failed and why they don't see any results in the UI.  This PR adds a few more try/except blocks around code sections where problems could occur and adds more helpful error messages ... however it doesn't fix the problem so I've still go more work to do there :/  
It also displays an error when the malware-detection app component unexpectedly fails as a whole which at least gives us a starting point for debugging the problem.

Make malware-detection app more resilient to unexpected errors

---

insights/specs/datasources/malware_detection.py

The new datasource timeout mechanism was causing malware-detection scans to be terminated after just 120 seconds, which isn't enough time to scan a system's filesystem.  This PR disables the datasource timeout alarm allowing malware-detection scans run for as long as necessary.

Disable datasource timeout alarm for the malware-detection app

---

insights/parsers/vdo_status.py
insights/tests/parsers/test_vdo_status.py

fix: https://github.com/RedHatInsights/insights-core/issues/3667

fix: Resolve VDOStatus excessive ParseException

---

insights/__init__.py
insights/core/dr.py
insights/core/plugins.py

Added the --show-skips cli arg to trigger SkipComponents to be captured in the broker for troubleshooting purposes.

feat: Add arg to capture skips in the broker

---

insights/specs/default.py

Signed-off-by: Pino Toscano <ptoscano@redhat.com>
The default environment for `simple_command` includes `LC_ALL=C`, which means ASCII (and not unicode); in case the language of the system is set to a non-English locale that uses unicode characters (e.g. non-Latin1 languages), then `subscription-manager` will fail to output that with encoding issues (e.g. [1]).
As a simple solution, enforce an unicode English locale for `subscription-manager`, which should avoid those encoding issues.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2074745

fix: use LC_ALL=C.UTF-8 for subscription-manager

---

insights/collect.py
insights/specs/datasources/kernel_module_list.py
insights/tests/datasources/test_kernel_module_list.py

The issue is https://github.com/RedHatInsights/insights-core/issues/3671
My first resolution is to add `keep_rc=True` into the spec:
~~~
modinfo_filtered_modules = command_with_args('modinfo %s', kernel_module_list.kernel_module_filters, `keep_rc=True`)
~~~
After updating, the spec can collect all of the output like this:
~~~
modinfo: ERROR: Module cvblk not found.
modinfo: ERROR: Module drbd not found.
modinfo: ERROR: Module emcpioc not found.
modinfo: ERROR: Module filepath not found.
filename:       /lib/modules/4.18.0-240.22.1.el8_3.x86_64/kernel/drivers/net/ethernet/intel/i40e/i40e.ko.xz
version:        2.8.20-k
...
~~~
However, the problem is that `modinfo: ERROR: Module XXX not found` can break the normal format: …

fix: Enhance datasource kernel_module_filters to check the loaded modules

---

docs/shared_parsers_catalog/blacklisted.rst
insights/client/data_collector.py
insights/collect.py
insights/core/blacklist.py
insights/core/dr.py
insights/core/exceptions.py
insights/core/spec_factory.py
insights/parsers/blacklisted.py
insights/specs/__init__.py
insights/specs/insights_archive.py
insights/tests/parsers/test_blacklist.py

Capture the name of blacklisted specs, and dump them to a file in the archive. Added parser and spec to parse the blacklisted specs and use in rules.

feat: Capture blacklisted specs inside archive

---

insights/core/spec_factory.py

Use the unique mangle_command for specs processes:
- Remove the duplicated definition of `mangle_command` from the `spec_factory` module
- Call the `mangle_command` defined in the `insights.util.mangle` module

chore: use the unique mangle_command for specs

---

.github/workflows/main.yml

To fix the following issue raised in the CI test of py26:
``` python2.6-dev : Depends: libssl1.0-dev but it is not going to be installed```

fix: py26 test: install libssl1.0-dev manually

---

insights/specs/default.py

There is no insights rule using spec lsinitrd_kdump_image and remove it.

chore: remove unused spec lsinitrd_kdump_image

---

insights/combiners/cloud_instance.py
insights/combiners/cloud_provider.py
insights/tests/combiners/test_cloud_provider.py

For Google Cloud Platform the `"provider"` and hence the `"provider_type"` should be `gcp` but not `google`

fix: provider of GCP should be 'gcp' but not 'google' 

---

insights/core/__init__.py
insights/tests/test_json_parser.py

The parse_content method raised ParseException on valid json string "null". To work with this data the raising SkipComponent part was moved outside the try/except block

fix: correct parse_content in JSONParser

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

Customer had their own self signed Satellite certificates.  Malware-detection couldn't download rules from the backend because it wasn't aware to use the custom CA certificates to verify the Satellite certificates.  This PR allows malware-detection to try different ca-cert/ca-bundle files to find the custom certificate and hence allow the rules to be downloaded successfully.
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2168808
Related Kbase: https://access.redhat.com/solutions/6997170

Better handle SSL cert verify errors when downloading malware rules

---

insights/combiners/os_release.py
insights/tests/combiners/test_os_release.py

- Add a new attribute "issued_packages" to the OSRelease to return the issued packages
that are must-installed but not signed or not provided by Red Hat.
- This update is useful to explain the reason to the customer.

feat: add OSRelease.issued_packages to return the issued packages

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

The malware SSL error fix lacked flexibility in detecting the SSL error.  This PR uses a regex to determine if the SSL error has occurred.  It probably needs a better way of determining an SSL error occurred other than string matching the SSL error message, but this seems to work well enough (for the time being).

Fix malware SSL error fix - make it more flexible

---

insights/core/filters.py
insights/tests/test_filters.py

fix: let 'get_filters' work for filterable=True specs only

---

insights/specs/datasources/malware_detection.py

* Helps integration tests to run smoothly
Hopefully this fixes an issue with the IQE tests where malware is displaying this error and causing problems with the tests:
```
2023-02-02 21:07:50 INFO Starting to collect Insights data for rhiqe.d6aa1c71-fd9c-447f-a5bf-58b04d1a4f6c.iqe-insights-client-plugin
Unexpected exception in malware-detection app: list index out of range
File "/iqe_venv/lib/python3.8/site-packages/insights/specs/datasources/malware_detection.py", line 23, in malware_detection_app
insights_config = InsightsConfig().load_all()
File "/iqe_venv/lib/python3.8/site-packages/insights/client/config.py", line 672, in load_all
self._load_command_line(conf_only=True)
File …
```

Log malware tracebacks to the log file, not the console

---

insights/client/connection.py

Previously, the error log just show the error:
_Error: multiple hosts detected_
The enhancement is to add resolution (re-register insights-client ) in the log.

fix: enhance the error message to reminder customers re-register

---

insights/core/spec_factory.py
insights/tests/core/spec_factory/test_listdir.py
insights/tests/core/spec_factory/test_listglob.py

The exact behavior of specs created using the listdir spec factory was difficult to predict because it depended on a number of subtle details:
- ContentException was raised instead of an empty list in some cases, an empty list was returned in other cases.
- The ignore filter was applied to returned values in some cases and to absolute paths in other cases.
- The specs returned only basenames of files and directories even for a complex glob (e.g. `some/*/file`) where returning relative paths makes more sense.
A dedicated `listglob` spec factory can have a more predictable behavior while keeping the implementation simple. In most cases, users will know if they want to list a directory or a glob pattern. An amphibious spec factory is not necessary.
This MR:
- Removes …

feat: Split listdir to listdir and listglob spec factories

---

insights/tests/__init__.py

PR #3663 added a `Broker.store_skips` attribute that allows for storing `SkipComponent` exceptions in the broker. This commit makes the feature available in tests based on the `run_input_data` function.

feat: Add store_skips argument to run_input_data

---

insights/combiners/os_release.py
insights/tests/combiners/test_os_release.py

- instead of the lone format "Red Hat Enterprise Linux"
- tiny update to return "RHEL" when `is_rhel==True`

chore: use RHEL for os_release.release

---

insights/parsers/php_ini.py

To fix the ParserException initialization in php_ini parser, this should be one typo.

fix: correct the initialization of ParserException in PHPConf

---

docs/custom_datasources_index.rst
insights/parsers/lsinitrd.py
insights/specs/__init__.py
insights/specs/datasources/kernel.py
insights/specs/default.py
insights/tests/datasources/test_kernel.py
insights/tests/parsers/test_lsinitrd.py

Add parser LsinitrdLvmConf, this parser is needed by RHINRULE-160.
When implementation:
1. Updated the existing ResistryPoint: lsinitrd_lvm_conf
2. Updated the existing parser LvmConf

Feat: Add parser LsinitrdLvmConf

---

insights/parsers/aws_instance_id.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_aws_instance_id.py

This tries to add an AWS public IP address, that is not known to the machine itself.
Issue: https://github.com/RedHatInsights/insights-core/issues/3731
Replaces: https://github.com/RedHatInsights/insights-core/pull/3732
Refs ESSNTL-4588
I would like to do the same for Azure and GCP too, would you prefer a single PR or multiple PRs?
This is my first contribution, review carefully and please guide me if I miss something. Thanks!

feat: AWS public IPv4 spec

---

insights/contrib/soscleaner.py

- the previous update didn't fix this issue totally
- fix: 2078807

fix: soscleaner get relative_path safely - 2

---

insights/parsers/azure_instance.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_azure_instance.py

This patch adds Azure public IP address:
Refs ESSNTL-4679
Related to: https://github.com/RedHatInsights/insights-core/pull/3741
Test on an Azure instance:
```
{
"name": "insights.specs.Specs.azure_load_balancer",
"exec_time": 0.0001773834228515625,
"errors": [],
"results": {
"type": "insights.core.spec_factory.CommandOutputProvider",
"object": {
"rc": null,
"cmd": "/usr/bin/curl -s -H Metadata:true http://169.254.169.254/metadata/loadbalancer?api-version=2021-12-13&format=json --connect-timeout 5",
"args": null,
"relative_path": "insights_commands/curl_-s_-H_Metadata_true_http_..169.254.169.254.metadata.loadbalancer_api-version_2021-12-13_format_json_--connect-timeout_5"
}
},
"ser_time": 0.017719268798828125
}
{
"loadbalancer": {
"publicIpAddresses": [
{ …
```

feat: Azure public IP spec

---

insights/client/client.py
insights/client/constants.py
insights/tests/client/test_client.py

This patch updates the logging file handler to no longer use a `RotatingFileHandler`
to prepare for the logrotate feature implementation in insights-client.
**Associated insights-client changes:** [insights-client PR](https://gitlab.cee.redhat.com/insights-platform/insights-client/-/merge_requests/49)

feat: logrotate client implementation

---

insights/parsers/dnf_module.py
insights/specs/default.py
insights/specs/insights_archive.py
insights/tests/parsers/test_dnf_module.py

DnfModuleList parser stores only the last module:stream which is incorrect, to solve this we should
- store all streams for module
- assign list of profiles to individual streams
- assign summary to individual streams
- parse [e] [x] [d] [a] [i] module stream and profile flags
- collect `dnf module list` output
This is going to be a breaking change but I haven't found any app using this parser in RedHatInsights org. It will be used by vulnerability-engine and patchman-engine to fix evaluation of CVEs/errata for modular packages by using this parser in insights-puptoo https://github.com/RedHatInsights/insights-puptoo/pull/272

fix: DnfModuleList parser and collect dnf_module_list

---

insights/client/apps/ansible/playbook_verifier/__init__.py
insights/tests/client/apps/test_playbook_verifier.py

Fixes a bug in the normalizeSnippet function that can inadvertently process elements in a CommendedSeq twice when iterating over elements in the sequence.
Fixes: ESSNTL-4354

Clarify logic when normalizing snippets

---

insights/tests/client/apps/test_playbook_verifier.py

sys.version_info named tuples were introducing with python 2.7. Test for lower version are failing because of that.
https://docs.python.org/2/library/sys.html#sys.version_info

fix: fix test playbook by using no named tuples

---

insights/parsers/dnf_module.py
insights/tests/parsers/test_dnf_module.py

While implementing https://github.com/RedHatInsights/insights-puptoo/pull/272 I noticed I made a bug in DnfModuleList parser. When a module is `default` and `disabled`, it can't be `active`

fix: default and disabled module cannot be active

---

docs/shared_combiners_catalog/ipa.rst
docs/shared_parsers_catalog/ipa_conf.rst
insights/combiners/ipa.py
insights/parsers/ipa_conf.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/client/apps/test_playbook_verifier.py
insights/tests/combiners/test_ipa.py
insights/tests/parsers/test_ipa_conf.py

``insights.parsers.ipa_conf.IPAConfig`` parses the IPA client and server config file ``/etc/ipa/default.conf``. The config file contains information such as domain, realm, and server URIs. The parser implements the same fallback logic as IPA's internal config parser.
``insights.combiners.ipa.IPA`` combines information from ``IPAConfig``, ``SSSDConfig``, and ``InstalledRpms`` to detect whether a system is an IPA server.
See: HMS-1285
This is an alternative take on PR #3764. It does not have spec and parser for ``/var/lib/ipa/sysrestore/sysrestore.state``. Instead it uses a combiner to check ``IPAConfig``, ``SSSD_Config``, and ``InstalledRpms`` whether a system is an IPA server. In addition it raises a ``ParserException`` when ``/etc/ipa/default.conf`` is invalid. …

feat: add parser and combiner for IPA

---

.github/workflows/main.yml

- fix the following errors in the py3.9 CI test:
```
>               u"strict": response.strict,
u"decode_content": response.decode_content,
}
}
E       AttributeError: 'HTTPResponse' object has no attribute 'strict
```
- See https://github.com/ionrock/cachecontrol/issues/292

fix: py3.9 test error: 'HTTPResponse' object has no attribute 'strict'

---

insights/core/filters.py
insights/tests/test_filters.py

- The current filters were generated in random order and in each release, 
it results in the MRs to the insights-core-assets containing a big change
and difficult to check the actual changes.
- This MR sorted the list of filters in the `filter.yaml`
- See INSGHTCORE-206 for details

fix: sort the filters in the filters.yaml

---

insights/specs/__init__.py

The spec dnf_modules is a glob spec, but didn't have the multi_output=True in the registry, so I added it.

fix: Add missing multi_output=True for dnf_modules spec

---

insights/specs/sos_archive.py

- To make rules against sos work, this spec is required

fix: add the lvm_conf back to sos_archive

---

insights/parsers/uname.py
insights/tests/parsers/test_uname.py

Changes behavior of Uname parser's `pad_release` such that a missing "el" segment of a release version results in the padded version having version numbers properly arranged.
The current behavior of the Uname parser's `pad_release` function is to unconditionally take the last segment of release version and place it at the end of padded version. This results in padded releases like below when no `el` segment is included (e.g. `el7`). 
- `0.0.0.0.1161`
- `1160.0.0.0.1`
This PR resolves this issue by first checking if the release string to be padded has a period to indicate multiple parts. If not, the release parts are simply joined with _trailing_ zeroes (instead of leading). If the release string _does_ have multiple parts and the last part contains alpha characters …

fix: uname pad release without el segment

---

insights/parsers/uname.py
insights/tests/parsers/test_uname.py

Resolves issue with Uname parser where the last segment of kernel version was always assumed to be the architecture if it didn't contain "el". A check is added to see if the last segment is a digit and if so we assume its not architecture.
Further resolves https://github.com/RedHatInsights/insights-core/issues/3799 and complements PR https://github.com/RedHatInsights/insights-core/pull/3800
When the Uname parser is given a partial kernel version (e.g. `3.10.0-1161.1`) the final segment of the version is incorrectly interpreted as the architecture iff it does not contain the letters `el` (e.g. `3.10.0-1161.1` would have `.1` interpreted as the architecture). 
This PR adds an additional check in `parse_content` to further identify if the last segment of version is just …

fix: correctly identify final segment of kernel version in uname

---

docs/shared_combiners_catalog/identity_domain.rst
insights/combiners/identity_domain.py
insights/combiners/krb5.py
insights/parsers/krb5.py
insights/parsers/sssd_conf.py
insights/tests/combiners/test_identity_domain.py
insights/tests/combiners/test_krb5.py
insights/tests/parsers/test_krb5.py

The new `IdentityDomain` combiner detects enrollment into identity domains such as IPA, Active Directory, and generic Kerberos/LDAP. The plugin combines information from `SSSD_Conf`, `AllKrb5Conf`, `SambaConfigs`, and `IPA`.
Also improves `AllKrb5Conf` combiner to parse a list of realm names and some `libdefault` settings like default realm and DNS lookup.
Also fixes issues with Kerberos tests. Kerberos realms are configured in `[realms]` section, not `[libdefaults]` section.
Also fixes an issue with `SSSD_Config.domains` property. The `domains` setting can contain white space.
See: HMS-1285

Feat: Add identity domain combiner

---

insights/tests/__init__.py
insights/tests/test_util.py

Beautify the deep_compare diff details for smooth rule test-cases development.
An example of the expanded AssertionError info looks like: 
```
>       assert eq(result, expected), _beautify_deep_compare_diff(result, expected)
E       AssertionError: 
E       	Missing result key "foo" not in expected;
E       	Extra expected key "bar_one" not in result;
E       	Extra expected key "bar_two" not in result;
E       	Unequal value of "common":
E       		Expected: "y"
E       		Result: "x"
E       Result: "RULE_ERROR_KEY:
E           foo            : None
E           common : "x"
E       "
```

feat: beautify testcase deep_compare diff details

---

insights/specs/datasources/kernel_module_list.py
insights/tests/datasources/test_kernel_module_list.py

modinfo_filtered_modules can only get the module which is same to the filter key words. Update it to get the modules which starts with the filter key words, so that we can get the information of all modules of mfe_aac_* (like mfe_aac_100713183, mfe_aac_100710368 and mfe_aac_100708119) with one filter ('mfe_aac'), rather than adding all modules full name to filter.

Enhance datasource kernel_module_list

---

insights/tests/client/apps/test_malware_detection.py

- To catch any potential changes in output/behaviour in newer yara releases
With newer versions of yara, I want to be sure that there are no changes in behaviour/output that might affect how the malware detection app uses yara.  This PR adds malware-detection app tests that run when an actual yara binary is detected on the test system.  It will skip the tests if yara isn't installed (which will probably be the case most of the time).  But still, having these extra tests will be useful for detecting changes in behaviour in newer yara versions.

Add malware-detection tests that use real yara

---

Dockerfile

Since CentOS 7 doesn't have pre-installed python 3.x we need to use this url `https://bootstrap.pypa.io/pip/2.7/get-pip.py` to get the right pip version, to avoid error on docker build process

fix: Using pip for python2.7 instead of python3x

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

- The cert_verify value may be set outside the malware-detection app Use its value if set, otherwise set it to True
Malware-detection had problems downloading rules via a Satellite.  Long story short, we weren't checking the cert_verify value from the InsightsConfig object and just blindly setting cert_verify to True.  This is ok with the customer portal, but with Satellites that use their own CA cert, then the cert_verify value should be /etc/rhsm/ca/katello-server-ca.pem.  This is what insights-client uses, but I failed to notice this and kept setting it to True, which meant downloading the malware rule via a Satellite didn't work correctly.
This PR checks the cert_verify value in the InsightsConfig and uses its value (if its set).  Only if its None do we change it …

Use the existing cert_verify value, if set

---

insights/core/__init__.py
insights/core/exceptions.py
insights/core/plugins.py
insights/parsers/azure_instance_plan.py
insights/parsers/azure_instance_type.py
insights/parsers/blacklisted.py
insights/parsers/branch_info.py
insights/parsers/cpuinfo.py
insights/parsers/docker_inspect.py
insights/parsers/engine_log.py
insights/parsers/installed_rpms.py
insights/parsers/ovs_vsctl_list_bridge.py
insights/parsers/podman_inspect.py
insights/parsers/rpm_pkgs.py
insights/parsers/tags.py
insights/parsers/version_info.py
insights/parsers/yumlog.py
insights/tests/parsers/__init__.py
insights/util/__init__.py

- Use 'removed from `3.#+1.0`' instead of 'removed after `3.#.25`'. 
Since sometimes the minor version would be greater than `25`.

chore: uniform the deprecation warnings and docstring

---

insights/client/apps/compliance/__init__.py
insights/tests/client/apps/test_compliance.py

This PR changes the format of the report that is uploaded from scan to ARF format.  ARF extends the XCCDF report with scan information such as OVAL results etc... This change has no impact on the other components.

RHICOMPL-3862 Adjust insights-client to upload reports in the ARF format

---

insights/specs/datasources/yum_updates.py
insights/tests/datasources/test_yum_updates.py

Take releasever and basearch from dnf config substitutions after loading them from variables.  It utilizes dnf.cli to load vars correctly.
RHINENG-985

fix(yum_updates): releasever and basearch

---

insights/client/insights_spec.py
insights/specs/default.py

Fix a regression of bugzilla 1935846, to also apply to dnf.
https://bugzilla.redhat.com/show_bug.cgi?id=1935846 was an issue that killed rpm and yum with SIGKILL on timeout, giving it no chance to clear their lock on the rpm database. This was fixed in #2974 by sending SIGTERM for yum and rpm. When these processes receive SIGTERM, they do have a chance to clear their locks.
Yum has been replaced by dnf in RHEL8. This PR adds dnf to the SIGTERM list.

Use SIGTERM for dnf command

---

insights/specs/default.py

This reverts commit 5b80bdada1ef3e635c7ee27691f887586331d441.
Re-add the spec `lsinitrd_kdump_image`

Revert "chore: remove unused spec lsinitrd_kdump_image (#3644)"

---

insights/specs/default.py

* Fix wrong filter reference in specs "ls_la_filtered" and "ls_lan_filtered"

fix: Fix wrong filter reference to 'ls_*_filtered' Specs

---

insights/client/apps/compliance/__init__.py
insights/tests/client/apps/test_compliance.py

**Closes** https://issues.redhat.com/browse/RHINENG-761 
In some situations our customers could  get TCP connection issue and then openscap parser fails to use tailoring file as instead of xml format we get json with error messages. We need better handling of tailoring file request.

RHINENG-761: Handle Compliance tailoring file request

---

insights/client/__init__.py

I catch the issue when was running insights-client against ephemeral environment. I don't have module-router-request application deployed there and registering host failed:
```
2023-07-04 04:02:14,506  NETWORK insights.client.connection GET https://env-ephemeral-ng0e91-gvcod9fw.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/api/module-update-router/v1/channel?module=insights-core
2023-07-04 04:02:14,615  NETWORK insights.client.connection HTTP Status: 200 OK
2023-07-04 04:02:14,615  NETWORK insights.client.connection HTTP Response Text: <!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<title>
Hybrid Cloud Console
</title>
<meta http-equiv="Content-Security-Policy" content="default-src 'self' https: wss: data: blob: 'unsafe-inline' 'unsafe-eval' …
```

Handle module router request response format

---

insights/parsers/ls.py
insights/parsers/ls_boot.py
insights/parsers/ls_dev.py
insights/parsers/ls_sys_firmware.py
insights/tests/parsers/test_ls_boot.py
insights/tests/parsers/test_ls_dev.py
insights/tests/parsers/test_ls_sys_firmware.py

- They are used by gss rules and other apps
See the latest comment to #3833

chore: discard the deprecation of LsBoot, LsDev and LsSysFirmware

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

When downloading the malware signatures file from stage, the insights-config.conf file usually has the entry cert_verify = False.  This caused malware-detection to fail to download the signatures file because it wasn't treating False as a string.  This fix treats False as a string and converts it to a boolean before trying to use it. *sigh*

fix: Malware fix to handle cert_verify set in conf file

---

insights/client/client.py
insights/tests/client/test_client.py

This commit resolves the incorrect permissions set
on log files when they are created and rotated by
being able to specify a umask before the file is created.
Resolves: ESSNTL-4198

feat: modify umask before creating log files

---

insights/combiners/os_release.py
insights/tests/combiners/test_os_release.py

- "name" to return the NAME of '/etc/os-release'
- "is_rhel_compatible" to return if convert2rhel could convert

feat: 2 new properties to OSRelease combiner

---

insights/client/data_collector.py
insights/specs/insights_archive.py

- fix: #3858 (workaround)
- and fix its incorrect file path in the `insights_archive.py`

fix: don't redact ls_systemd_units to avoid issue#3858

---

insights/combiners/os_release.py
insights/tests/combiners/test_os_release.py

- Identify non-rhel when one of them is non-rhel
- fix the following issue:
E.g. when `os_release` is non-rhel, but `redhat_release` is rhel, it will be identified as RHEL incorrectly.

fix: OSRelease when both os_release and redhat_release avaiable

---

insights/client/phase/v1.py
insights/tests/client/phase/test_update.py

Insights-client was printing to the terminal the traceback of an connection error.
~~~
Fatal error
File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
self.sock = ssl_wrap_socket(
File "/usr/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl( …

Handle exception when updating rules

---

insights/combiners/os_release.py
insights/tests/combiners/test_os_release.py

- Simplify the logic of OSRelease
Only continue the rest of the identification when cannot identify the OS is NON-RHEL

fix: simplify OSRelease: stop when identified NON-RHEL

---

insights/parsers/uname.py
insights/tests/parsers/test_uname.py

Detailed error is:
TypeError: '<' not supported between instances of 'str' and 'int'
The issue is: https://github.com/RedHatInsights/insights-core/issues/3815

fix: update Uname parser to fix LooseVersion comparision error

---

insights/formats/__init__.py
insights/tests/test_formats.py

Resolve INSGHTCORE-36 
When there is a typo in the rule's CONTENT attribute, an
UndefinedError exception would be raised during the jinja2
rendering process. This exception halts the rest of the processing,
so other, unrelated rule results are not output.
This feature adds try/except around individual CONTENT rendering,
so one "bad" rule has little to no impact on other rules.
See commit msg above.
Example before the fix: 
```
[INFO] shared_rules.sysmgmt.rhel_lifecycle_display.report
---------------------------------------------------------
File "/Users/joy/Work/gss-rules/venv/bin/insights-run", line 33, in <module>
sys.exit(load_entry_point('insights-core', 'console_scripts', 'insights-run')())
File …
```

feat: add try/except in jinja2 content rendering

---

insights/combiners/os_release.py
insights/tests/combiners/test_os_release.py

- In fact, this is not to fix an issue but to update the `release`
as per the requirement of puptoo

fix: OSRelease.release returns prepared OS Name

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

* Download disabled malware rules list
* Skip any matches on the disabled rules
* Make disabled rules case-insensitive
This PR downloads the list of disabled malware rules (if any) from the malware backend and skips any matches for these disabled rules, so those matches don't show up in the results archive that's sent back.

feat: Apply malware disabled rules

---

insights/client/config.py
insights/specs/datasources/yum_updates.py
insights/tests/datasources/test_yum_updates.py

To support satellite systems in Patch application, insights client will provide a flag (--build-packagecache) that will regenerate DNF/YUM cache and collect all the installable errata from the satellite system (dnf updateinfo list). 
I also want to add an option to the insights-client so this flag can be setup from the .conf file.

SPM-2113: allow re-generating dnf/yum cache on demand

---

insights/client/archive.py
insights/client/constants.py
insights/tests/client/apps/test_compliance.py
insights/tests/client/test_archive.py

This commit improve the use of temporary directories:
- The temporary directory will have a random name: `/var/tmp/insights-client-<random characters>`.
- It checks that the directory is not being in use before using it. If it existed, it will clean that directory and create a new one.
- Remove unused temporary directory and the function that used it: `archive_tmp_directory`.
- Change the cleanup mechanisms to be align with this change.
- Change the tests to be align with this change.
- Refactor the constants used.

feat: improve temp directories

---

insights/specs/datasources/machine_ids.py
insights/tests/datasources/test_machine_ids.py

- since the config is stored in `broker`, load it from `broker` instead of initiating a new one
- use client.get_connenction instead of InsightsConnection

fix: don't initiate InsighsConfig in dup_machine_id_info

---

insights/client/constants.py

insights-client was using /var/tmp to store the egg release file.
This commit changes the temporary directory to /var/cache/insights-client.

fix: improve temporary directory

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

This PR renames the malware rules file that is downloaded onto hosts to be scanned and puts it in /var/lib/insights.  This is to make the file more obvious as to its purpose and less likely for it to be flagged as malware itself.

Download malware rules into /var/lib/insights

---

insights/tests/__init__.py
insights/tests/test_run_input_data.py

The Broker.store_skips property needs to be set before the dependency graph execution in run_input_data().
See #3928

fix: store_skips argument of run_input_data has no effect (#3928)

---

insights/client/apps/malware_detection/__init__.py
insights/tests/client/apps/test_malware_detection.py

- And use a constant for the rules download directory
This PR uses constants.insights_core_lib_dir for the directory into which malware rules are downloaded, rather than hardcoding the /var/lib/insights directory.  It also improves the logging for matched disabled rules by logging the rule and the file/PID it was matched in.  Even though the rule is disabled, it would be nice to know which files/PIDs it still matches (if any).

Improve logging for disabled rule matches

---

insights/tests/__init__.py

- user can skip the check of filterable specs by
setting "do_filter=False" when calling run_test 
if the rule targets do not need to filter
- see INSGHTCORE-254

feat: add do_filter option to run_test for rule test

---

insights/specs/default.py

Due to a bug in xfsprogs, suspend the data collection for xfs_db command first.
The related jira card is: https://issues.redhat.com/browse/INSGHTCORE-257

fix: Suspend the data collection for xfs_db command

---

docs/custom_datasources_index.rst
insights/parsers/ls.py
insights/specs/__init__.py
insights/specs/datasources/ls.py
insights/specs/default.py
insights/tests/datasources/test_ls.py
insights/tests/parsers/test_ls.py

* The class "FileListing" can not parse the output of "ls" with "-nZ" now. We have to enhance the class to support it. Since the previous the "-n" argument in "ls -lanRz" and "ls -lanZ" is not meaningful, we decide to remove the "-n" in the arguments instead of make the class too complicated.

fix: Replace "ls_lanRZ" and "ls_lanZ" with "ls_laRZ" and "ls_laZ"

---

insights/core/ls_parser.py
insights/tests/parsers/test_ls.py

Fixes https://github.com/RedHatInsights/insights-core/issues/3939
* The base class "FileListing" of parsers for "ls -xxx" specs raises the error "ValueError: invalid literal for int() with base 10: '10,'" when parsing the output like "ls -lZ /dev"

fix: Fix bug of ls_parser when handling "major" and "minor" in e.g. "ls -lZ /dev"

---

insights/contrib/soscleaner.py

The _yum.log_ file collected by the _yum_log_ spec can in theory leak sensitive information. A RAT scan on the real customer data show that in reality this does not happen. The warning calls for caution when adding items to the list of excluded specs.
YUM plugins can write arbitrary information to the log file, potentially creating lines containing both a filter keyword (_Erased:_, _Installed:_, _Updated:_) and an IP address, e.g. a repository URL. Also, log files are persisted in their localized form, so they can contain various strings that are separate from the code and out of developer control.

Add warning to yum_log exclusion

---

insights/core/filters.py
insights/tests/core/test_filters.py

- when add_filter to component (parser or combiner),
add the filters to the datasource that the component
actually depends on
- and add relevant tests
- fix #3948

fix: add filter to dependency datasource only

---

insights/collect.py
insights/components/satellite.py
insights/parsers/satellite_postgresql_query.py
insights/specs/default.py
insights/tests/parsers/test_satellite_postgresql_query.py

* Since satellite 6.14, the column "default" has been deleted from the satellite_settings table.

fix: Enhance spec "satellite_settings" and parser to support satellite 6.14

---

insights/specs/datasources/satellite_missed_queues.py
insights/tests/datasources/test_satellite_missed_queues.py

* qpid ssl certificate "/etc/pki/pulp/qpid/client.crt" is removed since satellite 6.11, to list the qpid queues for goferd, we can use "ls /var/lib/qpidd/qls/jrnl2" now. In fact this directory only exists when satellite enables katello-agent.

fix: Enhance datasource "satellite_missed_pulp_agent_queues"

---

insights/core/spec_factory.py
insights/tests/test_specs.py

- Fix below issue:
For some specs defined with "first_of", the old check will raise the following exception:
```
AttributeError: 'simple_file' object has no attribute 'filterable'
```

fix: avoid AttributeError raised by filterable check when run rules

---

insights/parsers/getconf_pagesize.py

The `__str__` method of class `GetconfPageSize`
contains an unexpected parameter called `context`
that has no use in the method at all. Keeping the
parameter would result in an error. As a fix, I've 
removed the parameter.
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [getconf_pagesize.py](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/getconf_pagesize.py#L35), class: GetconfPageSize, there is a special method `__str__` that contains an unexpected number of parameters. Each call to this method will result in a TypeError. iCR suggested that special methods should have an expected number of parameters. More infomation can be found in the Python documentation on the various special method. …

Fixed Improper Method Call: `__str__`

---

MANIFEST.in.core

A while back datasources were added that referenced client code, this broke the rpm usage because it pruned the client code in it's build. This weirdly caused some specs to work, and some to not which caused it to go un-noticed for a bit. This change removes the prune line that removed the client code in the build process. So the rpms will be slightly larger, but will allow specs to work properly again.

fix: Remove pruning client code from rpm

---

insights/specs/datasources/httpd.py
insights/specs/default.py
insights/tests/datasources/test_httpd.py

This PR is used to enhance httpd_conf spec so that it can handle `Include` situation.

Enhance httpd spec include

---

insights/specs/datasources/kernel_module_list.py

* The class "command_with_args" requires the arg to be str or tuple. But the return value of the "kernel_module_filters" datasource is unicode with python2. As a result, an exception is raised.
* Fixes https://github.com/RedHatInsights/insights-core/issues/3980

fixes: Fix a bug about spec "modinfo_filtered_modules"

---

insights/parsers/mount.py
insights/tests/parsers/test_mount.py

* Option values in quotes with embedded commas are parsed incorrectly.
* Add a mount specific function to correctly parse mount options and use it for all mount option parsing.
* Fix #3983

fix: Fix issue with mount parsers mount option parsing

---

insights/parsers/mount.py
insights/tests/parsers/test_mount.py

* Fixes the problem introduced in #3984 where there was no embedded comma in the quoted value then the option would not be saved.

fix: Fix problem parsing mnt opt quotes

---

insights/parsers/xfs_quota.py
insights/tests/parsers/test_xfs_quota.py

Update data structure of xfs_quota to fix taking too long to run

Chore: Update data structure of xfs_quota to fix taking too long to run

---

insights/parsers/udev_rules.py
insights/specs/default.py

This spec was added for a new Advisor rule. Here to correct the spec's file paths.

fix: wrong spec file path of UdevRules66MD

---

insights/client/phase/v1.py

This commit adds a warning message to let user know BASIC auth is being deprecated:
- New message added to log. When the egg is running its first phase. This will log the message and also print it in the command output.
These messages appear when BASIC auth is configured.
Resolves: CCT-137

feat: add warning message when BASIC auth is used

---

insights/client/apps/compliance/__init__.py

The `_fetch_system_by_machine_id` might return `False` or `None` responses that weren't handled in our codebase properly. In this fix I am adding a type check on the list of returned systems to make sure that the `len()` method doesn't fail.

fix(compliance): RHINENG-1935 handle non-list responses from inventory

---

insights/specs/datasources/yum_updates.py

we need to load dnf plugins to get package updates from dnf, especially on AWS systems where amazon-id plugin substitutes substrings in repo url - RHINENG-7888
yum_updates collection failed on AWS systems because it tried to download repo with invalid url (rhui.REGION.aws.ce.redhat.com). `REGION` string is replaced by `amazon-id` dnf plugin, so we need to load dnf plugins. `configure_plugins` must be called after `read_all_repos` since it modifies loeaded repos.

fix(yum_udpates): load dnf plugins

---

.gitleaks.toml
insights/client/__init__.py
insights/client/collection_rules.py
insights/client/crypto.py
insights/tests/client/test_crypto.py

GPG creates a directory `$HOME/.gnupg/` every time it performs some operation. When run under root, but not manually (e.g. via subscription-manager Cockpit plugin), it tries to create and write to this directory, which causes SELinux denials.
This patch utilizes the `--homedir` argument GPG supports in order to move the home directory to a temporary directory for the time of the transaction. After the GPG action is performed, the directory is cleaned up.
You can verify this patch by performing the following actions:
1/ Create your own GPG key pair
```
~ $ gpg --full-generate-key
~ $ gpg --list-secret-keys --keyid-format long
~ $ (key identifier is on line `sec`, after the slash)
~ $ KEYID=9F2B2565A7CC100E  # (for example)
~ $ gpg --armor --export $KEYID > …
```

RHEL-2480: Do not create /root/.gnupg/ directory by accident

---

insights/tests/core/test_spec_cleaner_redact.py

This was causing the tests to fail locally.
On Python 2.7, these tests were failing because the strings were being compared by their identity, instead of equivalence.

fix(test): spec cleaner tests are using 'is' for comparing strings

---

insights/client/connection.py
insights/client/utilities.py
insights/tests/client/connection/test_LEGACY_reg_check.py
insights/tests/client/connection/test_reg_check.py
insights/tests/client/support/test_collect_support_info.py
insights/tests/client/test_utilities.py

When insights-client checked the status created a machine-id file to make some calls to the console service. That created a residual machine file if it had not access to the service (i.e. system was not registered to rhsm).
This PR refactors a bit the logic of generate_machine_id, and splits in a new function that will only get the machine id `get_machineid()`.
Checking status and `generate_machine_id` will use this new function.
Test have been changed and a new one has been created.
Resolves: CCT-161

fix: check status created a machine-id file

---

insights/parsers/mdadm.py
insights/specs/datasources/mdadm.py
insights/specs/default.py
insights/tests/datasources/test_mdadm.py
insights/tests/parsers/test_mdadm.py

Resolve https://github.com/RedHatInsights/insights-core/issues/4010 
~Local test with `insights-collect`,~ 
~~~
Create MD Array /dev/md1 /dev/md56, and touch a file /dev/mdxyz as a fake one:
#mdadm_D = command_with_args("/usr/sbin/mdadm -D %s", mdadm.raid_devices)      # command broken due to /dev/mdxyz
#mdadm_D = simple_command("/usr/sbin/mdadm -D /dev/md1 /dev/md56 /dev/mdxyz")  # command broken due to /dev/mdxyz
#mdadm_D = simple_command("/usr/sbin/mdadm -D /dev/md1 /dev/md56")             # command be collected successfully
mdadm_D = foreach_execute(mdadm.raid_devices, "/usr/sbin/mdadm -D %s")         # seperate command to not affect each other
~~~
~The collected `meta_data/insights.specs.Specs.mdadm_D.json` with `foreach_execute`:~
~~~ …

fix: spec mdadm_D to render arg /dev/md* properly

---

insights/core/spec_cleaner.py
insights/tests/core/test_spec_cleaner_obfuscate.py
insights/tests/core/test_spec_cleaner_redact.py

- when 'display_name' was specified,  the hostname was set to
display_name in spec cleaner by mistake,  resulting in the actual
hostname being missed to be obfuscated.
- see RHINENG-8200

fix: hostname is not obfuscated when using display_name

---

insights/core/spec_factory.py

- fix the following issue reported in Times And Error report:
`TypeError("MetadataProvider.__init__() got an unexpected keyword argument 'save_as'")`

fix: unexpect kwargs save_as

---

insights/specs/__init__.py

The output of the `subscription-manage identity` looks:
```
system identity: 9b53c93a-88ea-4168-9edf-b58e6c2ba66d
name: insights-xyz.redhat.com
org name: EXD
org ID: EXD
environment name: Library
```
The hostname should be obfuscated accordingly.

fix: subscription-manager identity should be obfuscated with hostname

---

insights/specs/datasources/leapp.py
insights/tests/datasources/test_leapp.py
insights/tests/parsers/test_leapp.py

- Resolves: RHINENG-6807
- parser for `/etc/migration-results` now collects all `LEAPP_*` and `CONVERT2RHEL_*` env variables, this will allow us to obtain knowledge of environments from where convert2rhel and leapp were executed and get very valuable statistics.

feat: collect LEAPP_* and CONVERT2RHEL_ env vars in migration-results

---

insights/parsers/dmidecode.py
insights/specs/__init__.py
insights/tests/parsers/test_dmidecode.py

- fix the typo of the key of UUID to "uuid"
- and remove it from Specs

fix: get bios_uuid (system_uuid) from dmidecode correctly

---

insights/core/__init__.py
insights/parsers/cpu_online.py
insights/tests/parsers/test_mssql_api_assessment.py

-----
Get this following exception from "Insights Times and Errors Report 2024-03-05" :
| -------- | ------- | -------- | ------- |
|271483|insights.parsers.mssql_api_assessment.ContainerMssqlApiAssessment|some_request_id|ParseException("insights.parsers.mssql_api_assessment.ContainerMssqlApiAssessment couldn't parse json.")|
An example of the file content: 
```
cat: /var/opt/mssql/log/assessments/assessment-latest: No such file or directory
```
Fix this by special handling the `CommandParser.__bad_single_lines` like output in `ContainerParser`.

fix: ContainerMssqlApiAssessment ParseException

---

insights/client/core_collector.py
insights/collect.py
insights/tests/test_collect.py
insights/tests/test_specs_save_as.py

- the "client_config" (InsightsConfig) already contains the
manifest read from the client tool, this change removes it
from the argument list of insights.collect() and simplify
the code

refactor: avoid passing duplicated mainfest to insights.collect()

---

setup.py

When following the egg build steps from a directory that is not the root
of the repository, this step fails because the README is looked up by a
relative path.

fix: Allow running setup.py from non-current directory

---

insights/client/connection.py
insights/client/utilities.py
insights/tests/client/connection/test_LEGACY_reg_check.py
insights/tests/client/connection/test_reg_check.py
insights/tests/client/support/test_collect_support_info.py
insights/tests/client/test_utilities.py

- #3965 was reverted in #4018 due to a false positive test failure
This PR is going to re-do the #3965 by reverting the #4018.
Hopes all things could be self-linked in this way.
This reverts commit 39f95b187330d80ad783e4e42f3f01f7edae47fb.

Re-Do "fix: check status created a machine-id file (#3965)"

---

insights/client/utilities.py
insights/tests/client/test_utilities.py

* Card ID: CCT-161
insights-client sometimes incorrectly regenerates identity while it shouldn't. Because the machine-id file is created preemptively, instead of at registration time (and deleted if the registration fails or Inventory returns error status signaling the system has been deleted in there), this is the easiest way to ensure the UUID will stay semi-stable.
subscription-manager already provides a stable way to identify a system. To ensure external tooling doesn't get confused, we should try to keep them consistent.

feat: Reuse subscription-manager identity for machine-id

---

insights/core/dr.py
insights/core/plugins.py
insights/core/spec_factory.py
insights/specs/__init__.py

- see RHINENG-6943 and RHINENG-6999
the priority of specs can be set via the new "prio" option
to the specs' RegistryPoint.  Integer is allowed, bigger
value gets higher priority, and 0 is default and for no priority.
- and set the blacklist relevant specs to the lowest priority

feat: collect specs in order based on given priority

---

insights/combiners/logrotate_conf.py
insights/parsers/logrotate_conf.py
insights/tests/combiners/test_logrotate_conf_tree.py
insights/tests/parsers/test_logrotate_conf.py

Fix: Fix LogRotateConfPEG cannot handle '='

---

insights/collect.py
insights/core/blacklist.py
insights/tests/test_collect_apply_blacklist.py

- see RHINENG-8898
- and do not support regex for commands/files anymore
- Per the manual, in file redaction, the "commands" and "files" do not support regex match, this feature is also removed from this change.

fix: support commands/files in file-redaction.yaml per manual

---

insights/tests/test_uploader_json.py

- The consistent check of the symbolic_name can be applied on the uploader.json in the canary deployment "/testing" instead of production "/release"

chore: use the uploader.json in '/testing' for unit test

---

insights/parsers/luksmeta.py
insights/tests/parsers/test_luksmeta.py

* It was not clear how to determine the number of key slots since the dictionary contained other keys. This PR adds new attributes to enable accessing the device uuid and a list of the key slot IDs.
* The existing dictionary key for device_uuid was left in place for backward compatibility.
* Testing was enhanced for new attributes
* Some minor cleanup
* Related to TYCHE-1036

feat: Enhance luksmeta parser

---

insights/core/spec_factory.py
insights/tests/test_specs_save_as.py

- The `command_with_args` helper function is a single command spec, 
its result should be saved under the `insights_commands` always.
Its `save_as` should be a file but not a directory.

fix: save_as of command_with_args cannot be a directory

---

insights/combiners/rhsm_release.py
insights/tests/combiners/test_rhsm_release.py

Parser SubscriptionManagerReleaseShow was deprecated,
remove it from combiner.rhsm_release accordingly.
for RHINENG-7882 

fix: deprecated parser usage in combiner.rhsm_release

---

insights/combiners/ps.py
insights/parsers/ps.py
insights/specs/datasources/ps.py
insights/tests/combiners/test_ps.py
insights/tests/components/test_ceph.py
insights/tests/core/test_dr.py
insights/tests/datasources/test_get_running_commands.py
insights/tests/datasources/test_package_provides.py
insights/tests/datasources/test_pcp.py
insights/tests/datasources/test_ps.py
insights/tests/parsers/test_ps.py

RHINENG-9075 
(Changes based on our last discussion about "Deprecate Specs.ps_eo".)
-   Move the data collection of ps columns(ppid and nlwp)
from Specs.ps_eo to datasource Specs.ps_eo_cmd. And
popular the data to Ps combiner.
This is for the future deprecation of Specs.ps_eo to
resolve https://github.com/RedHatInsights/insights-core/issues/4054
- Remove PsEo parser from Ps combiner
- Deprecate PsEo parser

feat: extend Specs.ps_eo_cmd to deprecate Specs.ps_eo

---

insights/client/collection_rules.py
insights/tests/client/collection_rules/test_get_rm_conf.py

- see RHINENG-9044
- A warning message should be printed to the console when the required `machine_id` is skipped for redaction by the customers.

chore: print warning when 'machine_id' is skipped for redaction

---

insights/parsers/nginx_conf.py
insights/tests/parsers/test_nginx_conf.py

* Fix issue #4086 by including empty quoted string as a valid param
* Added test for config

bug: Fix nginx conf parser for empty quoted params

---

insights/parsers/scsi.py
insights/tests/parsers/test_scsi.py

for RHINENG-9677 
Raise `SkipComponent` instead of `ParseException` for the empty content case. 
|------|---------------------|--------------------------------|--------------------------------------------------|
| 53234| insights.specs.Specs.scsi|some-request-id| ParseException('Empty content of file /proc/scsi/scsi', [])|
| 53234| insights.parsers.scsi.SCSI|some-request-id| ParseException('Empty content of file /proc/scsi/scsi', [])|

fix: ParseException raising in parsers.scsi

---

insights/client/connection.py
insights/tests/client/connection/test_checkin.py
insights/tests/client/test_connection_clean_facts.py
insights/tests/client/test_platform.py
insights/tests/client/test_upload_archive_cfacts.py

- When obfuscate=True/obfuacate_hostname=True is specified,
the canonical facts should also be obfuscated even when 'checkin'
- See RHINENG-9595
- RHINENG-9595

fix: canonical facts was not obfuscated when '--checkin'

---

insights/collect.py
insights/combiners/hostname.py
insights/combiners/redhat_release.py
insights/core/__init__.py
insights/core/hydration.py
insights/core/serde.py
insights/core/spec_factory.py
insights/shell.py
insights/tests/test_serde.py

- Pass the context and datasource to the Provider to fix the issue of: 
When running rules against insights-archive collected by core-collection
the context and datasource is not generated accordingly, it results in
different behavior than sos-archive, e.g. cannot get the filters of specs
fix: #4081

fix: no context and datasource when running against insights-archive

---

insights/core/exceptions.py
insights/core/spec_factory.py

- see RHINENG-9993
- the "non-filter" exception can terminate a first_file spec,
as the "filter" is based on the RegistryPoint, but not the sub-items
- the "non-existing" path exception should not terminate the first_file spec,
as all paths in the list should be checked one by one
- See RHINENG-9993

fix: only non-filter exception can terminate the first_file spec

---

insights/client/utilities.py

The bug in the signature makes this function write down the time the egg was loaded, not the current time when this function is actually being called.

fix: Make utilities.write_to_disk use current time by default

---

insights/core/filters.py
insights/core/spec_factory.py

- validate the filters of 'filterable' specs only when the variable is True
when it's False, all content will be loaded (this is not changed in this PR)
- fix: #4103

fix: env INSIGHTS_FILTERS_ENABLED no longer works

---

insights/client/client.py
insights/client/phase/v1.py

[CCT-372](https://issues.redhat.com/browse/CCT-372)
This pull request fixes a repeating issue that it’s hard to determine the core (egg) version from customer logs.
To improve client-side debugging, made the core log its version along its path whenever verbose mode is enabled. It is no longer necessary to pass --debug, which was the sole use case of this undocumented flag. Like this, the core version can be found in any log file captured from a customer’s machine.
The core path is now less confusing. It points to core package top directory, not to a module containing the log call. The logic is the same as in the Client.
To find the exact place where logged events occur, a line number is now part of every log message.
Steps to verify:
1. Run the Client with the …

feat: Improve debugging experience

---

insights/tools/query.py

fix this below error of `insights-info` run: 
```
$ insights-info insights.specs.Specs.hosts  
File "/Users/joy/Work/insights-core/venv/bin/insights-info", line 33, in <module>
sys.exit(load_entry_point('insights-core', 'console_scripts', 'insights-info')())
File "/Users/joy/Work/insights-core/insights/tools/query.py", line 412, in main
ds = get_matching_datasources(args.paths)
File "/Users/joy/Work/insights-core/insights/tools/query.py", line 193, in get_matching_datasources
if matches(d, path):
File "/Users/joy/Work/insights-core/insights/tools/query.py", line 177, in matches
search_tgt = d.cmd.strip('/').split()[0].split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'strip'
```

fix: 'NoneType' AttributeError in insights-info

---

insights/parsers/falconctl.py
insights/tests/parsers/test_falconctl.py

Had seen some `ParseException: "Invalid content: ['aid is not set.']"` .  enhance to special handle this `"not set"` case as `falconctl_backend`.

feat: enhance falconctl_aid exception parsing

---

insights/tests/client/apps/test_playbook_verifier.py

There exists a race condition when removing files in a directory in which GPG has saved its runtime data.
When GPG detects the files are getting removed, it will kill its socket and start deleting the files. In that case, `rmtree` may try to delete a file that has already been deleted by GPG, causing `OSError`.

fix(test): Catch errors caused by GPG

---

insights/client/utilities.py

New if-else statement is added to check if exit code of previous Popen call is == 0 . Statement is added to insights.client.utilities.print_egg_version method.
CARD ID: CCT-406
Originally, when unimportable egg was encountered, Insights client logged part of the traceback to the DEBUG log. I added a functionality which checks exit code of corresponding subprocess calling import and egg and if the code is not == 0, then it results to message ""path/to/egg: Corrupted egg." I was not able to capture exception from subprocess, so I choose this approach by using exit status. There is space for discussion whether there could happen another scenarios other than unimportable corrupted egg. Non-existing egg is already handled in code before.

fix: debug print of egg versions doesn't handle corrupted eggs

---

insights/specs/datasources/malware_detection/__init__.py
insights/specs/datasources/malware_detection/malware_detection_ds.py
insights/tests/datasources/malware_detection/test_malware_detection.py

RHINENG-10594
In the Insights archive, malware scan results are passed as GraphQL mutation query only.
Incoming changes include additional file `malware-detection-results-raw.json`, which contains JSON representation of python dictionary that was used to compose mutation query.
New file will be consumed by the newest version of malware-detection app. Old file is still needed for backwards compatibility.

feat: include JSON format in malware detection results

---

insights/parsers/installed_product_ids.py
insights/tests/parsers/test_installed_product_ids.py

* There are some whitespaces before the lines

fix: strip lines before parsing for InstalledProductIDs

---

insights/components/rhel_version.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/components/test_rhel_version.py

- this ausearch command will be executed at the end of collection
it can have the same 'prio' with the blacklisted_specs
as the latter is a datasource but not a command
- it will be executed only on RHEL 8.6 or later,
so new component IsGtOrRhel86 is also added in this commit
- no parser is required for this spec for now

feat: collect selinux issues of collection via ausearch

---

insights/core/spec_cleaner.py
insights/tests/core/spec_cleaner/test_clean_file_redact.py

- refine the workaround of #4074
- fix RHINENG-9901 as well

fix: password regex skip lines end with 'password'

---

insights/collect.py
insights/components/rhel_version.py
insights/specs/default.py

- In the first implementation of the spec, its collection
is failed due to its `deps` was not loaded before executing
- change to use full path of ausearch in command line
- keep the commend result even it's failed
- fix a typo in the IsGtRhel component
- Add the missed IsRhel6 for chkconfig spec
- see above

fix: add dependencies to manifest for ausearch_insights_client

---

insights/specs/__init__.py

- the content of lvm_system_devices contains `hostname` and should be obfuscated
it was set as `no_obfuscste=['hostname', 'ip']` by mistake.
This PR removed the 'hostname' from the `no_obfuscate` list.
- see RHINENG-10744

fix: lvm_system_devices contains hostname and should be obfuscated

---

Dockerfile

* To fix below error when build image by Dockerfile
> Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - “Could not resolve host: [mirrorlist.centos.org](http://mirrorlist.centos.org/); Unknown error”

fix: use ubi8 instead of centos7 in Dockerfile

---

insights/formats/__init__.py

Module insights.parsers.branch_info was deprecated and removed in insights-core-3.4.0
- This is a fix for RHINENG-11214
`insights.parsers.branch_info.BranchInfo` was deprecated in favour of `insights.parsers.client_metadata.BranchInfo`.
In `insights-core-3.4.0`, the module `insights.parsers.branch_info` was completely removed while it is still referenced by `insights.formats.EvaluatorFormatterAdapter`

FIX: remove reference for a deprecated module

---

insights/specs/__init__.py
insights/specs/default.py

RedHatInsights/insights-core#3848 added an image builder fact to the
subscription_manage parser, but there are multiple facts present in
osbuild.facts. Just expose all of them.

chore: collect image builder's osbuild.facts

---

insights/collect.py
insights/tests/test_collect.py

- datetime.utcnow() was deprecated since Python 3.12

feat: replace deprecated datetime.utcnow() usage

---

insights/client/apps/ansible/playbook_verifier/__init__.py
insights/client/apps/ansible/playbook_verifier/serializer.py
insights/tests/client/apps/test_playbook_verifier.py

* Card ID: CCT-538
The playbook verification relies signatures created from hashes of serialized snippets/playbooks. Python 3.12 changed the way it serializes OrderedDict objects into strings, making the verification fail, resulting in valid playbooks being rejected.
This patch mimics the old serialization logic in a tested and easy-to-debug way.

fix: Serialize playbooks manually on Python 3.12+

---

.gitleaks.toml
insights/client/__init__.py
insights/client/collection_rules.py
insights/client/crypto.py
insights/tests/client/test_crypto.py

* Card ID: CCT-131
* Card ID: CCT-405
* Card ID: RHEL-2480
* Card ID: RHEL-2482
This patch adds a self-contained and isolated GPG verification
environment. It runs GPG in an isolated environment where only selected
PGP keys are allowed to check the file signature matches its file.
GPG creates a directory `$HOME/.gnupg/` every time it performs some
operation. When run under root, but not manually (e.g. via
subscription-manager Cockpit plugin), it tries to create and write to
this directory, which pollutes user directories and/or causes SELinux
denials.
This patch utilizes the `--homedir` argument GPG supports in order to
move the GPG home directory to a temporary directory for the time of the
transaction. After the GPG action is performed, the directory is cleaned
up. …

feat(pgp): Use crypto.py during Egg and Collection verification

---

insights/specs/sos_archive.py

As the subdir/path of `crictl_logs` has changes in sos-report archive from `sos_commands/crio/containers/crictl_logs_-t_` to `sos_commands/crio/containers/logs/crictl_logs_-t_*`, This enhancement is to add the new path in existing specs of log path so that both the old and new path will be compatible and can be supported by insights-core. we may consider to deprecated the old path in a long term.

feat: update specs for parser crictl_logs 

---

insights/client/config.py
insights/tests/client/test_config.py

* Card ID [CCT-404](https://issues.redhat.com/browse/CCT-404)
The command has been removed from the CLI and from the documentation. It only used to raise a deprecation error message, that being its only presence in the actual logic. There was only a single test verifying the deprecation message.

feat: Remove --force-reregister command

---

insights/tests/client/init/test_fetch.py

Two tests were mocking result of tempfile to prevent files from being written to filesystem during a test. A few years ago, a cleanup method was added to the tested code, to ensure the temporary directory the egg was downloaded to is cleaned up. Since then, these tests have been emitting warnings that Mock cannot be `lstat`ed.
This patch fixes it.

fix: Prevent test teardown issues of fast_fetch

---

insights/core/spec_factory.py

- For Python 2, ascii encoding is used by default, so when 
writing content to a file, encode('utf-8') should not be used
- This issue caused the compliance data cannot be collected in RHEL 7, 
see RHINENG-11682
- No tests added for this change

fix: do not encode(utf-8) when writing content in py2 env

---

insights/client/apps/ansible/playbook_verifier/serializer.py
insights/tests/client/apps/test_playbook_verifier.py

* Card ID: CCT-647
* Card ID: RHINENG-11692
The string serialization should reflect what Python does.

fix: Properly serialize playbook strings containing quote marks

---

insights/core/spec_factory.py
insights/tests/test_broker_exceptions.py

- 'filterable' is an option for collection but not running
It should be acceptable to run plugins that depend on "filterable"
spec but do not "add_filter" for the spec.
And the results of running the plugin with or without "add_filter"
should be the same.
- This change limits the validation of filter checking to data
collection only. That is, the filters check only works when
collecting a 'filterable' spec but not running it.
- tests are added as well
- see RHINENG-11728

fix: 'filterable' specs were skipped incorrectly when running plugins

---

insights/client/crypto.py
insights/tests/client/test_crypto.py

* Card ID: RHINENG-11802
* Card ID: CCT-653
Ensure we get Unicode data back when we run GPG in a subshell. This will ensure we are able to parse output of the command even if the host is configured to use non-UTF-8 character set.

fix: Run subshells with LC_ALL=C.UTF-8

---

insights/client/connection.py
insights/tests/client/connection/test_LEGACY_reg_check.py

* Card ID: CCT-186
* When system was registered against Satellite server, and "insights-client --register" was triggered --group="tag" CLI option, then registration failed
* Satellite also contains some bug, and it always returns status code 200 and empty list regardless existence of given group.

fix: insights-client failed, when --group was used

---

docs/shared_combiners_catalog/sssd_conf.rst
insights/combiners/identity_domain.py
insights/combiners/ipa.py
insights/combiners/sssd_conf.py
insights/parsers/sssd_conf.py
insights/parsr/query/__init__.py
insights/parsr/tests/test_iniparser.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/combiners/test_identity_domain.py
insights/tests/combiners/test_ipa.py
insights/tests/combiners/test_sssd_conf.py
insights/tests/parsers/test_sssd_conf.py

This pull request fix multiple issues in ipa, sssd and identity_domain. Each commit has its own description about the fix. It also adds extensive tests to verify its functionality.

Fix and test IdM related parsers and combiners

---

insights/core/spec_factory.py
insights/tests/datasources/compliance/test_compliance_ds.py

- When running plugins, print a debug information only for 
empty spec, but not raise Exception
- As before, the empty spec will be collected, but the
reason will be recorded as an ContentException in its
meta_data JSON
- JIRA: RHINENG-11843
- And change to show the full real path instead of relative path
in the debug message
- Fix the relevant test of compliance ds
- fix #4180

fix: Skip empty spec only when collecting

---

.flake8
.github/workflows/main.yml
insights/parsers/nginx_log.py
insights/tests/client/test_archive.py
insights/tests/parsers/test_nginx_log.py
insights/tools/coverage.py

- add a script for checking python coverage in insights.tools
- use the script in ci/cd pipelines to check updated python
- remove unused mocking of os.path.join in test_copy_dir
- Jira: RHINENG-12134

feat(ci): add coverage check for changed python file

---

insights/tests/__init__.py
insights/tests/test_integration_support.py

Using `run_test` with `expected` parameter **DOES NOT** perform expected assertion if `expected` value evaluates to false. For example, if `expected` is an empty list or dict or str or a bool value of `False`. The result is that no assertion is performed meaning that when checking that an integration test for a `condition`, for example, returns `False` but it instead, in error, returns `True`, `run_test` does not perform the assertion giving the impression that the test passes even though it does not.
This change fixes this by using a default sentinel value for `expected` and always performing the assertion unless `expected` is the sentinel value.
This change required updating an existing integration test. Additionally, it is important to note that this change will …

Fix skipped assertions for itests

---

insights/specs/datasources/httpd.py
insights/tests/datasources/test_httpd.py

This is enhancement is used to solve issue https://github.com/RedHatInsights/insights-core/issues/4215

Enhance datasource httpd ignore include expanded inner

---

insights/client/client.py

While that file is deprecated and it is good that it is not written after non-legacy uploads, in practice it is actually used by tooling that uses insights-client.
To avoid breaking functionalities in other software when switching to non-legacy, write /etc/insights-client/.last-upload.results also after non-legacy uploads. While those softwares are fixed to not rely on that file, at least this is one small step ahead in switching the default away to non-legacy without regressions elsewhere.
Implements CCT-710

feat(client): write .last-upload.results also after non-legacy uploads

---

insights/collect.py
insights/specs/datasources/ssl_certificate.py
insights/tests/datasources/test_ssl_certificate.py

* Currently, the combiner and parser can not handle special characters like 'é', so remove the dependency on it first before we enhance the complicated "DocParser"

fix: ssl_certificate no longer depends on HttpdConfTree

---

insights/tests/datasources/test_ssl_certificate.py

test: fix the py26 flake8 error in ssl_certificate test

---

.github/workflows/main.yml

- RHINENG-12134
- enable gitleaks as required

test(ci/cd): add gitleaks pipeline

---

insights/client/client.py

Reverts RedHatInsights/insights-core#4217
- an issue was found in the OLD IQE Jenkins test

Revert "feat(client): write .last-upload.results also after non-legacy uploads"

---

insights/parsers/cups_confs.py
insights/tests/parsers/test_cups_confs.py

Update the value format of this parser to adjust the Advisor rule.
- Per the manual and tests of cups_browsed.conf, 
different directives will be handled differently. E.g, 
for `BrowseAllow`, all its configured values will be kept, 
but for `BrowseRemoteProtocols`, only its last one will work.

fix: Update value format of CupsBrowsedConf

---

insights/core/spec_factory.py

- when collecting in py26 env, if the foreach_execute specs depends
on datasource, the provider will be in unicode type and cause validate()
failed
- this change converted the unicode to string by force for all 'cmd' passed to
CommandOutputProvider
- In the integration test under py26, the `foreach_execute` depends on
datasources cannot be collected as expected due to the following error:
```
File "/root/insights-core/insights.zip/insights/core/spec_factory.py", line 365, in validate
if not which(cmd, env=self._env):
File "/root/insights-core/insights.zip/insights/util/__init__.py", line 60, in which
if os.access(cmd, os.X_OK) and os.path.isfile(cmd): …
```

fix: datasource pass unicode to foreach_execute in py26

---

CONTRIBUTING.md
insights/core/spec_factory.py

- Removed python2 related steps
- Added Sensitive PII to check list
- RHINENG-12618

doc: Update the contributing guidance

---

.github/workflows/main.yml
insights/core/spec_factory.py

- and guide the first-time contributor to read the CONTRIBUTING.md
- RHINENG-12619
For first-time contributor, the following comment will be added automatically:
---
Thanks for contributing to insights-core.
To make sure your code is compliant with the guide, please go through the [Contributing](https://github.com/RedHatInsights/insights-core/blob/master/CONTRIBUTING.md#contributing) and review your code first.

test(ci/cd): add first-interaction action

---

docs/conf.py

- as per the latest sphinx-rtd-theme, the definiation can be removed
To fix the following error when building doc:
```
Configuration error:
There is a programmable error in your configuration file:
File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/sphinx/config.py", line 529, in eval_config_file
exec(code, namespace)  # NoQA: S102
File "/home/runner/work/insights-core/insights-core/docs/conf.py", line 117, in <module>
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/sphinx_rtd_theme/__init__.py", line 24, in …
```

doc(conf): remove definiation of html_theme_path

---

insights/tests/datasources/malware_detection/test_malware_detection.py

Versions of yara 4.5.x and later change/fix the fast-scan option and produce different results than earlier versions.  This PR updates the malware-detection tests so they work with both versions before and after version 4.5.x.
This PR doesn't affect the functionality of malware-detection in any way.  It just modifies some of the unittests.  And even then, the modified unittests only run if yara is actually installed on system running the tests.

Update malware-detection tests for different version of yara

---

insights/specs/__init__.py

- to fix issue: `permitemptypasswords no` is redacted to `permitemptypassword*********`
- sshd_test_mode is a filterable spec, the current filters does not contain the password information, and the available options of "sshd -T" also does not contain password information.

fix: Set no_redact for sshd_test_mode

---

insights/parsers/dig.py
insights/tests/parsers/test_dig.py
insights/tests/parsers/test_lvs.py

- remove unknow hostnames from tests and docstring
- remove duplicate but useless test input in test_lvs
rh-pre-commit.version: 2.2.0

chore: remove useless lines and hostnames from tests and doc

---

insights/collect.py
insights/specs/datasources/ssl_certificate.py
insights/tests/datasources/test_ssl_certificate.py

- The combiner and parser cannot handle special characters, so remove the dependency on it first
- Jira: RHINENG-13447

fix: nginx_ssl_certificate_files no longer depends on NginxConfTree

---

insights/core/spec_factory.py
insights/tests/test_specs_special_content.py

- Originally, simple file content was encoded when loading in py2 env
but was not encoded when writing to archive file.
When there are unicode characters in simple file, it causes 
UnicodeEncodeError and results in file cannot be collected.
- fix RHINENG-13636

fix: encoding issue in python2 env

---

insights/collect.py
insights/specs/datasources/pcp.py
insights/tests/datasources/test_pcp.py

- reorder and regroup the 'configs' that should be loaded in collection
- use the full path to the Class for each 'configs'
- tapstop=2 for the inline YAML
- replace Services combiner in datasources with UnitFiles Parser
- and reorder python imports with pre-commit

chore: refine the format of default_manifest in collect.py

---

insights/tests/datasources/test_httpd.py

- this test tried to verify that the `httpd_conf` cannot be collected
when the main httpd.conf doesn't exist.  However, when running test
in a machine that have this httpd.conf in system already, it will fail.
- this PR mocks the `os.path.join` and hence simulates that the main
httpd.conf doesn't exist and ignore the facts
- Jira: RHINENG-13664

test: test_httpd_conf_files_main_miss failed when httpd.conf exists

---

insights/core/spec_factory.py
insights/tests/test_specs_content_redaction_empty.py
insights/tests/test_specs_runtime_ds_obfuscation.py

- For 'persist' specs, they might be used during collection,
to avoid failure collection of dependencies, they shouldn't
be obfuscated in runtime.  But they should be obfuscated when
writing to archive. See the tests
- Jira: RHINENG-13591

fix: do not obfuscate in runtime but in archive only

---

insights/client/connection.py
insights/tests/client/connection/test_test_connection.py

The internal methods used by the `--test-connection` command only used to catch `ConnectionError`, including `ConnectionTimeout`, but not other timeouts such as `ReadTimeoutError`. As a result, in case of a read timeout,  the failure is not fully handled. That means:
* an error message containing the failed URL is not logged;
* and in case of legacy upload, the URL fallback mechanism is interrupted.
Re-used the existing `REQUEST_FAILED_EXCEPTIONS` list to process all timeouts in the same way.
Card IDs:
* [CCT-859](https://issues.redhat.com/browse/CCT-859)

Catch Timeout on test urls

---

insights/specs/sos_archive.py

The **SubscriptionManagerStatus** parser is well-implemented for handling sosreport file content. 
Initially, the file path for the insights-archive was specified only in `/insights/specs/insights_archive.py`.
To extend support for sos archives, the corresponding file path  added to `/insights/specs/sos_archive.py`.

Add subscription_manager_status spec file path for sos_archive

---

insights/client/connection.py
insights/tests/client/connection/test_test_connection.py

In case of a connection error, an exception description was printed on the standard output twice: once by the outer test_connection method and once by the inner _\_(legacy\_)test\_urls_ method. The legacy version tries multiple URLs and prints the exception description on each failure. Thus, removed the outer print that only duplicates the last caught exception.
Card IDs:
* [CCT-724](https://issues.redhat.com/browse/CCT-724)

Remove double exception print

---

insights/client/connection.py
insights/tests/client/connection/test_test_connection.py

The `--test-connection` command only used to catch `ConnectionError`, including `ConnectionTimeout`, but not other timeouts such as `ReadTimeoutError`. Re-used the existing `REQUEST_FAILED_EXCEPTIONS` list to process all timeouts in the same way.
There is an integration test pull request https://github.com/RedHatInsights/insights-client/pull/244 for this fix.
Card IDs:
* [CCT-506](https://issues.redhat.com/browse/CCT-506)

Catch Timeout on test connection

---

insights/client/connection.py

To avoid confusion for developers, removed the unnecessary conditional for exception re-raise.
* It is unnecessary to set last_ex on non-legacy, because there is no fallback to other URLs. Only one URL is tried and if it fails, there is only a single exception.
* The `if last_ex` condition can never be false, because if an exception is not raised, the function hits a return clause earlier. It only gets to the conditional if an exception has been caught.
A simple `raise` is enough. Without an argument, the last caught exception is re-raised by default. It’s thus equivalent to `raise exc`.
Card IDs:
* [CCT-867](https://issues.redhat.com/browse/CCT-867)

Simplify re-raise for non-legacy

---

insights/tests/client/connection/test_test_connection.py

Tests for the `_test_urls` method are named `test_test_urls_*`, but tests for `_legacy_test_urls` are named `test_legacy_urls_*`. The latter does not match the method name. Fixed for consistency, so it’s clear which method is tested.
Card IDs:
* [CCT-944](https://issues.redhat.com/browse/CCT-944)

Make test_urls test names consistent

---

insights/specs/datasources/httpd.py
insights/tests/datasources/test_httpd.py

lower cases of "Include"/"IncludeOptional" can also work. Current code ignores the case like "include <file path>". This PR can fix this issue

Fix: Enhance datasource httpd include upcase

---

insights/tests/core/test_filters.py
insights/tests/datasources/container/test_containers_inspect.py
insights/tests/datasources/test_awx_manage.py
insights/tests/datasources/test_cloud_init.py
insights/tests/datasources/test_dir_list.py
insights/tests/datasources/test_kernel_module_list.py
insights/tests/datasources/test_ls.py
insights/tests/datasources/test_lsattr.py
insights/tests/datasources/test_machine_ids.py
insights/tests/datasources/test_package_provides.py
insights/tests/datasources/test_rpm_pkgs.py
insights/tests/datasources/test_semanage.py
insights/tests/datasources/test_user_group.py
insights/tests/parsers/test_dse_ldif_simple.py
insights/tests/parsers/test_ls_usr_bin.py
insights/tests/parsers/test_ls_usr_sbin.py
insights/tests/parsers/test_messages.py
insights/tests/parsers/test_rhsm_log.py
insights/tests/test_context_wrap.py
insights/tests/test_specs.py
insights/tests/test_specs_save_as.py

- add_filter() is a method that will affect global filters,
this PR resets the global FILTERS/CACHE for each test
that added filters
- fix the test issue of PR #4255

test: refine the tests used add_filter()

---

insights/client/crypto.py
insights/tests/client/test_crypto.py

* Card ID: CCT-967
While existing tests catch basic invalid playbook scenarios, this update aims to create more tests that cover specific verification failure points. Adding new unit tests helps "freeze" expected verification behavior, making it easier to detect unintended changes in the future. This PR is a modified version of [insights-ansible-playbook-verifier#24](https://github.com/RedHatInsights/insights-ansible-playbook-verifier/pull/24).

feat(client): Improve test coverage of crypto.py

---

insights/client/core_collector.py
insights/core/spec_cleaner.py
insights/tests/client/core_collector/test_run_collection.py
insights/tests/core/spec_cleaner/test_reports.py

- it causes circular import issue when triggering data collection
via 'insights-collect' command
- instead of importing the constants from insights.client,
this change sets the "rhsm_facts_file" to insights_config

fix: do not import 'insights.client.constants' in spec_cleaner

---

insights/combiners/httpd_conf.py
insights/tests/combiners/test_httpd_conf_tree.py

Options in httpd configuration files are not case sensitive. To avoid configuration files parsing missing, it is necessary to use `istartswith("Include")` instead of `startswith("Include")`.
Besides Options nginx configuration files are case sensitive, no need to update the nginx combiner.

fix: Update combiner httpd_conf include

---

insights/parsers/uname.py

- RHEL 9.5 - 5.14.0-503.11.1.el9_5
- https://access.redhat.com/articles/3078
- and commit the reformat done by black

chore: uname supports RHEL 9.5

---

insights/specs/datasources/ls.py
insights/tests/datasources/test_ls.py

- the 'fstab_mounted.dirs' was parsed/extracted in the `datasources.ls` already
should be removed from the args that passed to the `ls` command

fix: remove the 'fstab_mounted.dirs' from the final ls args

---

insights/parsers/azure_instance.py
insights/tests/parsers/test_azure_instance.py

See the following line in Errors report: 
| -------- | ------- | -------- | ------- |
|26780|insights.parsers.azure_instance.AzurePublicIpv4Addresses|xxx| ParseException('Unable to parse JSON')|
An example input of this `AzurePublicIpv4Addresses`: 
```
{ "error": "No load balancer metadata is found. Please check if your VM is using any non-basic SKU load balancer and retry later." }
```
To proper handle such content in parser `AzurePublicIpv4Addresses`.  
RHINENG-14573

fix: proper error handling of AzurePublicIpv4Addresses

---

.flake8
.pre-commit-config.yaml
insights/core/spec_factory.py

- the type of 'provider' is unicode in python2 env, use 'six.text_type' for compatibility
- add E203 to flake8.ignore as per 
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
- as it contains changes made by `black`, the major change of this pr is
https://github.com/RedHatInsights/insights-core/pull/4290/files#diff-139617115fa36c187b7abb769836928aff6051c743356cdf643582c0ba74f1daR1119-R1123

fix: add six.text_type to the check of command_with_args

---

insights/parsers/krb5.py
insights/tests/parsers/test_krb5.py

See the following line in Errors report: 
| -------- | ------- | -------- | ------- |
|33315| insights.parsers.krb5.Krb5Configuration|a9bd78cbb38e4c438e5f0e9c3b9eb57e| IndexError('list index out of range')|
An example input of this `Krb5Configuration`: 
```
[libdefaults]
permitted_enctypes =  
```
To proper handle such content in parser `Krb5Configuration`.  
RHINENG-14573

fix: handle empty value in krb5 config

---

insights/parsers/subscription_manager.py
insights/tests/parsers/test_subscription_manager.py

**Product Key Parsing:** Added support for parsing certain product key lines that start with "Red Hat Enterprise Linux for Virtual Datacenters", handling them as keys and capturing the following description lines as their values.
Here are couple of examples:
Test data sample 1:
```
+-------------------------------------------+
System Status Details
+-------------------------------------------+
Overall Status: Insufficient
Red Hat Enterprise Linux for Virtual Datacenters, Premium:
- Guest has not been reported on any host and is using a temporary unmapped guest subscription. For more information, please see https://access.redhat.com/solutions/XXXX
```
Test data sample 2:
```
+-------------------------------------------+
System Status Details …
```

feat: support more RHEL product key in subscription_manage_status

---

insights/client/config.py
insights/specs/__init__.py
insights/specs/datasources/compliance/__init__.py
insights/specs/datasources/compliance/compliance_ds.py
insights/specs/datasources/manifests.py
insights/specs/default.py
insights/tests/client/phase/test_collect_and_upload.py
insights/tests/datasources/compliance/test_compliance.py
insights/tests/datasources/compliance/test_compliance_ds.py

- This is a draft re-implementation of #4056 based on #4124

feat(compliance): RHINENG-8964 allow listing/assigning policies

---

insights/client/connection.py
insights/tests/client/connection/test_checkin.py

* Card ID: CCT-891
* Card ID: RHINENG-13984
The `insights-client --checkin` command currently succeeds on hosts that are not registered with `insights-client`, but are registered with `subscription-manager`. This fix addresses the issue to ensure the `--checkin` command properly fails as expected when the client is not registered.

fix(client): checkin for unregistered hosts should fail

---

insights/client/__init__.py
insights/client/connection.py
insights/client/phase/v1.py
insights/tests/client/connection/test_checkin.py

* Card ID: CCT-705
This patch will help us with identifying what is happening at given times.
- Include phase, version and arguments on each phase load. Some of the information may not be necessary, as newer builds of insights-client contain logs that carry the information about phase and version. However, older builds do not, and these bits are valuable when debugging.
- Disable logging of HTTP responses for collection rules and Inventory host. They are verbose and do not need to be logged in a file every time. The important parts of it are logged elsewhere.

chore: Improve and simplify logging

---

insights/specs/datasources/manifests.py

- it caused that compliance data was not collected

fix: add the missed compliance entry in compliance manifest

---

insights/client/__init__.py

- Mulitple eggs will be provided on CDN for different RHEL releases
- Decide the egg name before downloading according to the current RHEL major version
- The orignial "insights-core.egg" is set as default
- Jira Card: RHINENG-12166

feat: download egg as per the RHEL major version

---

insights/tests/datasources/compliance/test_compliance.py

- the timezone update in compliance tests breaks the
eap_reports tests which are time-sensitive
- in some test env, the eap_report test always fail as below:
```
FAILED insights/tests/datasources/test_eap_reports.py::test_eap_one_match_paths - AssertionError: assert 2 == 1
+  where 2 = len(['/var/tmp/insights-runtimes/uploads/file_a.json', '/var/tmp/insights-runtimes/uploads/file_b.json'])
FAILED insights/tests/datasources/test_eap_reports.py::test_eap_zero_match_paths - assert <function eap_report_files at 0x7fa4499e7420> not in <insights.core.dr.Broker object at 0x7fa44962e910>
```
- it's because that the two tests are time-sensitive, 
however the change of "TZ" in compliance test breaks
the timestamp of file creating in the eap_reports tests.

fix(test): failures of test_eap_reports in some test env

---

.github/workflows/main.yml

The harcoded RedHatInsights URL makes the Python 2.6 tests fail when a pull request is created in a fork. Using a dynamic URLs makes the GitHub Action to clone from the fork and use the code in the pull request.
github.repositoryUrl variable can’t be used, because cloning using  git:// protocol fails. HTTPS url is thus composed instead.
Card IDs:
* [RHINENG-14956](https://issues.redhat.com/browse/RHINENG-14956)

fix(ci): Use dynamic repo URL for python26-test

---

insights/core/__init__.py
insights/parsers/lspci.py
insights/tests/test_lazylogfileoutput.py

- Doesn't like the LogFileOutput, this LazyLogFileOutput doesn't load the
content during initialization.  Its content will be loaded later whenever
the parser instance being used.
- It's useful for the cases where need to load thousands of files that
belong to one single Spec in one pass of running.
- For implementation's convenience, converted the `"scanners"` from `list`
`dict` in which the `result_key` is key and `scanner` is value.  And
removed the `scanner_keys`.
- Updated the LsPci accordingly.
- see RHINENG-13810
- As some passive updates done by `black` pre-commit
were also committed in this PR, please majorly check this
[code slice](https://github.com/RedHatInsights/insights-core/pull/4309/files#diff-3f51854c15b54335dc91cd8acf82eff62d9aad50b6d3d413317f82f7b00 …

feat: add a base parser LazyLogFileOutput

---

insights/tests/client/test_crypto.py

This change fixes an occasional test failure due to a race condition with the gpg command. The tests in `test_crypto.py` were updated to include the `ignore_errors=True` parameter in `shutil.rmtree(home)`.

test(client): Fix unusual race condition in tests

---

.github/workflows/main.yml
insights/tests/client/connection/test_test_connection.py
insights/tests/client/init/test_write_pidfile.py
setup.py

Logger asserts are error-prone, because they assert calls, not actual messages. The `caplog` fixture is Pytest-native way to test logs. This makes integration-level unit tests easier to add.
For the `caplog` fixture to work on Python 2.6 (RHEL 6), `pytest_catchlog` needs to be installed. On more recent version of Python, the fixture is included in Pytest.
`pytest_catchlog` caused PID file write tests to fail. The fixture itself calls `os.getpid`, interfering with the patch. Every log message makes a `getpid` call that is recorded in the patch. `assert_not_called` patches then stopped working.
Fixed by removing the `os.getpid` patch. The original function is safe to use. `test_write_pidfile_not_called` verifies several calls among which `write_to_disk` is the …

feat: Use caplog to test log messages

---

docs/shared_parsers_catalog/ilab.rst
insights/parsers/ilab.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_ilab.py

Add this spec for a new Advisor rule

feat: Add spec and parser for ilab_model_list

---

insights/parsers/os_release.py
insights/tests/parsers/test_os_release.py

Add `is_rhel_ai` function to check if the system is from RHEL AI image

feat: Add is_rhel_ai into parser os_release

---

insights/parsers/fwupdagent.py
insights/specs/default.py
insights/specs/insights_archive.py
insights/tests/parsers/test_fwupdagent.py

RHINENG-15022 , rely on the merge of https://github.com/RedHatInsights/insights-core/pull/4317 
From [KCS#5436071](https://access.redhat.com/solutions/5436071), the command `fwupdmgr` supports since RHEL7.4. 
As we need to keep both command for spec `fw_security` for a while, use `first_of` instead of creating another spec for command  `fwupdmgr`.

feat: add new command fwupdmgr to spec.fw_security

---

insights/client/client.py
insights/tests/client/test_log_messages.py

- RHINENG-14959
- When any compliance apiv2 options is specified nothing will be collected, hence data collection relevant messages should not be printed to console. The rm_conf which includes the file/content redaction is also cleared for compliance apiv2 for this reason.

fix: do not print collection messages for compliance apiv2 options

---

insights/specs/default.py

- the option was specified as 'lanRl' by mistake
correct it to `lanRL`.

fix: typo options to the ls_lanRL spec

---

insights/core/filters.py
insights/core/spec_cleaner.py
insights/core/spec_factory.py
insights/tests/__init__.py
insights/tests/core/test_filters.py
insights/tests/datasources/container/test_containers_inspect.py
insights/tests/datasources/test_awx_manage.py
insights/tests/datasources/test_cloud_init.py
insights/tests/datasources/test_dir_list.py
insights/tests/datasources/test_kernel_module_list.py
insights/tests/datasources/test_ls.py
insights/tests/datasources/test_lsattr.py
insights/tests/datasources/test_machine_ids.py
insights/tests/datasources/test_package_provides.py
insights/tests/datasources/test_rpm_pkgs.py
insights/tests/datasources/test_semanage.py
insights/tests/datasources/test_user_group.py
insights/tests/parsers/test_messages.py
insights/tests/parsers/test_rhsm_log.py
insights/tests/specs/test_specs.py
insights/tests/specs/test_specs_filters.py
insights/tests/specs/test_specs_save_as.py
insights/tests/test_context_wrap.py
insights/tests/tools/test_apply_spec_filters.py

- Added a new keyword argument "max_match=MAX_MATCH" to `add_filter`.
By declaring the max_match, at most `max_match` number of lines that
contain the patterns will be filtered out in the collection.
For redundant declarations the maximum `max_match` will be kept as the
final scanning number.  If no `max_match` is declared when `add_filter`,
the filters.MAX_MATCH (=10000) will be take as the default value.
- Added a new keyword argument "with_matches=False" to the `get_filters`.
When "with_matches=True" is specified, the return value of the
`get_filters` will be dict in which the max scanning numbers for each
filter pattern are included as the dict value.
- update the exiting tests
- RHINENG-14669

feat: enhance add_filter to support the max matched lines 

---

insights/client/client.py

* Card ID: CCT-1008
With the introduction of IoP, the `insights-client` should display the correct URL for the respective environment. The client differentiates between Hosted, Stage Hosted, and IoP environments during registration.

fix(client): Display correct Insights URL

---

insights/specs/datasources/compliance/__init__.py
insights/tests/datasources/compliance/test_compliance.py

Jira: RHINENG-14834
- the assign/unassign api will return 404 when failed, which
means the specified `policy_id` doesn't exist.

fix: error msg for compliance apiv2 assign/unassign

---

insights/core/filters.py
insights/tests/core/test_filters.py

- Per the original design 'set()' should be supported by add_filter(). However, it was not supported in the code. Fixed it and added test.

fix: set should be supported by add_filter

---

insights/core/spec_factory.py

- this is to avoid the first keyword from starting with a dash ('-')
- see RHINENG-15287

fix: reverse the filters order when grep

---

insights/client/apps/ansible/playbook_verifier/serializer.py
insights/tests/client/apps/test_playbook_verifier.py

* Card ID: CCT-1065
Backslashes in regex patterns were not properly escaped, causing inconsistencies between Fedora 40 and CentOS Stream 9 environments. This commit ensures that all escape characters are properly serialized.
This pull request is a backport from [insights-ansible-playbook-verifier#27](https://github.com/RedHatInsights/insights-ansible-playbook-verifier/pull/27)

fix(client): Serialize properly escape characters

---

insights/client/apps/ansible/playbook_verifier/serializer.py
insights/tests/client/apps/test_playbook_verifier.py

* Card ID: CCT-1102
Empty values in playbooks were not serialized correctly. This commit resolves the issue by ensuring that empty values are not enclosed in quotes in the serialized output.
This pull request is a backport from [insights-ansible-playbook-verifier#30](https://github.com/RedHatInsights/insights-ansible-playbook-verifier/pull/30).

fix(client): Serialize properly playbooks with empty values

---

insights/client/apps/ansible/playbook_verifier/serializer.py
insights/tests/client/apps/test_playbook_verifier.py

* Card ID: CCT-1101
Empty maps in playbooks were not being correctly handled by the serializer. To maintain compatibility across various environments, they are now serialized as `ordereddict()`.
This pull request is a backport from [insights-ansible-playbook-verifier#29](https://github.com/RedHatInsights/insights-ansible-playbook-verifier/pull/29).

fix(client): Serialize properly playbooks with empty maps

---

insights/client/constants.py

Change was made in fle `insights/client/constants.py   [row 83]`
where the orginal file path `/tmp/insights-client.pidd` was changed
to `/tmp/run/insights-client.pidd`.
Motivation for the change was to place `insights-client.pid` file
to directory owned by `insights-client`.
CARD: CCT-375

Fix/cct-375: Change location of /tmp/insights-client.ppid

---

insights/core/spec_factory.py
insights/tests/specs/test_specs_filters.py

As some logs files are not with log rotate setting, these files contain old logging and more than 100 million lines. Use the 'tail' command to get the last 1 million only.

fix: 'tail' filterable text files before filtering with 'grep'

---

insights/parsers/ls.py
insights/tests/parsers/test_ls.py
insights/tests/parsers/test_ls_file_listing.py

The following error was raised from a @condition dependency usage: 
| -------- | ------- | -------- | ------- |
| 54299| insights.specs.Specs.ls_lanL|bc586c1df4aa4b6e8ac0456954d60487|AttributeError("'list' object has no attribute 'items'")|
Fix to restore the consistent of the return value type of `ls.listing_of()`.    
RHINENG-15244

fix: default return value type of ls.listing_of()

---

insights/client/phase/v1.py
insights/tests/client/phase/test_post_update.py

* Card ID: CCT-1059
Status code returned by `insights-client --status` should indicate whether a host is registered or not. This change ensures that the exit code is 0 if the host is registered and 1 if it is not.

fix(client): Status code should indicate registration status

---

insights/parsers/ls.py

- as the original specs are kept as they are, we don't need to collection them two times.

fix: remove /dev, /boot and /sys/firmware from ls_lanR

---

insights/specs/__init__.py

Re-adding 'ls_rsyslog_errorfile = RegistryPoint()' since it being missing causes an exception when loading parsers due to usage by 'LsRsyslogErrorfile' parser.
The removal of ls_rsyslog_errorfile = RegistryPoint() caused an exception when loading parser LsRsyslogErrorfile since it has a dependency on that spec

Bug: Re-adding 'ls_rsyslog_errorfile = RegistryPoint()' 

---

docs/shared_parsers_catalog/filefrag.rst
insights/parsers/filefrag.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_filefrag.py

Signed-off-by: xintli <xintli@redhat.com>
rh-pre-commit.version: 2.3.2
Add parser FilefragGrubenv to parse command filefrag /boot/grub2/grubenv
JIRA: RHINENG-14353

FEAT: Add new parser FilefragGrubenv

---

insights/client/__init__.py
insights/client/connection.py
insights/tests/client/connection/test_reg_check.py

* Card ID: CCT-721
* Card ID: RHINENG-11711
Currently, the client is using the `/hosts` endpoint to check if the host is registered. This change updates the client to use the `/host_exists` endpoint instead.

fix(client): Change registration endpoint to /host_exists

---

insights/client/connection.py
insights/client/support.py
insights/tests/client/support/test_collect_support_info.py
insights/tests/client/test_client.py

* Card ID: CCT-1122
Some commands, such as `--status`, could unintentionally unregister the system if the host was missing from Inventory, which led to the creation of a `.unregistered` file without user intent. This change ensures that unregistration only occurs when explicitly triggered via the `--unregister` command.

fix(client): Ensure unregistration is always explicit

---

insights/cleaner/__init__.py
insights/tests/cleaner/test_max_line_length.py

- for lines that are extra long, keep the first
1048576 characters. And the truncation will be
recorded in logs when occurring.
See RHINENG-16178

fix: truncate lines longer than 1MB

---

insights/specs/__init__.py
insights/specs/default.py

Add spec only for now, to serve RHINENG-16372
This new spec can also cover the collection of existing specs:    
- `Sepc.nvidia_smi_l`
- `Spec.nvidia_smi_active_clocks_event_reasons` 
A typical output of this command looks like:
```
$ /usr/bin/nvidia-smi --query-gpu=index,name,uuid,memory.total,clocks_event_reasons.active --format=csv,noheader
0, NVIDIA L4, GPU-24598a07-f97d-fc79-86de-485c4c82d01c, 23034 MiB, 0x0000000000000001
```

feat: add spec nvidia_smi_query_gpu

---

insights/client/cert_auth.py

Some tests may fail when the attribute is missing. We should always be able to test whether an identity certificate exists or not.

fix(client): Always set rhsmCertificate.PATH attribute

---

insights/specs/datasources/compliance/__init__.py
insights/tests/datasources/compliance/test_compliance.py

**How to test:**
1. Do `insights-client --register` on your machine
2. Install `yum install scap-security-guide -y`
3. Go to https://console.redhat.com/insights/compliance/scappolicies and Create policy and on Systems step associate your system that you registered, no need to change anything else while creating policy
4. Go back to VM and run `insights-client --compliance`
5. After a minute or less, observe that your system has been reported here https://console.redhat.com/insights/compliance/reports
Compliance recently started failing when we are running `insights-client --compliance` on missing inventory ID.
Issue:
```
2025-03-10 11:57:12,315  NETWORK insights.client.connection:188 GET https://cert-api.access.redhat.com/r/insights/platform/inventory/v1/host_exists?insights_id=c097a73b-7a …
```

Fix Compliance inventory data parsing

---

insights/core/ls_parser.py
insights/parsers/ls.py
insights/parsers/lsinitrd.py
insights/tests/parsers/test_ls_boot.py
insights/tests/parsers/test_ls_dev.py
insights/tests/parsers/test_ls_file_listing.py
insights/tests/parsers/test_ls_sys_firmware.py

- it's mem/size consuming to story the 'raw_entry' for each line
- add a raw_entry_of() method to return the rough raw line instead
- mark the "raw_entry" as deprecated in comment

fix: replace 'raw_entry' key with raw_entry_of method

---

insights/parsers/lvm.py
insights/tests/parsers/test_lvm.py

The former added warning keywords filtering breaks one of the testcase
in extraction-rules repo, eg. "duplicate" is a keyword from the lvm
report json, and should not be filtered out as warning messages.
~~Drop the whole find_warnings() keywords in LvmFullReport, to avoid
any hidden over-matching, instead, filter only on the known "WARNING:"
lines in the middle of the json. And copyied that testcase data here.~~
Consider all the keywords in find_warnings() are not just single word,
except this "duplicate".  Fix by changing the keyword to " duplicate ".
This also brings the consistency on warning messages handling
among the lvm commands.
The former LvmFullReport change: https://github.com/RedHatInsights/insights-core/pull/4386

fix: warnings keywords over-matching in LvmFullReport

---

insights/specs/default.py

Observed on the spec collection results, the command can be collected for most cases. But there is still a case that the command collection failed with message: "Field \"clocks_event_reasons.active\" is not a valid field to query".
To make sure the basic gpu info be collected, drop this option `clocks_event_reasons` in this spec command.
to serve RHINENG-16372

fix: drop issue option of Specs.nvidia_smi_query_gpu

---

insights/specs/datasources/files_dirs_number_of.py

Move the datasource `files_dirs_number` file path from `./data`  to `./data/insights_commands` 
A current data collection example:  
~~~
Downloads/insights-***-20250317xxxxxx $ ll data                           
...                                                                              
-rw-r--r--@   1 joy  staff   xxxB Mar 17 xx:xx files_dirs_number
drwxr-xr-x@ 164 joy  staff   xxxK Mar 17 xx:xx insights_commands
...
~~~

fix: path of datasource files_dirs_number

---

insights/parsers/files_dirs_number_of_dirs.py
insights/tests/parsers/test_files_dirs_number_of_dirs.py

- exception will break the rules execution and is useless for engine

fix: no exception for FilesDirsNumberOfDir

---

insights/specs/datasources/compliance/__init__.py
insights/tests/datasources/compliance/test_compliance.py

Currently default compliance limit is `10`. There are sometimes more than 10 policies so customers need to see all of them. At the same time, number of policies is reasonable and not going to be more than 100 for sure. So instead of having batch requests here, setting limit to `100` will be enough.

fix(RHINENG-15343): Limit compliance policies to 100

---

insights/client/connection.py
insights/client/phase/v1.py
insights/tests/client/phase/test_post_update.py

* Card ID: CCT-870
The unregistration command now updates local files (.registered, .unregistered, machine-id) without calling the DELETE /hosts/UUID API endpoint and removing the host from Inventory. This reduces unnecessary load on the Inventory service.

feat(client): --unregister should not delete inventory host

---

insights/combiners/grub_conf.py
insights/tests/combiners/test_grub_conf.py
insights/tests/combiners/test_selinux.py
insights/tests/core/test_get_dependency_specs.py

The 'ls_sys_firmware' is not suggested to collect in core collection, use the 'ls_lan_filtered' as another alternative input for combiners that depends on 'ls_sys_firmware'.

fix: ls_lan_filters as another input for uefi_boot checking

---

insights/tests/__init__.py

- add them to the test exclude list, so in corresponding test of rule, it's not necessary to add filters to ls_lan_filtered spec when using the combiner

fix(test): no filter required for ls_lan_filtered when using GrubConf&SELinux combiner

---

insights/parsers/ls_boot.py
insights/parsers/ls_dev.py
insights/parsers/ls_sys_firmware.py
insights/specs/default.py

- In some edge cases, the 3 specs are extremely large, results in engine's OOM the "ls_lan_filtered" is an alternative. Hence, we stop collecting them and change to use the "ls_lan_filtered" instead.
- In this PR only ls_boot and ls_sys_firmware is removed from collection.
For "ls_dev", more things should be done before removing it.
- See RHINENG-16906

chore: stop collecting ls_boot/ls_sys_firmware

---

insights/parsers/dnf_module.py
insights/tests/parsers/test_dnf_module.py

serve RHINENG-16933 , a multiple sections command output was found by QE during testing, the content be like: `DNF_MODULE_LIST_MULTI_SECTIONS`  
Enhance the parser `DnfModuleList` to better handle the duplicate stream entries

fix: duplicate stream entries in parser DnfModuleList

---

insights/collect.py
insights/specs/default.py

- `ilab` command needs the pre-initialized configuration file which can be located as per the "HOME" env by default
- fix below issue when collection `ilab` specs
```mkdir: cannot create directory '/.cache'```

fix(spec): inherit HOME env when collecting ilab commands

---

setup.cfg

when setting up some venv, it's reported 'license_file' is deprecated

fix(setup): change to license_files

---

insights/specs/datasources/compliance/__init__.py
insights/tests/datasources/compliance/test_compliance.py

This PR adds unit tests for the download_tailoring_file method in ComplianceClient and fixes an issue where an empty tailoring file was being created even when download conditions were not met. 
A fix for [card](https://issues.redhat.com/browse/RHINENG-17562)

fix: Ensure tailoring file is not created when content is empty

---

insights/components/rhel_version.py
insights/specs/default.py
insights/tests/components/test_rhel_version.py

`syspurpose` is a RHEL 8.4+ feature in `subscription-manager` command, add dependency for this spec
RHINENG-17549

fix: rhsm syspurpose sepc deps on IsGtOrRhel84

---

insights/combiners/cloud_instance.py
insights/tests/combiners/test_cloud_instance.py

RHINENG-17169 , fix for: 
| count| component| exception|
|------|---------------------|--------------------------------------------------|
|  7545|     insights.combiners.cloud_instance.CloudInstance|        AttributeError("'CloudInstance' object has no attribute 'type'")|

fix: no attribute 'type' error in CloudInstance combiner

---

insights/core/spec_factory.py
insights/tests/core/spec_factory/test_file_provider.py

The repr string effectively includes `repr(self.path)` (note `%r`) because `self.path` can be `str` or `bytest`. Since `repr()` adds quotation marks to `str` and `bytes` values, using `"%r"` adds extra quotation marks.
Original:
```
DummyFileProvider("'/some/path/sample_file.txt'")
```
Fixed:
```
DummyFileProvider('/some/path/sample_file.txt')
```
See above.

fix: remove extra quotation marks in FileProvider.__repr__

---

insights/core/__init__.py

The class was added based on the requirements of a downstream project. It didn't meet the requirements of the project; the project uses their own limited implementation now (no scans supported).
Specifically, LazyLogFileOutput is not a drop-in replacement for LogFileOutput. It requires each and every rule to call LazyLogFileOutput.do_scan() before using scans. This is error-prone; if a rule forgets to do it, everything might work until the rule is executed alone or until it is the first one executed.
LazyLogFileOutput should be deprecated and removed until we can invest the effor into developing an implementation that will work as a full drop-in replacement for LogFileOutput. We do not want downstream project to become dependent on the current implementation.
See …

chore: deprecate LazyLogFileOutput

---

insights/combiners/cloud_provider.py
insights/tests/__init__.py
insights/tests/combiners/test_cloud_instance.py
insights/tests/combiners/test_cloud_provider.py
insights/tests/components/test_cloud_provider.py

- add 'cloud init query' and 'subman facts' as optional candidates,
Check the 'subman facts' first to identify the CP more accurately.
Check the 'cloud init query' result the last.
- do not check RPM for Azure, as the 'walinuxagent' package can be
installed on other cloud instance
- refine the "_select_provider" method to use the checking results
- Jira: RHINENG-13705

fix: add more candidates to CloudProvider combiner

---

insights/client/__init__.py
insights/client/connection.py
insights/client/phase/v1.py
insights/tests/client/phase/test_LEGACY_post_update.py
insights/tests/client/phase/test_post_update.py

* Card ID: CCT-265
This patch updates the logging messages shown to the user when the host is not registered with subscription-manager or when the host is not registered with insights-client.

fix(client): Update log messages when unregistered

---

insights/parsers/config_file_perms.py

- and will remove them in 3.7.0 RHINENG-16177

chore: deprecate *ConfigPerms parsers

---

insights/tests/core/spec_factory/test_listdir.py
insights/tests/core/spec_factory/test_listglob.py

- Fix fixture scopes to be actually "module". The `scope` argument was passed to the test function instead of the `fixture` decorator by mistake.
- Use the standard tmpdir_factory fixture to create temporary directories. The advantages of the standard fixture is that it has customizable retention policy [1]:
- Our tests do not have to include cleanup code
- Test data remain available after test run for troubleshooting
- Pytest cleans up old test data eventually
[1] https://docs.pytest.org/en/latest/how-to/tmp_path.html#temporary-directory-location-and-retention
* [] Is this PR to correct an issue?
See above.

chore: improve listdir and listglob tests

---

insights/tests/core/spec_factory/test_content_provider_load.py

Addressed:
- Create the large file just once
- Test that load() skips the beginning of large files
- Test that filters are applied
- Use the standard `tmpdir_factory` fixture to maintain temporary
directories (with automatic cleanup and retention for successful and
failed tests alike)
Unaddressed:
- This is a test for a low-level provider class. It SHOULD NOT require
the setup of specs and `RegistryPoint`s. If it does, there is something
wrong about separation of responsibilities. The code is too convoluted
for me to tell for sure and address this within the time I could spend
on this change.
- The tests do not check that there is an additional filter on the
number of lines per filter term. This is INTENTIONAL. I would like to
see performance data before committing …

Improve load tests

---

insights/core/archives.py

- RHINENG-18485
Using insights-run in non-privileged systems raise an `insights.core.exceptions.CalledProcessError` exception, complaining about not being able to create device files.
Example:
`sosreport-.../dev/dm-7: Can't create 'sosreport-.../dev/dm-7'`
This change modifies the `tar` command used in `insights.core.archive` to skip extraction of all device files.

fix: Skip extraction of all device files in archive (#4468)

---

insights/specs/sos_archive.py

The **DnfModuleList** parser is well-implemented for handling the content of the sosreport file.
Initially, the file path for the insights archive was specified only in` /insights/specs/insights_archive.py `and `/insights/specs/default.py`
To extend support for the sos archives, the corresponding file path is added to `/insights/specs/sos_archive.py.`

add dnf_module_list spec file path for sos_archive

---

pyproject.toml

- '.md' and '.rst' cannot be used the same time in pypi

fix(setup): remove CONTRIBUTING.md from dynamic readme in pyproject.toml

---

insights/parsers/ls.py
insights/tests/parsers/test_ls_file_listing.py

- in some abnormal cases, the link info (->) is missing in the ls -l output, update the raw_entry_of to output the raw lines and ignore exceptions
- RHINENG-18729

fix: output abnormal raw line of ls entries

---

docs/shared_parsers_catalog/lru_gen_enabled.rst
insights/parsers/lru_gen_enabled.py
insights/specs/__init__.py
insights/specs/default.py
insights/tests/parsers/test_lru_gen_enabled.py

Signed-off-by: Ping Qin <piqin@redhat.com>
rh-pre-commit.version: 2.3.2
Add a new parser to parse the content of `/sys/kernel/mm/lru_gen/enabled` file.
It's required by a new advisor rule described in RHINENG-18456.

feat: Add a new parser LruGenEnabled

---

insights/specs/datasources/corosync.py
insights/tests/datasources/test_corosync.py

- it originally depends/uses IsRhel6/7 too.  Since IsRhel* depends on RedHatRelease too, remove the IsRhel* to make it a bit simple.
- See the original [comment](https://github.com/RedHatInsights/insights-core/pull/4483#discussion_r2162890119)

chore: update corosync datasource to use RedHatRelease only

---

insights/parsers/mount.py
insights/tests/parsers/test_mount.py

When the file path contains multiple slashes like "//MARIADB/tmp", the current "get_dir" will get in endless state as "os.path.split(path)[0]" always gets "//". This PR can fix this issue

fix: endless loop caused by Mount.get_dir()

---

insights/specs/datasources/ls.py
insights/specs/manifests.py
insights/tests/datasources/test_ls.py

- without these optional deps, the `ls` datasources may fail to collect

fix: add missed optional deps for ls datasources

---

insights/client/connection.py
insights/tests/client/connection/test_advisor_report.py

* Card ID: CCT-1286
- When calling --check-results and the client is not registered to the
system, insights-client will no longer call Inventory API
(/api/inventory/v1/hosts?insights_id=<machine-id>)

--check-results should call Inventory API only when the host is registered

---

insights/parsers/subscription_manager.py
insights/tests/parsers/test_subscription_manager.py

- The 'subscription-manager identity' command may return in multiple languages when system runs in non-English locale.
- Update the 'SubscriptionManagerID.identity' property to support this
- Jira: RHINENG-16383

fix: subman.identity supports multiple languages

---

insights/cleaner/__init__.py
insights/tests/cleaner/test_reports.py

fix: use tempfile.gettempdir as default tmpdir for obfuscation reports

---

insights/specs/datasources/compliance/__init__.py
insights/tests/datasources/compliance/test_compliance.py

- Make ComplianceClient can be used for general collection in which "legacy_upload=True" would be set.
- The "ComplianceClient.config" is redundant for connection, remove it and use the ComplianceClient.conn.base_url instead
- Split "download_tailoring_file" into fetch_tailoring_content and download_tailoring_file
- Resloves: RHINENG-19480

feat: ComplianceClient support general data collection

---

.github/workflows/main.yml
insights/parsers/installed_rpms.py
insights/tests/parsers/test_installed_rpms.py
insights/util/rpm_vercmp.py
pyproject.toml
setup.py

- follow up of #4490 (RHINENG-6913)
use rpm.labelCompare for comparing RPM versions when the
`rpm` module is available.
- deprecate the unused pad_version
- add rpm to runtime dependencies

chore(rpmcmp): use rpm.labelCompare first

---

insights/parsers/foreman_log.py
insights/specs/__init__.py
insights/specs/sos_archive.py
insights/tests/parsers/test_foreman_log.py

Add support for parsing the `/var/log/foreman-installer/foreman.log` configuration by registering a new spec, providing a ForemanLog parser, and including corresponding test.
New Features:
Introduce a **foreman_log** filterable registry point for `/var/log/foreman-installer/foreman.log` in the specs
Implement ForemanLog parser to the logs for the corresponding file.
Enhancements:
Register the new "foreman_log" spec in the default spec set
Documentation:
Tests:
Add unit tests for the ForemanLog parser
```
py.test -sv /Users/atewari/Desktop/tier3-rules/insights-core/insights/tests/parsers/test_foreman_log.py                                                                   ok  virtual_env py 
============================================================================== …
```

feat: New spec and parser for '/var/log/foreman-installer/foreman.log'

---

insights/tests/__init__.py
insights/tests/test_yaml_parser.py

- Fix the regression of (RHINENG-17357, #4466). The issue was introduced again in #4508.
Using @patch in archive_provider instead of impacting all tests.
- Corresponding test cases should be developed and added in the compatibility test suite.
- Jira: RHINENG-20647
(cherry picked from commit e3fa9410be9b221f87bb45fcc384413ca0213ef0)
This is a backport of #4557

fix(test): regression issue of yaml.SafeLoader in rule testing
