- docs/shared_parsers_catalog/pulp_worker_defaults.rst
- insights/config/specs.py
- insights/parsers/pulp_worker_defaults.py
- insights/parsers/tests/test_pulp_worker_defaults.py
A simple parser to read the `/etc/default/pulp_workers` file using the `SysconfigOptions` parser class.
> Pulp worker defaults 1.x

- docs/shared_parsers_catalog/pulp_worker_defaults.rst
- insights/parsers/pulp_worker_defaults.py
- insights/parsers/tests/test_pulp_worker_defaults.py
- insights/specs/__init__.py
- insights/specs/default.py
A simple parser to read the `/etc/default/pulp_workers` file using the `SysconfigOptions` parser class.
This is the master branch version of #950
> Pulp worker defaults for master branch

- docs/shared_parsers_catalog/subscription_manager_list.rst
- insights/config/specs.py
- insights/parsers/subscription_manager_list.py
- insights/parsers/tests/test_subscription_manager_list.py
This module provides a base class for parsing the output of ``subscription-manager list``, with a variety of tools to make it useful.
Documentation and complete testing is provided.
> Subscription-manager list parser for 1.x branch

- insights/parsers/nginx_conf.py
- For empty list `[]`, the depth is 0
> Add check for empty list in _depth in nginx_conf

- docs/shared_combiners_catalog/nfs_exports.rst
- insights/combiners/nfs_exports.py
- insights/combiners/tests/test_nfs_exports.py
- insights/parsers/nfs_exports.py
- insights/parsers/tests/test_nfs_exports.py
The NFS exports parser did not obey the semantics of duplicate exports, which is that a path can be listed multiple times but each host definition must be unique to a path.  Duplicate host definitions for a given path are ignored by `exportfs` after the first definition.  The NFS exports parser has been updated to obey these semantics.
This pull request also introduces an NFS exports combiner which reads all the NFS export parser objects and provides a unified interface to view all the paths exported in NFS on a system.
> NFS exports combiner and parser improvements

- .gitignore
* docs/components.rst is autogenerated during doc build and it should
not be added to any commits.
> Add auto generated file to gitignore

- insights/core/evaluators.py
This is to support image (i.e. non-host) archives
> Make hostname optional on SingleEvaluator

- insights/parsers/hostname.py
- insights/parsers/tests/test_hostname.py
- insights/tests/__init__.py
sos_commands/general/hostname sometimes contains the hostname with a newline at the end, which results in a file with two lines. The hostname parser specifically checks for one line but doesn't gracefully handle the problem.
I changed it to filter blank lines before parsing.
Also updated context_wrap with an optional parameter to skip whitespace stripping of content before splitting into lines. The strip was hiding this problem in unit tests.
> Ease hostname restrictions by filtering blank lines. Fix #1055.

- insights/combiners/tests/test_hostname.py
- insights/parsers/hostname.py
- insights/parsers/tests/test_hostname.py
Change the `Hostname` parser to raise a `ParseException` if its content has more than one non-empty line. It previously just defaulted its attributes to `None` and fell through. #1113
> Hostname parser raises ParseException on invalid data

- docs/shared_parsers_catalog/samba.rst
- insights/parsers/samba.py
- insights/parsers/tests/test_samba.py
Documenting the SambaConfig class, reformatting a few comments to fit in 80 characters, and implementing tests of the documented examples.
> Samba config documentation

- insights/parsers/fstab.py
- insights/parsers/installed_rpms.py
- insights/parsers/ipaupgrade_log.py
- insights/parsers/jboss_domain_log.py
- insights/parsers/libkeyutils.py
- insights/parsers/nginx_conf.py
- insights/parsers/ntp_sources.py
- insights/parsers/smbstatus.py
- insights/parsers/tomcat_xml.py
Just a few minor fixes to parser documentation headings
* FStab - put class in heading name, remove old shared dictionary
* Installed RPMS - put class in heading name, remove old shared dictionary
* IPA upgrade log - standardise to `parser - file path` format.
* Jboss domain log - standardise to `parser - file path` format.
* Libkeyutils - add contained parsers in subheadings
* NginxConf - add file to heading
* NTP sources - add contained parsers in subheadings
* Samba status - add contained parsers in subheadings
* Tomcat XML files - add contained parsers in subheadings
> Parser doc heading fixes

- insights/parsers/kdump.py
- insights/parsers/tests/test_kdump.py
Fix the wrong logic of 'using_local_disk' property.
Add two more properties to KDumpConf.
Adjust the test-cases.
> Enhance parser KDumpConf

- insights/client/client.py
I introduced a small bug when I removed much of the old code. We need to run `get_targets` once and check its length before accessing an index, otherwise the process will fail with a traceback when an image scan is attempted when Docker is missing or unreachable. 
Future enhancements should refactor the `get_targets` functions so this check is unnecessary. The empty array returned by the default function is a holdover from the old multi-target/uber-archive schema and is no longer needed.
> fail more gracefully on unreachable Docker

- insights/client/data_collector.py
This expects specs in uploader.json to be marked with an `"image": true` key/value pair.
> Explicitly mark commands for inclusion for image analysis

- insights/parsers/httpd_M.py
* Examples had a list results that is generated by
iterating over a dictionary so the list can be
in a different order
* Eliminated this issue in the example by replacing
the statement with equivalent statements
* If order matters then the parser needs to be fixed
> Fix examples in httpd_M parser

- insights/specs/sos_archive.py
Following parser entries are updated:
`candlepin_log`
`foreman_production_log`
`foreman_proxy_conf`
`foreman_proxy_log`
`foreman_satellite_log`
`qpid_stat_q`
`qpid_stat_u`
> Add parser entry to sos_archieve.py

- insights/parsers/fstab.py
- insights/parsers/tests/test_fstab.py
Resolve issue#1126.
Tested with archive provided files in insights-cli.
Without the escape decode of fs_file, tests for fsspec_of_path with
space in path will fail.
> Enhance parser for fstab to handle space in fs_file column

- insights/tests/test_specs.py
- insights/tests/test_subproc.py
- insights/util/subproc.py
Fix for #1181 
Command datasources were returning bytes by default instead of unicode, which causes string comparison failures in parsers in python 3. I added a "output_encoding" keyword to `insights.util.subproc.call` that defaults to UTF-8. Pass it `None` to get raw bytes.
> Add output_encoding keyword to subproc.call defaulting to 'utf-8'

- insights/parsers/tests/test_yum_repolist.py
- insights/parsers/yum.py
Often we need a list of repo-ids and not entire repo dictionary to
check if a repo is available in customer's environment. This patch
provides that property.
> [yum] Added new property to retrive RHEL repo names

- insights/tests/__init__.py
- insights/tests/test_add_component.py
Some people are writing components that call out to services. This will let them mock those services to test their components without external dependencies.
> Allow adding arbitrary components to InputData to mock dependencies.

- insights/core/spec_factory.py
- insights/specs/default.py
- insights/tools/specs_to_rules.py
Took the Insights Core 1.x version of specs_to_rules (insights-core/insights/tools/specs_to_rules.py) and refactored to work with Insights Core 3.x
> Update specs to rules script to work with version 3 of core

- cluster_rules/bash_version.py
- cluster_rules/ntp_compare.py
- insights/__init__.py
- insights/core/archives.py
- insights/core/cluster.py
- insights/core/context.py
- insights/core/hydration.py
- insights/core/plugins.py
- insights/util/fs.py
- sample_script.py
- stand_alone.py
Support analysis of clusters.
First extract "cluster facts" from individual hosts using our standard data model.
Then cluster rules use those facts from all the environments for further analysis.
```python
#!/usr/bin/env python
from insights import run
from insights.parsers.installed_rpms import InstalledRpms
from insights.core.plugins import cluster_fact, cluster_rule
@cluster_fact(InstalledRpms)
def get_bash(rpms):
rpm = rpms.get_max("bash")
return {"name": rpm.name, version=rpm.nvr}
@cluster_rule(get_bash)
def report(bash):
print(bash)
if __name__ == "__main__":
from insights import run
run(report, print_summary=True)
```
Run the script against a directory of archives or an uber archive:
`./bash_version.py archives/` for the rule to receive a list of dictionaries.
`./bash_version.py …
> [WIP] Cluster support

- insights/client/config.py
- insights/client/constants.py
We were referencing `constants.default_log_file` in `auto_config.py` but it didn't actually exist. So, create it.
> tweak constants

- insights/core/archives.py
This will enable for easy clean-up if some temp files get left behind after e.g. an insights process exits without being able to clean up.
Required by https://github.com/RedHatInsights/insights-core-frontends/pull/11
> Add prefix to temporary directories

- docs/notebooks/Config Tree Tutorial.ipynb
- insights/configtree/__init__.py
- insights/configtree/tests/test_dsl.py
- insights/core/__init__.py
Allow configuration filtering by sections (might have child nodes) or directives (no child nodes). For example, if you want all the sections that have names starting with "Dir" anywhere in the config:
```python
conf.find_all(startswith("Dir")).sections
```
> Allow filtering by node type

- insights/client/collection_rules.py
- insights/client/data_collector.py
- insights/client/insights_spec.py
- insights/client/utilities.py
- `shlex.split()` in python 3 barfs if you give it unicode
- `hashlib.sha1()` in python 3 expects bytes
- Need to explicitly write bytes to file instead of str
> few tweaks for py3

- insights/__init__.py
- setup.py
The `insights-run` command was broken and whatever it used to run in core is no longer present.  This change re-enables the insights-run command to do the same as `python -m insights`.
> Fix insights-run to run insights cmd line

- setup.py
- See https://github.com/yaml/pyyaml/issues/152
https://github.com/yaml/pyyaml/issues/152#issuecomment-402791014
> Update pyyaml to 3.13 to fix 'pip3 install pyyaml' error

- insights/__init__.py
- insights/formats/__init__.py
- insights/formats/_json.py
- insights/formats/_yaml.py
- insights/formats/text.py
Implement output formats as loadable modules. Cleans up the run function and allows us to extend with more formats if needed. The next formatter probably would be one that prints rule results or errors as they execute.
Examples:
*  `python -m insights -f json`
*  `python -m insights -f yaml`
*  `python -m insights -f text` (the default)
> Implement console output formats as loadable modules.

- insights/configtree/__init__.py
- insights/parsers/systemd/config.py
`parse_systemd_ini` required some `ConfigParser` behavior that changed between python 2.6 and python 2.7. This PR entirely removes the function's dependency on `ConfigParser`.
> Fix #324 by removing parse_systemd_ini's dependency on py2.7 ConfigParser

- Jenkinsfile
- insights/client/client.py
- insights/tests/client/test_client.py
- setup.py
Status code 412 means that the machine is unregistered. Thus there is almost no point in retrying as this is not a temporary condition.
This is rather a “hotfix”, since the `--retry` parameter is ignored regardless of whether the `.unregistered` file is actually written. This is because the `InsightsConnection.handle_fail_rcs` actually does not treat a 412 without a valid API response body as a reason to unregister. I’d address this separately.
If the assumption that 412 should result in not retrying at all is correct, then this solves https://bugzilla.redhat.com/show_bug.cgi?id=1554794 and https://projects.engineering.redhat.com/browse/MAASPLAT-205. @kylape and @YakovLittle can confirm this.
Added some tests and along with that [mock](https://pypi.org/project/mock/) as a development …
> Do not retry if server returns 412 on upload

- insights/parsers/neutron_metadata_agent_conf.py
Updated existing parser for OSP Neutron metadata_agent.ini to add the "[" filter in the parser.
> Added filter '[' to enable filtering of metadata_agent.ini

- insights/parsers/systemd/unitfiles.py
- insights/parsers/tests/test_listunits.py
Some services (failed services) in `systemctl_list-units` contains special char like * and ● at front
of that service line. This handle such situation to parse contain properly.
Signed-off-by: Akshay Gaikwad <akgaikwa@redhat.com>
> Update unitfiles to Handle Special char

- insights/client/__init__.py
- insights/client/client.py
- insights/client/config.py
- insights/client/connection.py
- insights/client/constants.py
- insights/client/phase/v1.py
- insights/tests/client/test_client.py
- insights/tests/client/test_utilities.py
This began as simply fixing the dotfiles being erased on timeout and turned into so much more...
Ended up refactoring registration functions a bit. I modified some of the "vision" functions as some of them were either incompletely implemented or copied code from elsewhere that was being unused.
Also removed the connection singleton due to an issue where its config was stale; the config in the connection class was a different object than the one it was initialized with. Moved the connection persistence to the `InsightsClient` class instead. Used a decorator to mark any methods that need network functionality. Also added an `http_timeout` option.
Finally, tests! I wanted to make sure registration was still behaving as intended.
There's a lot of passing of connection along with config now, …
> Fix unregister on timeout

- insights/client/utilities.py
I previously made a fix to maintain the .registered and .unregistered files in both needed locations. Well, turns out it doesn't work so well if you delete the old directory: https://bugzilla.redhat.com/show_bug.cgi?id=1610497
This change makes it so that existence of the containing directory is checked before writing any files.
> check directory before writing a file (BZ1610497)

- insights/client/__init__.py
- insights/client/config.py
- insights/client/phase/v1.py
- insights/tests/client/test_client.py
The registration refactoring brought about some bugs we didn't catch til today, namely:
- still using `InsightsClient.get_connection()`
- `http_timeout` not being parsed to a float correctly
This commit fixes those, as well as removing the duplicate function `get_registration_information` in favor of `get_registration_status`, to keep name parity with the matching function in `client.py`.
> remove dupe method, fix func call, fix timeout parse

- insights/core/plugins.py
Bandaid for a telemetry plugin that returns all rpms as metadata.
> Remove size validation on make_metadata_key response

- insights/core/plugins.py
The `rule ComponentType` overrode `invoke` instead of `process`. Invoke is too late to catch exceptions raise by missing requirements, so skips wouldn't be generated. This fixes that.
> Rule component should override process instead of invoke. #1376

- insights/client/client.py
- insights/client/collection_rules.py
- insights/tests/client/collection_rules/helpers.py
- insights/tests/client/collection_rules/test_get_conf_file.py
- insights/tests/client/collection_rules/test_get_conf_stdin.py
- insights/tests/client/collection_rules/test_get_conf_update.py
- insights/tests/client/collection_rules/test_get_rm_conf.py
- insights/tests/client/test_collect.py
- insights/tests/client/test_update_rules.py
When fixing #1226, I found the `get_conf` method very bulky with too many conditionals.
Reduced its cognitive complexity by splitting the method into smaller ones. Used separate methods for different configuration sources: file, url (with fallback to file) and stdin for regular configuration, and one for the remove_file configuration.
`InsightsUploadConf` class interface changed, existing behavior should remain the same. It’s just syntax shuffling that should not have any impact on an actual execution. I don’t have much confidence in the test coverage though: even when I intentionally break the code, no additional test fails. Thus I’d like to ask for a thorough review of the execution paths of former `get_conf` method calls.
My goal was not to make the code polished and beautiful, only to …
> [wip] Refactor connection_rules.InsightsUploadConf.get_conf

- insights/core/evaluators.py
Needs to be set if we are checking/setting it conditionally elsewhere.
> Fix release initialization.

- insights/client/data_collector.py
Changing `/bin/hostname` to `/bin/hostname -f` broke the soscleaner obfuscation... so from now on to avoid the code being out of step let's auto-determine what the hostname path is from what's in uploader.json.
> get hostname archive path from uploader.json

- insights/core/archives.py
Running into this intermittent error during testing:
```
File "/opt/app-root/src/insights_core_frontends/amqp/worker.py", line 257, in kafkaWorker
with archives.extract(tmp_file.name) as ex:
File "/opt/rh/python27/root/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File "insights/core/archives.py", line 112, in extract
ctx = extractor.from_path(path, extract_dir=extract_dir, content_type=content_type)
File "insights/core/archives.py", line 74, in from_path
subproc.call(command, timeout=self.timeout)
File "insights/util/subproc.py", line 119, in call
raise CalledProcessError(rc, cmd, output)
CalledProcessError: (64, [['tar', 'None', '-x', '--exclude=*/dev/null', '-f', '/tmp/tmp634Gz8', '-C', '/tmp/insights-GsWPxx']], …
```
> Fix tar content type check

- insights/tests/client/test_utilities.py
`write_(un)registered_file()` will delete the opposite dotfile but these weren't mocked out in testing. mock em out
> complete patching of dotfiles

- docs/shared_parsers_catalog/amq.rst
- insights/parsers/amq_broker.py
- insights/parsers/tests/test_amq_broker.py
- insights/specs/__init__.py
- insights/specs/default.py
Adds specs and an XML parser for the amq broker.xml configuration.
The specs look for the _conventional_ location of the configuration file.  In practice this may not happen very often as customers can place these files wherever suits them.
> Amq broker.xml parser

- insights/parsers/ovirt_engine_log.py
- insights/parsers/tests/test_ovirt_engine_log.py
Using datetime will make it simple to use the timestamp in the rule when using `.get_after()`
> [ovirt_engine_log] Use datetime object for timestamp

- insights/client/auto_config.py
- insights/tests/client/auto_config/test_try_satellite5_configuration.py
A [_set_auto_configuration_](https://github.com/RedHatInsights/insights-core/blob/5979ee1438cb75b46614c57c165c36daf269b753/insights/client/auto_config.py#L53) function call was [missing](https://github.com/RedHatInsights/insights-core/compare/master...Glutexo:fix_satellite5_autoconfig?expand=1#diff-2ff859dc8d708efc4e54514c0a483be0L196) a _config_ argument. That caused a runtime error if auto configuration [falls back](https://github.com/RedHatInsights/insights-core/blob/5979ee1438cb75b46614c57c165c36daf269b753/insights/client/auto_config.py#L212) to Satellite 5.
The test is not very nice – uses a lot of patching and virtually tests many things that are out of its scope. That‘s because the method is very non-atomic, does a lot of stuff that is not well mockable and thus is only difficultly …
> Fix Satellite 5 auto configuration

- insights/core/archives.py
Hit this error during testing:
```
File "/opt/app-root/src/insights_core_frontends/amqp/worker.py", line 257, in kafkaWorker
with archives.extract(tmp_file.name) as ex:
File "/opt/rh/python27/root/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File "insights/core/archives.py", line 116, in extract
if extractor.created_tmp_dir:
AttributeError: 'TarExtractor' object has no attribute 'created_tmp_dir'
```
`created_tmp_dir` should be defined at `TarExtractor` instantiation.
> Init created_tmp_dir variable at instantiation

- insights/formats/text.py
* Exceptions are stored in broker as a defaultdict(list)
* This exception was showing up when testing with Python 3.5
```
File "/home/bfahr/work/support/venv35/lib/python3.5/site-packages/insights/core/dr.py", line 548, in fire_observers
o(component, self)
File "/home/bfahr/work/support/venv35/lib/python3.5/site-packages/insights/formats/text.py", line 72, in progress_bar
if broker.exceptions[c] > 1:
TypeError: unorderable types: list() > int()
```
> Fix exception count for cmd line runs

- setup.py
* A bug in earlier version of python < 2.7.9 have a bug that is exposed
in version 1.8.0 of sphinx
* Locking the version to 1.7.9 avoids the issue
> Lock sphinx version to 1.7.9 to avoid python bug

- insights/client/__init__.py
- insights/client/connection.py
- insights/tests/client/connection/test_branch_info.py
- insights/tests/client/connection/test_init_session.py
- insights/tests/client/init/test_fetch.py
- insights/tests/client/test_net_comm.py
- insights/tests/helpers.py
If the API servers are not reachable, the first thing that fails is the egg update. To reach there, several requests are made to set up the right configuration. Most of those have no timeout set though. That results to a long waits when connection blocked by a firewall.
This is the first step to solve the reported bug that client hangs too long when connection is blocked by a firewall. In the long run it would be better to transparently use the timeout from config for every request. Solution to the failure on update will come in a separate PR. @kylape suggested not crashing on this, more specifically not crashing at all if it doesn’t prevent the app flow.
The functional tests are currently testing only one possible configuration. Improvements to this will come in a separate PR.
> Limit time of requests issued before failure

- insights/client/client.py
this is a bandaid for now just to fix the bug being seen. going to spend sometime next week examining py2/3 file writes and string behavior so we have a unified solution
> encode lastupload results before writing

- insights/specs/default.py
The original output size is undefined. Could be one, two, tens, etc. The improvement ensures it returns just one line with file path. The optimization is to stop 'find' command and return just the first found matching file.
https://bugzilla.redhat.com/show_bug.cgi?id=1628498
> Fix woopsie spec to exit on 1st found matching file

- insights/tests/client/collection_rules/test_get_rm_conf.py
- insights/tests/client/test_collect.py
[_test_get_rm_conf.test_no_file_](https://github.com/RedHatInsights/insights-core/blob/ce519eca9785a56495a2cd50e84917ab3f4aa058/insights/tests/client/collection_rules/test_get_rm_conf.py#L44) did not work properly: it tested the default value of the remote_file constant instead of the [patched](https://github.com/RedHatInsights/insights-core/blob/ce519eca9785a56495a2cd50e84917ab3f4aa058/insights/tests/client/collection_rules/test_get_rm_conf.py#L7) one. Fixed this to be consistend with other tests.
[_test_collect.patch_isfile_](https://github.com/RedHatInsights/insights-core/blob/ce519eca9785a56495a2cd50e84917ab3f4aa058/insights/tests/client/test_collect.py#L114) was patching the _isfile_ method and the [_collection_remove_file_](https://github.com/RedHatInsights/insights-core/blob/ce519ec …
> Fix remove file usage in collection tests

- insights/client/__init__.py
- insights/client/connection.py
- insights/client/phase/v1.py
- insights/tests/client/test_displayname.py
Previously, by design, setting display name would immediately exit the client.
An unfortunate side effect of this is that, because the client treats all config (env, conf file, cmd line) identically, having display_name permanently set in the config file will always cause the client to exit.
This patch will check against the command line args to see whether display_name came from there or not. Then, it will only exit when setting display-name as a command line switch. Otherwise it will continue with collection and upload as normal.
In addition, the PUT to update display name is no longer made if the name is unchanged, and some messaging is improved.
> Fix setting display name

- insights/formats/text.py
* When a script executes insights.run directly and the -d option is used
then a exception will occur in _find_context when trying to determine
the context of a report function, when it assumes a class context.
* Adding a check for a class object fixes the error in
insights.formats.text._find_context
* duplicate by running `./sample_script.py -d`
> Fixes an error when script executes insights run

- Jenkinsfile
- setup.py
Both RHEL 7 stages run _flake8_ linting, but the RHEL 6 one doesn’t. Flake8 documentation [says](http://flake8.pycqa.org/en/latest/) that it is important to run it on the exact version of Python used. Added this test from Python 2.6 used by RHEL 6.
This PR intends to replace @eduardocerqueira’s #1342 and my former #1335.
~~The reason why `flake8` command failed was because a version from RPM was used even though we wanted the one [described](https://github.com/RedHatInsights/insights-core/pull/1452/files#diff-2eeaed663bd0d25b7e608891384b7298R67) in [_setup.py_](https://github.com/RedHatInsights/insights-core/pull/1452/files#diff-2eeaed663bd0d25b7e608891384b7298). Fixed by [calling](https://github.com/RedHatInsights/insights-core/pull/1452/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R25) …
> Add flake8 linting to RHEL6 

- insights/specs/sos_archive.py
This was a typo in recently merged parser, pcs_config.
> fixed typo for pcs_config first file in sos_archive.py

- insights/parsers/installed_rpms.py
- insights/parsers/tests/test_installed_rpms.py
- insights/specs/default.py
* Fixes issue #1431 
* Switch input for installed RPMs to be collected in JSON format which is already supported by the parser.
* Missing epoch is '(none)' so check for that
* Add test for epoch
> Add epoch to installed rpms and use json format

- insights/core/__init__.py
- insights/tests/test_file_listing.py
* Fixes issue #1492
* selinux arg was present in FileListing class but was not used anywhere in the class. Selinux info is parsed regardless of what value the arg was set to.
* Removed the arg and updated the doc and tests.
> Remove unused arg from FileListing class

- insights/parsers/md5check.py
- insights/parsers/tests/test_md5check.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- Fix md5chk_files spec. Don't check libfreeblpriv3.so, libsoftokn3.so and pem file as prelink has been deprecated on RHEL7
- Check extra timezone files
- Keep prelink_orig_md5 spec disabled as it needs extra work under current framework
> Split MD5CheckSum parser into prelink version and normal version

- insights/__init__.py
- insights/combiners/tests/test_nginx_conf.py
- insights/core/__init__.py
Allow include directives anywhere in a configtree. Fixes #1477.
> Allow include directives anywhere in the tree

- insights/parsers/installed_rpms.py
- insights/parsers/tests/test_installed_rpms.py
We use function ```set()``` for InstalledRpm objects. In Python 3 InstalledRpm objects are not hashable and set() thus fails with an Exception. This pull request makes InstalledRpm hashable in Python 3.
> fix hashability of class InstalledRpm with Python 3

- insights/__init__.py
- insights/core/plugins.py
- insights/formats/text.py
> Obey -m flag for rules. Use default formatter when no CONTENT available.

- insights/core/evaluators.py
- insights/tests/test_evaluators.py
All subclass instances of `insights.core.plugins.Response` returned from rules will automatically be added to their own sections in the `json` and `yaml` reports. Closes #1510 .
> Add Response subclass instances to json response

- insights/core/ls_parser.py
- insights/tests/test_ls_parser.py
Throw away blank lines in the middle of ls stanzas. Delay full parsing of ls stanzas until a rule actually asks for something in a directory, and then only parse the requested stanza if it hasn't already been parsed. 
Fixes #1527.
> Ignore newlines at the ends of filenames. Delay stanza parsing.

- insights/__init__.py
- insights/core/cluster.py
- setup.py
* Remove the `--pandas` command line option and arguments to related functions.
* Add a new `cluster` section to `setup.py` to require `pandas` and `ansible`.
* Add a `-i` option for inventory when analyzing clusters. The value is a path to an ansible inventory file like `/etc/ansible/hosts`
> All cluster rules use pandas. Ansible inventory files define cluster topology.

- insights/parsers/ps.py
- insights/parsers/tests/test_ps.py
This commit adds a method to the Ps Parser that returns the number
of occurencies of commands with a given string. This is very much needed
and useful when writing rules for OpenStack because we have some performance
considerations wehn using a large number of worker processes for services.
For example, the recommendation is to cap the woker count at
ming(processorcount/2, 12) to avoid issues with database conenctions etc, so
we need the parser to provide this data in order to write rules.
> Add method to get count of processes with given string

- insights/client/config.py
- insights/tests/client/test_config.py
Discovered an issue where ENV-specified http_timeout wasn't parsed as a float and caused exceptions where it was being used during requests. Made the parsing a little more robust.
> improve parsing for number config vars

- insights/core/blacklist.py
- insights/core/context.py
- insights/core/spec_factory.py
- insights/tests/test_subproc.py
- insights/util/streams.py
- insights/util/subproc.py
This is part of getting core3 ready for client collection.
* Extend the blacklist capability to patterns and keyword substitution the current client does. Regexes patterns against lines in a file are not yet supported.
* New functions are added to insights.core.blacklist for adding patterns and keywords. Requires grep and sed to be installed on the target machine.
* Update the subproc module to simplify use.
* Allow specs to pass a list of environment variables to inherit from the parent process. Useful for inheriting kubernetes, openshift, etc.
* Introduces a new context for new style archives, although the collection implementation isn't in yet.
> Allow blacklist of patterns and keyword substitution. Refactor subprocessing and spec helpers.

- docs/api_index.rst
- docs/embedded_content.rst
- insights/__init__.py
- insights/configtree/__init__.py
- insights/core/context.py
- insights/core/dr.py
- insights/core/filters.py
- insights/core/plugins.py
- insights/formats/__init__.py
- insights/plugins/always_fires.py
- insights/util/__init__.py
- sample_script.py
- stand_alone.py
`tags` is an additional keyword argument you can add to any decorator like `@rule(InstalledRpms, tags=["security", "apache"])`. This is to help with various use cases that might require grouping or filtering of rule results.
Documentation updates include significant pydoc enhancements in insights.core.dr and insights.core.plugins.
> Add tags to components and update pydoc.

- insights/combiners/httpd_V.py
- insights/combiners/httpd_conf.py
- insights/parsers/engine_log.py
- insights/parsers/ipcs_sem.py
- insights/parsers/nfs_exports.py
- insights/parsers/nginx_conf.py
- insights/parsers/systemd/config.py
- use `warning` instead of `note`
- move/add `warning` into class's docstring
- correct the reference link in the warning
> Enhance the deprecated description in documentation.

- insights/tools/query.py
Show source for each if available (packages, modules, classes, or functions)
* insights-info -s os
* insights-info -s insights.parsers.installed_rpms
* insights-info -s insights.parsers.installed_rpms.InstalledRpms
* insights-info -s myrules.shift.foo
* insights-info -s myrules.shift.foo.report
Show pydoc for each if available (packages, modules, classes, or functions)
* insights-info -d os
* insights-info -d insights.parsers.installed_rpms
* insights-info -d insights.parsers.installed_rpms.InstalledRpms
* insights-info -d myrules.shift.foo
* insights-info -d myrules.shift.foo.report
> insights-info can show source and pydoc for any object.

- Jenkinsfile
Python 2.6 requires an older version of `idna` module. Locking it to 2.7
> Fix bug with idna in Jenkinsfile

- insights/client/connection.py
- insights/combiners/tests/test_virt_what.py
- insights/combiners/virt_what.py
This PR address an issue where virt_what sometimes returns `ovirt` instead of `rhev` for it's virtualization
property.
The issue has been address in BZ 1631361 - https://bugzilla.redhat.com/show_bug.cgi?id=1631361 
Even though this issue has been corrected in a bug fix it seems as though it has not been consumed by
all users so we have implemented a remedy by adding a new column that will contain the correct virtualization value.
> Added amended_generic column to virt_what combiner

- insights/parsers/qemu_xml.py
- The getchildren() method is deprecated
- fix #1594
> Avoid to use `getchildren` method

- examples/collection/manifest.yaml
- insights/__init__.py
- insights/collect.py
- insights/combiners/hostname.py
- insights/combiners/redhat_release.py
- insights/core/dr.py
- insights/core/hydration.py
- insights/core/serde.py
- insights/core/spec_factory.py
- insights/specs/default.py
- insights/tests/test_query.py
- insights/tests/test_serde.py
- insights/tests/test_spec_serialization.py
- insights/util/subproc.py
- manifest.yaml
- setup.py
This PR supersedes #1455  .
It includes a collection module that produces an archive from datasources or other components that have serializers and deserializers defined for their output types. The module can be invoked with the collect function in python or by running `insights-collect` from the command line. The archive it produces is recognized and processed by the rest of the framework in the same way as other archives.
Both invocations take a manifest with collection parameters and descriptions of which components to enable and persist to the archive. See insights/collect.py or manifest.yaml for an example.
```
mkdir tmp
$ insights-collect -m manifest.yaml -o tmp/
tmp/insights-alonzo-20181212234409.tar.gz
```
> Core 3 collection with whitelisted components and serde types. No client integration.

- insights/client/__init__.py
- insights/client/connection.py
- insights/client/phase/v1.py
- insights/tests/client/phase/test_post_update.py
Also modify how 4xx requests are handled by system creation function. 4xx response objects from python-requests are treated as "falsy" so there was an incorrect check happening when a 409 "duplicate machine id" error came back from the API.
> Disable reg on platform

- insights/core/context.py
* Add a timeout value so that when performing host collection a command
waiting for a response will not lock up insights run
* This is only for collection in the host context and does not
impact collection from archives or via the client
> Add timeout for host context collection

- insights/parsers/mysqladmin.py
- To skip parse error caused by:
/bin/mysqladmin: No such file or directory
> Change the base of MysqladminVars to CommandParsers

- insights/parsers/redhat_release.py
- insights/parsers/tests/test_redhat_release.py
Fixes parsing error where addition release info comes after the minor version:
```
Red Hat Enterprise Linux release 7.5-0.14
```
The parser now correctly returns 7 and 5 for the major and minor numbers.
> Fix redhat_release parser minor version parsing. Fixes #1590

- insights/__init__.py
I often run `insights-run <package>` instead of `insights-run -p <package>`.
This results in an exception and traceback as insights tries to interpret the
package as a directory or archive to analyze.
This commit fixes #1486 by catching the exceptions and logging friendlier
messages.
> Catch exceptions for invalid archives and content types.

- docs/shared_parsers_catalog/dnf_modules.rst
- insights/parsers/dnf_modules.py
- insights/parsers/tests/test_dnf_modules.py
- insights/specs/__init__.py
- insights/specs/default.py
Newer versions of YUM (based on DNF) are storing
additional metadata related to modularity functionality
in the /etc/dnf/modules.d/ directory.
These files are needed in order to properly calculate
package updates.
Signed-off-by: Tomas Kasparek <tkasparek@redhat.com>
> Gather modularity related information

- insights/core/archives.py
- insights/core/hydration.py
Some archives have directories with permissions that make it impossible
to write to them. Without delaying the permission set on those directories,
any files they contain will fail to extract due to PermissionDenied.
Archives that have multiple directories in the root evaluated the common
prefix to be too high in the directory structure. This change looks for
marker files (sos_commands, insights_commands, etc.) and take the immediate
parent as the archive root.
> Delay setting permissions when untarring. Adjust how roots are found.

- insights/parsers/ceph_version.py
- insights/parsers/tests/test_ceph_version.py
1. Fix the confusion between 'release' and 'version' according to N-V-R convention (note - this WILL BREAK existing rules)
2. Add 'downstream_release' field, to distinguish between (for example) 3.1.0 and 3.1.1.
> Fix ceph version - add 'downstream_release' field

- docs/shared_parsers_catalog/ceph_insights.rst
- insights/core/__init__.py
- insights/parsers/ceph_insights.py
- insights/parsers/tests/test_ceph_insights.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
The current set of Ceph-related parsers are fed by various CLI-based data sources (e.g. `ceph version` or `ceph osd dump`). This creates a tight dependency between insights parsers and the output formats of  Ceph CLI commands. The second issue is that we may want to provide certain types of data to insights that aren't necessarily relevant for exposing through CLI commands.
The merged PR here https://github.com/ceph/ceph/pull/23497 introduces a single Ceph CLI command designed specifically as a single data source for insights (i.e. `/usr/bin/ceph insights`).
This PR introduces a parser for this new data source. This renders most of the other Ceph-related data sources redundant. However, those parsers are specs are left alone since I suspect they will need to remain in the tree for older …
> Add parser for 'ceph insights' command

- insights/parsers/ceph_version.py
- insights/parsers/tests/test_ceph_version.py
I noticed that in RHOSP 10 environment the output of command `ceph -v` is
ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367)
which is not listed in the `community_to_release_map` and hence cause one of the
playbook(insights-playbooks PR#1783) to fail locally during breakit. This change includes the ceph version as listed in latest RHOSP 10 Controller node.
> Add Ceph version from RHOSP 10 environment

- insights/parsers/lspci.py
- insights/parsers/tests/test_lspci.py
- insights/specs/sos_archive.py
- This includes
* Add lspci files from sosreport in the `sos_archive` specs.
* Modify lspci parser to make it compatible with output of `lspci -nnvv`, `lspci -nvv` and `lspci -k`
Signed-off-by: Akshay Gaikwad <akgaikwa@redhat.com>
> Enhance lspci parser

- insights/__init__.py
- insights/collect.py
Allow user to defined plugins to load using the -c config.yaml option.
- Added a `package` list to define packages to be loaded.
- Modified insights.collect to handle the changes for handling yaml config files. files.
> Allow users to define plugins with -c option

- build_client_egg.sh
This change modifies the egg building script to include the tools as well as parsers and combiners.  This enables core collection for new use cases.
I decided to preserve the archive/ and test removal bits.  This keeps the archive size fairly small (750k vs over 3MB for the current set).
> include tools parsers and combiners in the trimmed version of the egg

- insights/tools/cat.py
Cat failed to load if colorama wasn't available. This PR lets cat use it if it's there but fall back to plain text if it isn't.
> Let cat use colorama but fall back to regular text if its not installed.

- insights/core/plugins.py
Fixes #1726.
Provides a common base class for our custom plugin types (parser, rule, combiner, etc.) so that common exceptions raised by datasources are caught and logged at the appropriate level.
> Provide common base class for our plugin types

- insights/client/connection.py
- insights/tests/client/test_platform.py
This reverts commit 04553661ec50c5e918a19f13b438466201682370. Change was based on a mistaken assumption.
> Revert "Canonical fact fix (#1730)"

- insights/__init__.py
before fix, the following exception appears when running the `canonical_facts` module:
```
UnboundLocalError: local variable 'formatters' referenced before assignment
```
> initialize formatters var

- insights/parsers/date.py
There's no `dateutc` binary. The correct command is `date --utc`
This is a minor change.
> [DateUTC] Fix typo in the command

- insights/specs/insights_archive.py
Parser for parsing command `ovs-vsctl list bridge`.
Merged Parser PR: https://github.com/RedHatInsights/insights-core/pull/1733
This PR adds spec for **insights_archive** for parser `ovs_vsctl_list_bridge`.
> Updated parser ovs_vsctl_list_bridge to add spec for insights_archive

- insights/specs/insights_archive.py
Parser for parsing output of command `ip netns exec <namespace > lsof -i`.
Merged Parser PR: https://github.com/RedHatInsights/insights-core/pull/1745
This PR adds spec in insights_archive for parser **ip_netns_exec_namespace_lsof**.
> Updated parser ip_netns_exec_namespace_lsof to add specs for insights_archive

- insights/parsers/ssh.py
- insights/parsers/tests/test_ssh.py
When parsing ssh config, equals signs are permitted but were not correctly handled by the parser. Additionally, provided values may be quoted, and the quotes are stripped.
See https://github.com/RedHatInsights/insights-core/issues/1807
> Improve sshd_config parsing for BZ 1697477

- insights/combiners/cloud_provider.py
- insights/combiners/tests/test_cloud_provider.py
This small patch fix the following Issue:
```
../insights-core/insights/tests/__init__.py:77: AssertionError
---------------------------------------- Captured stdout call ----------------------------------------
File "/pub/INSIGHTS/insights-core/insights/core/dr.py", line 952, in run
result = DELEGATES[component].process(broker)
File "/pub/INSIGHTS/insights-core/insights/core/dr.py", line 673, in process
return self.invoke(broker)
File "/pub/INSIGHTS/insights-core/insights/core/plugins.py", line 63, in invoke
return super(PluginType, self).invoke(broker)
File "/pub/INSIGHTS/insights-core/insights/core/dr.py", line 653, in invoke
return self.component(*args)
File "/pub/INSIGHTS/insights-core/insights/combiners/cloud_provider.py", line 80, in __init__ …
```
> Ensure rpms is not None before getting attribute

- insights/client/config.py
- insights/tests/client/test_config.py
- make env, CLI, conf load functions private (should only be using load_all outside this module)
- move validate and imply calls to after sources are loaded, both in init and load_all
> tweak how options are validated after load

- insights/parsers/modprobe.py
Modprobe parser reads data from the file `/etc/modprobe.d/*.conf`
[Specs for modprobe parser](https://github.com/RedHatInsights/insights-core/blob/master/insights/specs/default.py#L484)
> Fix docstring for modprobe parser

- insights/parsers/software_collections_list.py
Parser for the spec `scl --list`  is not in use, also the spec is ``deprecated`` in RHEL-8 and there is no such a requirement of the new specs `scl list-collections` for any of the plugin code hence just enhanced doc to inform that the spec is valid for RHEL-6/7 only.
> Added a doc string for RHEL-6/7

- insights/combiners/cloud_provider.py
- insights/combiners/tests/test_cloud_provider.py
Correct an issue where only the first rpm that matches the rpm pattern
for a provider is stored in the list.
Does not affect provide selection.
> Correct an issue where only the first rpm that matches the rpm pattern

- insights/core/ls_parser.py
- insights/tests/test_ls_parser.py
Fixes #1825.
I found a way to disambiguate the regular RHEL6 and RHEL7 lines from the selinux RHEL8 lines at the cost of a little performance. Since only a small percentage of the ls data is ever fully parsed, I don't think we'll see a big impact.
> Allow ls_parser to handle rhel8 selinux lines

- insights/combiners/krb5.py
- insights/combiners/tests/test_krb5.py
When multiple config files in /etc/krb5.conf.d/ have the same section, the sections are not merged by the combiner. However, they should get merged.
> Fix parsing of /etc/krb5.conf.d/crypto-policies on RHEL8.

- insights/specs/__init__.py
- insights/specs/insights_archive.py
The client drops a display_name file into the root of the archive to get around
the fact that metadata isn't forwarded for legacy uploads.  This spec collects
it from the insights archive so canonical fact gathering in pup can pick it up.
Closes #1891
> Add display_name spec to insights_archive.py

- insights/client/support.py
RHCLOUD-631
When not using legacy_upload the registration check will output the following values for "status": True, False, None
> Resolving TypeError from the support option when legacy_upload is false

- insights/parsers/rabbitmq.py
- insights/parsers/tests/test_rabbitmq_report.py
- insights/specs/sos_archive.py
1. Fix the issue occurs when handling '\n' in content.
When the '\n' is read from archive-files, it means letters ('\\', 'n'),
and when from local test-data variables, it will be treated as 'a-new-line'.
Base on these, the parsing failed toward archive-files.
To fix this issue, let 'value_tword' can also cover letter '\'.
2. Remove the hiding of parsing errors for friendly debug usage.
> Enhance parser for rabbitmq_report

- conftest.py
- insights/plugins/rules_fixture_plugin.py
- insights/tests/test_rules_fixture.py
* Add test fixture run_rule that provides integration test
functionality like @archive_provider, but runs as a normal
pytest.
* Add plugin and tests for new fixture.
> Add alternative integration test fixture

- insights/tools/insights_inspect.py
When invoking "insights-inspect" command without colorama
installed, we fake having the module by returning an empty
string using "__getattr__". However the magic method was
missing one of the leading underscores and thus not
having any effect.
Fixes https://github.com/RedHatInsights/insights-core/issues/1956
> fix "__getattr__" missing an underscore

- insights/specs/default.py
- insights/specs/insights_archive.py
- The plugins using this rule are against sosreport archives and it's not added to uploader.json ever
> Remove the subscription_manager_list_installed from insights_archive.py

- insights/specs/default.py
- insights/specs/insights_archive.py
- Need to change to use other specs in the related rule
- Will also remove it from the uploader.json
> Remove subscription_manager_list_consumed from insights_archive.py

- insights/parsers/cpuinfo.py
- insights/parsers/tests/test_cpuinfo.py
* fixes https://github.com/RedHatInsights/insights-core/pull/1965
* added x86 stepping
* added other architectures
* it is the same mess as before and the new things are accessible only through `["str indexes"]`, not through properties
* rules have to be changed to support non-x86 archs (no change for rules here - they crashed with the previous cpuinfo parser on non-x86 anyway)
* no change necessary for existing rules that support only x86
* if we want to make a deeper and more systematic refactoring, I'm interested in a discussion as to how to achieve it (I see multiple possible ways, e.g. concerning backwards compatibility or the level of abstraction from the raw cpuinfo data)
> cpuinfo - x86 stepping & other architectures

- insights/specs/sos_archive.py
sos-3.4 and newer sosreport version collects `ip -s -d link` output.
> Update ip_s_link specs for sosarchive

- insights/specs/default.py
* From Satellite 6.4, the forman task configuration file changed to
"/etc/sysconfig/dynflowd"
> New spec of foreman task for Satellite 6.4

- setup.py
- let's use current version of `pyyaml` if possible, there is security issue in old version, see [CVE-2017-18342](https://nvd.nist.gov/vuln/detail/CVE-2017-18342).
- we can use old version only if it's necessary (python version < 2.7)
- it requires only small change in `setup.py` file
> pyyaml dep set to version 5.1.1

- insights/client/data_collector.py
- insights/core/__init__.py
- insights/tests/client/test_skip_commands_files.py
- setup.py
Replaced 'xml.etree.ElementTree as ET' with
'defusedxml.ElementTree as ET' for secure xml parsing.
> Replace xml.etree.ElementTree with defusedxml.ElementTree to protect against malicious xml

- insights/combiners/tests/test_httpd_conf_tree.py
- insights/specs/default.py
* For satellite 6.2, foreman config file located at
"/etc/httpd/conf.d/05-foreman-ssl.d/katello.conf"
> Collect nested httpd config files

- insights/parsers/ifcfg.py
- insights/parsers/tests/test_ifcfg.py
Added `raw_device_value` key along with raw network device name, and `DEVICE` key is set with the proper device name.
https://github.com/RedHatInsights/insights-core/issues/2037
> Modified ifcfg parser to seperate raw_device_value

- insights/parsers/rabbitmq.py
- insights/parsers/tests/test_rabbitmq_report.py
- insights/specs/__init__.py
- insights/specs/sos_archive.py
> New Parser RabbitMQReportOfContainers

- insights/tools/apply_spec_filters.py
If we do not limit the specs to default we run into errors related to
openshift and kubernetes.
We've been running just the default specs. If there is a better way to
solve this, we can do that instead.
> Fix spec errors when running apply_spec_filters

- insights/parsers/ceph_cmd_json_parsing.py
The commands associated with the parser name were incorrect.
> [ceph_cmd_json_parsing] Fix commands in the docstring

- insights/client/phase/v1.py
Moving to post update to ease anxiety about interrupting the pre-update step.
> move egg version logging to post-update

- insights/tools/dupkeycheck.py
- setup.py
This utility can be run against several sets of plugins and checks to see if the base names of any modules containing rules are the same. I think this is as close as we can get to rule result key collision detection before run time.
Fixes #2082 
> dupkeycheck util for finding rules with possible key collisions.

- insights/combiners/dmesg.py
> Dmesg combiner requires at least one valid dependency.

- insights/core/__init__.py
- insights/tests/test_json_parser.py
JSONParser currently expects to parse JSON objects only.
Calling from_dict will fail if the JSON text is an array.
Protect the call to from_dict and do nothing if the text is
an array.
> JSONParser: protect call to from_dict (#2056)

- insights/core/__init__.py
- insights/tests/test_yaml_parser.py
YAMLParser currently fails to parse list-like YAML texts
as calling from_dict will fail.
Remove 'self.doc = from_dict' as it seems unused.
> YAMLParser: remove call to from_dict (#2060)

- insights/core/__init__.py
This was covered up by two other PRs (#2057, #2061) that each removed the call, and after those were both merged the error showed up.
> Fix flake8 error due to extra import

- insights/specs/default.py
- insights/specs/insights_archive.py
* Remove this command from insights due to bug described in
bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1731496
* Spec is still enabled for sosreport
> Remove getcert list command from insights specs

- insights/command_parser.py
- insights/core/dr.py
Errors resulting from bad command line args result in tracebacks. This PR suppresses them and just prints the exception message.
Fixes #2097 
> Protect top level CLI from tracebacks.

- Jenkinsfile
- setup.py
Removing unnecessary PyOpenSSL and adding an additional require tag for QE RHEL 6 testing
> remove pyopenssl req, add new require

- insights/client/apps/compliance/__init__.py
- insights/client/config.py
- insights/client/phase/v1.py
- insights/tests/client/apps/test_compliance.py
- insights/tests/client/phase/test_collect_and_upload.py
This is currently how I'm running it locally, but the x-rh-identity isn't necessary for production.
```
sudo x-rh-identity=$X_RH_IDENTITY BYPASS_GPG=true insights-client --no-gpg --compliance
Running scan... this may take a while
Uploading Insights data.
Successfully uploaded report for rhel7-insights-client.virbr0.akofink-laptop.
```
> [RFC] Add --compliance option to run oscap and upload the report

- insights/command_parser.py
The top level try/except around the InsightsCli caught BaseException.
That included SystemExit, which is raised by argparse parsers at the
end of handling the -h option. This PR allows SystemExit to propogate.
> Propogate SystemExit so insights run -h doesn't print '0'.

- insights/formats/__init__.py
- insights/formats/html.py
- insights/formats/simple_html.py
- insights/formats/template.py
- insights/tests/test_formats.py
- setup.py
`insights run -p<rules> -f html ...` generates an html page with `make_info` results in a card at the top and other results in a color coded accordion beneath. Rule cards include the rule name, result, rule module doc, rule doc, path to rule source, and all data files or commands that may have contributed to the results.
`insights run -p<rules> -f simple_html ...` generates a similar html that's easier to navigate with console browsers like elinks.
> Add Html Format

- insights/specs/default.py
- '/cpuinfo' is for foreman-debug archive, and should be placed in a
separated spec file
> Remove the '/cpuinfo' from cpuinfo's spec

- insights/core/filters.py
- insights/core/spec_factory.py
- insights/tests/__init__.py
- insights/tests/test_find.py
Contains a new helper class to wrap up adding a filter and selecting just the relevant lines for it.
```python
from insights import make_info, rule
from insights.core.spec_factory import find
from insights.specs import Specs
service_starts = find(Specs.audit_log, "SERVICE_START")
service_stops = find(Specs.audit_log, "SERVICE_STOP")
@rule(service_starts, service_stops)
def report(starts, stops):
return make_info("STARTS_STOPS", num_starts=len(starts), num_stops=len(stops))
```
The result of a `find` is a dictionary with key as the command or file string and value as the list of matching lines.
> New "find" helper for streamlining log handling

- insights/tests/client/apps/test_compliance.py
This allows the test to pass even when run on non-EL linux distros like Fedora.
> Stub linux_distribution in compliance test

- docs/shared_parsers_catalog/installed_product_ids.rst
- insights/parsers/installed_product_ids.py
- insights/parsers/tests/test_installed_product_ids.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
* Parser for command rct cat-cert command to be run on each pem file in
the directories /etc/pki/product-default/ and /etc/pki/product/
* Add filter for the command output to only capture ID field
* Add tests for parser
* Add documentation for parser
> Add new parser for installed product IDs

- docs/shared_parsers_catalog/freeipa_healthcheck_log.rst
- insights/parsers/freeipa_healthcheck_log.py
- insights/parsers/tests/test_freeipa_healthcheck_log.py
- insights/specs/__init__.py
- insights/specs/default.py
* add data source for FreeIPA HealthCheck logs
* add parser for /var/log/ipa/healthcheck/healthcheck.log
Requires the fix for issue https://github.com/RedHatInsights/insights-core/issues/2056 e.g. PR https://github.com/RedHatInsights/insights-core/pull/2057
> Add freeipa healthcheck log parser (#2071)

- insights/parsers/tests/test_yum_repolist.py
- insights/parsers/yum.py
I found this parser is used in a lot of plugins, and many of them don't consider that maybe
it starts with exclamation mark. I think it is useless for comparation, so we can remove
it in the parser.
> Remove prefix "!" or "*" for yum repolist

- insights/parsers/__init__.py
- insights/parsers/tests/test_parsers_module.py
- insights/parsers/tests/test_yum_repolist.py
- insights/parsers/yum.py
* On production, some of the outputs have no column of "yum name"
- fix: #2149 
> Fix a bug that it can not parse output when there is no yum name

- docs/shared_parsers_catalog/db2licm.rst
- insights/parsers/db2licm.py
- insights/parsers/tests/test_db2licm.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
Adde SPEC collects `db2licm -l` command stdout:
```sh
Product name:                     "DB2 Enterprise Server Edition" 
License type:                     "CPU Option" 
Expiry date:                      "Permanent" 
Product identifier:               "db2ese" 
Version information:              "9.7" 
Enforcement policy:               "Soft Stop" 
Features: 
DB2 Performance Optimization ESE: "Not licensed" 
DB2 Storage Optimization:         "Not licensed" 
DB2 Advanced Access Control:      "Not licensed" 
IBM Homogeneous Replication ESE:  "Not licensed" 
```
> Added db2licm command parser

- insights/specs/sos_archive.py
`lspci_-nvv` provides more verbose information than `lspci`. Hence, reordering
list of lspci files.
> Reorder lspci file path from sos archive

- insights/specs/sos_archive.py
- Required for OSP fingerprinting to check the trusted containers SHA's
> Docker specs for sosreport

- insights/specs/sos_archive.py
* The content in package-data is the same with installed-rpms but it includes more extra fields
like redhat sign info
> Use package-data for spec installed_rpms too

- insights/__init__.py
* When using a local spec with bare file it may not
include all attributes such as multi_output.  This
change insures that the bare file option will still
work with locally defined specs.
> Fix issue when using local spec with bare file

- insights/client/client.py
- insights/tests/client/test_client.py
Signed-off-by: Alec Cohan <acohale97@gmail.com>
Made fixes to --logging-file switch which now allows files without paths to be logged in the current directory.  
See:  https://projects.engineering.redhat.com/browse/RHCLOUD-2147
for more details on the bug.
> Fixed problem with --logging-file switch

- insights/specs/sos_archive.py
On older sosreport version dmesg would be captured under sos_commands/general/dmesg.
Inisght rules would fail in such instances. Same goes for blkid,lsblk, pvs and vgs.
Add the same in sos_archive.py file to make it work.
This patch does not address all issues. Going forward I will try to update the sos_archive
as I discover more such files.
Signed-off-by: Kenneth D'souza <kennethdsouza94@gmail.com>
> Update sos_archive to process old sosreport V2 files.

- insights/parsers/fstab.py
- insights/parsers/mount.py
- insights/parsers/tests/test_fstab.py
- insights/parsers/tests/test_mount.py
- fix: #2081 
- revert the AttributrAsDict as the base class of MountEntry, MountOpts, and FSTabEntry
- remove the fixed attributes from MountOpts, change to all dynamic attributes
- change dynamic attributes of MountEntry and FSTabEntry to fixed attributes
- update docstring
> Update entry classes in mount and fstab

- insights/parsers/bond.py
- insights/parsers/tests/test_bond.py
Enhance `bond.py` parser to read "ARP Polling Interval" and "ARP IP target" lines.
> Enhance bond Parser to parser ARP lines

- insights/combiners/tests/test_httpd_conf_tree.py
- insights/combiners/tests/test_logrotate_conf_tree.py
- insights/parsr/__init__.py
We've had a couple instances of comments containing unicode characters. I patched logrotate with #2218 but realized there's a more general solution after seeing #2219.
This PR fixes #2219 and should also fix the issue I hacked around in #2218 
> Change AnyChar to mean any character instead of only ascii printables

- insights/core/__init__.py
- insights/tests/test_commandparser.py
> CommandParser handles systemctl cat missing service output.

- insights/parsers/ceph_version.py
- insights/parsers/tests/test_ceph_version.py
Fixed the regex issue in the 'ceph_version.py' parser file.
Also updated the community_to_release_map to add new Ceph release.
Signed-off-by: Ashish Singh <assingh@redhat.com>
> Fix issues with in ceph version parser.

- insights/combiners/httpd_conf.py
- insights/combiners/logrotate_conf.py
- insights/combiners/nginx_conf.py
- insights/core/plugins.py
- insights/tests/test_parser_continue_on_error.py
Some parsers that consume multi_output specs like globs, like ethtool,
can succeed or fail independently. However, configuration parsers that
are combined to form one config tree should succeed or fail as a unit.
Otherwise, rules would get an incorrect view of the configuration.
Fixes #2208
> Create continue_on_error flag for lists of parsers

- docs/notebooks/Parsr Query Tutorial.ipynb
- insights/command_parser.py
- insights/ocp.py
- insights/parsr/query/__init__.py
- insights/parsr/query/boolean.py
- insights/parsr/query/tests/test_boolean.py
- insights/parsr/query/tests/test_find.py
- insights/parsr/query/tests/test_where.py
- setup.py
This PR lets you navigate insights parsr query results with attribute access in addition to dictionary access. It also introduces a `where` clause you can use to select nodes based on names and values in their immediate children. Include queries for multiple names and values in the `where` by using the `make_child_query` helper.
```
In [1]: from insights.parsr.query import contains, from_dict, make_child_query as q
In [2]: import json
In [3]: doc = json.load(open("/Downloads/config/version"))
In [4]: d = from_dict(doc)
In [5]: d.status.conditions.where("status", "False")
Out[5]: 
[conditions]
type: RetrievedUpdates
status: False
lastTransitionTime: 2019-08-04T23:17:08Z
reason: RemoteFailed
message: Unable to retrieve available updates: currently installed version …
```
> Allow attribute navigation for parsr query results. Add ability to search based on child nodes.

- insights/core/__init__.py
1) The documentation for the return value (or rather the value set in
the attribute being created by the token_scan) is a boolean, not a
list of dicts.
2) Because we search for the presence of a matching line anywhere in
the file, the 'reverse' parameter is useless here.
Signed-off-by: Paul Wayper <paulway@redhat.com>
> LogFileOutput token_scan returns a bool, reverse is meaningless

- insights/combiners/dmesg.py
For using this combiner is necessary to have a filter for 'Linux version' string (so we don't have to rely on its presence in the rules).
> New filter for dmesg combiner

- docs/api_index.rst
- docs/manpages/insights-info.rst
- docs/manpages/insights-run.rst
- docs/tools.rst
- insights/__init__.py
- insights/core/evaluators.py
- insights/core/taglang.py
- insights/formats/template.py
- insights/tests/test_taglang.py
- insights/tools/query.py
All components have a `tags` keyword in their decorators, and the values defined there can be overridden in configuration. This PR provides a `--tags` option to `insights run` that allows users to express which rules they want to run based on how they're tagged.
Tag expressions are written in a simple language that allows exact match, regular expression match, quoted strings or regexes, and grouping along with operators for negation, `and`, and `or`.
For example, `insights run -p telemetry --tags 'network & apache & !mod_cluster'` means select rules that have the `network` and `apache` tags but not a `mod_cluster` tag.
`insights-run` also has a `-k` option that applies the same expression language to the full module names of loaded components. If `-k` and `--tags` are used at the same …
> Allow filtering by full module name and tags. Add rule tags to response json doc.

- insights/__init__.py
- insights/core/evaluators.py
- insights/core/plugins.py
- insights/formats/html.py
- insights/formats/simple_html.py
- insights/formats/template.py
- insights/tests/test_evaluators.py
The value of the links keyword must be a dictionary with strings as keys and lists of urls as values.
Example:
```
LINKS = {
"kcs": [
"https://access.redhat.com/solutions/3237861"
],
"bugzilla": [
"https://bugzilla.redhat.com/show_bug.cgi?id=1508644",
"https://bugzilla.redhat.com/show_bug.cgi?id=1531456"
]
}
@rule(..., links=LINKS)
def report(...):
...
```
Links are included in the json and yaml responses. They're also shown in the simple_html and html output formats.
> Ability to attach urls in rule decorators

- insights/client/utilities.py
- insights/tests/client/test_utilities.py
RHEL 8 systemd complains pretty loudly if you try to run `systemd-notify` outside the systemd job itself. So, don't try to run `systemd-notify` unless `NOTIFY_SOCKET` is available.
In addition, use `package_info` directly instead of calling `InsightsClient().version()` to get the egg versions. `InsightsClient()` does things in its init function that we don't want to do superfluously, so let's not instantiate it just to get the version info.
> use package_info instead of client method, check systemd env

- insights/parsr/query/__init__.py
This allows you to walk back up a config structure from the leaves to an arbitrary parent that matches a query instead of just immediate parents or furthest ancestor.
> Add 'upto' to query API.

- insights/core/context.py
- insights/core/hydration.py
- insights/tests/test_context.py
A context gets registered automatically when subclassing ExecutionContext.
Each subclass should specify a marker file relative to the archive root that is unique to the archive type the context handles.
Execution context classes are consulted in reverse of the order in which they are loaded, so it's possible to load your own context in place of one provided by core.
```python
class MyContext(ExecutionContext):
marker = "mycontext.txt"
```
> Execution contexts register themselves and decide if they handle an archive.

- insights/parsers/nmcli.py
- insights/parsers/tests/test_nmcli.py
An exception occurs while parsing the output of `nmcli dev show`  cmd when the `value` is missing from the `key` while splitting the line content. 
Sample output:
~~~
GENERAL.DEVICE:                         br0
GENERAL.TYPE:                           bridge
GENERAL.HWADDR:                         7A:C3:4C:23:65:8A
GENERAL.MTU:                            1450
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     br0
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/1
IP4.GATEWAY:
IP6.ADDRESS[1]:                         fe80::78c3:4cff:fe23:658a/64
IP6.GATEWAY:
~~~
Exception occurs while spliting `IP4.GATEWAY:`
> Enhanced nmcli parser

- insights/client/connection.py
- insights/client/constants.py
- insights/tests/client/connection/test_init_session.py
This PR enhances the data included in the insights-client User-Agent. Rather than a (relatively) constant `<app_name>/<app_version>` string, it now includes version information about the platform (both host and Python platform information).
> Add more info to insights-client user agent

- insights/client/__init__.py
- insights/client/config.py
- insights/client/data_collector.py
- insights/client/utilities.py
- insights/tests/client/test_utilities.py
This PR introduces a new config file, `tags.conf`, as well as the mechanisms to include tags in the collected archive.
The file `/etc/insights-client/tags.conf` is a YAML file containing key/value pairs that can be used to tag the node with desired attributes. For example:
```yaml
---
zone: us-east1
owner: zach
exclude: true
```
Upon collection, the file `/etc/insights-client/tags.conf` is parsed and its contents are written to the insights archive for inclusion in the upload.
In addition, if the `--group` argument is passed to `insights-client`, the value of the argument is written to the tags file with the `group` key. For example:
```
---
zone: us-east1
owner: zach
exclude: true
...
---
zone: us-east1
owner: zach
exclude: true
group: app-db-01
#
```
If the `--group` tag is then omitted …
> Add tags.conf

- insights/client/utilities.py
The tags file is not opened with mode="w+", so it was not being created if it did not yet already exist.
> Create the tags file if it does not exist

- insights/specs/sos_archive.py
The sos_archive context does not currently collect the contents of
/boot so contexts wrapping sosreports can not provide the LsBoot
spec set or parser. This commit adds a missing call to
simple_file() to pull in the specs for LsBoot.
Signed-off-by: chaithco <chaithco@redhat.com>
> Adding LsBoot to sos_archive spec source

- insights/parsers/ip.py
- insights/parsers/tests/test_ip.py
Enhanced to get all the details of vxlan and openvswitch from `ip -s link`.
fix: https://github.com/RedHatInsights/insights-core/issues/2329
> Enhanced to get vxlan and openvswitch details

- insights/specs/sos_archive.py
Load `openvswitch_other_config` specs from `sos_commands/openvswitch/ovs-vsctl_-t_5_get_Open_vSwitch_._other_config` in sos-archives.
> Add Sos-archive path to openvswitch_other_config

- docs/api.rst
- docs/index.rst
- docs/ocp.rst
- insights/core/context.py
- insights/ocp.py
- insights/ocpshell.py
This PR allows insights-core to recognize OCP 4 insights-operator and must-gather archives. It exposes the entire cluster configuration as a single component that rules can be written against in exactly the same way as queries in an interactive ocpshell session. External contexts may override the ones that are built in.
> insights-operator and must-gather archive recognition. top level config component for both.

- insights/parsers/freeipa_healthcheck_log.py
- insights/parsers/tests/test_freeipa_healthcheck_log.py
FreeIPA Healthcheck JSON schema changed from 0.2 to 0.3:
the 'severity' key was replaced by 'result'.
> Adapt FreeIPAHealthCheckLog parser for Healthcheck 0.3 (#2369)

- docs/shared_parsers_catalog/kpatch_patches.rst
- insights/parsers/kpatch_patches.py
- insights/parsers/tests/test_kpatch_patches.py
- insights/specs/__init__.py
- insights/specs/default.py
This patch creates a parser to report on the possible module names of kpatch patches that are installed on a machine.
Also add a supporting spec 'kpatch_patch_files'
Signed-off-by: Joel Savitz <jsavitz@redhat.com>
> Add parser to report local kpatch patches

- docs/shared_parsers_catalog/readlink_e_mtab.rst
- insights/parsers/readlink_e_mtab.py
- insights/parsers/tests/test_readlink_mtab.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
Added
insights/parsers/readlink_e_mtab.py
insights/parsers/tests/test_readlink_mtab.py
docs/shared_parsers_catalog/readlink_e_mtab.rst
Updated
insights/specs/insights_archive.py
pytest -k readlink_e_mtab
================ test session starts ================
platform linux -- Python 3.6.8, pytest-3.0.6, py-1.8.0, pluggy-0.4.0
rootdir: /root/src/insights/shlao/insights-core, inifile: setup.cfg
plugins: cov-2.4.0
collected 1878 items 
insights/parsers/tests/test_readlink_mtab.py .
================ 1877 tests deselected ================
======== 1 passed, 1877 deselected in 4.11 seconds ========
> Add parser for command readlink /etc/mtab

- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
Ulimit spec cannot be collected because it is a shell builtin.
> Remove unused ulimit spec

- insights/specs/sos_archive.py
Since sos-3.7, foreman related data is collected via native sos plugins
instead of collecting foreman-debug. So spec file paths for sos_archive
needs to be updated.
> Update foreman sos_archive spec paths (#2385)

- insights/parsers/ip.py
- insights/parsers/tests/test_ip.py
`IpLinkInfo - command ``ip -d -s link```   parsing logic does not support Geneve tunnel protocol. Added support for the Geneve protocol details. 
~~~
5: geneve0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
link/ether 8e:a3:1d:43:d6:d9 brd ff:ff:ff:ff:ff:ff promiscuity 0 
geneve id 10 remote 192.168.43.254 dstport 6081 noudpcsum udp6zerocsumrx addrgenmode eui64 
RX: bytes  packets  errors  dropped overrun mcast   
0          0        0       0       0       0       
TX: bytes  packets  errors  dropped carrier collsns 
536        8        0       0       0       0       
6: geneve1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
link/ether 22:14:52:d4:a2:13 brd ff:ff:ff:ff:ff:ff promiscuity 0 …
```
> Added support for geneve tunneling

- insights/client/connection.py
- insights/tests/client/test_platform.py
Add full branch_info into the metadata of client uploads when using the
--payload option.
Left the satellite_id key where it is in case other apps continue looking for it in the same place.
JIRA: RHCLOUD-3697
> Add branch_info into the metadata for payloads

- insights/specs/insights_archive.py
Fix: https://github.com/RedHatInsights/insights-core/issues/2399
* add the missing "insights_command/" to readlink in insights_archive.py 
> Enahce readlink

- insights/client/client.py
- insights/client/config.py
- insights/client/constants.py
This is to create a separate log file when we use the --payload argument. The problem was sending up a payload and a classic upload daily would leave you with only 2 days worth of logs due to our rotation settings. If we split them, we can keep the same rotation, but it will create a different set of files depending on which type of upload you do. 
This also helps identify which type of upload was performed, which is pretty handy. 
RHCLOUD-2141
> Separate payload logging

- .gitignore
- insights/command_parser.py
- insights/tests/test_command_parser.py
* Added `version` command and `--version` argument, `ArgumentParser.add_argument` `version` action was not used because of a bug in earlier versions of python.
* The version info can be retrieved using `insights version`, `insights --version` or `insights <command> --version`.
* Added `insights/tests/test_command_parser.py` with couple basic unit tests.
Resolves #2408
Signed-off-by: Vitaliy Dymna <vdymna@redhat.com>
> Add --version flag to the Insights CLI

- insights/specs/default.py
Add path of "/usr/bin/" to simple_command for readlink
> add path to simple_command for readlink

- insights/core/__init__.py
Rather than always relying on the pure Python SafeLoader, try importing
the CSafeLoader locally, handling the ImportError by falling back to the
Pure Python SafeLoader.
Fixes #2271
> Try to load CSafeLoader and gracefully degrade

- insights/parsers/freeipa_healthcheck_log.py
- insights/parsers/tests/test_freeipa_healthcheck_log.py
This new parser method makes creating per-check rules easy, like this:
```
freeipa_healthcheck_log.get_results('ipahealthcheck.ipa.certs', 'IPACertTracking')
```
Signed-off-by: Rob Crittenden <rcritten@redhat.com>
> Add method to healthcheck-parser to find failures for a specific check

- insights/parsers/__init__.py
- insights/parsers/tests/test_ps.py
* Modified `calc_offset()` function to correcly locate
`target` string in a line by removing whitespace chars.
* Modified `test_ps.py` units tests to not strip input content
lines for PsEo tests.
Resolves #2435
Signed-off-by: Vitaliy Dymna <vdymna@redhat.com>
> Correct PsEo parser ValueError exception

- insights/parsers/aws_instance_id.py
- insights/parsers/aws_instance_type.py
- insights/parsers/tests/test_aws_instance_id.py
- insights/parsers/tests/test_aws_instance_type.py
- insights/specs/default.py
* Fix #2441 by adding -s switch to aws command specs
* Fix parsers to check for stats in output
* Update tests
> Fix issue with curl command stats in aws data

- insights/parsers/ip.py
- insights/parsers/tests/test_ip.py
- insights/specs/__init__.py
- insights/specs/sos_archive.py
The parser has been added to parser the output of `ip neigh show` or `ip -s -s  neigh show` commands stored in sosreport. 
> Parser for  ip neigh show

- docs/api.rst
- docs/notebooks/Filters Tutorial.ipynb
- insights/core/filters.py
- insights/plugins/ps_rule_fakes.py
- insights/tests/__init__.py
- insights/tests/test_filters.py
- insights/tests/test_integration_support.py
* Modified `add_filter` so non-datasouce component can be passed into the function.
* Added relevant unit tests to `test_filters.py`.
* Modified `_intercept_add_filter` function to correctly test for missing filters
during integration tests, based on changed to `add_filter`.
* Added `test_integration_support.py` with unit tests for integation testing
support functions.
* Added `plugins/ps_rule_fakes.py` with dummy rules that areused in `test_integration_support.py`
unit tests.
* Modified `Insights API` docs page and `Filtering of Data in Insights Parsers and Rules`
notebook (added new paragraph under **Adding Filters to Rules** section) to include information about the non-datasource component level filtering.
Resolves #2429
Signed-off-by: Vitaliy Dymna <vdymna@redhat.com>
> Extend insights.core.filters.add_filter() functionality

- docs/shared_combiners_catalog/ps.rst
- insights/combiners/ps.py
- insights/combiners/tests/test_ps.py
* Added `Ps` combiner that consolidates data from `PsAlxwww`,
`PsAuxww`, `PsAux`, `PsAuxcww`, `PsEo` and `PsEf` parsers.
* Added `insights.combiners.tests.test_ps.py` with tests for `Ps` combiner.
* Added `ps.rst` to include Ps combiner documentation in the
`Shared Combiners Catalog` section.
Resolves #2423
Signed-off-by: Vitaliy Dymna <vdymna@redhat.com>
> Add PS combiner to consolidate data from the PS parsers

- insights/parsers/tests/test_pcs_quorum_status.py
Change test to look for text in the exception that is added by the parser instead of random text within the test data.  This allows the test to work with the latest version of pytest.
> Fix test to run with latest pytest version

- insights/parsers/satellite_installer_configurations.py
- insights/parsers/tests/test_satellite_installer_configurations.py
Fixes #2469 
* As default, the file "/etc/foreman-installer/custom-hiera.yaml" is empty with some comment.
However this is reasonable, it means customers haven't done tuning, and we should remind
customers to do some tuning.
> Enhance satellite_installer_configurations

- docs/shared_combiners_catalog/rhsm_release.rst
- docs/shared_parsers_catalog/rhsm_releasever.rst
- insights/combiners/rhsm_release.py
- insights/combiners/tests/test_rhsm_release.py
- insights/parsers/rhsm_releasever.py
- insights/parsers/subscription_manager_release.py
- insights/parsers/tests/test_rhsm_releasever.py
- insights/parsers/tests/test_subscription_manager_release.py
- insights/specs/__init__.py
- insights/specs/default.py
* Add new parser for rhsm releasever file
* Update subscription manager release show parser to handle RHEL8
* Add new combiner for both release version parsers
* Update tests for both parsers and combiner
* Add new parser and combiner to documentation
> Add new parser/combiner for RHSM release version

- insights/core/__init__.py
- insights/parsers/tests/test_swift_log.py
- insights/tests/test_syslog.py
- Fix: #2454 
- Adjust the order of the log lines in test_syslog.py
> Keep the timestamp returned by Syslog as it is

- docs/shared_parsers_catalog/abrt_status_bare.rst
- insights/parsers/abrt_status_bare.py
- insights/parsers/tests/test_abrt_status_bare.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
This is a really basic parser for `abrt status` to be used in diagnosing potential problems in tools that interface with ABRT via D-Bus.
> Add parser for abrt status --bare

- .gitignore
- insights/client/__init__.py
- insights/client/client.py
- insights/client/config.py
- insights/client/connection.py
- insights/client/phase/v1.py
- insights/client/url_cache.py
- insights/client/utilities.py
- insights/tests/client/phase/test_LEGACY_post_update.py
- insights/tests/client/phase/test_post_update.py
- insights/tests/client/test_url_cache.py
Part of an effort to integrate Insights into Cockpit involves Cockpit knowing more details about the latest Advisor report. To that end, this PR is added a new command line flag `--show` that does not run through the collection and upload process; instead it gets the latest report as compiled by Advisor and returns the JSON. Responses are cached by ETag (however the certificate-based authentication does not appear to respond with `304` status codes).
There are two well-known files that can be monitored for changes. Both files contain unmodified responses from their respective backend API calls. Both files are updated within a few seconds of each other (both files get updated within the same function call, so realistically, they should be updated at "the same time").
`GET …
> Enable client to retrieve advisor report

- insights/client/connection.py
We are currently logging debug information twice when using --net-debug.
This change makes it so that we only report the failure once in stdout.
The output for the failure message still provides relevant info that's
needed to find out what happened. The --net-debug prints some additional
info rather than printing the same thing twice
> Deduplicate http response content when upload fails

- insights/client/apps/compliance/__init__.py
- insights/client/auto_config.py
- insights/tests/client/apps/test_compliance.py
Notice this is only meant to work on CI for now - it cannot be promoted to production as hitting the endpoint for downloading tailoring policies would not work. I can change the code to handle that situation but it's probably better to hold off releasing this until the production API responds appropriately with a `policy['tailored']` field.  
:warning: To create a tailored policy, you would need:
https://github.com/RedHatInsights/compliance-frontend/pull/423 in the frontend
https://github.com/RedHatInsights/compliance-backend/pull/352 in the backend
> compliance: Download tailoring file for tailored policies

- .gitignore
We don't want the filters to end up in pypi, so this is just a safety
measure to make sure they don't accidentally get committed to the repo
> Ignore filters.yaml in insights-core

- insights/client/schedule.py
Fixes a bug where calling "systemctl start" before "systemctl enable" creates a situate where units that depend on insights-client.timer will not be enabled, therefore they will not start along with insights-client.
Fixes: RHCLOUD-5320
> systemd: use --now to only run systemctl once

- insights/core/filters.py
- insights/tools/apply_spec_filters.py
We can add the new filters.yaml creation to the current apply_spec_filters script so we don't have to add an extra step to the release process. The default dump() location is where we want it to go.
In addition, there was a typo in filters.dump() that has been fixed.
> Add new filter method

- insights/client/config.py
Adding tags has restored the ability to use groups in the platform, so remove the error when using it.
> do not error out when using --group on platform

- insights/core/archives.py
This allows callers to specify exactly which decompression binary to
use, skipping the content-type check and allowing for use of novel
programs such as igzip.
Signed-off-by: Jesse Jaggars <jjaggars@redhat.com>
> Prefer igzip over gzip when handling tarballs

- insights/client/collection_rules.py
- insights/client/config.py
- insights/client/constants.py
- insights/client/utilities.py
- insights/tests/client/test_utilities.py
Catch invalid YAML issues related to tags.conf
We don't die if this fails, but we do throw in a warning for it.
Validate will now check that `tags.conf` is v alid as well
> Validate tags

- insights/__init__.py
- insights/core/evaluators.py
- insights/formats/__init__.py
- insights/formats/html.py
- insights/formats/template.py
- insights/tests/test_evaluators.py
- insights/util/__init__.py
The new analysis_metadata section contains:
- analysis start time in UTC
- analysis end time in UTC
- execution context (host, sos report, insights archive, etc.)
- list of loaded plugin sets that registered themselves with `insights.add_status`
```
"analysis_metadata": {
    "start": "2020-04-24T21:52:06.342965+00:00",
    "finish": "2020-04-24T21:52:07.778594+00:00",
    "execution_context": "insights.core.context.SosArchiveContext",
    "plugin_sets": {
      "insights-core": {
        "version": "insights-core-3.0.8-dev",
        "commit": "placeholder"
      },
      "example-plugins": {
        "version": "example-plugins-1.2.3-4",
        "commit": "placeholder"
      }
    }
  }
```
Closes #2560
> Include analysis metadata in json and yaml responses.

- insights/core/archives.py
- insights/core/hydration.py
- insights/tests/test_extractors.py
This PR replaces the get_all_files function with an `os.scandir()` based implementation.  `os.scandir()` was added in 3.5 and offers a performance increase over `os.walk` since it reduces the number of system calls to stat files.
Signed-off-by: Jesse Jaggars <jjaggars@redhat.com>
> adding a scandir() based option for get_all_files

- insights/client/config.py
We need to see the network log messages when testing the connection.
This will imply net-debug if we use test-connection.
> Set net_debug true when test_connection is true

- insights/client/connection.py
When using test-conenction we now enable --net-debug. In order to see
the url that is being printed, we need to put the url in the NETWORK log
level
> Move test URL messages to network logger

- insights/parsers/cpuinfo.py
- insights/parsers/tests/test_cpuinfo.py
I think we can reject this and instead remove the core_total and instruct people to use lscpu (per @bfahr s suggestion)... but just to be thorough this should be accurate.
Closes #2555
> Fixes improper calculation of core_total

- insights/client/archive.py
We opted not to create `archive_tmp_dir` when `obfuscate=True` because soscleaner does its own tempfile management and archive creation.
Compliance is using the `create_tar_file` function which expects this directory to exist, so we kinda pulled the rug out from under them there if obfuscation happens to be enabled. So let's always create the dir just in case.
> always create archive_tmp_dir for compatibility

- insights/parsers/cpuinfo.py
> Remove duplicated apicid in mappings of CpuInfo

- insights/client/apps/compliance/__init__.py
@jcrafts recommended this method instead of canonical facts to determine
the hostname of the client system. This fixes RHCLOUD-6495.
> Use determine_hostname instead of get_canonical_facts()['fqdn']

- insights/client/apps/compliance/__init__.py
- insights/tests/client/apps/test_compliance.py
unicode strings in RHEL 6, Python 2.6.6 that are split with shlex insert
null characters '\x00', which cause Popen to fail. call() may handle
this in the future, but for now, compliance will be sure to encode any strings
passed to call.
I've manually tested this with the `--compliance` option against RHEL 6 and 7.
@gravitypriest I decided to put the `encode` calls directly in the `call` arguments so it's really future proof against people adding more things to the commands in `call`.
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-670
> encode() messages to call()

- insights/tests/test_formats.py
- setup.cfg
* Add new marker syslog_format to syslog formatter tests to allow
turning them off when testing in a container that doesn't allow calls
to ``getuser``
* Turn off tests with the `-m 'not syslog_format'` switch to pytest
> Add markers to syslog format tests

- docs/shared_parsers_catalog/cni_podman_bridge_conf.rst
- insights/parsers/cni_podman_bridge_conf.py
- insights/parsers/tests/test_cni_podman_bridge_conf.py
- insights/specs/__init__.py
- insights/specs/default.py
Added
```
insights/parsers/cni_podman_bridge_conf.py
insights/parsers/tests/test_cni_podman_bridge_conf.py
docs/shared_parsers_catalog/cni_podman_bridge_conf.rst
```
Updated
```
```
> Add parser for file /etc/cni/net.d/87-podman-bridge.conflist

- insights/client/client.py
- insights/client/config.py
During unregister, this allows cleanup of local files even when API unregistration fails. This is to enable unregistration along side RHSM.
> client: add suppressed --force option

- insights/combiners/cloud_provider.py
- insights/combiners/tests/test_cloud_provider.py
We need the full name of a specific cloud provider to show a better wording in insights-content.
> Add 'long_name' to CloudProvider combiner

- insights/core/hydration.py
After archive is extracted, if top level dirs end with string which is
a valid compression type, current logic determines context as
ClusterArchiveContext. This change double checks if path is a file
along with ending with a compression extension.
Example : 
When a sosreport named `sosreport-system-2020-04-14-asmmxgz.tar.xz` is extracted, top level dir is `sosreport-system-2020-04-14-asmmxgz` which ends with `gz` and sosreport is wrongly identified as a Cluster Archive.
The probability of archive names ending with one of ('zip', 'tar', 'gz', 'bz2', 'xz') strings might be rare but I accidentally hit this bug on a customer sosreport.
> Fix context checking in create_context_fix

- insights/core/remote_resource.py
- insights/tests/test_remote_resource.py
The class level variable was __cache, but the instance was being saved to .cache, so it wasn't surviving the if check.
> Fix saving cache instance.

- insights/specs/insights_archive.py
PR #2616 missed specifying files in `first_file()` as list(`[]`) which cause dependency error in the rule.
> [rpm_V_packages] Fix first_file() should include a list

- insights/client/client.py
When the `--unregister` option is invoked with `--force`, we circumvent the remote URL checks. This resulted in a `False` being returned by the unregistration operation, but in the case of `--force`, we know the remote URL is unreachable; we want to force the unregistration operation anyway, so we explicitly return `True`.
> client: return True if unregister with --force

- insights/client/connection.py
When importing this package, sys.path warnings are recorded on RHEL6.
These are noise and can be safely ignored. They are currently causing
cron emails to be sent every time insights runs on a RHEL6 box.
RHCLOUD-7066
BZ 1847104
> Silence user warning when importing pkg_resources

- insights/specs/insights_archive.py
Found insights-info usage and `insights.parsers.lvm.LvmConfig`  broken due to this.
> Fix first_file usage for lvmconfig spec

- insights/specs/default.py
- insights/specs/insights_archive.py
The FreeIPA CA certificate at /etc/ipa/ca.crt expiration date should
be monitored too.
> add /etc/ipa to certificates_enddate

- insights/parsers/installed_rpms.py
- insights/parsers/tests/test_installed_rpms.py
- This MR is trying to fix #2651 
- The spec "installed_rpms" sometimes collects nothing but the following
kind of error messages only:
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages database in /var/lib/rpm
- Add docstring to remind the user when doing exclusion checking, check if the `packages` is empty at first.
> Update 'corrupt' and docstring of InstalledRpms for empty packages

- insights/core/spec_factory.py
CommandOutputProvider gets the timeout value from the ExeuctionContext if one
isn't supplied in the related datasource definition.
> Apply default timeout to commands during collection.

- insights/parsers/tests/test_yumlog.py
- insights/parsers/yumlog.py
In the former yum_log version, there is no version in erased packages, like:
~~~
May 23 16:09:09 Erased: redhat-access-insights-batch
~~~ 
So the code handle this situation with following code:
~~~
if state == self.ERASED:
pkg = InstalledRpm({'name': pkg})
else:
pkg = InstalledRpm.from_package(pkg)
~~~
However, in new yum.log version, there is version in erased packages, like:
~~~
Jul 28 23:24:36 Erased: systemd-219-67.el7.x86_64
~~~
So it is necessary to handle change like:
~~~
if state == self.ERASED and "." not in pkg:
pkg = InstalledRpm({'name': pkg})
else:
pkg = InstalledRpm.from_package(pkg)
~~~
> Enhance parser yum_log to handle erased package with version

- insights/specs/default.py
* Removing this spec because it can collect too much data and cause
failures in collection and processing of the archive
* Leaving it in sosreport and insights archives in case it has already
been collected
> Remove initscript spec due to performance issues

- insights/client/client.py
Write the `/etc/insights-client/.lastupload` file during platform upload too.
Fixes: RHCLOUD-8339
> client: write lastupload during platform upload

- docs/shared_parsers_catalog/sendq_recvq_socket_buffer.rst
- insights/parsers/sendq_recvq_socket_buffer.py
- insights/parsers/tests/test_sendq_recvq_socket_buffer.py
- insights/specs/__init__.py
- insights/specs/sos_archive.py
Add parser SendQSocketBuffer and RecvQSocketBuffer to parse files `/proc/sys/net/ipv4/tcp_wmem`
and `/proc/sys/net/ipv4/tcp_rmem` respectively.
Add test cases as well for the parser.
Fixes #2557
Signed-off-by: Yadnesh Kulkarni <ykulkarn@redhat.com>
> Add parser for senq & recvq socket buffer

- insights/specs/sos_archive.py
The Spec for subscription_manager_id added in sos_archive.py to parse the associated file:
- sos_commands/subscription_manager/subscription-manager_identity.
> Added spec for subscription_manager_id sos_archive.py

- insights/specs/default.py
Updated the pattern for ssh_config_d
```
```
> Fixed the pattern for ssh_config_d

- insights/client/apps/compliance/__init__.py
- insights/tests/client/apps/test_compliance.py
Related to https://github.com/RedHatInsights/compliance-backend/pull/496
https://projects.engineering.redhat.com/browse/RHICOMPL-610
CC @bastilian, @gravitypriest
> [compliance] Only scan against internal, non-canonical profiles

- insights/parsr/__init__.py
- insights/parsr/examples/arith.py
When parsing fails, print only the _named_ parsers in the list of attempted parser stacks.
Fixes #2231 
> Make parsr error messages more concise.

- insights/client/config.py
`--check-results` is not intended for general use, so we can suppress it from the `--help` output.
> suppress help output for --check-results

- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/collection_rules/test_map_components.py
There is a rule that needs the info from DmsetupInfo, so I create a new PR for this.
Updated
```
insights/specs/insights_archive.py
```
> Update the spec of DmsetupInfo

- insights/parsers/foreman_log.py
- insights/parsers/tests/test_foreman_log.py
Fix issue #2729
Parse each log line into raw_message, message, timestamp for ease of use.
> Parse foreman production log lines

- insights/client/url_cache.py
Rather than deleting the entire `_cache` instance variable, only delete the entry in the `_cache` dictionary that corresponds to `url`.
> url_cache: Delete the cache key rather than the entire cache

- insights/__init__.py
- insights/core/context.py
- insights/shell.py
- insights/specs/core3_archive.py
Core3 archives were being processed as regular archives because the context
detection tested contexts in reverse order of their definition, and
`HostArchiveContext` was defined after `SerializedArchiveContext` (core3 archive).
In other words, `HostArchiveContext` would always win and treat $ROOT/data as
the archive root. This PR reverses the order and fixes that.
Regular specs wouldn't work for core3 archives, but the client puts some
critical files like satellite branch_info directly into the archive root, so
I've allowed regular specs to depend on and fire in the presence of
`SerializedArchiveContext`.
Fixes #2736 
> Reverse context definition order. Add core3_archive spec file.

- insights/core/spec_factory.py
We used codecs.open for py2 compat, and it's an order of magnitude slower decoding unicode than vanilla open in py3. Use six to be smarter.
> Use builtins.open in python 3.

- insights/core/__init__.py
- insights/tests/test_logfileoutput.py
strptime supports Microseconds with %f but not Milliseconds. When logs
have milliseconds, %f still works fine to convert to datetime object as zeros
are padded to right.
When LogFileOutput uses %f in time_format but there are 3 digit milliseconds,
get_after function does not work correctly as it looks for a 6 digit
number. This change adjusts the regex to {1,6} digits for get_after to
work.
Source : Comments for %f in following documentation :
https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
"%f is an extension to the set of format characters in the C standard (but implemented separately in datetime objects, and therefore always available). When used with the strptime() method, the %f directive accepts from one to six digits and zero pads on the right."
> Fix %f regex for get_after

- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/collection_rules/test_map_components.py
This spec is needed for rule development which is used by ls_edac_mc parser, this spec was removed sometime back as no rule was using this spec.
> new spec ls_edac_mc

- insights/core/__init__.py
- insights/tests/test_commandparser.py
The CommandParser now watches for "not a directory" to catchcommand failures.
Fixes #2753
> Catch when grep produces "Not a directory" on failure.

- insights/combiners/httpd_conf.py
- insights/combiners/tests/test_httpd_conf_tree.py
Allow digits after the first character in directive names. This allows directives like `H2Push`.
Fixes #2748
> The http_conf Name definition is too strict.

- insights/parsers/__init__.py
- insights/parsers/tests/test_parsers_module.py
* If we keep blank lines, it will generate a dict with empty values,
* which is useless.
> Remove blank lines for parse_fixed_table

- insights/parsers/engine_db_query.py
- insights/parsers/tests/test_engine_db_query.py
- insights/specs/default.py
- insights/specs/insights_archive.py
Two major changes
-----------------
1. Remove the ";" from DB query statement:
ON RHV Manager the statement ending with ";" failed with below error
```
SELECT
row_to_json(t)
FROM
(SELECT vs.vds_name, rpm_version FROM vds_dynamic vd, vds_static vs WHERE vd.vds_id = vs.vds_id;) t
File "/usr/lib/python2.7/site-packages/engine_db_query/__init__.py", line 337, in query_return_json
query
SyntaxError: syntax error at or near ";"
LINE 5: ...ds_dynamic vd, vds_static vs WHERE vd.vds_id = vs.vds_id;) t
^
File "/usr/bin/engine-db-query", line 281, in <module>
sys.exit(main())
File "/usr/bin/engine-db-query", line 273, in main
knowledge_base=args.kb_url
File "/usr/lib/python2.7/site-packages/engine_db_query/__init__.py", line 213, …
```
> Remove the semicolon from query statement

- insights/__init__.py
- insights/core/evaluators.py
- insights/core/hydration.py
- insights/formats/__init__.py
- insights/formats/_json.py
This PR also adds a procedure for initializing brokers from an archive whose type is automatically detected. This new API should be used by service wrappers.
Fixes #2756
> Ensure evaluators are populated with system_id and branch_info.

- insights/client/apps/compliance/__init__.py
- insights/tests/client/apps/test_compliance.py
Before, if a SCAP profile was missing on the client system, the
--compliance run would halt and inform the user, even if there were more
profiles assigned to the host that did exist. After this change, the
user still gets an error message for a missing profile, but other
existing profiles will still be scanned and uploaded as usual.
Here's what it looks like to the customer:
```
$ sudo insights-client --compliance
XML profile file not found matching ref_id xccdf_org.ssgproject.content_profile_rhelh-vpp-nonexistant
Running scan for xccdf_org.ssgproject.content_profile_hipaa... this may take a while
Uploading Insights data.
Successfully uploaded report for rhel7-insights-client.virbr0.akofink-desktop.
```
https://issues.redhat.com/browse/RHICOMPL-737
CC @gravitypriest @bastilian @vkrizan …
> [RHICOMPL-737] Fail gracefully for missing profiles

- insights/combiners/sap.py
- insights/combiners/tests/test_sap.py
All the following instance types indicate that the server is SAP NetWeaver server.
- 'D', 'ASCS', 'DVEBMGS', 'J', 'SCS', 'ERS', 'W', 'G', 'JC'
The old "is_netweaver" only checks 'D', this PR added all the other types.
> Update the check of NetWeaver for Sap combiner

- insights/parsers/__init__.py
- insights/parsers/tests/test_parsers_module.py
The RAW line should not be stripped.
- The `raw_line_key` is used to keep the RAW lines in the target table
But the current code stripped the RAW line before saving it to the specified "RAW key"
> Update the 'raw_line_key' of parse_delimited_table

- insights/core/context.py
* Sometimes, the dir named "sos_commands" appears more than once in
sosreport. In this case, the common path should be the one which is
the closest to the root.
> Return the common path of marker which is close to root

- insights/parsers/open_vm_tools.py
- ESXi is only one type of VMware hypervisor arch
This attribute is too specific.
> Remove the vmware_esxi_version attribute

- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/collection_rules/test_map_components.py
The Spec was not used earlier in the rule and was removed in https://github.com/RedHatInsights/insights-core/pull/2663.
> Add du_dirs Spec to contexts

- docs/shared_parsers_catalog/rhsm_conf.rst
- insights/parsers/rhsm_conf.py
* Add rhsm_conf.rst to include parser in doc build
* Fix docstring errors
> Include rhsm_conf module in documentation

- insights/tools/cat.py
- insights/tools/insights_inspect.py
* To properly hydrate core for core collected archives we need to use
new hydration function to identify context and hydrate broker
> Fix cmdline utils for core archives

- insights/client/data_collector.py
- insights/tests/client/test_skip_commands_files.py
Fixed the bug and added some tests. The affected message is only one of a few more that serve the same purpose. I added tests for the sister warns too, so they are all covered. Used mocks to avoid relying on real files being present and possibly running into permission issues.
To reproduce:
1. Add a rule to _remove.conf_ to remove a file that would be matched by a glob rule. E.g. _/etc/yum.repos.d/redhat.repo_.
```ini
[remove]
files=/etc/yum.repos.d/redhat.repo
```
2. Run the client and see that a warning is emitted. This warning contains a file name and not a full specification dictionary dump.
```
WARNING: Skipping file /etc/yum.repos.d/redhat.repo
```
> RHCLOUD-8745 Fix warning when skipping a glob

- insights/client/__init__.py
- insights/client/phase/v1.py
- insights/tests/client/init/test_write_pidfile.py
This is a fix for [RHCLOUD-9230](https://issues.redhat.com/browse/RHCLOUD-9230).
The reported bug was that the _insights-client_ does not delete its (P)PID files if called with the _--version_ argument. The problem is that the files are created whenever the wrapper is used, but deleted only at the end of the _collect and output_ phase. If this phase does not happen, the files are not deleted.
Fixed by registering the delete at the same place where the files are written. Like this, the files are deleted even on failure and regardless of what phases are run or whether even any phase is run. This includes the _--version_ switch that results in no phases being run at all.
Along with this I slipped in these following tiny changes:
- Fixed the tests that got broken by …
> RHCLOUD-9230 Delete pid files on exit

- insights/parsers/samba.py
- insights/parsers/tests/test_samba.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/specs/sos_archive.py
testparm command parsing is the better way for handling Samba configuration. Especially it allows getting server role.
The code in the review is not considered to be final but rather draft. I would like to start a conversation about how to handle this.
> Added parser for testparm data for Samba configuration

- insights/specs/default.py
- insights/specs/insights_archive.py
* Spec was removed for core collection
* It is now needed, parser is already in place
> Readding spec for sap_hdb_version

- insights/combiners/sap.py
There is a possibility that the FQDN of a system is used as the
shortname in SAP configurations. We want to verify that the short
hostname is used in these comparisons.
> Ensure hostname comparisons in SAP are accurate

- insights/combiners/rsyslog_confs.py
- insights/combiners/tests/test_rsyslog_confs.py
- insights/parsers/rsyslog_conf.py
- insights/parsers/tests/test_rsyslog_conf.py
- insights/specs/__init__.py
- insights/specs/default.py
Before RHEL8, the format of rsyslog.conf is like:
~~~
$IncludeConfig /etc/rsyslog.d/*.conf
$ModLoad imtcp
~~~
However, it changes like following in RHEL8:
~~~
include(file="/etc/rsyslog.d/*.conf" mode="optional")
module(load="imuxsock" 
SysSock.Use="off")
~~~
We also need to consider the `RainerScript` when parsing rsyslog.conf, then it becomes too complicated if we want to parse this file in detail. Per our discussion in https://github.com/RedHatInsights/insights-core/pull/1952, we decide to return the content directly with format line by line. As `LogFileOutput` can not handle multi lines, I do not use this class, and parse the content with my own code. Also, if we use filter for multi lines, we will get only one line and it may not be useful for plugin check, so I remove the filter.
> Add combiner for rsyslog_conf

- insights/parsers/tests/test_yum_repolist.py
- insights/parsers/yum.py
- In RHEL8 the repo for satellite is not started with "rhel-", but contains '-rhel-'
Make sure the `rhel_repos` gives all the repos for RHEL
> Update the YumRepoList.rhel_repos for RHEL8 satellite

- insights/specs/default.py
Current rsyslog spec is following which is not correct:
~~~
rsyslog_conf = glob_file(["/etc/rsyslog.conf", "/etc/rsyslog.d/test.conf"])
~~~
"/etc/rsyslog.d/test.conf" is a typo, it should be "/etc/rsyslog.d/*.conf"
~~~
rsyslog_conf = glob_file(["/etc/rsyslog.conf", "/etc/rsyslog.d/*.conf"])
~~~
> Enhance rsyslog spec

- insights/specs/default.py
* Foreach_execute specs take a datasource or list of datasources as the
first argument
* Fix #2824 
> Fix foreach_exec specs to use datasource as arg

- insights/specs/default.py
- insights/tests/client/collection_rules/test_map_components.py
* initially added by #1656 and removed by #2663
* it's still needed for insights.parsers.dnf_modules used by RedHatInsights/insights-puptoo project
> collect missing DNF modules data

- insights/collect.py
* This fixes an issue with collection of the sap_hdb_version spec in
core collection
> Add sap combiner and deps to manifest for core collection

- insights/specs/core3_archive.py
There are issues with display_name in core3 archives
RHCLOUD-10799
> fix(specs): add spec for display_name to core3_archive

- insights/specs/default.py
- insights/specs/insights_archive.py
- The specs in this PR are not used by any rule, remove them temporary
They are not added to uploader.json, no need to change the insights-core-assets repo.
> Remove the unused SAP specs

- insights/parsers/installed_rpms.py
- insights/parsers/tests/test_installed_rpms.py
- The current `InstalledRpm.vendor` treats the `(none)` and `no vendor outputted` as the same
Updated as:
- set the value as `'(none)'` string, when the vendor is `(none)`
- set the value as `None` (NoneType), when there is no `vendor` column/item.
> Enhance the vendor of InstalledRpm

- insights/specs/default.py
- It was known that the `ss` command will load required kernel modules
automatically and won't release them after the execution.
To avoid changing the system after the collection, `pre-check` is added
to ensure only collecting this spec when required modules are loaded
See: https://bugzilla.redhat.com/show_bug.cgi?id=1903183
> Add pre-check for the 'ss' command

- insights/parsers/saphostexec.py
- insights/parsers/tests/test_saphostexec.py
- Use the `dict` as the base class instead of LegacyItemAccess
- Fix the bug that cannot handle empty output correctly.
> Enhance the parsers of saphostexec

- insights/parsers/lvm.py
- insights/parsers/tests/test_lvm.py
Added ``raw_lines`` property to the parsers extended by ``LvmHeadings``
class. The content may contains warning or debug information which can
be access using this property.
> Add warnings property for LvmHeadings parsers

- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/collection_rules/test_map_components.py
* Add spec for core collection of
subscription_manager_installed_product_ids command
* Fixes Bugzilla 1905503
* Already being collected by client for legacy collection
> Add specs for existing parser InstalledProductIDs

- insights/parsers/lvm.py
"unknown device" is not part of warning messages of pvs/lvs/vgs
commanmds but pvs will display unknown device when device is
missing. See example of such output:
```
PV                   VG     Fmt  Attr PSize   PFree DevSize PV UUID
/dev/fedora/home                 ---       0     0  418.75g
unknown device                   ---       0     0   50.00g
/dev/fedora/swap                 ---       0     0    7.69g
```
> [lvm] Remove "unknown device" string from warnings

- insights/collect.py
> Add LsMod parser to the pre-loaded component for 'ss' spec

- insights/specs/sos_archive.py
Newly added "ls -lanR /sys/firmware" command output in sosreport.[1]
This PR adds ls_sys_firmware spec for sos_archive.
[1] https://github.com/sosreport/sos/commit/959c5a4a78c797dc68206aff21e2eba63e99bb18
> Add ls_sys_firmware spec in sos_archive

- setup.py
* There is an open issue with ipython and jedi that causes an exception
if tab completion is triggered in insights inspect
* Open issue in
[IPython](https://github.com/ipython/ipython/issues/12740)
* This closes #2878
> Fix error with ipython and jedi in inspect

- insights/specs/default.py
- insights/tests/test_specs.py
* Commands argument could be a type other than a list which caused
archive collection to fail
* Identified in bugzilla 1915219
* Added tests for exceptions
> Ensure that args to get_running_commands is a list

- insights/parsers/chkconfig.py
- insights/parsers/systemd/unitfiles.py
- insights/parsers/tests/test_chkconfig.py
- insights/parsers/tests/test_unitfiles.py
- fix: #2882
- When nothing is parsable in the collected file, skip it. 
> Skip empty result in chkconfig and unitfiles

- insights/core/spec_factory.py
`cmd` members should be strings, not lists of lists.
Signed-off-by: Reid Wahl <nrwahl@protonmail.com>
> Doc: Fix data type for spec_factory cmds

- insights/parsr/query/__init__.py
`six` 1.9 doesn't have `ensure_str`. This PR uses a different test.
Fixes #2898
> Ensure strings can be interned in py2 and py3

- insights/core/dr.py
- insights/tests/test_dr_enabled.py
Only call `get_component` if the argument is a string.
Fixes #2903
> set_enabled works on components and their fully qualified names.

- insights/core/dr.py
When dr is asked for a component, it will first ensure that relevant module is
loaded. Since the component can be a module attribute or a class attribute, the
loader tries to get it as each, and this can cause harmless ImportErrors. A
debug statement was added to log them for visibility, but in practice they're
causing confusion in the logs.
Fixes #2912
> Remove debug call that prints unhelpful tracebacks during component loading

- insights/core/serde.py
Sometimes commands fail during archive creation. core logs the failures at
debug level, but they're generally harmless and causing confusion when people
inspect the collection log. Since we also capture the failures in the metadata
for each component, we can remove the debug statement and not lose the info.
Fixes #2913
> Remove debug log messages generated when commands fail during serialization

- insights/specs/core3_archive.py
- insights/specs/default.py
Looks like we need this spec defined for core3 archives. Ran a test
locally and this is the only reason I can spot that we wouldn't be
populating this field in some cases.
> fix: collect version_info in core3 archives

- insights/client/config.py
- insights/tests/client/connection/test_init.py
- insights/tests/client/test_client.py
- insights/tests/client/test_config.py
The Inventory URL is composed incorrectly if legacy upload is enabled. There is a workaround for this in place that disables legacy upload for actions that use the Inventory API. Added the check-in to the list of such actions.
Removed _show_status_ from the workaround action list, because the legacy upload config option does not affect it in any way.
> Fix checkin URL with legacy upload

- insights/components/rhel_version.py
- Add the minor attribute to the IsRhel* components to make them can be widely used
E.g. replace the `RedHatRelease` [here](https://github.com/RedHatInsights/insights-core/pull/2910/files#diff-3d5665cd194cc52869c22cc075e78581f83602790b2fb1a695dea1f55576754dR402)
> Enhance the IsRhel# components and add the 'minor' attr

- insights/specs/default.py
- It's necessary to get all the instances instead of the local instances
Since It's possible for SAP HANA instances to use alias hostname
> Change to use all_instance for HDB Version

- insights/parsers/tests/test_virsh_list_all.py
- insights/parsers/virsh_list_all.py
The `keywords` attribute stores VM names in lowercase, however
`search()` look-up into `self.cols` that does not contains VM names
in lowercase.
> Correctly handle uppercase VM name in "VirshListAll.get_vm_state()"

- insights/specs/default.py
* For satellite 6.8, it uses rh-postgresql12-postgresql-server,
the location of configuration file and error logs changes too.
> Add more path to postgresql_log and postgresql_conf

- insights/specs/sos_archive.py
Sosreport spec entry for mdadm_E spec.
Collect mdadm -E output in sosreport: https://github.com/sosreport/sos/commit/7c7cf6687ea39d9502a229cc15628c7dca7a3569
> Add mdadm_E spec for sosreport

- insights/util/__init__.py
When importing insights-core as a Python module, if the process has no PATH in the env, the import will crash.
Check for a nonexistent PATH value before trying to split the value in the init here.
> fix: check for null PATH

- insights/combiners/multinode.py
- insights/combiners/sap.py
- insights/core/evaluators.py
- insights/tests/test_evaluators.py
- The hostname combiner is deprecated, change to use the Hostname
To avoid the "DeprecationWarning"s in test of rules.
> Change to use 'Hostname' instead of 'hostname' combiner

- insights/client/uploader_json_map.json
- insights/specs/default.py
- insights/specs/insights_archive.py
* The saphostctrl command is a better source of the information
* Fixes two open bugzillas with the lssap command 1922937 and 1936951
* Registry spec and parser will remain for use in the future
> Remove lssap command from collection

- insights/parsers/virt_uuid_facts.py
SubscriptionManagerFactsList was added and then removed in (#1935)
Though reading this file is not a good way of gathering virt uuid, deprecated warning should be removed unless a parser exists for `subscription managers facts`.
> Remove deprecated warning for VirtUuidFacts

- insights/parsers/tests/test_yum_repolist.py
- insights/parsers/yum.py
* Fix #2857 issue where parser throws exception with empty repolist
* Add tests for exception handlers
> Fix exception in YumRepolist parser

- insights/core/spec_factory.py
* Fix #2970 issue with datasources where the DatasourceProvider output
was being deserialized as raw instead of text
> Fix datasourceproviders to deserialize as text

- insights/client/apps/compliance/__init__.py
- insights/tests/client/apps/test_compliance.py
Tailoring will now happen against specific rule sets per OS minor version rather than the initial profile of each policy. If a policy has no profile with a matching OS minor version (i.e. the UI tab does not exist), tailoring will not occur; the host will scan against the canonical rule set. If os_minor_version is missing completely from the API response (via old behavior or feature flag), the initial profile on the policy will be used for tailoring, the same behavior we have before COMP-E-133.
Related backend feature flag PR: https://github.com/RedHatInsights/compliance-backend/pull/787
This is part of COMP-E-133.
> feat: RHICOMPL-1401 Send OS info in profile request

- insights/client/map_components.py
- insights/client/uploader_json_map.json
- `lspci_kenrel` is the same as the `lspci`
It's OK that just keep the `lspci` which is used by rules.
> Remove the duplicated lspci_kernel

- insights/parsr/query/__init__.py
- insights/parsr/query/tests/test_choose.py
This PR allows the function passed to `parsr.query.Entry.choose` to include scalar results as part of its response.
e.g.
```python
def selector(c):
return (
{"status": True if c.status.value == "True" else False},
{"reason": c.reason or "None Provided"},
c.message
)
df = conf.status.conditions.where("type", "Progressing").choose(selector).to_df()
```
> Allow scalars in parsr.query.choose results.

- setup.py
The latest version of docutils break the documentation build
* Change setup.py to use an older version of docutils for the Jenkin build
> Docutils 0.17 break doc build

- Jenkinsfile
* Updated python3 CI image uses RHEL default python3
> Update jenkinsfile to use updated python3 image

- insights/client/apps/ansible/playbook_verifier/__init__.py
- insights/client/apps/ansible/playbook_verifier/__main__.py
- insights/tests/client/apps/test_playbook_verifier.py
Change Validation function to manually skipVerify until all playbook-snippets are signed.
I also commented out most of the tests for the playbook verifier until such a time when we can remove the manual skip verify.
> Manually overide skipVerify

- docs/shared_parsers_catalog/azure_instance_plan.rst
- insights/parsers/azure_instance_plan.py
- insights/parsers/tests/test_azure_instance_plan.py
- insights/specs/__init__.py
- insights/specs/default.py
We'll need to identify azure marketplace systems inside puptoo. Since we
rely on core for this, we need to have this parser in place.
RHCLOUD-13520
> Azure marketplace parser

- insights/specs/default.py
- https://bugzilla.redhat.com/show_bug.cgi?id=1949056
Currently, sap_hdb_version runs for all the `<SID>adm` users,
while `HDB` is only valid for HANA instances, this patch limits it to
HANA SID only.
> Run the sap_hdb_version datasource only for SAP HANA

- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/collection_rules/test_map_components.py
* The ssl certificate changes from satellite 6.6,
however since no rules use this spec, no need to update it,
we can remove it directly
> Remove the spec because it is not used by any rule

- Jenkinsfile
This package was removed from pypi. We still need it for python2, so
we'll download it directly via git.
> [testing] download idna 2.7 directly

- Jenkinsfile
- Reverted #3025, because it was only an intermittent partial fix that was not targeting the real cause.
The original motivation was to fix _pip_ being unable to install _idna_ and _pycparser_ from PyPI. The cause of the failure is unknown. For the time being, changing the source to direct GitHub release URL fixed the failure, but then other failures started to appear, this time for packages installed by `pip install .[testing]`. Now, the original PyPI installation works again for both cases.
- Upgraded PIP to 9.0.3, the last version supported by Python 2.6.
Again, we don’t know what was the cause of the PyPI query failures. But I think we can assume that a newer version of PIP would have fewer issues with the current-day API. Also PIP ≥ 9 is able to check package compatibility with the …
> 👷🏻‍♂️ Pipeline: Upgrade PIP and revert pip install changes

- docs/shared_parsers_catalog/gcp_license_codes.rst
- insights/parsers/gcp_license_codes.py
- insights/parsers/tests/test_gcp_license_codes.py
- insights/specs/__init__.py
- insights/specs/default.py
- insights/specs/insights_archive.py
This is needed to identify marketplace systems in the GCP cloud.
> [parser] GCP parser to gather license codes from instances

- insights/parsers/lvm.py
- insights/parsers/tests/test_pvs.py
- insights/parsers/tests/test_vgs.py
* Fix issue were leaked file descriptors messages in the output caused
exceptions.
* Add test for parsing with the leaked file descriptor messages.
> Fix ValueError exception in Lvm parser.

- insights/specs/sos_archive.py
* The file outputted by the pvs, vgs, lvs and vgdisplay commands
changed in sos v3.6 and again in v4.0, so I added the new filenames to
the specs.
> Update spec pvs, vgs, lvs, and vgdisplay

- insights/parsers/dmsetup.py
- insights/parsers/tests/test_dmsetup.py
* The parser wasn't setup to parse the output if there weren't any
devices found.
* Added test for "No devices found" output.
* Fix #3042
> Fix ValueError exception in dmsetup parser

- insights/parsers/installed_rpms.py
Sometimes, developers forgot to check "epoch" while it is not "null", then the rpm comparison would get unexpected result. Add this docstring to emphasize this point
> Enhance docstring installrpm

- insights/parsers/systemd_analyze.py
- insights/parsers/tests/test_systemd_analyze.py
* The parser wasn't setup to parse all of the possible column amounts,
it was only setup to expect two columns, so seconds only. But the
command can have up to 8 columns of output, so I updated it to parse
all of the columns properly.
* Added all of the possible columns to the test file.
* Fix #3040
> Fix ValueError exception in systemd_analyze parser

- insights/client/apps/compliance/__init__.py
- insights/tests/client/apps/test_compliance.py
This changes all API calls to Compliance to use the host ID, retrieved
from the Inventory API via machine_id, rather than the hostname. This
fixes the use case when a user has updated the display name using the
client's --display-name option.
> fix(compliance): RHICOMPL-1111 Use ID instead of hostname

- Jenkinsfile
* This fix uses a new python26 image with required modules included
* This goes with [this image](https://github.com/SteveHNH/jenkins-s2i-example/pull/4)
> Fix issues in rhel6/python26 CI

- insights/parsers/tests/test_uname.py
- insights/parsers/uname.py
* Debug kernels append .debug to the end of the kernel name in the uname
output, so I updated the parser to check and remove the appended
.debug because it causes exceptions.
* Fixes #2709
> Fix uname parser for when a debug kernel is being used

- setup.py
* Update doc build modules to latest versions
* Pinned jinja2 to the last version that worked with core
> Fix error created by jinga2 3.0.0 release

- insights/parsers/tests/test_uname.py
- insights/parsers/uname.py
* Add the mappings for the 3 kernel-alt releases, I added -alt to the
release number to distinguish it from the normal release kernel versions.
* Fixes #2770
> Add kernel-alt release mappings

- .github/workflows/main.yml
The old jenkins CI that this runs on is far out of date and very
unstable. Moving to Github actions satisfies all the requirements we
have for testing the project
> [testing] start using github actions for tests

- insights/core/plugins.py
Bugfix for: https://github.com/RedHatInsights/insights-core/issues/3069
> Correct the `unit_files` format in pydoc

- insights/combiners/smt.py
- insights/combiners/tests/test_smt.py
* On some systems the /sys/devices/system/cpu0/online file doesn't
exist, which causes an IndexError in the combiner. Updated it to
to handle the missing file since cpu0 will always be online.
* Add test to replicate the missing cpu0 online file.
* Fixes #3073
> Fix IndexError exception in smt combiner

- insights/parsers/cpuinfo.py
- insights/parsers/tests/test_cpuinfo.py
* Added the ability to parse the different cpuinfo output for s390x
cpus, and added model_ids correctly for power pc cpuinfo.
* Added new test cases for s390x on r7 and r8 since r7 and below
doesn't display per cpu clock speed, and r8 an above does.
* Fixes #2629
> Fix s390x cpuinfo parsing

- docs/manpages/insights-run.rst
- insights/__init__.py
- insights/formats/text.py
* Add new switch --color[=WHEN] to allow the choice of color output
encoding. The options for when are always, auto, and never. Always
sets colorama to not strip the encoding, so the color can be piped.
Auto sets colorama to the default, and never disables color encoding.
* Fixes #2980
> Add new switch to run to choose the color output

- insights/combiners/cloud_provider.py
- insights/combiners/tests/test_cloud_provider.py
* There are systems that end up with uuids that start with ec2 that
aren't aws systems. I added an extra check on the asset tag so non aws
systems aren't detected.
* Added a new test for a non aws system with a uuid starting with ec2.
* Fixes #2904
Provide complete details of the issue and how this PR fixes the issue. You can link to one or more existing open, publicly-accessible issue(s) that provide details.
* Some non aws systems have uuid's starting with ec2. Currently it checks the bios_vendor, then bios_version, then rpms before last checking if the uuid …
> Fix non aws systems from being detected as aws

- insights/specs/default.py
- insights/tests/client/collection_rules/test_map_components.py
The specs partitions is already available for sos archive however it
is missing from default and insights archive. This commits add
partition spec to default and insights archive so that archive
generated by insights would also gather /proc/partitions file.
Since a new rule is developed to use partitions specs, hence it is
removed from skipped_specs list. See CEECBA-4818 for a reference.
> Add partitions spec to default and insights archive

- insights/combiners/modprobe.py
- insights/combiners/tests/test_modprobe.py
* Added a check that the type of the entry is a list before attempting
to append.
* Added duplicate blacklist entries to the test.
* Fixes #3107
When there is duplicate blacklist entries it will cause an attribute error due to blacklist entries being bools not list, which can't be appended to. So I added a check to make sure the entry is a list before appending.
> Fix attribute error in AllModProbe combiner

- setup.py
* Fixes #3113 
* Futures is included in python3 but a separate module in python2
* Installing the python2 module when using python3 causes problems
* Collect.py is the only place that futures was used, and it was only
loaded if the client collection was run in parallel.  This is not
feature we currently use.
* The parallel collection feature will still work with python3, but not
with python2
> Remove futures module from setup.py

- insights/tests/datasources/test_cloud_init.py
Test was using imported `simple_file` object directly for test data.  This change replaces that obj with a `mock` object in all of the tests.
> Fix test for cloud_init datasource

- docs/custom_datasources_index.rst
- insights/combiners/ps.py
- insights/combiners/tests/test_ps.py
- insights/parsers/ps.py
- insights/parsers/tests/test_ps.py
- insights/specs/__init__.py
- insights/specs/datasources/ps.py
- insights/specs/default.py
* This new datasource/parser will enhance the ps combiner output by
ensuring that we have the full command path but don't collect args
that may include PII and sensitive info
* Add new datasource for ps eo pid,args that removes args leaving the
command only
* Add new parser for the datasource
* Update ps combiner to use new parser
* Add tests and docs for both
> Add new datasource and parser for ps eo pid,args

- insights/collect.py
- insights/components/cloud_provider.py
- insights/components/tests/test_cloud_provider.py
- insights/specs/default.py
The `is_aws`, `is_azure`, `is_gcp` look more like Components than datasources, this PR move them to the `insights.components.cloud_provider` module.
> Refactor is_aws, is_azure, is_gcp to Component

- docs/custom_datasources_index.rst
- insights/specs/datasources/ethernet.py
- insights/specs/default.py
- insights/tests/datasources/test_ethernet.py
* Add new ethernet interfaces datasource, to properly gather a list of
valid ethernet interface names. That way ethtool is ran against the
proper interface names.
* Fixes #1791
Switch from just listing the files under the /sys/class/net to run ethtool against, instead parse the ip -o link command for any interfaces with link/ether in it. Also correct the interface name when it is a vlan interface, as it appends the parent interface on the end after an @ symbol. This plus an update to the uploader.json should fix the majority of the ethtool parse exceptions that occur in production.
> Fix ethtool parse exceptions due to a spec issue

- docs/manpages/insights-run.rst
- insights/__init__.py
- insights/core/plugins.py
- insights/formats/text.py
- insights/tests/test_rules_fixture.py
Reverts RedHatInsights/insights-core#3135 as it will require changes in tests that depend on the results being `None` instead of `make_none()`.
> Revert "Add make_none response for rules"

- insights/parsers/logrotate_conf.py
- insights/parsers/tests/test_logrotate_conf.py
* When one line endswith "}" in script part, the parser will consider it is ending of
current section.
It fixes https://github.com/RedHatInsights/insights-core/issues/3152
> Fix "KeyError" bug

- insights/client/connection.py
Comparing string literals by is yields a SyntaxWarning on newer Pythons. This happens in insights.client.connection that uses _is/is not_ to compare with string and number literals. Not only this issues warnings, but is itself incorrect behavior that may lead to bugs. Hence the warnings. Fixed and tested.
> Fix SyntaxWarnings

- insights/parsers/systemd/config.py
- insights/parsers/tests/test_systemd_config.py
- insights/specs/__init__.py
- insights/specs/default.py
Signed-off-by: Rahul Srivastava <rasrivas@redhat.com>
This is an enhancement PR to check for the `/bin/systemctl cat dnsmasq.service` config
> Added SystemdDnsmasqServiceConf method to the systemd_config parser

- insights/tests/datasources/test_candlepin_broker.py
Fixes [ESSNTL-958](https://issues.redhat.com/browse/ESSNTL-958).
_insights/tests/datasources/test_candlepin_broker.py_ contains a circular import causing tests to fail. The problem is that the _insights.specs.candlepin_broker_ module imports _from insights.specs.default_, which itself imports from _insights.specs.candlepin_broker_. Any direct import from _insights.specs.candlepin_broker_ is thus predestined to fail.
(Hot)fixed by importing _candlepin_broker_ from _from insights.specs.default_ instead. Like that, Python handles the circularity well, not failing and making the tests green again. I am not sure whether this is the best solution. The circular reference looks like a bad practice to me.
> Fix candlepin broker test

- insights/parsers/systemd/config.py
- insights/specs/insights_archive.py
Signed-off-by: Rahul <rasrivas@redhat.com>
This MR is to add spec for the `systemctl_cat_dnsmasq_service` parser to the insights archive spec to fix: https://github.com/RedHatInsights/insights-core/issues/3165 issue and also correct the docstring for it.
> Add spec for the systemctl_cat_dnsmasq_service to the insights archive spec

- insights/core/__init__.py
- insights/parsers/engine_db_query.py
- insights/parsers/tests/__init__.py
- insights/parsers/tests/test_awx_manage.py
- insights/parsers/tests/test_ceph_cmd_json_parsing.py
- insights/parsers/tests/test_cloud_cfg.py
- insights/parsers/tests/test_cni_podman_bridge_conf.py
- insights/parsers/tests/test_engine_db_query.py
- insights/parsers/tests/test_freeipa_healthcheck_log.py
- insights/parsers/tests/test_httpd_open_nfs.py
- insights/parsers/tests/test_ndctl_list.py
- insights/parsers/tests/test_rhsm_releasever.py
- insights/parsers/tests/test_rhv_log_collector_analyzer.py
- insights/parsers/tests/test_tags.py
- insights/parsers/tests/test_teamdctl_config_dump.py
- insights/parsers/tests/test_teamdctl_state_dump.py
- insights/parsers/tests/test_version_info.py
- insights/parsers/tests/test_virt_uuid_facts.py
* Add a check for no content in the JSONParser class instead of checking
in each individual parser for no content.
* Add a test for empty output to each parser's test that uses the JSONParser
class.
* Fixes #3163
Fix several parse exceptions that are occurring in production, since jsonparser doesn't check for empty content. I figured instead of checking in each parser, that it was better to do the check in the jsonparser class.
> Fix json parsing of empty content.

- conftest.py
- docs/manpages/insights-run.rst
- insights/__init__.py
- insights/core/plugins.py
- insights/formats/html.py
- insights/formats/text.py
- insights/plugins/returns_none.py
- insights/tests/__init__.py
- insights/tests/test_plugins/test_returns_none.py
- insights/tests/test_rules_fixture.py
Add make_none response for rules
* Changes how rules that return none are handled. Instead of raising a
SkipComponent and ignoring the rule, they will now be counted in the
results.
* Add a make_none response type
* Update formatters to handle the new type
* Update tests
* Fix #3026
* Remove none rules from detailed output
* Update to add none option to text format
Fix legacy CI tests that check for None
* This change allows the legacy tests that check for None result from a
rule to work with make_none() without requiring changes to the rules
* The simplified integration testing fixture includes a new flag that
allows turning switching to the new functionality on a per test basis
> Add make none ci fix

- insights/parsers/etc_udev_rules.py
- insights/parsers/tests/test_etc_udev_rules.py
- insights/parsers/tests/test_udev_rules.py
- insights/parsers/udev_rules.py
- insights/specs/__init__.py
- insights/specs/default.py
This spec is used to detect the Oracle ASM diskgroup outage issue proactively. If the disks in the Oracle ASM diskgroup are managed by udev, and the `add|change` actions are not configured `nowatch` in the udev rule, the customer will hit this issue. Detailed info is in the CEECBA-5525.
> New spec for getting oracle asm disks udev rules

- insights/combiners/tests/test_lspci.py
- insights/parsers/lspci.py
- insights/parsers/tests/test_lspci.py
The `Slot` is Key information for each PCI device outputted by the `lspci -k` command.
Typical output of `lspci -k`:
```
]# lspci -k
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
Subsystem: Red Hat, Inc. Qemu virtual machine
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
Subsystem: Red Hat, Inc. Qemu virtual machine
```
And since it is named as `Slot` in the output of `lspci -vmmkn`, I renamed the name of the variable `bus_device_function` used in the parser to `slot` too.
Typical output of `lspci -vmmkn`
```
insights_repos]# lspci -vmmkn
Slot:   00:00.0
Class:  0600
Vendor: 8086
Device: 1237
SVendor:        1af4
SDevice:        1100
Rev:    02
Slot: …
```
> Insert the 'Slot' to the parser result of LsPci

- docs/intro.rst
Signed-off-by: Thibault Guittet <tguittet@redhat.com>
Just a typo.
> Docs typo: extra dot at the end of URL points to the wrong page

- insights/parsers/sysconfig.py
- insights/parsers/tests/test_sysconfig_doc_examples.py
- insights/parsers/tests/test_sysconfig_oracleasm.py
- insights/specs/__init__.py
- insights/specs/default.py
This spec is used to detect the Oracle ASMlib configuration issue proactively. If the configuration doesn't ignore the single disk scan, the oracle service will crash when a single path in multipath fails. Detailed info is in the CEECBA-5575.
> New spec for oracle asmlib configuration

- insights/client/phase/v1.py
- insights/tests/client/phase/test_update.py
In order to facilitate removal of the `uploader_json_map.json` file from the egg, resume update of the `/etc/insights-client/.cache.json` file so that the file on disk is updated along with the egg.
> always update uploader.json

- insights/specs/default.py
- insights/specs/insights_archive.py
- insights/tests/client/collection_rules/test_map_components.py
This spec `ntpq_pn = simple_command("/usr/bin/ntqp -pn")` is required by an enhancement of an existing rule. It's in the uploader.json already, NO need to require SPEC approval for this change.
> Revert the 'ntpq_pn' spec back

- insights/parsers/lsof.py
- insights/parsers/tests/test_lsof.py
Currently Parser assumes minimum start index of the values of columns but it can change if value width exceeds causing parser to give wrong data as explained in issue.
> Fix Lsof parser logic (#3172)

- insights/parsers/tests/__init__.py
- insights/parsers/tests/test_awx_manage.py
- insights/parsers/tests/test_ceph_cmd_json_parsing.py
- insights/parsers/tests/test_cloud_cfg.py
- insights/parsers/tests/test_cni_podman_bridge_conf.py
- insights/parsers/tests/test_engine_db_query.py
- insights/parsers/tests/test_freeipa_healthcheck_log.py
- insights/parsers/tests/test_httpd_open_nfs.py
- insights/parsers/tests/test_ndctl_list.py
- insights/parsers/tests/test_rhsm_releasever.py
- insights/parsers/tests/test_rhv_log_collector_analyzer.py
- insights/parsers/tests/test_tags.py
- insights/parsers/tests/test_teamdctl_config_dump.py
- insights/parsers/tests/test_teamdctl_state_dump.py
- insights/parsers/tests/test_version_info.py
- insights/parsers/tests/test_virt_uuid_facts.py
* In pytest 4 fixtures can't be called directly, so I changed
test_empty_skip to skip_exception_check and removed the fixture 
decorator.
In pytest 4 fixtures can't be called directly, and shared function names can't start with test. To fix this I renamed test_empty_skip to skip_exception_check, and removed the fixture decorator.
> Fix fixture error in pytest 4 for test_empty_skip

- docs/shared_parsers_catalog/mssql_api_assessment.rst
- insights/parsers/mssql_api_assessment.py
- insights/parsers/tests/test_mssql_api_assessment.py
- insights/specs/__init__.py
- insights/specs/default.py
Currently, RedHat insights team is cooperating with MSFT to create a script to run MSSQL Assessment API rulesets[0], and store the result on "/var/opt/mssql/log/assessments/assessment-latest". Then Insights-client will read the content of the file, and insights-plugin will return valuable items for customers. Although script execution method is under discussion, the content and store path of the output are determined(we can update it if there is any change in the future). This parser is used to parse the content of file "/var/opt/mssql/log/assessments/assessment-latest".
[0] https://github.com/microsoft/sql-server-samples/blob/master/samples/manage/sql-assessment-api/ruleset.json
> Add parser mssql api assessment

- insights/specs/default.py
Remove "mssql_api_assessment = simple_file("/var/opt/mssql/log/assessments/assessment-latest")" as the path has not been determined currently
> Remove the spec mssql_api_assessment from default

- insights/formats/__init__.py
- insights/formats/_markdown.py
- insights/formats/text.py
- the 'make_none' is also a type of rules
- do not show the 'make_none' rule by default
it means show 'make_none' only when "none" is specified in the `--show-rules`
The `make_none` rule is also a type of rule, how about merge this option `--none` to the `--show-rules`
> Merge the -N (show make_none rules) to -S (show rules per type)

- insights/parsers/ntp_sources.py
- insights/parsers/tests/test_ntp_sources.py
- and refine the parser to dict/list
- add the tests of doc
- fix #3192 
fix: #3192
> Skip the parsers in ntp_sources when input is empty

- insights/parsers/lsof.py
* The code utilizing the iter/next functions in the lsof parser changed
in python 3.5 based on PEP 479
* This change makes the code compliant with that PEP and removes the
deprecation warning for tests
> Fix deprecated generator code in Lsof parser

- insights/combiners/lspci.py
- insights/combiners/tests/test_lspci.py
- In case the `lspci -k` sometimes outputs the `Slot` in the full format of
`domain:bus:device.function`, the combiner will take the `Slot` of the
`lspci -k` as the key.
- fix: #3176
Fix #3176
> Fix the LsPci combiner for full format of 'Slot'

- insights/tests/test_canonical_facts.py
- insights/util/canonical_facts.py
* The `ip_addresses` command `hostname -I` sometimes includes localhost and IPV6 addresses
* The `mac_addresses` glob spec sometimes includes invalid mac addresses
* Apply validation to IP addresses and MAC addresses to ensure that unexpected/invalid values are not saved in canonical facts
* Add tests for canonical facts
> Fix issues in canonical facts ip and mac addr

- insights/specs/default.py
* Due to problems with netstat output formatting, ss is the best source
for network information
* The ss command was restricted to only run if certain modules were
already loaded since those modules were necessary for ss.  This change
removes those restrictions. The side-effect is that the modules
inet_diag, tcp_diag, and udp_diag may be loaded by execution of the ss
command.
* See issue #2909 
> Adding ss command back in without restrictions

- insights/parsers/lsblk.py
- insights/parsers/tests/test_lsblk.py
* Fix the regex to catch the various raid types raid0, raid1, etc.
The regex only catches lower case letters for the type field, so if the type is raid1 then the mountpoint was being set to "1 /boot" for example if /dev/md127 is mounted on /boot. So I added 0-9 to the regex to catch the various raid types properly.
> Fix lsblk parsing raid1 types

- insights/parsers/bond.py
- insights/parsers/tests/test_bond.py
* Added in the missing attribute that is often set in the bond opts.
* Added in testing to confirm the attribute was set properly.
I found that the MII polling interval wasn't parsed from the output, even though it is set quite often in the bonding opts config. I figured since ARP polling interval is parsed the MII should be as well.
> Add MII polling interval attribute to the bond parser

- insights/core/dr.py
* Moved the do_include and do_exclude to the top and added a check for
excludes before importing path.
There was an issue reported that running insights info was throwing no module pytest. After looking into it I noticed that the default exclude in _load_components wasn't actually getting excluded, so it was trying to load all of the tests.
> Fix excludes not working in _load_components

- insights/collect.py
- insights/specs/default.py
The datasource specs removed by this PR are not used by any Advisor/CCX/ProdSec rules.
They can be added back when necessary to the new datasource structure
Relates to #3087
> Remove the unused datasource specs from default.py

- insights/shell.py
Insights-core does a very good job detecting, parsing and caching large amount of data in archives. The main interface it exposes is an iypthon shell (`insights shell`). The use of ipython shell is quite convenient because, apart from exposing an interactive shell, it supports client-server mode, or in ipython terminology client-kernel mode. That way, both data and logic living inside the insights shell can be exposed to an external process such as command line tool or even a jupyter frontend.
This small patch just allows insights shell to start a ipython server in "kernel" mode allowing jupyter clients to connect and interact with it. Example
```
$ insights shell -k $ARCHIVE
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.
To exit, you will …
```
> shell: support running shell in kernel mode

- docs/shared_parsers_catalog/yum_updates.rst
- insights/parsers/tests/test_yum_updates.py
- insights/parsers/yum_updates.py
- insights/specs/__init__.py
- insights/specs/datasources/yum_updates.py
- insights/specs/default.py
Dynamically imports os-specific library for handling DNF/YUM interaction.
Performs a resolution of updateable packages, and outputs it as JSON.
Expected performance is on the order of seconds for both RHEL7 and RHEL8.
cc: @MichaelMraka
> Add custom datasource for collecting yum/dnf updates

- insights-core.spec
* Update the requires entries in the rpm spec file to allow building it
on el7. Since a lot of the packages start with python36 on el7.
* Added the missing CacheControl and pyyaml requirements.
I added a check for el7 in the rpm spec, so that the requirement package names are correct since for el7 a lot of python3 packages start with python36. Also added in the missing CacheControl and pyyaml requirements.
> [3.0] Update requires in core rpm spec for el7

- insights/parsers/netstat.py
The netstat parser previously used an assert to make sure self.name was in the NETSTAT_SECTION_ID dictionary. Instead use an if statement and raise a parser exception if not met.
> Replace assert with parse exception in netstat parser

- insights/specs/sos_archive.py
Though sos report runs the sources command with "-n" switch, the output works fine with existing parser in core.
~~~
➜  sosreport-test1-2021-04-22-qtdzftt ls -lrt sos_commands/chrony 
total 32
-rw-r--r--. 1 roarora roarora 1122 Apr 22 11:20 journalctl_--no-pager_--unit_chronyd
-rw-r--r--. 1 roarora roarora  465 Apr 22 11:20 chronyc_tracking
-rw-r--r--. 1 roarora roarora  500 Apr 22 11:20 chronyc_sourcestats
-rw-r--r--. 1 roarora roarora  159 Apr 22 11:20 chronyc_serverstats
-rw-r--r--. 1 roarora roarora 3121 Apr 22 11:20 chronyc_ntpdata
-rw-r--r--. 1 roarora roarora  506 Apr 22 11:20 chronyc_-n_sources
-rw-r--r--. 1 roarora roarora  207 Apr 22 11:20 chronyc_-n_clients
-rw-r--r--. 1 roarora roarora  156 Apr 22 11:20 …
> Add Spec path of chronyc_sources for sos_archive

- insights/core/__init__.py
Moved find_main into the ConfigCombiner class since it's not used anywhere else, and find_matches is already in the class. Added a raise SkipException to find_main, so if no files are returned in the loop it doesn't return None.
Fixes #3276
> Fix: Add raise SkipException to ConfigCombiner for missing main_file

- docs/shared_parsers_catalog/nss_rhel7.rst
- insights/parsers/nss_rhel7.py
- insights/parsers/tests/test_nss_rhel7.py
- insights/specs/__init__.py
- insights/specs/default.py
Signed-off-by: Jakub Svoboda <jsvoboda@redhat.com>
Red Hat Directory Server and Red Hat Identity Management use 389-ds (389 Directory Server) for LDAP. To analyze current SSL&TLS settings on RHEL7, it is necessary to read up to four configuration directives from `dse.ldif` files and from the `nss-rhel7.config` file. To analyze current TLS settings on RHEL8, it is necessary to read the same `dse.ldif` files and `crypto-policies` configuration. This PR adds one of the two specs and parsers that are not provided yet by insights-core to achieve that goal – for `nss-rhel7.config`
> Spec & parser for nss-rhel7.config

- docs/shared_parsers_catalog/dse_ldif_simple.rst
- insights/parsers/dse_ldif_simple.py
- insights/parsers/tests/test_dse_ldif_simple.py
- insights/specs/__init__.py
- insights/specs/default.py
Signed-off-by: Jakub Svoboda <jsvoboda@redhat.com>
Red Hat Directory Server and Red Hat Identity Management use 389-ds (389 Directory Server) for LDAP. To analyze current SSL&TLS settings on RHEL7, it is necessary to read up to four configuration directives from `dse.ldif` files and from the `nss-rhel7.config` file. To analyze current TLS settings on RHEL8, it is necessary to read the same `dse.ldif` files and `crypto-policies` configuration. This PR adds one of the two specs and parsers that are not provided yet by insights-core to achieve that goal – for `dse.ldif`
> New specs and parsers for analyzing 389-ds TLS-related settings.

- insights/client/apps/compliance/__init__.py
- insights/tests/client/apps/test_compliance.py
Using the relationships=false API attribute during the client call to get the assigned host policies. The purpose of this update is so that unnecessary relationships are not requested in the client profiles API call.
This PR is a draft because the new 'relationships' parameter still needs to be added to the API before we can use it. Will take this ticket out of draft when this functionality has been added to the API. That work is here: https://github.com/RedHatInsights/compliance-backend/pull/1023
> Fix: RHICOMPL-1980 Adding the 'relationships' API attribute to the client profiles API call

- insights/parsers/samba.py
- insights/parsers/tests/test_samba.py
On some older releases of Samba, testparm -v -s contains progress
messages such as `Processing section "[homes]"`. Because these
messages contain section names, they aren't removed by filtering.
This change removes them in the testparm parser.
Signed-off-by: Keith Grant <kgrant@redhat.com>
Some older versions of Samba contain messages in the output of `testparm` that cause exceptions in the testparm parsers. This change removes those lines in the parser.
> Strip progress messages from testparm output

- insights/parsers/pmlog_summary.py
- insights/parsers/tests/test_pmlog_summary.py
Enhance the PmLogSummary for the following lines of new metrics.
```
kernel.all.pressure.io.full.avg ["10 second"] 0.001 none
kernel.all.pressure.cpu.some.avg ["1 minute"] 14.942 none
kernel.all.pressure.memory.full.avg ["5 minute"] 0.002 none
disk.dev.total ["vda"] 0.016 count / sec
disk.dev.total ["vdb"] 0.445 count / sec
disk.dev.total ["vdc"] 2.339 count / sec
```
> fix: update the pmlog_summary to support new metrics

- docs/custom_datasources_index.rst
- insights/collect.py
- insights/specs/datasources/pcp.py
- insights/specs/default.py
- insights/tests/datasources/test_pcp.py
- Update pmlog_summary to read all "mandatory on" metrics in config.ros
- Move the depended specs to the new datasource directory
- Add test for these datasources
- Update pmlog_summary to read all "mandatory on" metrics in config.ros
- Move the depended specs to the new datasource directory
- Add test for these datasources
> Refactor: read metrics from config.ros for pmlog_summary

- insights/parsers/ethtool.py
- insights/parsers/tests/test_ethtool.py
Updated the logic to loop through the content and start parsing after finding the starting line. This way operation not permitted messages at the beginning of content are ignored. Updated the tests to test with operation not permitted messages at the top of content. Fixes #3268
> Update ethtool's parsing logic

- insights/client/apps/malware_detection/__init__.py
- insights/tests/client/apps/test_malware_detection.py
* https://bugzilla.redhat.com/show_bug.cgi?id=2025009
This PR removes the yara_binary config option and only looks for yara in specific/known locations, ie /bin/yara, /usr/bin/yara and /usr/local/bin/yara.  This prevents a user from pointing to a specific rogue yara binary, or modifying the search path so it finds a rogue yara binary.  Of course, this doesn't stop someone from replacing a good yara binary with a rogue one, but at least these changes make malware-detection less likely to be coerced to use a rogue yara binary.
> Remove yara_binary as a config option

- insights/client/apps/malware_detection/__init__.py
- insights/client/connection.py
- insights/tests/client/apps/test_malware_detection.py
* https://issues.redhat.com/browse/YARA-232
* Don't log the malware signatures download in verbose mode
* It is a big binary blob and may leave artifacts on the command line afterwards
The malware-detection app downloads the malware signatures as a big binary blob.  When running insights-client in verbose mode, this binary blob is displayed on the terminal and can leave trailing text after the command has finished.  There is no real need to display this binary blob and this PR adds a flag to the connection module to toggle displaying the response.text or not when in verbose mode.  It is on by default which maintains the current behaviour, but for malware-detection, it is turned off so the binary blob isn't displayed on the …
> Add log_response_text flag to log downloads or not in verbose mode

- insights/tests/client/data_collector/test_redact.py
- insights/tests/client/test_skip_commands_files.py
By running the tests with the flag --system-site-packages set to true (which is needed in the virtual environment for the client), some tests are failing:
Added the parameter core_collect to false when the InsightsConfig is created. This solution prevents InsightsConfig from checking the client's version that is in the system packages and modifying the core_collect value that should be false. 
The error is produced by using the --system-site-packages while ruining the tests.
> Fix test system

- insights/client/apps/malware_detection/__init__.py
- insights/tests/client/apps/test_malware_detection.py
* https://issues.redhat.com/browse/YARA-249
* Old rules files may cause false positives
The rules file that is downloaded from the backend should be automatically removed when the malware-detection client exits. 
However it *can* happen that the rules file isn't removed for some reason.  This PR makes sure any old rules files are removed before beginning a new scan, otherwise they may show up as matches in the scan results.
> Remove old rules files before starting a new scan

- insights/client/apps/malware_detection/__init__.py
- insights/tests/client/apps/test_malware_detection.py
* https://issues.redhat.com/browse/YARA-249
* Scanning the log files may cause false positives
Need to do a better job of excluding the insights-client log files from being scanned.  Previously I had them listed as a scan_exclude entry in the config file, but that entry can be easily removed and the log files will be scanned, possibly causing false positives.  This PR now gets the list of log files and adds them to the exclude items within the code, so it can't be easily changed.
> Improved excluding of the insights-client log files

- docs/shared_parsers_catalog/systemctl_status_all.rst
- insights/parsers/systemctl_status_all.py
- insights/parsers/tests/test_systemctl_status_all.py
- insights/specs/__init__.py
- insights/specs/sos_archive.py
The Open Shift Node will fail to start the `cri-o` service with the error messages showing in the command `systemctl status --all`.  Detail info please see: INSIGHTOCP-525 card.
> feat: Add spec and parser for systemctl_status_-all

- insights/parsers/systemd/unitfiles.py
- insights/parsers/tests/test_unitfiles.py
In RHEL9 there is an additional column in the list-unit-files output for the vendor preset, so updated the parser to handle the old and new output.
> Fix: Update the unitfiles parser for RHEL9 output

- insights/specs/datasources/cloud_init.py
- insights/tests/datasources/test_cloud_init.py
The current implementation does not parse the `0` value correctly. The value is evaluated as `False` and is ignored.
This PR solves mentioned problem.
> Fix parsing problem in cloud_cfg datasource

- insights/parsers/lscpu.py
- insights/parsers/tests/test_lscpu.py
In RHEL9 lscpu added indentation and several section headers that don't have any values after the colon. So updated the parser to handle these section header lines.
> Fix: Update lscpu parser to support RHEL9 output
